### ISSUE TITLE
Encoding of supplications

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1003]
Maybe we can split the supplication issue from #946 :

> How to encode supplications (terminology should be discussed: eulogy, final blessing formula) is not yet completely decided. We have agreed that it is important to mark them up wherever in a manuscript they can occur (beginning, end, within the text). As supplications can be integrated in colophons (of the work (now called titles) or manuscript) it would be desirable to find ways of encoding them that work for cases:
> 
> where the supplication is present only in one manuscript, clearly separated from the other textparts
> where the supplication is present only in one manuscript but seamlessly integrated into a textpart (title or other msItem)
> where the supplication can be said to be part of the work as it is transmitted in all manuscripts in the same place, but with varying names

Do you have any suggestions for this, @PietroLiuzzo ? I think that we need to be able to mark up supplications both within the text (whether a title, addition, div type edition or whatever) as well as refer to their existence in cases where we have no transcribed text. 

@nafisa-valieva also might have more requirements related to differentiating in an edition supplications that belong to the archetype from others.

**Comment by nafisa-valieva** [comment]
I am not sure whether it is possible and therefore correct to differentiate between all these cases for each individual manuscript.
What means clearly separated? And how someome is going to decide whether the supplication is present only in one manuscript?

The same question is true for how to understand whether it is part of the work (limited evidence: all manuscripts, but then in each case one has to collate manuscripts) 
I was encoding supplications as additions (to the text), but I was wrong, because there are added supplications (with a later hand), however, in most cases supplications belong to the same moment of production and therefore they are not additions. 
I would suggest following:
If we can identify an inscriptio (this can be done on the basis of one manuscript), expanded through a supplication, in this case it is inscriptio that consists of a title and a supplication.

 <div type="textpart" subtype="title expanded subscriptio"> or  <div type="textpart" subtype="title expanded inscriptio"> and here we need to say what are the elements of an inscriptio/subscriptio ( e.g. Basmala+title+supplication) how to do it correctly I do not know yet.

one can mark supplications at the beginning or end of a text as part of the incipit/explicit. I think we agreed to do it.  (Here the question is what is the true incipit and explicit, like this one can limit himself to the evidence in the manuscript but give a bit more lines before the supplication begins, in case supplication was added later and confuse indentification of a text)
<incipit>   
<incipit type="supplication">
<explicit>
<explicit type="supplication"> 
If supplication is 'separated', probably one can specify it within a <note>?

Supplication within the work can be conceptualized as an articulation of the content (it seem to be an end of a reading part, chapter, whateever), so this is an open question how to encode it. I think I will encode it as an end of articulated unit, so it will be again part of an explicit. 
<explicit>
<explicit type="supplication"> 
Yours, Nafisa

**Comment by thea-m** [comment]
I think that the deep encoding of supplications is best carried out by specialists of particular works and mss, since it presupposes a thorough knowledge of the textual history. 
For now, i still think that the supplication type in incipit and explicit is very useful, as well as a possibility to mark up supplications wherever in a text they occur would be. Seg type supplication seems reasonable to me? @PietroLiuzzo?
We also already have the possibility to mark up supplications as textparts in work records.
Then all supplications are encoded and searchable, and anyone working on a particular case study has a starting point for their own work.

**Comment by PietroLiuzzo** [comment]
Yes, I agree on the use of `<seg>`. See last taks to be carried out in https://github.com/BetaMasaheft/Documentation/issues/895#issuecomment-397746728 which actually should be part of #946
