### ISSUE TITLE
<pb> not visualized

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1012]
`<pb>` in encoded text seems not to be visualized anymore, for example http://betamasaheft.eu/manuscripts/BLorient719/text or http://betamasaheft.eu/manuscripts/EMML6952/text

**Comment by PietroLiuzzo** [comment]
It was realized with a pipe, but the absence of further specification does not make it very clear.
There is no change since last releases in the XSLT template for this but I do have screenshots taken when this was there. I have added back the pb/@n as a superlinear number after the pipe 
https://github.com/BetaMasaheft/BetMas/commit/2d5cc1d6cb1344d44a9640d542f8e84f82ddb256
