### ISSUE TITLE
subtype="institution" in place records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1032]
There are several place records which have a subtype="institution" in `<place>`, for example LOC7038SinaMikael or LOC5496SallaD. According to my understanding, these should be institution records, since they all seem to refer clearly to a church holding manuscripts. If there were reasons for keeping them in places, could you maybe clarify the guidelines?
http://betamasaheft.eu/Guidelines/?id=placeOrInstitution
Thank you!

**Comment by PietroLiuzzo** [comment]
I think this is simply a mistake, probably due to an earlier stage of the write of the guidelines.

There is no reason to keep them in places, they shall be moved.

there are only 14
http://betamasaheft.eu/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%2Fplaces%27%29%2F%2Ft%3Aplace%5B%40subtype%3D%22institution%22%5D

**Comment by thea-m** [comment]
@eu-genia since you are working with place records now anyway, would you do it?

**Comment by thea-m** [comment]
sounds good, thank you!

**Comment by PietroLiuzzo** [comment]
For completeness, I thing the list which @eu-genia mentioned is a list sent by Steve Delamarter, which she is reconciling with the institutions in our db

**Comment by sologebre** [comment]
I think it is theoretically correct to move all churches and monasteries from place record to institutions, whether or not they have a manuscript in our records. All monasteries and churches should have similar elements to describe it. We know that in tradition, a given church also has at least one manuscript.

**Comment by eu-genia** [comment]
this is in principle true (same applies to some other LOC record types, e.g. mosques, they too always have at least one manuscript)
there are many entities in our list which are only known from sources and may not even exist any more, or are not used, i do not know if we can treat them as repositories automatically (even if they once may have been...). i thought we define as repository/institution only the entity we know to hold manuscripts we have in the database. if we move all we have to extend the definition.

**Comment by eu-genia** [comment]
On rereading the Guidelines (http://betamasaheft.eu/Guidelines/?id=placeOrInstitution) I have discovered something that I believe was discussed differently: churches etc. holding manuscripts become repositories which becomes the main record with full information; we do not need a parallel LOC record as then the users are confused as to where to look for data.  Can we consider revising the Guidelines accordingly? @thea-m?

**Comment by PietroLiuzzo** [comment]
please let us bear in mind that a place and a repository are two different **concepts**. As discussed, there is no need theoretical or technical to delete a place concept if this is also a repository. As well as there is no need theoretical or technical to create a place record for each repository. Please do not be deceived by the fact that we use the same content model for these two conceptually distinct things. I personally find the guidelines clear on this, but it does not hurt to add a few sentences more to unpack this, if we feel it is needed.

On the point above at the beginning of the discussion, those record which were meant to be repositories and have been created as places by mistake need to be corrected. But this is just because they were intended as repositories as the subtype=institutions seams to mean, not because of any more general rule or undocumented discussion.

Another order of problems is the user experience. If we think, and I gather that this is what concerns @eu-genia , that the user is not able to make this simple distinction between a concept of place and a concept of repository, which allows us to have both or none or one of the two according to what is that we actually know, then we might remove the one or the other record. I think the guidelines are right in advising not to do so, but if there is really no point in having two, because we have that place concept only because it is a repository, then it does no harm as explained above to remove the place (updating the ids) but, let me stress once more that I think it is entirely unnecessary. 

For this reason I think that the simple points in that page of the guidelines hold true and are simple enough to avoid confusion.

**Comment by eu-genia** [comment]
I believe the subtype institution in the list above was added by JG to mark that they contain manuscripts without moving records or creating new ones. It was not there originally.

I think we must be consistent. Either we say these are two distinct things - no problem for me - but then we do need always two parallel records (meaning also, e.g., if the name or administrative division, or coordinates, or anything else relevant has to be changed, one has to do it twice - and also that we have to decide whether e.g. the information on history, on tābots, etc. belongs to the church as place or to the church as repository - or is doubled again???), or places that are repositories are only repositories, the whole information is provided once, and the users e.g. when marking "places" in the search filter also get the results from the Institutions folder.

The information must be retrievable and it must be absolutely clear where.

I am OK if we say we have all churches and monasteries as places, with full information on history etc., and additionally records for those which are repositories with no information apart from a relation to the LOC record. But for the moment the Guidelines advise otherwise.

**Comment by eu-genia** [comment]
I would then suggest that place records are created for all Institutions of type church/monastery/mosque in Ethiopia/Eritrea (if there are none), where the whole file is copied to, and in INS record only a link to the LOC record is placed instead. Then there is no ambiguity as to where to look for information and no confusion between the concepts.

**Comment by Gnisci** [comment]
> I believe the subtype institution in the list above was added by JG to mark that they contain manuscripts without moving records or creating new ones. It was not there originally.
> 


I used it @eu-genia, but because I found it used in other files, I didn't create it-

**Comment by PietroLiuzzo** [comment]
I have discussed this again also with @thea-m and we understand the need for consistency but do not see the immediate use of going through all this work in the current project phase.

- the need for repository record emerges primarily when a manuscript needs to be assigned to a repository. We will always have to create a repository in this case. For this situation, the page of the guidelines about PlaceOrInstitution has worked as guidance well and clearly for encoders.

- It would be of course optimal to have a place and a repository for each church, for example, but this will come along with the needs of the encoding. For example as above an repository will be created when encoding a manuscript, a place might be additionally created when encoding a text. And given the similarity of the model of repository and place, there is no immediate need to have two for each. So, when encoding the text, if a complete repository record is available the encoder might well choose not to create a place record, for the sake of time and efficiency. We might add to the guidelines, that it is best practice to add these records, but we do not think that any real need is there to go back to all the data and change eventually repository ids used to identify a place. We exploit here the similarity in content model, which might be a bit forcing the conceptual distinction but is in line with the mixed understanding of such distinction and functional to a fluid and smooth continued data entry work.

- in cases where there are a INS and a LOC record for a repository and a place which happen to share known coordinates, we certainly need to decide where to place the information about tabot etc. A link between the two is helpful, but not necessary. Duplicating the information would be wrong and create ambiguity and additional unnecessary work. This would require some work, which was anyway needed to make this page in the Guidelines http://betamasaheft.eu/Guidelines/?id=institution more helpful
   - splitting the example in digestible and readable pieces
   - argue to put tabot information here as well as other types of information we might discuss
   - a specification of the above discussion  about place and repository could be placed here and in the overview page to avoid duplications of information (which anyway currently do not happen)
   - an example of how to relate an repository and a place record
   - update the title of the page to remove /institution

If the record above where actually not meant as repository they can stay as places and we will just remove the subtype or change it.

**Comment by eu-genia** [comment]
the records above are both places and repositories, they also appear on the EMML list

**Comment by PietroLiuzzo** [comment]
a comment by jacopo made it to the email but not to this thread as far as I can see. 
It clarifies that the intention of creating an institution, which I assumed, was not there, so those records can safely stay where they are and and we can just remove the subtype="institution". This is the minimal fix needed. we could create other records and move information, but it is not needed. 

When there will be manuscript from one of these churches which (as for the case of EMML) somebody will be in charge of encoding nicely, they might have to create a record. But since they are in the list, at that stage they will be happy to find the repository they are looking for already in there, because I will add these from the list if we do not yet have a repository, to update the information in repository/@ref

**Comment by PietroLiuzzo** [comment]
#125 #1024 #1036 #1034

**Comment by eu-genia** [comment]
I have now removed the subtype institution in the list below, even though they were actually created by JG with institution in mind - since they all appear on the EMML list they will be now recreated as institutions anyway so I did not move the record. A relation shall be inserted too.

```
LOC7012DansMikael
LOC7027EndadeTaklaH
LOC7013DebreBerhanSp
LOC7014GihurMedhaneA
LOC7018MitaqTaklaH
LOC7017MitaqAmanuel
LOC7036QobboMaryam
LOC7002AnkobaMaryam
LOC7038SinaMikael
LOC7037MogaFequrWalda
LOC7003AnkobaMikael
LOC7039YegamAbbo
LOC7004AnkobaKidaneM
LOC5496SallaD
```

**Comment by Gnisci** [comment]
Thank you Genia, I was going to do this, but just relocated to a new country so I've been a little overwhelmed at present, sorry.
