### ISSUE TITLE
more than one repository?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1099]
Is it possible to add more than one repository to manuscript records? I would like to encode the "physical" repository of EMIP/EMML manuscripts, where the repository element is already taken up by the respective projects. (Sorry if this has already been discussed, but I couldn't find it anywhere...)

**Comment by PietroLiuzzo** [comment]
Those are placeholders, they can be replaced from the true repository. information about EMML-EMIP is in collection already

**Comment by thea-m** [comment]
Perfect!

**Comment by thea-m** [comment]
I also like the way @anaiswion has done this, with adding the repository in altIdentifier
` <altIdentifier><repository ref="INS00001BL"></repository><idno>BL Or 819</idno></altIdentifier>`
That way, the EMML/EMIP ID is not lost. What do you think?

**Comment by PietroLiuzzo** [comment]
The EMML EMIP repo id is nonsensical and needs to go. neither EMML nor EMIP are repositories

**Comment by PietroLiuzzo** [comment]
EMML / EMIP is an information for collection

**Comment by thea-m** [comment]
should they then stay within their current repository folders in github or be moved? I can imagine that some confusion might arise if manuscripts of the same repository are distributed among several folders, as is the case currently (but manuscripts in the EMML/EMIP are extremely easy to find, which is an advantage)

**Comment by PietroLiuzzo** [comment]
The folder structure is irrelevant and arbitrary and can stay as is.

**Comment by thea-m** [comment]
I understand that it is irrelevant. But I am afraid that someone working for example through Wrights BL catalogue would not be aware of BL Orient 819 already being encoded, but saved in another folder as EMML 50, and might start working on it again. Obviously, in this case, searching for the ID before starting the work would solve this, and for now the amount of concerned manuscripts is small and we can keep track of them easily. But there might be cases in the future where the alternative ID is not correctly encoded, or other confusion arrises. Any ideas of how to prevent this except encouraging people to make encoding of all known identifiers a priority and search for manuscripts before starting to work on them?

**Comment by PietroLiuzzo** [comment]
I do believe this should be up to the encoder to make sure. Actually, for this example, reading the provenance statement also the BL repository indication is not correct, it should be an Identifier for Enṭoṭṭo Rāguel (INS0599AKU ?? ). In `<history>` EMML and BL can be linked to the respective ids and the identifiers should certainly be listed in `<msIdentifier>`, while the bibliography should contain the catalogues references. Once these informations are there it should be really a deliberate act to miss it, because even the simple search will look into `idno` and there are lists by catalogue and by repository. Of course we cannot expect everything to magically be there so, the more we can add the better and every little bit will help to disambiguate more. The risk to overlook existing content and duplicate work will always exist, no matter how much we try to hinder it. We can certainly encourage in the guidelines to act as you suggest, and once this EMML50 record is completed it will make certainly a nice example for this kind of situation. 

We might indeed also improve our use in `<history>` of `<provenance>` and `<acquisition>`, see 
https://tei-c.org/release/doc/tei-p5-doc/en/html/examples-provenance.html 

Our guidelines have little or no guidance on this https://betamasaheft.eu/Guidelines/?id=history

**Comment by eu-genia** [comment]
I agree that the main repository is the one where the manuscript is/was kept, not the images/microfilms. EMML mss should be treated the same way as the E-S mss (and later if we ever get to them Tanasee mss). 
Yet I wonder if it might make sense, in such case as EMML, to help the users and editors get to the right place, to have a stub record with a cross-reference in a second folder (?) So that if one opens a record with ID EMML50 one gets a stub that says this is the digital copy of -->BLorient819?
