### ISSUE TITLE
Ethio-SPaRe conversion: missing data Finding aids

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1122]
Finding aids are missing in the converted files, e.g. 
ESagm005
see
https://mycms-vs03.rrz.uni-hamburg.de/domlib/receive/domlib_document_00000899?XSL.Style=xml

```
<cbfindingaids class="MCRMetaBoolean" heritable="false" notinherit="false">
<cbfindingaid xml:lang="en" inherited="0">true</cbfindingaid>
</cbfindingaids>
<txfindingaids class="MCRMetaLangText" heritable="false" notinherit="false">
<txfindingaid xml:lang="en" inherited="0" form="plain">
- Monthly readings of Text I are indicated as follows:
 Fol: 21va: Yäkkatit;
 Fol. 31va: Ṭәrr;
 Fol. 34ra: Gәnbot;
 Fol. 45rb: Mäggabit;
 Fol. 51rb: Miyazya;
 Fol. 65rb: Ḥamle,
 Fol. 71va: Näḫase;
 Fol. 76rb: Mäskäräm;
 Fol. 82rb: Ḫәdar.
</txfindingaid>
</txfindingaids>

```

**Comment by PietroLiuzzo** [comment]
Dear @eu-genia I am sure there are several other things which are missing, but I am very unlikely to update the conversion, unless there are really hundreds of cases, because many files have been updated already and taking in consideration all the variants would be a task of a size not worth the effort. I can look at how many of these there are but I still think it would go much faster if you simply copied it over in the place where you want this information (which I am also not sure how we encode)

**Comment by eu-genia** [comment]
There are over a 100 records with this, maybe at least a commented passage can be inserted everywhere relevant, and I will go through the XML then? It is faster than having to open each domlib record.

**Comment by eu-genia** [comment]
One could eventually put under `physDesc `a new `<ab>` (under `layout`?) of type @findingAid and print it accordingly; or use a `<note>` of type @findingAid in `msContent`? (I do not think there is a tei standard, I could not find anything)

**Comment by eu-genia** [comment]
I have now found `<anchor type="bookmark">`, could we use this?

**Comment by eu-genia** [comment]
just corrected above - there are 567 records with finding aids. worth batch importing.

**Comment by PietroLiuzzo** [comment]
An item with an extra with type findingAid for desc has been added to all files.
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Adesc%5B%40type%3D%22findingAid%22%5D

**Comment by eu-genia** [comment]
In the web app, the subtitle "Finding aids" should be printed
