### ISSUE TITLE
findingAids/ leaf string marks

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1130]
In the retrieved findingAid category, there are many descriptions in ES manuscripts of "Red threads are inserted in the right upper corner" and similar, for example in ESakm001. Are these the same leaf string marks that are the subject of the never to be closed #972 ?
@DenisNosnitsin1970 @eu-genia

**Comment by PietroLiuzzo** [comment]
@eu-genia told me that the finding aids in Ethio spare are actually textual additions, markes etc. content related, while the ones in the issue above are binding features. if there is a note about the threads in the finding aid description from EthioSpare, that should go into binding. There is already a PR to the Guidelines (https://github.com/BetaMasaheft/guidelines/pull/19) which would hopefully also close #972

**Comment by PietroLiuzzo** [comment]
perhaps the guidelines varia page should have a finding Aid example which would make clear the distinction from these threads and point to the updated binding page

**Comment by eu-genia** [comment]
they should be corrected by hand in the post-processing of the E-S mss. the ones I have had for now had textual finding aids. one has to go case by case...

**Comment by DenisNosnitsin1970** [comment]
Textual additions for navigation in the text do exist, but they are encoded as extras, as far as i understand. 
"Red threads are inserted in the right upper corner" (= leaf string marks) serve functionally for the same purpose, but are the phenomenon of a different level and should be described. They should not be necessarily described together only because they surve to the same purpose (actually the question is - is it exactly the same not?). It was a point of tension in Ethio-SPaRe descriptions, but at least the information was not lost.

**Comment by thea-m** [comment]
The encoding of leaf string marks has been documented in the guidelines, the discussion on textual additions for navigations (definitions and examples would be good) should take place in new issues or possibly https://github.com/BetaMasaheft/guidelines/issues/42. Ethiospare descriptions, as always, will be continuously adapted by @eu-genia or whoever is working with them.
