### ISSUE TITLE
SewingStations

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1142]
We have a sewingStations type in the bindingDesc but it seems to only take a number. 
The E-S descriptions have "One pair of sewing stations" or "Two pairs of sewing stations" in words. Can we allow words? Or should I reduce it to e.g. `<decoNote xml:id="b4" type="SewingStations">1</decoNote>` ? I am not sure that it is as clear, would prefer to keep words for now, and maybe one could add a value field?

**Comment by ElianaDalSasso** [comment]
Dear Eugenia, 
the schema asks to type a number, which corresponds to the number of holes in centerfold of a quire used for stitching, or the chain-stiched "rows" that can be seen on the spine of the codex. 
Thus, one pair of sewing stations corresponds to 2 sewing stations and two pairs of sewing stations corresponds (most of the times) to 4 sewing stations. 
It is important to encode the number of sewing stations because, even if less common, the structure with 3 sewing stations actually is a structure on two paired sewing stations (the one in the middle is shared). 
You can always specify with words in a general deconote.
`<decoNote xml:id="b6" type="SewingStations">4</decoNote> 
<decoNote xml:id="b7"> The sewing is a chain-stitch on four sewing stations (two pairs).</decoNote>`

**Comment by eu-genia** [comment]
I understand that it is important to have the number but maybe the two things could be potentially combined in one decoNote, something like 

`<decoNote xml:id="b6" type="SewingStations"><unit>4</unit><desc>Two pairs of sewing stations</desc></decoNote>`

**Comment by PietroLiuzzo** [comment]
I agree with Eliana suggestion, there is no need to combine in that special decoNote. @ElianaDalSasso could I perhaps copy the comment above to update with this useful clarification the guidelines?

**Comment by ElianaDalSasso** [comment]
@PietroLiuzzo yes, sure!
@eu-genia I think that the separation between the two things is good, because it gives the opportunity to describe manuscripts which don't have an Ethiopic binding (where sewing stations are not paired).
