### ISSUE TITLE
Macombare item 117 

### ISSUE THREAD

**Issue by AngelaMueller** [BetaMasaheft/Documentation#1152]
There are two different manuscript numbers listed for item 117.
I already filled in the incipit for CAe 3674.
Suhtelen 255 is also mentioned though and I can't find it. Shall I leave it without incipit?

**Comment by thea-m** [comment]
Suhtelen 255 is the record of a manuscript that contains the Miracles of Mary (IVsuhtelen255), not another miracle record, so you can leave it as it is (it does actually contain another incipit for this miracle, which you could of course copy to LIT3674Miracle). 
(Are you working from the [list of cited publications view](https://betamasaheft.eu/bibliography?pointer=bm%3AMacomberMiracles&collection=all)? You can always click on the names of the records there and have a look at their page on the app. Since in this case the record is of a manuscript, you will not find it in the work repo on GitHub, but in the manuscript repo.)
