### ISSUE TITLE
link to NETBible

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1167]
In the text of LIT1367Exodus on the app, the verse numbers link to the English bible (which is very nice), and next to them there is "[link]", which links there as well. Is this a visualization problem or was the double link implemented because people don't click on the verse numbers?

**Comment by PietroLiuzzo** [comment]
comes from the source file, I will have a look to unify the view. the text was provided by Ran HaCohen

**Comment by PietroLiuzzo** [comment]
this is what a verse looks like.
```xml
<l n="1">
<ref target="http://classic.net.bible.org/verse.php?book=Exo&chapter=1&verse=1"/>
ዝውእቱ ፡ አስማቲሆሙ ፡ ለደቂቀ ፡ እስራኤል ፡ እለ ፡ ቦኡ ፡ ብሔረ ፡ ግብጽ ፡ ምስለ ፡ ያዕቆብ ፡ አቡሆሙ ፡ [ለ]ለአሐዱ ፡ አሐዱ ፡ በበ ፡ አዕጻዲሆሙ ፡ ቦኡ ።
</l>
```
the template for tei:l was making the superscript 1 for the verse number linking it to the content of a `ref[@target]`, but then using apply template and matching again ref, which in case there is target prints a link. I have aded an exception to the template for l, so that the link is only on the verse number
