### ISSUE TITLE
bibliography adjustments

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1183]
I have noticed that there are many bibliographical references (I saw them mainly in work records) that don't adhere to our guidelines. I assume that this was part of the Ethiospare manuscript adjustments? I understand that adjusting the bibliography as well would take a lot of time, but, then, it would also be a great improvement (especially when the references consist only of abbreviations which would be not understandable to people not familiar with these works). I have added this to the list of [small tasks](https://github.com/BetaMasaheft/Documentation/wiki/small-tasks-list), because I think a Hiwi could do it or it could be a potential workshop exercise, but maybe it would be possible to integrate this into the workflow?

**Comment by PietroLiuzzo** [comment]
correcting bibliographical records in the zotero library can only be done by us, so, it would be much better if we could fix as we go, for the good of all. this fixing needs a good amount of precision, carefulness and knowledge of what and how the bibliography is used, so I am not sure I would delegate any of it to a student.

**Comment by eu-genia** [comment]
I think @thea-m means that in some cases I moved the bibliography from E-S mss descriptions when it related to works to the work records, but leaving it as is, (or sometimes inserting the info in a comment), without processing properly the XML, so there are undeciphered E-S abbreviations in some files
I wanted to go through this once the mss are all through, but of course someone can start going through the records earlier

**Comment by thea-m** [comment]
I think that for most of the concerned references the zotero entries are already there, it is just a question of inserting the tags. But @eu-genia probably has the best overview on the situation

**Comment by PietroLiuzzo** [comment]
thanks for both clarifications. 
If I understood what is going on correctly, I do not think that moving an issues related to ES mss somewhere else where it will be quite hard to find it again, and thus propagating the untidiness which is present there, is a good practice. we should keep it there and tidy up as we go. Much better would be simply commenting off the part you want to exclude and not correct at this stage. In this way you will have the material you need to correct and move to works once finished with fixing the manuscript structure in the place where you expect it, so with the ES manuscripts which are undergoing reworking.  You will then go through these parts which you want to move to works and achieve that task. Also the some cases/same cases is potentially dangerous and clearly prone to errors in the process. Are you keeping a list of these and why each has been treated differently? I would strongly encourage you to go back to those works where the bibliographies have been moved and harmonise the work, commenting out all wrong bibliographies and keeping a list of the files in which these erroneous bibliography has been copied, so that when you come to that task you will start from those. and then move on with the parts you have commented in the manuscripts.

**Comment by eu-genia** [comment]
as a rule, all is commented out, but in works, where the information belongs, and can be easily retrieved, i will go through the records
(e.g. LIT1103Anapho has now           `     <!-- from ESam007: cp. MQ, “Qǝddāse śalastu mǝʾǝt”, §132; DMEthLit “The Anaphora of the Three Hundred, §132” -->` )

**Comment by PietroLiuzzo** [comment]
cool, as far as you are keeping track of this and the wrong data is not further spread, it will be fine. I am not creative enough at the moment to come up with a method with which I could retrive easily those files where a piece of wrongly encoded bibliography has been copied, but I would be curious to know. I would personally start from the fact that I know you had done this, but it appears there are no change elements stating this change (which is ok) so all I would be left with is looking at your commits to the works repository and look at the edited files one by one to spot where wrong bibliography has been copied over. The simple presence of a comment does not make them easier to find to me, the comment in the form above might help, if used consistently in all instances but as said, as long as you are keeping a list or know other ways, it will be fine.  thanks!

**Comment by eu-genia** [comment]
They are all marked by "from ES" (or already deciphered), no worries.
still, a good and useful task for a student would be to map the E-S list to the Zotero bibl, as not all titles used by E-S is already in Zotero. the list is here https://www.aai.uni-hamburg.de/en/ethiostudies/research/ethiospare/results/data/biblio.html (I only received it from Denis a month ago for the first time! up until then I had no idea what the abbreviations meant..)

**Comment by eu-genia** [comment]
@JanetFre is checking that EthioSPARE bibliography is present in Zotero, thank you!
