### ISSUE TITLE
Baptismal name

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1200]
I was looking for the correcht assigned for a baptismal name in an authority file. I couldn't find it, neither in the guidelines nor in the taxonomy file. Old issues on this confused me. What si the correct value? and where can I find it?

**Comment by PietroLiuzzo** [comment]
> I was looking for the correcht assigned for a baptismal name in an authority file
sorry, I do not understand this. 
A search for baptismal does not give anything in the guidelines, you are right, because the word does not occur in the text. we could add an explicit example for this.
The definition for the value baptismal, which is only a value for the attribute type of persName in the schema can be seen in oXygen/atom directly, and in the guidelines you can find the definition of this value, for example under the persName element 
https://betamasaheft.eu/Guidelines/?id=persName 
The usage of the attribute type in persName is described and exemplified directly in the main page for persons, see e.g. Example 5 and preceding paragraph.
https://betamasaheft.eu/Guidelines/?id=persons

**Comment by SusanneHummel** [comment]
Maybe I was not clear: When searching in the guidelines "Persons" I wa snot able to find the correct name of the value which I have to assign for a "baptismal name" (e.g., "batizmal" (like in the EAE) or "baptismal" or somthing else); in Example 5 is no baptismal name 
I think it would be helpful for the user to find it in the guidelines. Nur ein Vorschlag

**Comment by PietroLiuzzo** [comment]
In the first link I sent you this is given, so the value is baptismal and the definition for it is simply "name given at baptism". If you, using oxygen, enter a persName element and start entering the attribute type, a list of values **should** appear which tells you exactly this, without going to the guidelines at all. It looks like it does not, and I have pushed a commit to make that list visible there

**Comment by SusanneHummel** [comment]
Okay, thank you.

**Comment by thea-m** [comment]
doesn't appear yet for me...

**Comment by PietroLiuzzo** [comment]
yep, should be fine now, but you will have to reopen oxygen to refresh the schema cache there
