### ISSUE TITLE
names of ethiospare cataloguers in catalogue bibliography

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1213]
#1159 
In addition to @thea-m 's request, I would like to suggest that the names of the cataloguers of each manuscript catalogued in the ethiospare database is explicitly mentioned in the "Catalogue Bibliography", as the names of the authors of all other catalogue references are also always mentioned there. Would that be possible @PietroLiuzzo ?
@vitagrazia81 @SophiaD-M @DenisNosnitsin1970 @MassimoVilla @MagdaKrzyz @DariaElagina

**Comment by vitagrazia81** [comment]
This issue and the one opened by @thea-m are very important. I am completely in favour of the ideas proposed.

I)	Concerning the idea proposed by @thea-m . As former member of Ethio-SpaRe and also as a normal user, I would expect in the BM database the link to the specific manuscript in the Ethio-SpaRe database. It is a matter of fairness towards the original/Ethio-SpaRe cataloguer, but also towards the BM cataloguer who worked again on it. It is also a matter of transparency.
This is important in case of Ethio-SPaRe descriptions which are in BM like there were (without any changes, or only with few formal ones), or in case of Ethio-SPaRe descriptions which have been updated, corrected, enlarged by a BM cataloguer, and which therefore appear different in the BM database.
Then, suppose that two different users use, check the same MS description, independently, on the two different databases, and for instance, they want to give the quotation: they will quote the MS description, with the names of the cataloguers, in two different ways (in Ethio-SpaRe database, it is well indicated how to quote a manusctipt and a catalogue description , as “Notes for the User”,  here: https://mycms-vs03.rrz.uni-hamburg.de/domlib/content/below/index.xml).
II)	In addition to providing the link, I agree on what 
@SusanneHummel suggests: in the BM database, the name of the Ethio-SPare cataloguers should be there, mentioned in a more clear way. I would add that there should be a more clear dinstiction between:
-who was the original/Ethio-SpaRe cataloguer (and when, of course);
- who encoded (including the formal changes) the description in BM;
- who, as BM cataloguer, worked again on it, updating, revising the content.

Thank you.

**Comment by PietroLiuzzo** [comment]
@SusanneHummel the entries list all known contributors one by one, eventually with the specification of their role and with a full list of the description of changes, so that each entry is entirely and precisely citable. so, the cataloguer, encoder, editor, contributor, etc, of that manuscript is listed and as far as the information is available, reported in all possible forms. I think it is way better, more precise and easier to quote a ms description from BM than from EthioSpare, but I would be glad to improve the reported information if something is missing. The information listed in the two points by @vitagrazia81 seams to me to be already there and with all possible precision. Of course the application cannot infer what is not in the data. With reference to the indications given in domlib, these are relevant when quoting a manuscript from domlib and their content, and are quite hard to reproduce there, but their content is carried over to BM entirely, and in facts with more and better details. When quoting from BM a EthioSpare manuscripts all places where you can get a citation apply those indications: you get all authors and contributors, access date, link back, even permanent links, which are impossible to get in domlib. 

So, I am not sure that I actually understand where is the issue. Perhaps I would understand more if you could pick an example (providing the ID and eventually a link for convenience), and reproduce here:
- how you would quote the DomLib record (and where you would take the information from)
- how you would quote the BM record
- what is actually not fine in the suggested citation

part of this is related to #1214 in as far as the same information is used to produce the suggested citation (and embedded metadata) and the revisions of the data sections in the web page and in other outputs and formats. The changes for that issue will affect also the suggested citation of the record, by adding more details in the data.

A different matter is the generic reference to the Ethio-Spare  _database_ as a source in the catalogue bibliography, which is the only publication which is in the catalogue bibliography points to this zotero record
https://www.zotero.org/groups/358366/ethiostudies/items/itemKey/WFDU87AX/tag/bm%3AEthioSparehttps://www.zotero.org/groups/358366/ethiostudies/items/itemKey/WFDU87AX/tag/bm%3AEthioSpare
Here you can see that all (?) the contributors are listed. The Zotero Style does not print a list of contributors but only authors and translators, also for this type of bibliographic resource (webpage). You could simply edit the Zotero record, but it would be IMHO untrue to say that all those contributors to the database are authors of the database. I think the indication of the database only is more correct in that context as is, as well as the format of the bibliographic entry as it is. The only thing which we could certainly improve is the reference to the project in this Zotero entry. 
The citation could be improved with the use of citedRange and link to the exact record as requested in #1159 which I will do.

**Comment by vitagrazia81** [comment]
Dear Pietro, concerning the first point: as @thea-m says in #1159, there is now the link to the Project but not to the specific description. I don`t really understand the reason.
Then, concerning the names in the "catalogue bibliography",  the names of the  cataloguers of the specific Ethio-SpaRe MS should be there, as it is for the other catalogue references. The information, like it is now, is for me incomplete.
Then, I asked for a more  clear distinction (s. #1216) in "Revisions of the data" between  the two data:   the original one created in Ethio-Spare and the one created (from the original one) in BM . As it is now it looks like everything was created in BM. All names of the persons involved, with what they did, are listed without a distinction and specification.  It should be specified that what is now appearing in BM is a trasformation of data made originally in another project and by different people.   It would be really precise, infact, if (as already written in  #1216) we could read, in  "revisions of the data", that the original data is an Ethio_Spare description with all other linked information about the original cataloguer, date, etc..  Then, separated by this, and  in addition (as infact it is now), all kind of changes made in BM and who did them.

**Comment by PietroLiuzzo** [comment]
- [ ] I can add, evaluating the date in the attribute `when`, a further indication that the revision before the import are those from ES, no problem, so that it will be more clear which one in the revisions come from there.
- [ ] I will also add a static note to explain that domlib did not have any versioning, so that what is in between creation and last edit is not registered, this will also detail the transformation from ES to BM of the data. it will be a modal called on click.

**Comment by vitagrazia81** [comment]
Good idea. Thank you, Pietro.

**Comment by SophiaD-M** [comment]
First of all thank you all for discussing this matter, and I really like the changes. 
I think it should be made **over** clear to all user of both databases how to correctly use and cite the material. There has just now been this unfortunate case of a German article on the devil in Falascha (STOP USING THIS WORD!) literature, using Ethio-Spare SDM-021 and AP-020 without the proper reference to Denis, Vita or me (who did most of the work on these mss). While it is the responsibility of the scholar to give proper references we should make it very easy and clear for all users on how to use the material.

@PietroLiuzzo the Zotero list of Ethio-Spare members needs to be updated as many people are missing:
Magdalena Krzyzanowska
Daria Elagina
Ekaterina Gusarova
Hagos Abraha (I think he did a few - not sure though)

Verena Krebs and I think also Yacopo Gnisci described objects and should also be mentioned in the list.

**Comment by DenisNosnitsin1970** [comment]
Dear Sophia, Hagos did not do any descriptions.

**Comment by SophiaD-M** [comment]
Thank you Denis, my sleep derived brain was not sure any more.

**Comment by vitagrazia81** [comment]
Also the names of Irene Roticiani and Massimo Villa are missing in the Zotero list.

**Comment by SophiaD-M** [comment]
Ahhh Vita, of cause! I am embarrassed (or tired).
Thank you!

**Comment by vitagrazia81** [comment]
Dear Sophia, thanks to you first :-)

**Comment by PietroLiuzzo** [comment]
@eu-genia could you please update the zotero record?

**Comment by eu-genia** [comment]
sure done
