### ISSUE TITLE
Asmat prayers as main text items and as additions

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1224]
I have had an initial discussion with Pietro. The problem is that when an asmat prayer is an additional item it can be identified as such with a @type entry, but it if is a main item of the text (which it occasionally is in the EMIP collection) then there is no special way of identifying it as an asmat prayer. The suggestion is that we create a narrative unit for asmat, and this narrative unit should be linked to the keyword Asmat, so that both the identified and unidentified texts related to either the keyword generically or to a more fitting narrative unit, either in the main content or as additions in a manuscript, would be picked up in a request for the keyword or the concept.

**Comment by Ralph-Lee-UK** [comment]
I have just come across another case where this is relevant. Should I go ahead an create the narrative item for Asmat, and link this to the keyword 'Asmat' so that these connections may be made?

**Comment by PietroLiuzzo** [comment]
@DenisNosnitsin1970 @thea-m @eu-genia

**Comment by DenisNosnitsin1970** [comment]
You are right, there is no way of identifying it as Asmat-text, but there is no immediate indication to the content also for other "works", except the title (if the record for work is filled properly), and the incipit/explicit. It is assumed that, to learn about the content, one should go along the link to the record for the respective work.  Yes, asmat-prayers can appear as the main content, I don't see anything preventing us to register it as a work with its proper ID. If you do this, however, please type in a good portion of the text, and have a look in the DB on account of the same text appearing somewhere else (the problem is that we do not have enough text in work records, with the consequence that we sometimes create doublets for the same works). Clear, if it appears elsewhere, it is definitely a work. We use "Narrative units" predominantly for parts of a work or for documentary writing. Finally, whatever option you pick, just add a good portion of the text.

**Comment by PietroLiuzzo** [comment]
Denis is right also technically speaking. we do this in work records, so that there is no need to reiterate in a ms. We could however also consider adding an encoding practice which we currently don't use, namely the attribute class in [`<msItem>`, which could result in something like `@class="#asmat"` ](https://tei-c.org/release/doc/tei-p5-doc/en/html/MS.html#msclass)

**Comment by Ralph-Lee-UK** [comment]
These are both really good suggestions. I suppose in the end I am interested because I am thinking of doing a broad project on Asmat prayers, seeking to survey the themes that come up in these prayers. That would require the ability to find all Asmat prayers, including those that are catalogued as main items. In that sense, knowing what I know (which isn't necessarily very much!) Pietro's suggestion seems more straightforward and suits the purpose. How would be proceed to implement this?

**Comment by PietroLiuzzo** [comment]
we could also think to generalise this even more by allowing a search for type of content, which would leave the encoding as is, avoid the counting confusion between attestations of a given asmat (identified) and generic asmat which are only tagged as such in additions or eventually in msItems. however, I am not sure if this is also due to the fact that you perhaps have a main content but cannot identify it with an existing Textual Unit, or be sure enough to create one? in this case you would need anyway the above encoding

**Comment by Ralph-Lee-UK** [comment]
You are quite correct. Asmat prayers vary hugely in content, so it is unlikely that we will encounter two with identical content. Sometimes they are listed as 'main items' in a catalogue, particularly in works that are specifically collections of prayers, so there will not be a specific textual content. They are characterised by the way they are introduced, with a series of names for God - and even these names have a huge variety. That was the appeal of your suggestion of using a 'class' comment.

**Comment by PietroLiuzzo** [comment]
https://betamasaheft.eu/additions?termText=&otherText=&type=Asmat 
https://betamasaheft.eu/authority-files/list?keyword=Asmat
contain lists of asmat but I could not find Textual units with that keyword, which is under the category additiones.

**Comment by PietroLiuzzo** [comment]
I am trying to think what could `@class` contain, but I guess we could stick to anything in the taxonomy which has sense...

**Comment by PietroLiuzzo** [comment]
once we have agreed on this usage, there is nothing preventing you to use it, but we will have to document it in the guidelines and give it a visualization/update existing visualizations. for example I would say this use applies only where a Textual Unit really cannot be assigned or not yet. in view of a study which will then classify and identify these Textual Units, this could be a fair way to temporarily encode what will then be better structured and identified at a later stage. @eu-genia @thea-m @DariaElagina what do you think? @DenisNosnitsin1970 golden advice above remains entirely valid, and should also perhaps become part of this piece of guidelines.

**Comment by Ralph-Lee-UK** [comment]
I hope that we are nearly there. So far, in the work that I have done, I have not come across any two Asmat prayers that are the same, but of course this is possible. The idea that we create a textual unit that is for research purposes is very attractive, and would serve the purpose well, if I am understanding this correctly. At some point I plan to draw all these together in a project that would necessarily involve categorising them and identifying any that are the same. As said above, this would then necessitate the creation of perhaps several textual units. One thing that I have noted is that there is a fairly limited number of themes, so Asmat prayer cover things like 'to win the love of a woman', 'against hail', 'to memorise the psalms' and this would be another way of categorising them. In this sense, Denis' suggestion that we create a work is appealing. As the understanding of the category develops, the work record could be used as a place to give clear summary information about these prayers, and ultimately then find a better way of categorising them. @DenisNosnitsin1970, have I got the idea of your suggestion correctly? Also, as above, what do @eu-genia and @DariaElagina think?

**Comment by PietroLiuzzo** [comment]
I think this is also fitting well with what we already do. It is more from my point of view a matter of encoding process/plan. In the end you will have anyway a Textual Unit for each identifiable text. but until you can do that you want to be able to collect those and classify as asmat without yet creating a Textual Unit. plan could be
- [ ]  allow `@class` in `msItem` also in gl, only for asmat at the moment
- [ ] make searches look also in this attribute when looking for types
- [ ] adapt the taxonomy so that asmat is not only a type of addition and eventually has a subclassification 
- [ ] update the schema with these values

This will allow you to easily encode and have these accessible when you will start your project. To facilitate your future work you may add in those msItems as much information and copy as much text as possible. 
At the stage of starting that project you will already be able to access these both in msItems and additions, although they are not identified, and you will be able to use the standard methodology and add a Textual Unit references as needed. You will then gain a lot of room for classification in the records for the textual units.

**Comment by DariaElagina** [comment]
Just to let you know, I have already created a general record for an unidentified Asmat-prayer: LIT5888AsmatPrayer

**Comment by Ralph-Lee-UK** [comment]
Perfect, I will start using this straight from now.

**Comment by PietroLiuzzo** [comment]
so, I gather my proposition for `@class` ([which has however already been used](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-root%2F%2Ft%3AmsItem%5B%40class%5D) by @DariaElagina ) has been discarded in favour of the creation of a generic Work record. Fair enough! I would have 100% gone for the NARR, as initially suggested by @Ralph-Lee-UK according to our Guidelines, since there is no possibility of a textual comparability. With a Narrative Unit and the association of it to the keyword Asmat (i.e. adding `<relation name="skos:broadMatch" active="NAR0001gwelt" passive="betmas:LandGrant"/>`), you would have add the same configuration available for land grants, e.g. https://betamasaheft.eu/narratives/NAR0001gwelt/main  where, in the Narrative Unit page the manuscripts list on the right contains first the list of mss which contain this as main content and then also the list as additions with the keyword 'Asmat'. We support this direct association between a keyword and a narrative unit only, not with a work, for the reason above. 
Since you all agree this should be a Textual Unit, that is ok for me, and I will not do any of the above. In the same list on the right you will find for Textual Units as LIT5888AsmatPrayer, after the list as main contents also the list of additions related to that identifier (not to the associated keyword, as for Narrative Units).

You may now have
- [a main content related to LIT5888AsmatPrayer](https://betamasaheft.eu/manuscripts/list?contents=LIT5888AsmatPrayer) i.e. you can identify that specific Textual Unit, which happens to be defined as a "generic" record
- a main content related to a Textual Unit (LIT*) which has a keyword "Asmat" (but there is none, although there [are 11 Textual Units which contain the word Asmat](https://betamasaheft.eu/facet.html?query=asmat&type-facet=textual+unit) and which I would expect to be good candidate for this keyword)
- [a secondary content with type "Asmat"](https://betamasaheft.eu/additions?termText=&otherText=&type=Asmat)
- [a secondary content related to LIT5888AsmatPrayer](https://betamasaheft.eu/additions?termText=&otherText=&target-work=LIT5888AsmatPrayer)
- a secondary content related to a Textual Unit (LIT*) which has a keyword "Asmat" (there is none yet)
- [a manuscript which only has a keyword "Asmat"](https://betamasaheft.eu/manuscripts/list?keyword=Asmat) 
- [a manuscript where some descriptive text includes the word "Asmat"](https://betamasaheft.eu/facet.html?query=asmat&type-facet=manuscript)
 
I would strongly suggest to assign the keyword Asmat to Textual Units named as such or described as such and to consider if the use of this keyword for manuscripts is appropriate. This simple step would allow you to unify your work around that keyword. An Additional way to make this a bit more homogeneous would be to systematically add also in additions a Textual Unit identification.
