### ISSUE TITLE
The Spiritual Meaning of the Hebrew Letters of Ps118

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1225]
In the EMIP collection, a frequent item included is the spiritual meaning of the Hebrew letters of Ps118. Can anyone suggest how this should be included in the manuscript description? These are written as superscriptions, so that suggests that they should be written as additions

**Comment by PietroLiuzzo** [comment]
@DenisNosnitsin1970 @thea-m @DariaElagina @eu-genia

**Comment by eu-genia** [comment]
If these are part of the original unit of production, written by the main scribe, they should not be additions, as far as I understand the guidelines

**Comment by Ralph-Lee-UK** [comment]
There are different cases, but usually they are indeed part of the original work. In this case, then, they should be coded as part of the details of a particular item - as a note?

**Comment by thea-m** [comment]
Hi! Do you mean these (in Weiner Codex 21):
![image](https://user-images.githubusercontent.com/19650382/84485777-bf257480-ac9c-11ea-9196-8d5f62fa68c4.png)
To me, they are cleary not secundary additions, they are completely integrated in the main body of the text. So I would definitely not mark them up as additions.
(I am a bit confused because Weiner Codex 3 has the same description, but these texparts are not there:
![image](https://user-images.githubusercontent.com/19650382/84485979-0875c400-ac9d-11ea-91e6-c22fd03b01ce.png))
I could imagine creating a new work ID for a Psalter with these spiritual meanings (or creating a sub-ID in LIT2000 for them, for Psalm 118 with and without spiritual meanings), if these are interpreted as important textual difference. If they are interpreted as belonging to scribal practices, an extra stating their presence could be included. The most simple solution would be a note in the msItem, as is done now.

**Comment by DenisNosnitsin1970** [comment]
Perhaps a special sub-ID would work out better.

**Comment by Ralph-Lee-UK** [comment]
Thanks for all this, and yes I agree that in the majority of cases they are not additions, but a feature. @DenisNosnitsin1970 what would a sub-ID involved?

**Comment by DenisNosnitsin1970** [comment]
As far as I understand, this might be a version of Ps 118. Dorothea, do I understand right that the Psalter is transcribed under LIT2000Mazmur, but it is not distributed into "parts of work" (= individual Psalms)?

**Comment by eu-genia** [comment]
this is not necessary, as psalms have their sub-IDs (LIT2000Mazmur#Ps118); one could add another div with ID e.g. LIT2000Mazmur#Ps118HL for the version of the Psalm with the interpretation of the Hebrew letters

**Comment by Ralph-Lee-UK** [comment]
This looks like a good solution. Does anything need doing before I can use this?

**Comment by Ralph-Lee-UK** [comment]
I think that this is not quite ready for use, is it?

**Comment by thea-m** [comment]
We are just waiting for a Pull Request to be merged. The ID to be used will be LIT2000Mazmur#Ps118Spiritual instead of LIT2000Mazmur#Ps118 (it can also be used in a note with  `<ref type="work" corresp="LIT2000Mazmur#Ps118Spiritual"/>` to refer to this particular psalm, if no complete description with one msItem per Psalm is carried out)
