### ISSUE TITLE
filter for female donors etc.

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1229]
I wanted to use the role filter in the advanced search to filter for female patrons or donors, but it doesn't work, the results show both male and female persons. That's what I did:
![image](https://user-images.githubusercontent.com/19650382/65708721-83576a00-e08f-11e9-99da-9e62945feb97.png)

**Comment by PietroLiuzzo** [comment]
as explained in the form, the role filter will do an entirely different action from a search. I agree, and it is not the first time that this is observed, that this is confusing although there is an explanation. other filters should be at least made inactive if the role filter is selected. However, if this is the expected behaviour I will try to model the search differently, but the issue here is: role is encoded in attestations of a person (persName[@ref][@role]) gender is encoded in the person record.

**Comment by PietroLiuzzo** [comment]
this should be the kind of search which is much easier in RDF. However, the gender information was omitted. I am updating the entire RDF for persons having added foaf:gender  http://xmlns.com/foaf/spec/#term_gender

**Comment by PietroLiuzzo** [comment]
SPARQL will be 

```sparql
SELECT ?person ?role ?gender
WHERE {
?person bm:hasRole ?role ;
              foaf:gender ?gender .
}
```

where ?gender and ?role can be FILTERed. foaf:gender is a literal, bm:Role is a URI

**Comment by PietroLiuzzo** [comment]
reloaded all persons files with gender information

**Comment by PietroLiuzzo** [comment]
the correct query to be added to the search guidelines and example is 
````sparql
PREFIX bm: <https://betamasaheft.eu/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX oa: <http://www.w3.org/ns/oa#>

SELECT ?ms ?person
WHERE {
  ?annotation a bm:donor ;
              oa:hasBody ?person ;
  			  oa:hasTarget ?ms .
  ?ms a bm:mss .
  ?person foaf:gender 'female' .
} 
````

[current result ](https://betamasaheft.eu/sparql?query=SELECT+%3Fms+%3Fperson%0D%0AWHERE+%7B%0D%0A++%3Fannotation+a+bm%3Adonor+%3B%0D%0A++++++++++++++oa%3AhasBody+%3Fperson+%3B%0D%0A++%09%09%09++oa%3AhasTarget+%3Fms+.%0D%0A++%3Fms+a+bm%3Amss+.%0D%0A++%3Fperson+foaf%3Agender+%27female%27+.%0D%0A%7D+)is

ms | person
-- | --
 bm:BAVet79 | bm:PRS11600WalattaI
 bm:ESbmqm003 | bm:PRS10564Zamada
 bm:ESbmqm003 | bm:PRS9840Walatta
