### ISSUE TITLE
something is wrong in BLorient481

### ISSUE THREAD

**Issue by abausi** [BetaMasaheft/Documentation#1233]
I see that the description is underway.

Yet, I do not understand why the dating of the MS is given "1400 - 1500 (dating on paleographic grounds)": (aside from "paleographic" for "palaeographic" we use,) which is the reason for this dating? the manuscript is obviously later; it might go back to a prototype with this dating, but it is a completely different matter; this dating should be corrected and postponed of centuries; this is likely to be a Gondarine manuscript. Wright writes "latter half of the xviith cent.".

Also the note on "Decoration" is unfinished: "The decorations accurately imitate the style and iconography of the earlier Octateuch kept in Amba Gǝšän Maryam ↗ and painted in the " (?).

**Comment by thea-m** [comment]
@eu-genia do you remember anything about the dating? It might have been copy pasted from the record of Orient 490? 
@PietroLiuzzo could you correct the visualisation to "palaeographic"?
The missing sentence end is due to the mark up, where there is <term key="ThirdSolomonicStyle"/>, which is not visualized. I don't remember now whether there was ever any discusscion on the visualization of empty `<term>`s (probably...), in any case, I can correct it when I am back.

**Comment by PietroLiuzzo** [comment]
I fixed palaeography and the term element, which was rendered only in the description and not in the summary. on the dating itself, no clue!
