### ISSUE TITLE
langUsage

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1243]
As noted by @DenisNosnitsin1970 , our generous inclusion of languages which are not used in the record in  `<langUsage>` leads to the fact that it is not possible to get any meaningful results when filtering records by language in the search. He had wanted to search for records containing Amharic works, where the problem could be partly circumvented with the keyword AmharicLiterature. However, I can easily imagine that someone would like to find all records using Amharic, which do not necessarily all have this keyword (for instance with Amharic additions or notes). 
Would there be any way to either fix the languages used in  `<langUsage>` (thousands of records are concerned) or have a filter that only considers the languages encoded everywhere in the records except in `<langUsage>`?

**Comment by PietroLiuzzo** [comment]
The langUsage is used only in some filters, so it wold be useful to know to which ones you are referring and perhaps we can fix the filter form. You are also more than welcome to edit the XML where you feel the langUsage information is not necessary.

Why should Amharic additions and notes not have this marked? is foreign[@xml:lang="am"] not allowed there? or xml:lang="amh" on item or desc?

It is lovely to see you wanting to run queries which are entirely possible but not yet returning sufficiently accurate results due to the state of the data, but that this data is work in progress is a fact which will hardly change before 2040. 

I would suggest to try, with knowledge of the data, to figure out a more precise query, because "records using Amharic" is definitely too vague in any case. what record? a textual unit? an item in a mss? anything which is in Amharic (a note, a part of a text, a word somewhere in a person description?)

I will share here some links and searches which I had already shared with @DenisNosnitsin1970 at the end of September together with some additional ones as they emerge from your post.

- [Xpath query for msItems in Manuscripts which have been marked up with element textLang with either main or other language equal to Amharic](
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3ATEI%5Bdescendant%3A%3At%3AtextLang%5B%40mainLang%3D%27am%27+or+%40otherLangs%3D%27am%27%5D%5D)
- [Manuscripts , Works, etc  marked up with the keyword Amharic literature](
https://betamasaheft.eu/authority-files/list?keyword=AmharicLiterature)
- [Only works with keyword Amharic literature](
https://betamasaheft.eu/works/list?mainname=&date-range=0%2C2000&cp=&clavistype=&clavisID=&keyword=AmharicLiterature&period=)
- [Those Work records which have a div with xml:lang = am](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootW%2F%2Ft%3ATEI%5Bnot%28contains%28%40xml%3Aid%2C+%27IHA%27%29%29%5D%5Bdescendant%3A%3At%3Adiv%5B%40xml%3Alang%3D%27am%27%5D%5D)
- [Those BM Textual Units records which have any element with xml:lang = am](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootW%2F%2Ft%3ATEI%5Bnot%28contains%28%40xml%3Aid%2C+%27IHA%27%29%29%5D%5Bdescendant%3A%3At%3A*%5B%40xml%3Alang%3D%27am%27%5D%5D)
- [Those BM Manuscripts records which have any element with xml:lang = am](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3ATEI%5Bnot%28contains%28%40xml%3Aid%2C+%27IHA%27%29%29%5D%5Bdescendant%3A%3At%3A*%5B%40xml%3Alang%3D%27am%27%5D%5D)
- [manuscripts with additions which contain something tagged amharic](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3ATEI%5Bnot%28contains%28%40xml%3Aid%2C+%27IHA%27%29%29%5D%2F%2Ft%3Aadditions%5Bdescendant%3A%3At%3A*%5B%40xml%3Alang%3D%27am%27%5D%5D)
- [items in Additions which contain something tagged with amharic](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Aadditions%2F%2Ft%3Aitem%5Bdescendant-or-self%3A%3At%3A*%5B%40xml%3Alang%3D%27am%27%5D%5D)
- [manuscripts with the keyword AmharicLiterature](
https://betamasaheft.eu/manuscripts/list?mainname=&date-range=0%2C2000&cp=&keyword=AmharicLiterature&numberOfParts=&height=&width=&columnsNum=&tmargin=&bmargin=&rmargin=&lmargin=&intercolumn=&folia=1%2C1000&qn=1%2C100&qcn=1%2C40&wL=1%2C100&restorations=)

This said, I do not think a change in the use of langUsage is necessary. We can update the filter behaviour to use other indexes and of course we can tag as much as we want these texts so that we get the corresponding results.

**Comment by thea-m** [comment]
Thank you! I was using the language filter in the advanced search (https://betamasaheft.eu/as.html?query=&homophones=true&AttestedInType=1&xmlid=&language=am). 
I assume that additions etc. are correctly marked up. My problem was rather that there are too many "wrong" (in the sense of "wrongly" though in conformity with the guidelines added language to langUsage - the search obviously works well). 
The links you gave are lovely and it is of course possible to run more precise queries. But my search (find all records that use Amharic) would actually be quite simply done with the general filter (and can be done for Tigrinya, French etc. with meaningful results, because these languages were never automatically included in all records), if the languages were added only to the records in which they are used. I see no reason to insist on what seems to me inherited imprecision, for which there were probably good reasons at the beginning of the project. Otherwise the language filter should be removed from the general search (but why, since it does what it is supposed to do, the problem is in the data).

**Comment by PietroLiuzzo** [comment]
we could adjust this with a facet to be used for searches which will check and archive only those values of language/@ident which are actually also used in a @xml:lang, or use the same check to clean up the data. in each file I will check the list of distinct values of xml:lang and delete all language elements which are not english or one of the ones used.

**Comment by PietroLiuzzo** [comment]
I will clean up the data during data freeze this weekend

**Comment by PietroLiuzzo** [comment]
e.g. 

"LIT4636Chronicle -->en <-- attested in xml:lang, but declared en,ar,it,am,gez. Thus falsly declared --> ar,it,am,gez"
2
"LIT4230Conclusion -->en,gez <-- attested in xml:lang, but declared en,ar,it,gez. Thus falsly declared --> ar,it"
3
"LIT4176Prayer -->en,gez <-- attested in xml:lang, but declared en,ar,it,gez. Thus falsly declared --> ar,it"
4
"LIT4206Prayer -->en,gez <-- attested in xml:lang, but declared en,ar,it,gez. Thus falsly declared --> ar,it"

means I should remove the ones which are falsly delcared

**Comment by thea-m** [comment]
Thank you! It will be wonderful!
