### ISSUE TITLE
printing catalogue bibliography from E-S (domlib)

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1251]
1)
The `<altIdentifier>` should not be printed (now in ESbgy004 the catalogue bibliography is printed as 
"MS , BGY-004 TCTA no. 1, 24-08-93 (digitized by the Ethio-SPaRe project), Maṣḥafa gǝbra ḥǝmāmāt “Book of the Rite of the Holy Week”, 1699, Catalogued by Vitagrazia Pisani..."
should be
"MS Ethio-SPaRe BGY-004 (digitized....) etc."

2)
It should be "MS" and not "MS ,"

3)
Possibly because of the altIdentifier (?) there is, at least for ESbgy004, no direct link to the actual description on DomLib

**Comment by PietroLiuzzo** [comment]
I have made the reference more precise, so that the idno is the one in which is accompanied by `<collection>Ethio-SPaRe</collection> `
Ethio-Spare before the identifier etc. is not in the example, so it should not be, and the comma is now in the right place, simply because of the multiple identifier the title of the ms was not printed and thus left blank.

**Comment by eu-genia** [comment]
but the link to DomLib still does not work

**Comment by PietroLiuzzo** [comment]
the value for this examples was not present in the local list, I have added it.
