### ISSUE TITLE
translations of additions

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1262]
translations of additions should be encoded according to the guidelines in `<foreign>`. It is not specified whether `<foreign>` should be contained in `<q>` or follow it. If it follows, it is currently not visualized on the app, for example in a1 in ESamq001. Should the encoding or visualization be updated?

**Comment by PietroLiuzzo** [comment]
I would move the foreign inside q, so update the encoding to match what is recomended in the guidelines (if that is what the gl say)

**Comment by thea-m** [comment]
My issue and the guidelines were on the same level of confusion. The guidelines actually don't say anything on the translation of additions at all (https://betamasaheft.eu/Guidelines/?id=additionsVaria). I was mixed up with what they say on the translation of incipits or explicits, which should use foreign. It is not stated explicitely where the foreign should be, in the example given it is included in the respective incipit element.

**Comment by PietroLiuzzo** [comment]
Yes, there is a bit of mix up.

There where cases in the past where some words inside incipit and explicit where in another language, those must use foreign, also because we want to preserve the fact that there are as many incipit elements as there are actual incipits. I may be forgetting about some further reasoning behind this, but that is the state of things.


In additions, it is perfectly logical to add as many `<q>` as needed, not `<foreign>`

Whilst I do not think that the confusion between incipit is easily generated (and thus adding text to the guidelines would result more confusing), the additionsVaria page definitely needs editing and an example of this which I am committing now, together with a fix to the erroneous example 4 (with a desc in english inside q)

**Comment by PietroLiuzzo** [comment]
there are a total of 12 such cases of items in additions with a foreign with xml:lang after a q
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Aadditions%2F%2Ft%3Aitem%5Bt%3Aq%2Ffollowing-sibling%3A%3At%3Aforeign%5B%40xml%3Alang%5D%5D

**Comment by PietroLiuzzo** [comment]
153 cases of use of multiple q
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Aadditions%2F%2Ft%3Aitem%5Bt%3Aq%2Ffollowing-sibling%3A%3At%3Aq%5B%40xml%3Alang%5D%5D

I will take an example from DSethiop3, although here it seams these second q is not meant as a translation of the previous. which brings to a deeper ambiguity problem: are these two parts of an addition in different languages or two additions? and if we encode translations of additions, how to make clear that the translation is not in the manuscript?

**Comment by PietroLiuzzo** [comment]
we could easily make this distinction with a `type="translation"`

**Comment by thea-m** [comment]
Thank you!
