### ISSUE TITLE
Pages for Patrologia Orientalis - Question out of ignorance

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1283]
I have questions to "books" from the Patrologia Orientalis series, such as this: https://www.zotero.org/groups/358366/ethiostudies/items/itemKey/UAXWZV3G/q/GUerrier

1. Why are they treated as books and not book sections? 
If you click on the link provided in the above example it appears that there is one volume of the PO with several contributions, to my ignorant mind this makes it a book section. And therefore:
2. Why are they given without page numbers? 

And lastly a sidenote, I think in the above example the year should be 1913.

**Comment by FrancescaPanini** [comment]
Hi Sophia,
I think this is a bit more complicated than it looks at first sight and I think the record is correct.

I tend to consider them as separate and not as a book sections because they are fairly different from a chapter. Each of them is defined as a fascicle of Tomus IX of PO, each of them has their own cover,  there are two sets of page numbers (not only the continuous one but also the one starting from 1), and each of them has its own editorial year. In fact, when you look on the second page, you will see that the permis d'imprimer for this book is 1912, hence the date in the Zotero record.
