### ISSUE TITLE
Define "Contributions"

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1284]
When should we add a "Contributor"? 
See example: https://www.zotero.org/groups/358366/ethiostudies/items/itemKey/WK7X6SAT/q/Secundus
Weninger is listed here as Contributor in the title, should he not also be listed as "Contributor" under the "author" sections?

Another example: https://www.zotero.org/groups/358366/ethiostudies/items/itemKey/UAXWZV3G/q/Guerrier
When you follow the provided link to archive.org you see that Grébaut is listed on the title as well. Same question as before.

**Comment by FrancescaPanini** [comment]
Hi Sophia,
I see your point. This is my opinion about this matter:

1) One can and should fill the "Contributor" field in Zotero but this is useful only when one looks in Zotero, because, when you extract the record from Zotero, the information stored in the "Contributor" field is completely lost.

2) In my view, the situation of Weninger and Grébaut is different. Weninger's role seem much more defined and restricted and I think the way in which the record was made is correct. With regard to Grébaut, the record should have been done better as his role went lost. The troubble is (see point 1) that you can and should put him as "Contributor" but this won't be reflected when you extract the record. For this reason in Aethiopica I then must correct manually these cases.

I hope this makes some sense.
