### ISSUE TITLE
Tarika nagast

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1288]
While checking manuscripts for #1281 , I came across several manuscripts containing LIT2422Tarika, where I noticed some issues, related to the fact that I don't really know literature on this work. 
All the manuscripts where we used this ID contain an Amharic text (BNFet144, BNFet145, BLadd16253), yet the work record refers to both a Geez and an Amharic version. Do you know whether a Geez version exists?
The work ID is also used in the record IVEf29, where the entry seems however to refer to a collection beginning with Walda Amid, different from the other manuscripts?
Maybe you can help me with this?
@DenisNosnitsin1970 @DariaElagina @sologebre

**Comment by DariaElagina** [comment]
In IVEf29 I followed a catalogue description, which designates this whole work as Tarika Nagast, but now I see that I have been possibly mislead. I will correct the description asap.

**Comment by DenisNosnitsin1970** [comment]
The title Tarika nagest is a generic one and may be traditionally used to refer to various texts or collections. The problem is that Turaev does not designate where he picked the title: is it used in one of the texts or somehow as the title of the entire manuscript, or it is the title supplied by Turaev (perhaps the most probable).
