### ISSUE TITLE
disappearing of the encoded portion

### ISSUE THREAD

**Issue by nafisa-valieva** [BetaMasaheft/Documentation#1291]
Hi, Pietro, there is an issue indeed, I am sorry for this.

which records or views are affected? DabraLibanosHamGG1

on which branch are you? manuscripts, Nafisa_GG1

what is that you are trying to do?
I was encoding the content, while I was changing from English into geez here
`<div type="edition"  xml:lang="en" corresp="#p2_i2">`
just when I started to write geez with latin lettres, having english as default, I lost everything what I have encoded up to here ጾሮ፡ወጻላhቶ፡ሞቱሂ፡
so as you could probably see, several steps ago I was changing one lettre into a different equivalent lettre in geez. I did not encode it as h, "h" has just "eaten" my work.

I have tried to repeat this and I could proceed once less, once more, but with a certain command I would come to the very same place, where I just changed a lettre.
I have had this problem since the very beginning of my work on Ham, it seems to me somehow related to the change of a language. 
what have you tried ?
I have tried sometimes to write either in a different file or outside the tag, it helps but from time to time I try to change a lettre or something else and loose my data. 
I have tried to save the portion and then proceed, but in this case "save" command does not help, it jumpes anyhow back into time. It happens only for content encoding, it never happens for description encoding. 
If there is a guidelines page please add link.
there is no page to my knowledge, I guess something is wrong with my Atom settings. 
if you get an error, which error do you get, just copy it here
I do not get any error.
I hope you can help me with this!
ciao
Nafisa

**Comment by thea-m** [comment]
I am sorry, I cannot immediately grasp the problem. Let me try to rephrase it so that you can correct my mistakes of understanding (please be patient).
You were working in the Nafisa_GG1 branch, in the manuscript record DabraLibanosHamGG1. You were adding the transcribed text of msItem p2_i2 in fidal in `<div type="edition" xml:lang="en" corresp="#p2_i2">`. Because English is your default language, when you started typing, Latin letters came, which you immediately noticed. You switched your input language to Geez, and while this switch took place, you lost previously encoded text (and presumably the Latin characters you just typed, but these were not meaningful anyway). I do not exactly understand whether you only typed "h" in Latin, and the problem occurred when you switched keyboard to correct the "h", or at an earlier or later stage.
The last version of this file that I can access is this here, which is 14 days old: https://github.com/BetaMasaheft/Manuscripts/commit/928758ff2c890cc87e7954559496e87aff0e16e9#diff-93bf7b63d3fdcc6fb5bb5db6014f0780
(if you click on expand down at the bottom left of the view of the record, the entire record will become visible)
I cannot see any commits younger than 14 days, not even ጾሮ፡ወጻላhቶ፡ሞቱሂ፡. Did you only work on your computer without committing to your branch?

**Comment by PietroLiuzzo** [comment]
Well, in either formulation this sounds quite interesting.
My best guess here is that the keyboard combination you use to switch language is in conflict with some short cuts (keybindings) in Atom. Do you use a keyboard combination to change from english to amharic?
