### ISSUE TITLE
multiple edition text display

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1309]
Of the text given in the record of LIT1758Lefafa, only the two first sections are printed in https://betamasaheft.eu/works/LIT1758Lefafa/text, and I see no possibility of choosing other sections to read, as is usually the case in this view.
In the edition in the record, the same numerical value is often used twice in @n,  but otherwise everything seems normal to me.

**Comment by thea-m** [comment]
same for LIT1709Kebran

**Comment by PietroLiuzzo** [comment]
This is quite an issue. I found out a bug, which I have worked around to get at least the text displayed. The code was wrongly checking the number of primary divisions in the first edition. now it looks at the div[type=edition] with most textparts and uses that for the maximum number of parts. Then for each edition it makes a column splitting the available space and prints the primary divisions.

This is far from being optimal of course, to name one reason only because it imposes to navigate all editions together based on the one which has more divisions and unduly puts side by side things which may not be. 

I think we need to specify how to deal with this multiple edition at view time. for example we could specify a list of possible editions and defer the display to a further view, or list in the text options already the available editions and provide a text view for each. This would however require some form of identification of each edition. I could use the corresp if based on some item in the bibliography and I could use "default" for the one without any further specification.

what do you think @thea-m @eu-genia @DariaElagina @DenisNosnitsin1970 ?

**Comment by eu-genia** [comment]
Still does not work for LIT1709Kebran?

**Comment by PietroLiuzzo** [comment]
as explained, it does not, we need to decide how to do this before I procede to fix. the workaround was only to make the text visible

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/Documentation/issues/1339
perhaps here the solution is really to base this on dynamic visualization querying DTS API

**Comment by PietroLiuzzo** [comment]
a complete redesign of text view, affecting both transcription of mansucripts and editions of texts, is needed, which will allow to 
- [ ] select one among different editions, 
- [ ] provide navigation options based on different structures present
- [ ] fetch and display images
- [ ] collapse away bibliography, etc.
- [ ] provide links back to indexes
- [ ] etc
needs further examples and investigation

**Comment by PietroLiuzzo** [comment]
- [ ] navigate sections as in perseus
- [ ] offer for each visualised fragment citation uris (DTS)

**Comment by PietroLiuzzo** [comment]
the text viewer should allow any passage URI to be resolved, and provide evidence of the passage citation structure as in Perseus, to allow citability.
requests to the DTS URN should eventually return the passage or the navigation endpoint
https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-refsDecl.html

**Comment by PietroLiuzzo** [comment]
an Xquery module parsing requests to a DTS API, would allow to surface in our editor any DTS text

**Comment by PietroLiuzzo** [comment]
but would create great redundancy in calls: my TEI which is now simply transformed, would be called by the DTS module, which calls zotero and sparql via http, eventually even more over title requests and which is called by an http request by another module. it is a lot of layers. but the same could point to a DTS API from Syriaca e.g.

**Comment by PietroLiuzzo** [comment]
I have done some major changes to the text visualization, allowing not only to better navigate our few, but increasing texts, but also eventually to load external DTS texts, as well as resolve citable uris.

the default view is now on the entire text available. if can be filtered down from the navigation on the side, which provides the first available level of nested references.
<img width="986" alt="Schermata 2020-06-14 alle 18 08 30" src="https://user-images.githubusercontent.com/508012/84598313-19276500-ae6a-11ea-9686-668591e610d3.png">

if no edition is specified, a list of available editions and translations will be provided at the top (to be viewed in a separate window) and all edition nodes will be shown, as they occur in the file.

a specific edition can be reached, clicking the button, or by either appending a parameter edition or attaching to the id a string with this format _(ED|TR)_(xmlid), so, for the example above _ED_editionBudge or _ED_ for example.  
<img width="825" alt="Schermata 2020-06-14 alle 18 35 05" src="https://user-images.githubusercontent.com/508012/84598840-d49dc880-ae6d-11ea-8f34-3aa5b73990d9.png">

passages can be navigated in their context. if `@n` is used, then that will be used as a pointer, otherwise `@xml:id`, or a concatenation of `@subtype` and @n or of the `@n` of `pb` and `cb`.

available references liste on the side bar are also directly reacheable, and the direct link is shown in a tooltip on the reference and below, clicking on DTS URI for the current view.
<img width="423" alt="Schermata 2020-06-14 alle 18 38 58" src="https://user-images.githubusercontent.com/508012/84598900-53930100-ae6e-11ea-9ca4-d0772a8dde9c.png">

it is possible to navigate, and use a uri as poitner, to the correct passage in multiple ways.
https://betamasahef.eu/EMIP01859.1.1.1 will lead to the commemoration of Barkisos as much as 
https://betamasahef.eu/EMIP01859.month1.day1.NAR0019SBarkisos, although the navigation will always offer `@n` if available.

<img width="689" alt="Schermata 2020-06-14 alle 18 42 23" src="https://user-images.githubusercontent.com/508012/84598961-cd2aef00-ae6e-11ea-9880-01a14ae1b58e.png">

This will be available with the next release.

**Comment by PietroLiuzzo** [comment]
(the screenshots to not have correct titles printed, this is simply due to my local set up)

**Comment by PietroLiuzzo** [comment]
- [ ] check that collate.xqm uses these
- [x] fetch and display images (done the old way)
- [ ] collapse away bibliography, etc.

**Comment by PietroLiuzzo** [comment]
also support for quotations needs to be updated, to make linked texts actually linked
guidelines need to be updated to say a xmlid is very useful on edition and translation and how the referencing of passages works

**Comment by PietroLiuzzo** [comment]
locus elements, where some transcription is available can transclude that directly
also ID.1-2 is supported, matching start and end of a selected range

**Comment by thea-m** [comment]
Thank you, it looks good and really easier to navigate!

**Comment by PietroLiuzzo** [comment]
for navigation
BLorient718.1 gives the folio 1
BLorient718.1r gives the recto of folio 1
BLorient718.1ra gives column a on the recto of folio 1
BLorient718.1ra1 gives the first line of column a on the recto of folio 1
BLorient718.1ra1-1ra3 gives line 1 to 3 of column a on the recto of folio 1
BLorient718.1ra1-2vb6 gives from line 1  of column a on the recto of folio 1 to line 6 of column b on the verso of folio 2
also BLorient718.1.1 can be used to point to a line, if this is uniquely identified with `@n`
in collatex these can be further limited to the first occurrence of a string with `@`

https://github.com/BetaMasaheft/Documentation/issues/1162

**Comment by PietroLiuzzo** [comment]
<img width="1537" alt="Schermata 2020-06-15 alle 23 42 24" src="https://user-images.githubusercontent.com/508012/84709062-e52f6b00-af61-11ea-988d-914c22bd7e59.png">

**Comment by PietroLiuzzo** [comment]
`<locus from="1ra1" to="5vb2"/>` when some text is present in `div[@type='edition']`
will become
<img width="111" alt="Schermata 2020-06-16 alle 20 00 23" src="https://user-images.githubusercontent.com/508012/84810744-0b114a00-b00c-11ea-9d60-c1e520a73894.png">
where the icon links to the selected text from the transcription in the text view in another tab
