### ISSUE TITLE
more collation help

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1317]
Is there a way of encoding the presence of a single leaf sewn to a stub?
This is the quire structure, but f. 10 is sewn to the stub
```xml
   <item xml:id="q3" n="2">
                                 <dim unit="leaf">4</dim>
                                 <locus from="9r" to="12v"/>
                                 3, stub after 1
                              </item>
```

Thank you!
@DenisNosnitsin1970 @PietroLiuzzo

**Comment by DenisNosnitsin1970** [comment]
I would say, you indicate (leaf 2 = f. 10)
"2, added" if it is added later, 
or 
"2, no stub" 
if the double leaf was originally constructed of two single leaves.
As far as I understand, there is no way to indicate in the scheme how the single leaf is fixed in the quire technically, 
you can only make a comment.

**Comment by thea-m** [comment]
Thank you!
