### ISSUE TITLE
EMIP Pages crashing

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1332]
The following pages in the Tweed collection crash

https://betamasaheft.eu/manuscripts/EMIP01970/main
https://betamasaheft.eu/manuscripts/EMIP02000/main
https://betamasaheft.eu/manuscripts/EMIP02020/main
https://betamasaheft.eu/manuscripts/EMIP02052/main
https://betamasaheft.eu/manuscripts/EMIP02055/main
https://betamasaheft.eu/manuscripts/EMIP02072/main
https://betamasaheft.eu/manuscripts/EMIP02077/main
https://betamasaheft.eu/manuscripts/EMIP02086/main

The code appears to validate in Atom, and I have done some basic checks, so I am unclear as to what the problem is. Any help most welcome!

**Comment by PietroLiuzzo** [comment]
all these are inconsistencies in the collation. In the new version there will be better error reporting about this, I will comment out in the app (not in the source!) the parts which are failing

**Comment by PietroLiuzzo** [comment]
https://betamasaheft.eu/manuscripts/EMIP01970/main 

the following is not possible, because if the total is three and there are two stubs and two singletons, then we do not have anything accounted for the third leaf
`````xml
<item xml:id="q1" n="a">
                              <dim unit="leaf">3</dim>
                              <locus from="i" to="iii" facs="001"/>
                              <note>Folio stubs are visible before <locus target="#i" facs="001"/> and between <locus target="#i #ii" facs="002"/> and <locus target="#ii #iii" facs="003"/>.</note>
                              Protection Quire:
                              1, stub after 2
                              3, stub before 1
                            </item>
`````
I do not personally see in the images a stub before 1, and 1 with a stub after 2 would require 2 to have a stub as well, which is not declared. from the images however this does not seem so. I would go for 
1, stub before 2 
2, stub before 3
3, stub before 1 
which is the correction I hard coded in the app (if fine you can reproduce it and commit to your branch)

https://betamasaheft.eu/manuscripts/EMIP02000/main
in quire 1, if there is a stub of i after  folio 10, the quire has actually 11 leaves, not 10 as it is currently. the diagram will not display correctly due to the well known issue of the use of numerals for protectives. I have hard coded this change in the app, it will have to be replicated in your branch 

https://betamasaheft.eu/manuscripts/EMIP02020/main
here 1, no stub can be safely omitted, since the "quire" has already been declared as consisting of one leaf

https://betamasaheft.eu/manuscripts/EMIP02052/main
"quire" 1 consists of two loose leaves. we cannot define them as added because they are added to nothing. you could consider adding them to the the following quire, I have only commented out the two added declarations.

 https://betamasaheft.eu/manuscripts/EMIP02055/main
the quire causing problems is the last one, I have only commented it out in the application, please check with the photos to fix.

https://betamasaheft.eu/manuscripts/EMIP02072/main
the description of one leaf as a quire is not working in q1, I have commented out the 1, stub after 1 declaration, and at least it does not break all and reports that it cannot produce the graphs.

https://betamasaheft.eu/manuscripts/EMIP02077/main
I think the four stubs are after 8, not after 7. the total count of leaves is actually 8. I have hard coded this change which, if correct, you will have to reproduce in your branch

https://betamasaheft.eu/manuscripts/EMIP02086/main
the problem is in quire 6, I actually cannot find out from the images where this stub is and I change it to a stub of the fifth leaf, but the issue was with the leading space in @facs

**Comment by PietroLiuzzo** [comment]
@Ralph-Lee-UK please note that these changes are now all gone, because they have not been reproduced in the branch before the PR. I can make them and push them to your new branch. please let me know when you have a new branch

**Comment by PietroLiuzzo** [comment]
please also note the suggestion in #1347 which uses `ref` and not locus to indicate the item. I can make that change for you and commit it to the new branch

**Comment by Ralph-Lee-UK** [comment]
Jonah. Can you take a look at these issues with the quire descriptions?

**Comment by Ralph-Lee-UK** [comment]
Pietro, I have included Jonah here so that he can see the problem with the quire descriptions. We have a new branch now, which I will make a pull request on tomorrow in the evening (or possibly Thursday morning as I will be out most of tomorrow). Are you able to make the edits again now?

**Comment by jonahsandford** [comment]
I can see that some of these errors are due to my own bad counting. I will
take a closer look at these in the next couple of days.

--
Jonah Sandford, MATS
Adjunct Professor of Greek
Portland Seminary
Phone: (208) 651-0225

**Comment by PietroLiuzzo** [comment]
if changes have not been made, I will make them before merging. no worries!

**Comment by Ralph-Lee-UK** [comment]
I have just looked at these files, and while they don't crash any more, the main page is blank. The image viewer works, but there is no data on the main page at all. The xml files seem to be in order. Can you check whether there are any problems that I should be dealing with?

**Comment by PietroLiuzzo** [comment]
until those things are fixed and merged into master, and I have not yet managed to look at your pr from yesterday, in case the fixes are there, they will look like this. this is better than the  ugly error page, but still the error is there.

**Comment by Ralph-Lee-UK** [comment]
Got it! I think Jonah has looked at them, but we will see. Thanks for clarifying

**Comment by PietroLiuzzo** [comment]
should all be fine now

**Comment by Ralph-Lee-UK** [comment]
Perfect!
