### ISSUE TITLE
add ʿāmata qamar to calendar

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1336]
I would like to add the value qamar (for ʿāmata qamar) for @calendar in the schema.
Do you agree? @DenisNosnitsin1970 @DariaElagina 
Related - why is the calendar section in the schema commented out? @PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
I cannot find a reason back in the schema repository history for this being commented.

**Comment by thea-m** [comment]
thank you!

**Comment by thea-m** [comment]
@PietroLiuzzo could you add the value "qamar" with desc ʿĀmata qamar (Year of the Moon – variant of ʿĀmata məḥrat according to the 532-year cycle)?

**Comment by thea-m** [comment]
thank you!

**Comment by DenisNosnitsin1970** [comment]
Sorry, why  ʿĀmata qamar is "year of the moon"?

**Comment by thea-m** [comment]
In this case, mainly because the EAE says so :) Would you suggest a different translation?

**Comment by DenisNosnitsin1970** [comment]
Aha! Could you tell me where?

**Comment by thea-m** [comment]
I, p. 733b

**Comment by DenisNosnitsin1970** [comment]
It is not quite correct. First, it is said to be a variant of the term "Amata mehrat", second, it means more or less what is indicated in EAE at the same place: year according to the 532 year cycle, the cycle is called "qamar". 
"Amata qamar" means just "year of the (532 year) cycle", or plainly "year of the cycle". It can be obviously applied to the Era of Diocletian, which is also counted with 532 year cycles. EAE I, p. 734a gives an example of a colophon. But we only deduce that writing "Amata qamar", the scribe meant "Amata mehrat" because the year 288 of Grace corresponds indeed to 1711/12, that date provided according to two other eras.

**Comment by thea-m** [comment]
Good, how would you suggest we proceed? Could you change the definition in the schema?

**Comment by DenisNosnitsin1970** [comment]
We can have ʿāmata qamar as "year of the (532 year cycle)" or qamar as "(532 year) cycle", why not. Qamar as 532 cycle fits at least two eras: Era Diocletian/Martyrs and the true Era of Grace (that starts 76 years after the Era of Diocletian).  Despite that one example, I would not fix "amata qamar" as equivalent of "Amata mehrat", it can be a bit confusing.

**Comment by thea-m** [comment]
Did you have a chance to look at the other calendar values? So that in case there are other things you would like to edit we can do it all in one go.

**Comment by DenisNosnitsin1970** [comment]
Is it urgent? I cannot do more than 3 things at the same time.

**Comment by thea-m** [comment]
of course not. I'll just reopen then so that we won't forget.
