### ISSUE TITLE
Encoding the presence of textile inlays in bindings

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1337]
@DenisNosnitsin1970 has noted that it would be desirable to be able to search and filter for the presence of textile inlays. These are currently encoded in free text in a decoNote in binding (`<decoNote type="Boards">`, if used). I was wondering whether it would be possible to simply create a "inlay" keyword, in analogy to the other keywords which can be used in the binding description (for example mirror)
What do you think? @DenisNosnitsin1970 @PietroLiuzzo

**Comment by thea-m** [comment]
Any thoughts on this? :)
@eu-genia  @DariaElagina

**Comment by DariaElagina** [comment]
That would be a good and easy solution, I think. However, it would provide with the possibility to filter the existence of an inlay, but not its material, as far as I can understand

**Comment by eu-genia** [comment]
Makes sense to me. We could use textile as a keyword too (should already be there). 
Btw how do we encode protective textile "curtains" sewn onto pages?

**Comment by thea-m** [comment]
Good, then we'll work with keywords. Which materials can occur? I have seen cotton (or what I take to be cotton...), silk and velvet. Are there inlays not made of textile? We could in principle create keywords for each of them (and one general "inlay" one for cases where we cannot identify the material or don't have enough information), taking care that filtering for "inlays" will then bring as results all the more precise ones as well. 
Good question about the "curtains" - does anyone know if they are known under an established terms? I believe I have only seen those over decorations, which might indicate that we could describe them with those (but my selected experience is restricted).

**Comment by DariaElagina** [comment]
I would rather just use textile, otherwise there might be a lot of confusion. Velvet is a type of fabric which might be produced out of silk or cotton. In case of satin fabric the material is also not obvious. So, there might be a lot of confusion.
I think there are cases with paper inlays.

**Comment by DenisNosnitsin1970** [comment]
Yes, textile as general is better. Only a specialized person can distinguish between the types of historical textiles. To catalogue them is more difficult then to distinguish between parchment types (though both are desiderata).   What we can state is only is the way it is coloured, maybe. But they are normally coloured (uncoloured are rare, mono-coloured also not frequentl).

**Comment by thea-m** [comment]
@DariaElagina you are right, we even have several records with paper inlays. Good to know!
I would now tend to create the keywords Inlay, TextileInlay and PaperInlay, and to state further information as to kind of textile, colour etc. in free text. What do you think?

**Comment by DenisNosnitsin1970** [comment]
A few manuscript have parchment inlays.

**Comment by eu-genia** [comment]
Here they speak of protective "curtains" https://www.getty.edu/art/exhibitions/shrine_shroud/, https://www.themorgan.org/manuscript/119041, so does Scheper in her book on Bindings, but it does not seem to be an official term, many codicological books speak of pieces of cloth sewn onto parchment to protect miniatures, without introducing any particular term at all. Yet "curtain" sounds like the best take for me.
Yes, this is a way to protect illuminations, but is at the same time part of support.

**Comment by thea-m** [comment]
Then let's go for "protective curtains" with explanations. I'm not sure whether I would consider it part of the support, because it is clearly added later to protect something written/drawn on the support. I would tend towards a keyword to be used the the description of the protected decorations.

**Comment by thea-m** [comment]
The inlay keywords have been created, open remains the issue of how to encode protective curtains sewn above decorations (or other places?). 
Would you encode this information with the support or decoration description?
@DenisNosnitsin1970 @Gnisci

**Comment by DenisNosnitsin1970** [comment]
I think it better fits decoration.

**Comment by Gnisci** [comment]
Where the information is encoded does not seem to me so easy to determine. I am not sure about placing keywords in the art keywords/art themes sub-sections of the keywords as I don't see the conceptual link: there is an obvious physical link to the miniatures - but it's the same kind of physical link between the content of a manuscript and its wooden boards.

Also, somewhere down the line, researchers might one to draw connections between the types of textiles used for lining and as protective curtains (I think the term works well), so I believe it would be important to create an approach that leaves the door open for that kind of future development.

So, as I see it, it's a matter of balancing out two things: a) the need to not create too much extra workload for encoders (as there is already so much to be done and known for each manuscript); b) a need to think about where this information could be better placed for these developments further down the line. For sake of simplicity and a), since there will be typically overlap with the location of the miniatures or illustrations it could be tempting to just place a keyword within that description, but for sake of b) I am not sure this is the ideal solution?

(I might be stating the obvious here, sorry!)

**Comment by DenisNosnitsin1970** [comment]
Understanding all this, I still think it better (provisionally at least) fits "decoration", to be bound to each item where this device is used.

**Comment by thea-m** [comment]
Thank you, everyone, very helpful! I will create the protectiveCurtain keyword, which can then be used by anyone where they deem it fits best within their own description. There is no need to overregulate, I think.
