### ISSUE TITLE
use of ETH records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1348]
While going through the relation problems, I saw several instances of ETH records used to relate to places or a language. I have never really worked with them and might have missed decisions on their use, however, I could also not find these decisions documented in the guidelines.
The cases I saw are: 
1. `Its national language is <persName ref="ETH2126Tegren">Tǝgrǝññā</persName> ` in LOC5932Tegray
1. ` <relation name="gn:locatedIn" active="LOC6901Kareb" passive="ETH2288Yabesho"/>` in LOC6901Kareb
1. `<note>possibly identifiable with the <ref type="place" corresp="ETH1149Argobb">Argobba</ref>`  in LOC6818Agurba
1. `<placeName ref="ETH1085Aggabe" xml:id="aggabe">` in LIT5019MonumentumAdulitanum2

1. `<relation name="saws:isRelatedTo"
                         cert="medium"
                         active="LOC6830Awesa"
                         passive="ETH1171awsa"/>` in LOC6830Awesa

I think it would be helpful to include this in the guidelines, with some specifications on how to decide whether to use an ETH record.
@eu-genia @PietroLiuzzo

**Comment by thea-m** [comment]
old saws relations in my examples, but the main point remains :)

**Comment by PietroLiuzzo** [comment]
I think what has always been confusing here is that we keep ETH with persons. However, this also has its point, especially for people which cannot be associated even generically with a specific place.

about the points above 
1. I think the use for language is just wrong.
1. I think can only be valid if inverted: I understand a people located in a place, I struggle to understand a place located in a people. It is the only case I could find, I think it can simply be reconsidered.
1. I do not see an issue here, this is just a simple use of ref, as any other. I do not see the need to add this statement, or to identify a people with a place, but well, [we have 2 instances](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-root%2F%2Ft%3Aref%5B%40type%3D%27place%27%5D%5Bstarts-with%28%40corresp%2C+%27ETH%27%29%5D) both by @eu-genia perhaps she can share what the annotation means and we can document that usage in the GL.
1. Also in this case I do not see an issue or an under documented case: a placeName is marked because it is so in the text and a reference is given to a people because it is an Ethnonim. here, as noted above, is only that we keep ethnonyms with persons, which should not however prevent us from being accurate in the markup and use of the authority files.
1. we do not have the latter any more
once fixed the two instances requiring a fix I do not think we lack documentation here

**Comment by eu-genia** [comment]
1. - agree this is plain wrong, must be corrected
2. -5. I believe are part of the same issue, which was discussed in several meetings at the onset of the project: how do we distinguish ethnonyms and regions inhabited by peoples, whether we create additional records, etc. etc.
The decision at that point was - no there is only one record, for the people, which may also be used as place name when the context speaks of the area inhabited by the people.
We have Gurage both for the people and the "land of Gurage".

**Comment by PietroLiuzzo** [comment]
`<placeName ref="ETH"/>` = land of 
`<persName ref="ETH"/>` = people 
?

**Comment by eu-genia** [comment]
precisely

**Comment by PietroLiuzzo** [comment]
should we document this last distinction then?
