### ISSUE TITLE
AT or keyword for representations of the cross?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1362]
We have the (art) keyword record "cross" and the Art Theme "AT1071Cross" ("The artistic representation of the `<ref corresp="TrueCross" type="authFile">True Cross</ref>`"). Which one would you suggest using in cases where the catalogue says something like "on f. x is a cross"?

**Comment by Gnisci** [comment]
Cross appears as an object in a lot of ATs but, I think it very rarely appears in a miniature together with the other instruments of the Passion (which is what I assume this AT was created for). The keyword cross does allow you to flag up all those instances where it appears but it is not Art Theme "AT1071Cross", which is why I crated the keyword at the time and it does also allow you to distinguish between an illustration/drawing and a scribble of a cross (if such a distinction is accepted within you general operational system).

**Comment by thea-m** [comment]
Thank you. I will go with the keyword then.
