### ISSUE TITLE
accessing BM links

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1380]
When clicking on a link to BM in a word file, this window opens:
![image](https://user-images.githubusercontent.com/19650382/78156336-f5de4380-743e-11ea-9bfe-3449c53e0ca5.png)

After typing my information, I can access the link normally, but it would of course be better if this wouldn't happen. I don't know if it is related to the website's security or my computer?

**Comment by PietroLiuzzo** [comment]
I would be very curious to know what the link is... and where does it actually points....

**Comment by PietroLiuzzo** [comment]
in general this is what should happen for pages which are protected in the backend or under password, for example, if you try to add a link to the page for the creation of new entries this is exactly what should happen, as if you point to a specific port.

**Comment by thea-m** [comment]
It has happened with all links I recently clicked on in word, which, I think, all happened to be links to work records. These were the most recent ones:
https://betamasaheft.eu/works/LIT2908RepCh189/main
https://betamasaheft.eu/works/LIT2736RepCh20/main

**Comment by thea-m** [comment]
Ah, no, they were all completely public pages

**Comment by PietroLiuzzo** [comment]
I have just created a word file, added these links, saved, closed, opened the file and clicked on the links and this did not happen at all. could I please have a copy of the word document you are using?

**Comment by PietroLiuzzo** [comment]
and which user and password did you use to access, the bm ones?

**Comment by thea-m** [comment]
This one is a private one not by me, but if you open the attached document in the last mail to Wendy Belcher, the same thing happened there

**Comment by thea-m** [comment]
Yes

**Comment by PietroLiuzzo** [comment]
I have clicked all links in there and got no issue, I am afraid it is your windows setting. I will try from another pc as well

**Comment by PietroLiuzzo** [comment]
I cannot test on the pc. please @DariaElagina, @eu-genia and @DenisNosnitsin1970 could you try and do the same test I did above and let me know? it takes a minute.

**Comment by thea-m** [comment]
If it's only my settings, it's not so dramatic :) I was just wondering because it's the first time I noticed something like that happening (and it did consistently with BM links).

**Comment by PietroLiuzzo** [comment]
I cannot know without at least another test. If you have another pc in your house you could also try that and see what happens.

**Comment by DenisNosnitsin1970** [comment]
It works, as I can see.

**Comment by DenisNosnitsin1970** [comment]
Ok, yes, it is the same as above, with window.

**Comment by PietroLiuzzo** [comment]
sorry @DenisNosnitsin1970 I do not understand where the above points to. you have the same issue and see the same request for password  as dorothea? could you please both also try to open those in a normal browser?

**Comment by PietroLiuzzo** [comment]
I have tried also from libre office, google docs, as well as pdf, and I cannot reproduce this issue. Please try clearing your cache in all browsers if you have not done so already, and check if word itself has settings related to the opening of specific domains, e.g. betamasaheft.eu...

**Comment by DenisNosnitsin1970** [comment]
Yes, I did what you asked. I opened the link through a word document, and got that window. I was able to login, though.

**Comment by PietroLiuzzo** [comment]
thanks, the website is entirely open and this request for password should not come from that. I really do not know why your word asks you for user and password, and I am still unsure what user and password you gave in, if that of bm or that of your computer.

**Comment by DenisNosnitsin1970** [comment]
Now I login with my lap top password. It just forward me to the BM site.

**Comment by PietroLiuzzo** [comment]
thanks, that is very helpful, if the user and password you used are those of your laptop, than it is not BM which asks for these but your local software.

**Comment by DenisNosnitsin1970** [comment]
Now i did not enter anything, just clicked OK, and was redirected to the BM site.

**Comment by PietroLiuzzo** [comment]
thanks

**Comment by thea-m** [comment]
I am very sorry for having opened this issue. I had first used the BM user name and password and now tested with a nonsense one and all works

**Comment by PietroLiuzzo** [comment]
why should you be sorry? this is an important issue, potentially affecting a lot of people. If it is the server is actually causing this, I have to find out where and why as soon as possible and fix it, but since I am not able to reproduce this behaviour to test,  I need your help.
the expected behaviour is that a link simply opens. you should not be asked anything. Another matter is if your software is asking for that and this does not depend on the server, which is what I am trying to understand. 
it looks like this is the case for @DenisNosnitsin1970 , I am not sure about you, the nonsense password test which makes all work is a bit puzzling for me

**Comment by thea-m** [comment]
As I understood Denis, he had first used the BM password and then the computer password and bóth worked?

**Comment by eu-genia** [comment]
I get the same window, but I am pretty sure it is a Windows Security issue since Windows10/Office16. You don't have to enter any password though, if you click Cancel/Abbrechen the web page opens just as well.
I have both Office13 and Office16 on my laptop - I get the popup in Word16 but NOT in Word13. The software looks the same but is very different (only Word16 is recognized as an "App" by Win10).
I can try to explore whether one can disable the feature

**Comment by eu-genia** [comment]
For the moment I am not very optimistic, as the TrustedCenter options that were available in earlier Office versions are not available in newer versions https://support.microsoft.com/en-us/office/enable-or-disable-security-alerts-about-links-and-files-from-suspicious-websites-a1ac6ae9-5c4a-4eb3-b3f8-143336039bbe?ui=en-us&rs=en-us&ad=us (I am not 100% sure that these warnings are what we get, but it could be part of the problem)

**Comment by eu-genia** [comment]
I think this is something for Matthias to solve

**Comment by eu-genia** [comment]
@PietroLiuzzo I just did another test, adding several other random links to the document - the popup does not appear. So there is something with betamasaheft.eu after all. Will try to dig more...

**Comment by eu-genia** [comment]
After more searches I assume that the problem may arise from a combination of the site security and the settings in Word, and possibly also of the non-authentificated use of Word (at least in my case:
![image](https://user-images.githubusercontent.com/17987728/78194562-cbf84180-747d-11ea-90de-1d71f7cdccc5.png)
On the other hand there are many users who get similar experiences (though not exactly); in many cases this was solved through an Office update - something I at least cannot carry out because the Word does not see me as a registered user.
If you are luckier than me and have access to the update - try it out and then tell us if it works.
![image](https://user-images.githubusercontent.com/17987728/78194765-550f7880-747e-11ea-9823-1b5db880f43b.png)

**Comment by DariaElagina** [comment]
I see the same window and then I am redirected by simply clicking ok. So, the same thing which has already been reported

**Comment by PietroLiuzzo** [comment]
from this all conversation I do not see any BM related issue for server or any other setting. I will forward this issue to AAI IT service and close this issue which is confirmed not to be relevant. if the IT coordinator will point me to an issue on the server I will take action from there
