### ISSUE TITLE
incipit and explicit of additions

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1392]
I am a bit unsatisfied with the way we encode incipits and explicits of additions. I believe this was discussed many years ago, and the current informal way was decided, but I don't find this discussion now.
There is the recurring need to encode incipits and explicits of additions, either because they are given explicitly by catalogues, or because we want to do this in the case of lengthy additions in new cataloguings.
Currently, we are using informal ways as writing in `<desc>` something like "the following is the incipit", followed by the text in `<q>`.  If we have both an incipit and an explicit, we might use `<gap>` within the text. But this results in some inconsistency.
The elements incipit and explicit are not allowed in additions. I could imagine using `<seg>` with a @type, but this might result in confusion with the encoding of titles, subscriptions etc.
If I am overthinking this and no one sees a real problem to this, just let me know :) At least, I think, it could be useful to record the current practice in the guidelines.

@PietroLiuzzo @DenisNosnitsin1970 @DariaElagina @eu-genia

**Comment by PietroLiuzzo** [comment]
is it relevant to call the piece of text you are quoting an incipit or explicit in there? I am not sure of the semantic overlap and relevance in this case. Could you please give an example of what you want to encode and how you would like to encode it? thanks

**Comment by thea-m** [comment]
Thank you! For example, in DSEthiop2, there is guest text contained on f. 75rb-76ra, so quite long for an addition. We would like to include the beginning and end of this text in the `<item> `.  It is a known work with its work ID, and there is no reason not to include this information, as we would if it were an msItem.

It is currently encoded as
```
 <q xml:lang="gez">ወካእበ፡ ናስተበቈኦ፡ ለአምላከ፡ ምሕረት፡ ዘረዳእከ፡ ለአብርሃም፡
አመ፡ ይቀት፡ ሎሙ፡ ለነገስት፡ ዘአድሐንኮ፡ ለይስሐቅ፡ እምነ፡ መጥባሕት፡ ዘመራሕኮ፡ ለያዕቆብ፡ በውስተ፡ መንገድ፡
<gap reason="ellipsis" resp="DN"/>ፈኑ፡ እማዴ፡ ሰማይ፡ ወምድር፡
ባርክ፡ ማህበረነ፡ በኵሉ፡ ጊዜ፡ ወበኩሉ፡ ሰአት፡ በአሐዱ፡ ወልድከ፡ ዘቦቱ፡ ለከ፡ ምስሌሁ፡</q>
```
This is just a recent example, it is really not a rare case in my estimation.
I have no particular preference as to how to encode or call it, though it would of course be nice for users to understand that it is the beginning and end of the text (which they currently do because we state it in `<desc>`). I gave some suggestions in my previous comment, but if the current way is estimated as being the best, I would just add  this to the guidelines.

**Comment by abausi** [comment]
Forgive me in something escapes me: would it be possible to allow "the elements incipit and explicit" in additions? which are the (non acceptable) consequences of this? there are really long additions, and there are (rare, but there are) additions that occur more times.

**Comment by thea-m** [comment]
It is not foreseen in TEI and therefore not possible in our schema currently (i.e. the records will be marked as invalid if we do it), that's why I opened the issue - anything can presumably be done, but it has to be discussed and documented ( and as you wrote, this need is a recurring one).

**Comment by PietroLiuzzo** [comment]
We can add these elements in `additions`, with good motivation, but there are many ways to do this and I am not sure we have yet a full case to go ahead with any. There are more than 5k items with a `q` inside an item within additions in our data, containing the text  of the additions, so this definitely needs consideration before making a move with a lot of backlog, including changing encoding practices which is of no little concern.  One consideration related to this is our use of `q` in this instances, which may be revised within the scope of this issue and made more appropriate or replaced with better encoding. 
One thing we can do is to allow model.msQuoteLike  https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.msQuoteLike.html in the `item`s in `additions`, making those items effectively identical to msItem. Following this train of thoughts we could allow in `additions` `msItem`s and change the entire structure of `additions`, which are now in a simple `list` of `item`s. 

We now do `additions`, like this ([GL](https://betamasaheft.eu/Guidelines/?id=additionsVaria))

`````xml
<list>
                    <item xml:id="a1">
                        <locus target="#1r"></locus>
                        <desc type="OwnershipNote">Crude ownership note in pencil.</desc>
                        <q xml:lang="gez">ዘ<persName ref="PRS11944GabraM" role="owner"><roleName type="title">አባ፡</roleName> ገብረ፡ ማርያም፡</persName></q>
                    </item>
</list>
`````
We would instead have something like

`````xml
<msItem xml:id="a1">
       <locus target="#1r"></locus>
       <desc type="OwnershipNote">Crude ownership note in pencil.</desc>
       <incipit xml:lang="gez">ዘ<persName ref="PRS11944GabraM" role="owner"><roleName type="title">አባ፡</roleName> ገብረ፡ ማርያም፡</persName></incipit>
</msItem>
`````
very much like we do within `msContents` ([GL](https://betamasaheft.eu/Guidelines/?id=manuscriptContents)) . this would actually be quite sensible because we treat them in the same way, and they would end up being distinguished not much by the model, but by their position in the record. I have to investigate the actual feasibility of this in the ODD.

This would require changing the ODD, the guidelines, all the data and the code of the application. But we have done this before in many occasions, so, nothing to be too scared of. Your example which is now

````xml
<item xml:id="a6">
<locus from="75rb" to="76ra"/>
<desc type="GuestText">
<title ref="LIT4859Litany"/>
</desc>
<q xml:lang="gez">
ወካእበ፡ ናስተበቈኦ፡ ለአምላከ፡ ምሕረት፡ ዘረዳእከ፡ ለአብርሃም፡ አመ፡ ይቀት፡ ሎሙ፡ ለነገስት፡ ዘአድሐንኮ፡ ለይስሐቅ፡ እምነ፡ መጥባሕት፡ ዘመራሕኮ፡ ለያዕቆብ፡ በውስተ፡ መንገድ፡
<gap reason="ellipsis" resp="DN"/>
ፈኑ፡ እማዴ፡ ሰማይ፡ ወምድር፡ ባርክ፡ ማህበረነ፡ በኵሉ፡ ጊዜ፡ ወበኩሉ፡ ሰአት፡ በአሐዱ፡ ወልድከ፡ ዘቦቱ፡ ለከ፡ ምስሌሁ፡
</q>
</item>
````

 would be in this scenario (staying within `additions`, but without `list`)

`````xml
<msItem xml:id="a6">
       <locus from="75rb" to="76ra"/>
<desc type="GuestText">
<title ref="LIT4859Litany"/>
</desc>
<incipit xml:lang="gez">
ወካእበ፡ ናስተበቈኦ፡ ለአምላከ፡ ምሕረት፡ ዘረዳእከ፡ ለአብርሃም፡ አመ፡ ይቀት፡ ሎሙ፡ ለነገስት፡ ዘአድሐንኮ፡ ለይስሐቅ፡ እምነ፡ መጥባሕት፡ ዘመራሕኮ፡ ለያዕቆብ፡ በውስተ፡ መንገድ፡
<gap reason="ellipsis" resp="DN"/>
ፈኑ፡ እማዴ፡ ሰማይ፡ ወምድር፡ ባርክ፡ ማህበረነ፡ በኵሉ፡ ጊዜ፡ ወበኩሉ፡ ሰአት፡ በአሐዱ፡ ወልድከ፡ ዘቦቱ፡ ለከ፡ ምስሌሁ፡
</incipit>
</msItem>
`````

But if I understand this ellipsis is the entire text inbetween, so you would have, in the current scenario better something like
````xml
<item xml:id="a6">
<locus from="75rb" to="76ra"/>
<desc type="GuestText">
<title ref="LIT4859Litany"/>
</desc>
Incipit: <q xml:lang="gez">
ወካእበ፡ ናስተበቈኦ፡ ለአምላከ፡ ምሕረት፡ ዘረዳእከ፡ ለአብርሃም፡ አመ፡ ይቀት፡ ሎሙ፡ ለነገስት፡ ዘአድሐንኮ፡ ለይስሐቅ፡ እምነ፡ መጥባሕት፡ ዘመራሕኮ፡ ለያዕቆብ፡ በውስተ፡ መንገድ፡</q>
Explicit: <q xml:lang="gez">ፈኑ፡ እማዴ፡ ሰማይ፡ ወምድር፡ ባርክ፡ ማህበረነ፡ በኵሉ፡ ጊዜ፡ ወበኩሉ፡ ሰአት፡ በአሐዱ፡ ወልድከ፡ ዘቦቱ፡ ለከ፡ ምስሌሁ፡
</q>
</item>
````
or in the msItem scenario 

`````xml
<msItem xml:id="a6">
       <locus from="75rb" to="76ra"/>
<desc type="GuestText">
<title ref="LIT4859Litany"/>
</desc>
<incipit xml:lang="gez">
ወካእበ፡ ናስተበቈኦ፡ ለአምላከ፡ ምሕረት፡ ዘረዳእከ፡ ለአብርሃም፡ አመ፡ ይቀት፡ ሎሙ፡ ለነገስት፡ ዘአድሐንኮ፡ ለይስሐቅ፡ እምነ፡ መጥባሕት፡ ዘመራሕኮ፡ ለያዕቆብ፡ በውስተ፡ መንገድ፡</incipit
<explicit xml:lang="gez">
ፈኑ፡ እማዴ፡ ሰማይ፡ ወምድር፡ ባርክ፡ ማህበረነ፡ በኵሉ፡ ጊዜ፡ ወበኩሉ፡ ሰአት፡ በአሐዱ፡ ወልድከ፡ ዘቦቱ፡ ለከ፡ ምስሌሁ፡
</incipit>
</msItem>
`````

Another lighter option is the one already imagined by @thea-m, and would entail to either assimilate in our schema `q` to `seg`, or use  `seg` within `q` and instead of `@type` slightly abuse [`@part` ](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.fragmentable.html).
You should be already able to use `gap` in `q` as you do in `incipit` and `explicit`, so the only remaining issue is declaring that it is the beginning of the text, which the above would do.

````xml
<item xml:id="a6">
<locus from="75rb" to="76ra"/>
<desc type="GuestText">
<title ref="LIT4859Litany"/>
</desc>
<q xml:lang="gez">
<seg part="I">ወካእበ፡ ናስተበቈኦ፡ ለአምላከ፡ ምሕረት፡ ዘረዳእከ፡ ለአብርሃም፡ አመ፡ ይቀት፡ ሎሙ፡ ለነገስት፡ ዘአድሐንኮ፡ ለይስሐቅ፡ እምነ፡ መጥባሕት፡ ዘመራሕኮ፡ ለያዕቆብ፡ በውስተ፡ መንገድ፡</seg>
<gap reason="ellipsis" resp="DN"/>
<seg part="F">ፈኑ፡ እማዴ፡ ሰማይ፡ ወምድር፡ ባርክ፡ ማህበረነ፡ በኵሉ፡ ጊዜ፡ ወበኩሉ፡ ሰአት፡ በአሐዱ፡ ወልድከ፡ ዘቦቱ፡ ለከ፡ ምስሌሁ፡</seg>
</q>
</item>
````

Another possible solution is to use the text to encode the text and use `@corresp` in your addition, instead of reproducing the text in the `q` within the addition. You will normally encode your transcription, assign a div to contain the text within the relevant `pb`s and have your text in full or part encoded there to the extent to which you are copying it. This attribute may be in the text transcription or in the addition item in the same way as we document for regular msItem / div correspondences https://betamasaheft.eu/Guidelines/?id=ColophSupplTit
Your example would be 

````xml
<item xml:id="a6" corresp="#add6">
<locus from="75rb" to="76ra"/>
<desc type="GuestText">
<title ref="LIT4859Litany"/>
</desc>
</item>

....

<div type="edition">
....
<div type="textpart" subtype="additiontext" xml:lang="gez" corresp="#a6" xml:id="add6">
            <ab><pb n="75r"/><cb n="a"/><cb n="b"/>
ወካእበ፡ ናስተበቈኦ፡ ለአምላከ፡ ምሕረት፡ ዘረዳእከ፡ ለአብርሃም፡ አመ፡ ይቀት፡ ሎሙ፡ ለነገስት፡ ዘአድሐንኮ፡ ለይስሐቅ፡ እምነ፡ መጥባሕት፡ ዘመራሕኮ፡ ለያዕቆብ፡ በውስተ፡ መንገድ፡
<gap reason="ellipsis" resp="DN"/>
<pb n="75v"/><cb n="a"/><cb n="b"/>
<pb n="76r"/><cb n="a"/>
ፈኑ፡ እማዴ፡ ሰማይ፡ ወምድር፡ ባርክ፡ ማህበረነ፡ በኵሉ፡ ጊዜ፡ ወበኩሉ፡ ሰአት፡ በአሐዱ፡ ወልድከ፡ ዘቦቱ፡ ለከ፡ ምስሌሁ፡

<cb n="b"/>
            </ab>
          </div>
</div>
````
This could also contain `seg` with `@part` or `@type`.

And just for completeness, I find also the informal way in use just fine.

**Comment by thea-m** [comment]
Dear @PietroLiuzzo , thank you, all are wonderful suggestions. I probably cannot give a qualified opinion, but will share my unqualified estimations: 
- I would maybe still be in favour of slightly formalizing this, as compared to the current use.
- Having stated this, the priority should be (a part from correctness of the data and sustainability of the encoding, which I take are present in all options) feasability of the approach. The `<seg>` solution seems the easiest to implement and would not require changes to the existing records (in a large part of them, `<q>` contains anyway the entire addition, not parts of it). But I also see the appeal of the `<msItem>` idea.
- the encoding the text in `<div>` in `<edition>` is also very logical, but I am hindered here maybe a bit by the current visualisation on the app, which will separate description and text for users (again, I know this is very logical and the whole point of the `<msDesc>` and `<text>` elements....)

So, I personally would lean towards `<seg>` but will happily be convinced of anything that might be conceptually better.

**Comment by eu-genia** [comment]
I agree with @thea-m that the `<seg>` solution seems to be the most feasible. We cannot replace `<q>` with `<incipit>` as is obvious from the very first example given, in most cases the quotes are not incipits but entire notes (or could be quotations from anywhere within).
(For long additions that occur in more than one MS one should consider creating a Work ID and put the edition there.)

**Comment by PietroLiuzzo** [comment]
Then we can go for `<seg>`. I will update the guidelines with the following example and render in the visualization Incipit and Explicit, where `@part="I"` or `@part="F"` are used respectively.

<item xml:id="a6">
<locus from="75rb" to="76ra"/>
<desc type="GuestText">
<title ref="LIT4859Litany"/>
</desc>
<q xml:lang="gez">
<seg part="I">ወካእበ፡ ናስተበቈኦ፡ ለአምላከ፡ ምሕረት፡ ዘረዳእከ፡ ለአብርሃም፡ አመ፡ ይቀት፡ ሎሙ፡ ለነገስት፡ ዘአድሐንኮ፡ ለይስሐቅ፡ እምነ፡ መጥባሕት፡ ዘመራሕኮ፡ ለያዕቆብ፡ በውስተ፡ መንገድ፡</seg>
<gap reason="ellipsis" resp="DN"/>
<seg part="F">ፈኑ፡ እማዴ፡ ሰማይ፡ ወምድር፡ ባርክ፡ ማህበረነ፡ በኵሉ፡ ጊዜ፡ ወበኩሉ፡ ሰአት፡ በአሐዱ፡ ወልድከ፡ ዘቦቱ፡ ለከ፡ ምስሌሁ፡</seg>
</q>
</item>

**Comment by thea-m** [comment]
Thank you, @PietroLiuzzo !
