### ISSUE TITLE
encoding of parchment holes and repairs

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1393]
In many manuscript descriptions, the presence of holes in the parchment and parchment repairs (for this issue, I mean those parchment repairs that took place in the parchment production process before the text was written on it, not later repairs) is mentioned, but we have never discussed where to encode these. 
It seems to me that for now, they are mentioned in `<condition>` or under Varia. Which would be the best place to state this information? Condition doesn't seem appropriate to me (though I apparently thought this on 19 Apr 2019, https://github.com/BetaMasaheft/guidelines/issues/42...), and Varia is quite a vague and often overloaded category. Could this logically belong to the description of the support? What do you think?
@DenisNosnitsin1970 @DariaElagina @eu-genia

**Comment by DariaElagina** [comment]
I would suggest to describe holes or repairs which occured in the process of parchment production in the description of support, because it is just a feature of parchment, as well as its quality. But the holes or repairs which occured later should be encoded under the condition (if we can of course always distinguish between them).

**Comment by abausi** [comment]
I agree with Daria: this is a feature that belongs to the support.

**Comment by thea-m** [comment]
Perfect, everyone agrees.

@PietroLiuzzo any encoding objections to something like
```xml
   <support>
   <material key="parchment"/>
   Parchment repairs on <locus target="#23 #26"/>. Hole in the parchment on <locus target="#46"/>.
</support>
```
?

**Comment by DenisNosnitsin1970** [comment]
I think one can assume that the "patched" holes are those that have been left during parchmenting and closed later when the parchment was dry. Those that are "sewn" like a wound were closed when the parchement was still wet. I would record all together in one field, because both are done after the parchment was produced. Actually, I would not record single unrepared holes or damages in the margins as it is a common thing and usually no meaning can be drawn out of it. What can be attempted under "support" is: to leave options for the definition of the source of parchment, like goat, sheep, bovine, others (?). No one attempted to define it in descriptions, as far as I know, but this is said to be probably possible on the basis of good images, some features that parchment may show, etc.

**Comment by thea-m** [comment]
I am extremely confident that such options for the source of parchment can be easily incorporated (@type, or specifying the @key value), but maybe let's wait until someone can actually use them? Maybe the Italian cataloguing project at some point? I am also waiting (since a long time) for the analysis results of two scrolls.
Regarding the holes, repairs etc.: Regardless of its value, this information is already present in many records, so it would be good, in my opinion, to have it encoded consistently. As always, what is discussed here and documented in the guidelines is a documentation of what can be encoded, not a cataloguing checklist. You are right, we need maybe to state this more clearly.

**Comment by PietroLiuzzo** [comment]
> Perfect, everyone agrees.
> 
> @PietroLiuzzo any encoding objections to something like
> 
> ```
>    <support>
>    <material key="parchment"/>
>    Parchment repairs on <locus target="#23 #26"/>. Hole in the parchment on <locus target="#46"/>.
> </support>
> ```
> 
> ?

if it is valid, it is fine for me. not sure it will be visualized in the app. I would suggest a `p` at least around the sentence.

**Comment by thea-m** [comment]
updated guidelines, thank you everyone!
