### ISSUE TITLE
Marking up missing word separators at the end of a line

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1413]
Missing word separators when the end of a word coincides with the end of a line seem to be a feature of a considerable amount of manuscripts, possibly from a certain period and therefore relevant to their dating (as was pointed out to me by @karljonaskarlsson ). I would like to mark this feature up better than I do currently, which is simply with:
`<supplied reason="omitted" resp="DR">፡</supplied>`
Since I don't encode line breaks (and have no desire to do so consistently...), the reason for this "omission" remains unclear to those who do not see the photos. I could spontaneously imagine either a new, specific value for `@reason` in these cases, or exceptionally marking up the following line break (which could seem strange since it is done nowhere else).  What do you think?
@PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
I think your encoding is already quite distinctive. because the salient feature is eventually that the omitted separator is at the end of a line, I am afraid the best way to mark this would be to add that <lb/>. It does not need to be numbered. with this markup we would eventually have the feature you are talking about encoded and extractable from the encoding.

**Comment by thea-m** [comment]
thank you, very sensible
