### ISSUE TITLE
binding material

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1420]
1. Would it be possible to add 'cotton' as a binding material?
2. I would like to state: 'silk or cotton'. Is the follwoing encoding possible (adding the new key term): 
`<material key="silk"> or cotton (see <ref target="#e3"/>)</material>`

**Comment by PietroLiuzzo** [comment]
The value is now available. yes, as in the guidelines, the encoding for `<material>` is fine within `<decoNote xml:id="b2" type="bindingMaterial"/>` however, note that the application will only print the value of the elements, not the text in between. if you want it on the app, please add it in this form in another `<decoNote>`. thanks

**Comment by SusanneHummel** [comment]
Sorry, it is not clear to me:
1. If I want to have the outcome: "silk or cotton" I cannot use the element material (because in this case it will show "silk AND cotton" which is not true) but simply describe it in a deco note? I am really sorry to ask again in this. The Ms I am describing is a very special case (normally one could use simply "textile"), but in this case I would like to be precise. 
2. If the app does not print the text within the material; I also cannot encode the follwoing?
<decoNote xml:id="b1">Two<material key="wood">wooden</material>
                                    boards covered with tooled reddish brown tooled <material
                                        key="leather"/>. 
@thea-m

**Comment by SusanneHummel** [comment]
```here the enoding again
<decoNote xml:id="b1">Two<material key="wood">wooden</material>
                                    boards covered with tooled reddish brown tooled <material
                                        key="leather"/>. 
```

**Comment by PietroLiuzzo** [comment]
Dear @SusanneHummel it is not a question of what can or cannot, just of how, and the how depends on schema, guidelines, and finally application, which seems to be your main concern. 
1. for silk or cotton, would `<material key="silk"/> or <material key="cotton"/> (see <ref target="#e3"/>)` work for you? I should have looked better, that is actually what I thought I had seen. Now, this encoding, if you put it in [`<decoNote xml:id="b2" type="bindingMaterial"/>`](https://betamasaheft.eu/Guidelines/?id=bindingDescription) will only show silk and cotton as values. If you put it in a different decoNote it will consider all the content.

````xml
<decoNote xml:id="b1">
                           ... silk or cotton (see <ref target="#e3"/>)...
                        </decoNote>
                        <decoNote xml:id="b2" type="bindingMaterial">
                           <material key="silk"/>
                           <material key="cotton"/>
 </decoNote>
````

2. No, the app does not print the content of material in most cases, because it is an element which we use for classification, not to markup text. If you check some of the existing manuscripts, you will see that this has been done by providing the general description, like your sentence, inside decoNote[@xml:id='b1'] without markup for material, while decoNote[@xml:id='bindingMaterial'] has only the empty material elements. e.g. DSEthiop1, you would have

````xml
<decoNote xml:id="b1">
                           Two wooden boards covered with reddish-brown blind-tooled leather.
                        </decoNote>
                        <decoNote xml:id="b2" type="bindingMaterial">
                           <material key="leather"/>
                           <material key="wood"/>
 </decoNote>
````

**Comment by thea-m** [comment]
I'm sorry for some of the confusion here, which I caused. Several issues were combined here, which are part of larger "concerns" (in a positive sense, I don't find the right word....) on binding descriptions.
These concerns mainly arose out of the hope of combining from the beginning an encoding of the binding which fully uses the mark up and subsequent possibilities for quantitative research for which Eliana's detailed binding encoding guidelines provide the basis, and having in mind a final printed output, in which the binding will be described in paragraphic form. Since I am lazy I was hoping for a way of combining both and not having two sets of descriptions, one purely paragraphic without mark up, and one purely schematical mark up.
This "double encoding" is what has been done partly in the DS records (with a tendency towards the paragraphic) as the simplest way to produce the current catalogue, but I would not consider these choices normative at all. They certainly do not take advantage of the more sophisticated guidelines developed by Eliana. 
It might well be possible that this combination is not the most desirable encoding, and that for example the printed catalogue would lean more towards a schematic rendering of the binding description. 
This is the background of @SusanneHummel's quote
```
<decoNote xml:id="b1">Two<material key="wood">wooden</material>
                                    boards covered with tooled reddish brown tooled <material
                                        key="leather"/>. 
```
We were wondering whether it would be possible of having such a sort of description, where the binding materials mentioned would be encoded within the description and could then be retrieved, being aware that this is not currently in any way approved, documented or supported.

**Comment by thea-m** [comment]
Regarding the original silk or cotton issue, I would now maybe tend towards actually only using the keyword textile, because in my understanding by listing both values we state that both materials are present in the manuscript, which is probably not true.  Otherwise it would also be possible to use the certainty element.

**Comment by PietroLiuzzo** [comment]
We can change our encoding practice, but I would not consider this "double encoding", you markup the binding material  once, just not inline. This format for binding comes originally from ES and has only been modified by Eliana for some values which are more specific to binding. The encoding [has been used in 4225 records](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Abinding%2F%2Ft%3AdecoNote%5B%40type%3D%22bindingMaterial%22%5D%2Ft%3Amaterial), many of which I reckon where mechanically created, but many not. 
This use in the data, the guidelines, the scripts showing these values, all can be changed to accomodate inline encoding as well, but I am personally not persuaded that this is necessary by the PDF argument I am afraid. what actual cases would it serve and how would it be better?
regarding the silk and cotton, the easiest correct thing to do is to simply say that in the sentence in decoNote. which values you want to list with the materials is up to you, they perform a classificatory function which does not mean they are made of this material, but only, this material has been tagged in this manuscript description. the user landing on this manuscript will read of course the information available. you can have the three of them, you can certainly use `<certainty>` or just `@cert`
A separate issue is that of graphical representation, these are based on that assumption, i.e. that is an encoded element is present, that information is to be counted. but that is also stated there, and it is also probably what one would want to do for that purpose.
