### ISSUE TITLE
Textpart labels visualization/alignment

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1435]
Textpart labels in Works are visualized very differently depending on whether there is an edited bit inside or not (here LIT2050Nagara)
![image](https://user-images.githubusercontent.com/17987728/85004314-b7137c00-b157-11ea-848d-6057ebadfc64.png)

This looks a bit strange. 

Even stranger when there is a corresp, since its value takes the place of the label in cases of labels with texts
![image](https://user-images.githubusercontent.com/17987728/85004614-0eb1e780-b158-11ea-8119-060e103f1a72.png)

Can we have all labels given in the same place (left aligned) and font size? 
And maybe suppress the gray box when there is not text provided?

**Comment by PietroLiuzzo** [comment]
I have anticipated these changes and uploaded them to the live app, after all, they are just xslt. please have a look. I have moved all to a template so that the information is always returned in the same way. 
label is printed first if available, then, if a `@resp` is provided in div[edition], that is taken into account, then `@subtype` and `@n` eventually with a link, either to the value of `@corresp` or to the msItem in the main entry, finally, if available `@corresp` in brackets and at the end the versions button. This string I have italicized just to further distinguish it from the eventually present note.

**Comment by eu-genia** [comment]
looks good
