### ISSUE TITLE
five digits clavis number

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1441]
I just created a new work record, LIT60498MazDenIntro. The numerical part of the ID has now five digits - I wonder how that came? I understand that it would not be a problem per se, but nevertheless I think it would be better to stay in the four digits for as long as we can...

**Comment by PietroLiuzzo** [comment]
this IS a huge problem.

**Comment by PietroLiuzzo** [comment]
@DariaElagina wrote in an email (edited for the issue):
here is a work ID which has been created by application right now: LIT6.050132E6PraiseOfMary, with a dot! @MarcinKrawczuk  has reported the same case to me.

**Comment by PietroLiuzzo** [comment]
Now the creation of files is fixed.  It looks like a file was created last week where the name started with a number, e.g. 1pietro . It has certainly been an accident, which reveals a weakness in the workflow for records which are created in the app, which did not emerge until now. Due to the structure of our IDs, we cannot really prevent this, but I will add a check in the form.

The following clean up is necessary for the following files which were already in the db (created, but not yet committed, a part from some). Because you know better what these are and where you have used them in which branch, etc. PLEASE fix asap the files which you are concerned with and tick when done.

|status |current wrong id | to be changed in all occurrences to |
|:--- | ------------- |-----:|
| <ul><li>[ ] </li></ul> |  LIT6050131SundayRetuaH | LIT6049SundayRetuaH
| <ul><li>[ ] </li></ul>  |  LIT605012SundayRetuaH | LIT6050SundayRetuaH
| <ul><li>[ ] </li></ul>  |  LIT60495TammeraZamikael | LIT6051TammeraZamikael
| <ul><li>[ ] </li></ul>    |  LIT60496MMIntrPrayer | LIT6052MMIntrPrayer
| <ul><li>[ ] </li></ul>    |  LIT60497EsaggedLaki2 | LIT6053EsaggedLaki2
| <ul><li>[ ] </li></ul>    |  LIT60498MazDenIntro | LIT6054MazDenIntro
| <ul><li>[ ] </li></ul>    |  LIT60499HymnMarySalotki | LIT6055HymnMarySalotki
| <ul><li>[ ] </li></ul>    |  LIT60500IntroPs | LIT6056IntroPs
| <ul><li>[ ] </li></ul>    |  LIT6.050132E6PraiseOfMary | LIT6057PraiseOfMary
| <ul><li>[ ] </li></ul>    |  LIT6.050132E6Ladder | LIT6058Ladder
| <ul><li>[ ] </li></ul>    |  LIT6.050132E6ForLentRetuaH | LIT6059ForLentRetuaH
|<ul><li>[ ] </li></ul>    |  LIT6.050132E6BeginningOfLent | LIT6060BeginningOfLent
| <ul><li>[ ] </li></ul>   |  LIT60493SundayRetuaH | LIT6061SundayRetuaH
| <ul><li>[ ] </li></ul>    |  LIT60494TaammeraUrael | LIT6062TaammeraUrael

**Comment by PietroLiuzzo** [comment]
HOLD ON

**Comment by DariaElagina** [comment]
Thank you, @PietroLiuzzo !!!
LIT6.050132E6PraiseOfMary is corrected, tick function does not work

**Comment by thea-m** [comment]
corrected LIT60496MMIntrPrayer, LIT60498MazDenIntro
LIT60497EsaggedLaki2 had been deleted before its PR was merged 
LIT60500IntroPs looks to me like I might have created it, but I cannot find it anywhere now. I probably deleted the record before making a PR.
I think these were the ones in which I was involved. 
@DenisNosnitsin1970 @MarcinKrawczuk can you correct those that you created or do you need help? Let us know!

**Comment by DariaElagina** [comment]
Marcin has just contacted me, he will get access to his PC in the evening.

**Comment by eu-genia** [comment]
corrected
LIT60495TammeraZamikael
LIT60499HymnMarySalotki
LIT60494TaammeraUrael

https://github.com/BetaMasaheft/Works/pull/224
https://github.com/BetaMasaheft/Manuscripts/pull/646

**Comment by eu-genia** [comment]
BTW probably the question has been answered and is irrelevant - but what happens with the records where the system had assigned an ID but they were deleted before the first PR merge? Can these IDs that were never in use be traced and deleted? Or is it OK and disturbs noone?

**Comment by PietroLiuzzo** [comment]
It is not ok, no. I actually fail to see what this flow looks like. why is a work record created and then deleted before a PR?

**Comment by thea-m** [comment]
I have done this. It happens when someone (me) thinks that a new work record should be created, but then some information comes up that makes this unnecessary. This can happen before the record is created, before the PR, after the PR...

**Comment by PietroLiuzzo** [comment]
we should really really avoid this. a record creation should prompt a commit and a pr to align to the database in any case. In all these cases the app will have learned about the new files because you created it there in the first place, but will never get to know it was then deleted, because you deleted it somewhere else. That is way we need a commit and a PR. Is there any part of the guidelines which contradicts with this and the blinking indication in the confirmation message upon file creation? We need to fix that quickly...

**Comment by PietroLiuzzo** [comment]
I will compare directories to spot residual files in the database

**Comment by thea-m** [comment]
Nothing in the guidelines for this, at least in my memory. But, I am sorry, people complain when we make many small PRs and when we make few large ones. If I work on a manuscript with several hymns, of which some need new IDs, I usually do not make one PR per ID. I could of course. It just feels silly to PR a file and then to delete it, but if that would be better, we can do it.

**Comment by PietroLiuzzo** [comment]
This is necessary because those numbers we assign become clavis numbers. There is no way to trade this off, it just needs to be done like this to maintain data flexibility, and as far as I remember this has been the case for a long long time, it is not something new. It may have become different since last August with the introduction in our workflow of PRs. If this clashes with working habits we can certainly think of solutions, but these will not be technical, only in workflow and procedure. for example, what would you think of making an exception for work records creation, so that they are automatically self-merged? Additionally we could add guidance where needed, in the form, in the guidelines, in the file creation message, etc. about the fact that creating a work record is not a light-weight operation, and until this is not 100% sure, one may use local files which do not need to be committed as placeholders until it is clear that a Work record has to be created for which a dedicated PR will be opened and merged. Everything should be made as easy as possible, but not easier.

**Comment by eu-genia** [comment]
sorry I went on to rename and delete work files (something I was not supposed to do?)

**Comment by PietroLiuzzo** [comment]
@eu-genia perhaps this is not the correct issue where you wanted to comment?

**Comment by thea-m** [comment]
I see no problem at all, it just has to be clear. 
I would like to stress that there is no 100% certainty, and that I think most of us do not take creating any (!) records easily. There will always be records created and at some point deleted, whether this is two minutes after their creation or two decades is only a gradual difference, not a conceptual one.
I don't know what "automatically self-merged" means. 
For me, there is no problem to have the rule of having to commit any record that has been created, and only delete after a commit (as long as deleting during a PR pre-master-merge is fine? This happens of course more often than deleting records before a PR, and is a testimony to the usefulness of a review process).

**Comment by PietroLiuzzo** [comment]
I think we are talking in parallel. for sure you can create and delete, here is just a matter of how this is done.
I have understood this kind of scenario, for example: 
1. you edit a manuscript, 
2. think a work record is needed, 
3. create it in the app (it needs to, is a work), 
4. make no PR to Works, 
5. and then use it, 
6. and then  PR  your manuscript to Manuscript
7. during review it turns out it was not a necessary  Work record which you created at point 3, 
8. then you delete the record in Works like it never existed.
9. the record still exist in the app, where it was created 

What I think needs to be clear is that the creation on the app of a record, needs to be followed, as it always did, but a PR, so that the github data is in sync with the database. it has nothing to do with the review and its usefullness IMHO. the above should look like

1. you edit a manuscript, 
2. think a work record is needed, 
3. create it in the app (it needs to, is a work), 
4. make a PR to Works and eventually discuss it if in doubt or directly / automatically, merge it by your self, 
5. and then use it, 
6. and then  PR  your manuscript to Manuscript
7. during review it turns out it was not a necessary  Work record which you created at point 3 and merged at point 4, 
8. then you delete the record in Works and make a PR justified by the review of your manuscript, which can also be directly / automatically, merge it by your self.
9. also the app gets to know and stays in sync.

**Comment by thea-m** [comment]
Yes, I agree with all that, with one meaningful exception: I think for now a very crucial step has been exactly the PR in the work repository, not only the PR of the manuscript. So I would be very much against self-merging new work records. 
Often in many peoples' workflow editing the manuscript and the works contained in it is naturally part of one working unit. The division in PRs in the different repositories is already slightly counterintuitive. Therefore, the PR for the work and manuscript records are often done at the same time, which is also better for reviewers, who can then have a better overview.
The review of manuscripts is not more meaningful than the review of works for work records.

**Comment by PietroLiuzzo** [comment]
I see. I think this needs to be discussed in an issue before creation in the app, which must be swiftly followed by a merge if we want also a successful delete eventually.

1. you edit a manuscript, 
2. think a work record is needed, 
3. open an issue, ping relevant people and make sure it is the case
3. create it in the app (it needs to, is a work), 
4. make a PR to Works and merge it by your self (it needs to be merged, you have created a record in the app, which needs to be kept in sync), 
5. and then use the record, 
6. and then  PR  your manuscript to Manuscript
7. during review it turns out it was not a necessary Work record which you created at point 3 and merged at point 4, 
8. then you delete the record in Works and make a PR justified by the review of your manuscript, which can also be directly / automatically, merge it by your self.
9. also the app gets to know and stays in sync.

**Comment by PietroLiuzzo** [comment]
once we agree on this I will also update this page of the gl https://betamasaheft.eu/Guidelines/?id=create and link it in more places

**Comment by eu-genia** [comment]
needing to have an issue before creating a work record will slow us down ages...

**Comment by PietroLiuzzo** [comment]
yes, but from the above, seems necessary. discussion in a PR or in an issue is the same, it is simply a matter of what comes first. perhaps it will hint at more prompt attention to issues, which will not harm.

**Comment by PietroLiuzzo** [comment]
> I will compare directories to spot residual files in the database

eventually this will be fixed at the next data freeze.

**Comment by thea-m** [comment]
Let's just try out having issues before creating new works. If after some weeks we notice a dramatic slow down without any benefits, we can revise the process.
Again, though, I would be against self-merging work records. There are often little mistakes in the title (actually, if it is not too much trouble, @PietroLiuzzo could you modify the work creation to create records with `xml:lang="" ` in the title, without gez? Then there would be an error and we would be forced to chose the correct language, and not be tempted to stick to the wrong one...) or other places, which would be difficult to foresee through the issue.

**Comment by PietroLiuzzo** [comment]
I really do not think that there will be any time impact, discussion is necessary, and if it comes before the PR this will eventually speed up the process, by eliminating errors, avoiding useless record creation, etc. I also do not see how one could be stopped by the absence of an ID. an msItem can well be without a title[@ref], until one is available, so there is no reason why the process of identification of Textual Units should collide with the timeliness of the creation of manuscript records...

**Comment by thea-m** [comment]
It is nicer in the work flow to have a coherent manuscript/work creation process than half finished manuscripts scattered everywhere, whether on unmerged branches or on the master branch waiting for updates :)
But I agree that the time impact here should not be dramatic.

**Comment by MarcinKrawczuk** [comment]
I've corrected three of mine, but there are further three which I cannot find. They are:
LIT6.050132E6BeginningOfLent 	LIT6060BeginningOfLent
LIT6.050132E6Ladder 	                LIT6058Ladder
LIT6.050132E6ForLentRetuaH 	LIT6059ForLentRetuaH
@PietroLiuzzo Could you please help?

**Comment by PietroLiuzzo** [comment]
Dear @MarcinKrawczuk , you and @DariaElagina reported on this error, so I assume you attempted the creation of these files. if you did not download the produced file and do not have them in pending branches, please let me know and I will simply replicate the files from the database in github. thanks a lot!

**Comment by MarcinKrawczuk** [comment]
@PietroLiuzzo that is correct, I don't have these three in any pending branches, I produced them but once I saw that the system assigns incorrect number I didn't download them (or at least that's how I remember it). I will appreciate any help :)

**Comment by PietroLiuzzo** [comment]
thanks!
