### ISSUE TITLE
Visualizing notes to altIdentifier

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1444]
In E-S mss it is often mentioned where the local shelfmark is provided.
E.g. in ESdd006
`<altIdentifier>
                     <idno>C3-IV-221</idno>
                     <note>(<locus target="#8r">8r</locus>)</note>
                  </altIdentifier>`

Is it possible to visualize such notes next to the idno? If notes can be automatically put in brackets in such context I would remove the brackets in the code

**Comment by eu-genia** [comment]
(in general, the notes element is possible almost anywhere but for the moment it is not automatically visualized, is there a way to have it visualized by default, even if the specific context is not specified in the css?)

**Comment by thea-m** [comment]
(I know that the amount of time that can be invested in the Ethio-Spare records is limited: the better place for the information included here in note would be as an extra. Then the list of identifiers is clean and easily searchable, and the references for those identifiers are clearly stated in the record.)

**Comment by eu-genia** [comment]
OK will try

**Comment by PietroLiuzzo** [comment]
>  is possible almost anywhere but for the moment it is not automatically visualized

it is possible, but I would argue it is not what one really wants, also because our use of note is rather free and in same places is just used as a magic element which fits all, some other times really as note, in some contexts, like in apparatuses it is used with a specific function, etc. In practice this is a matter of applying templates of printing a specific value, so in most cases this is already the behaviour, i.e. if there is note, it will be rendered. For purposes of search, faceting, etc.  I would not think that `idno` would be a place to allow mixed content and apply templates and @thea-m has already made that case as well. The simple fact that an element is allowed does not mean we ought to use it without good reason and documentation of that usage in the GL. So, I think that @thea-m comment closes this issue.
