### ISSUE TITLE
new records for Orient 593

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1451]
I need to creat two work records for BL ORient 593 n.5 and n.7

https://archive.org/details/catalogueofethio00brituoft/page/230/mode/2up

Is it ok with you, @DenisNosnitsin1970 , @thea-m ?

**Comment by thea-m** [comment]
According to the EAE, 5-7 are chapters from the "Collectio monastica" (LIT4838CollectioM), they are listed in EAE III, p. 994b. Since they do not seem to be consecutive chapters, it would probably still be better to create individual IDs. Maybe there will be more information in the edition, to which I don't have access now.

**Comment by DariaElagina** [comment]
yes, according to the same article 996a n.6 is a witness to the Rules of Pachomius LIT2228Ruleso, which has its own circulation. I think that individual IDs for 5 and 7 with a relation to the Collection make sence. Or should I rather compress them into 1 msItem by now?

**Comment by thea-m** [comment]
I would be in favour of following the catalogue's subdivision and creating two new items
