### ISSUE TITLE
Acts of Galāwǝdewos 

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1459]
EMIP 458 contains the ገድለ፡ ገላውዴዎስ፡with 
incipit, በስመ: አብ: ወወልድ: ... ድርሳን: ዘነበበ: አቡነ: ቅዱስ: ክቡር: በዘዚአሁ: ጾታ: አባ: ቴዎድሮስ: ሊቀ: ጳጳሳት: ዘሀገረ: አንጾኪያ: በእንተ: ክብሩ: ለቅዱስ: ጽኑዕ: ወኃያል: ድንግል: መዋኢ: መስተጋድል: መልክዓ: መላእክት: እግዚእ: ገላውዴዎስ: ወልደ: ንጉሥ: 

I haven't been able to identify this in the clavis, so wish to query whether a new work should be created?

Image of the first page is attached
![image](https://user-images.githubusercontent.com/39619238/88951600-210e5d80-d28e-11ea-8205-a0876e37baad.png)

**Comment by thea-m** [comment]
No, it does not seem like there is a record for this work, thank you!
@DenisNosnitsin1970 has noted that from the incipit it would appear that this is a dərsān rather than a gadl. 
This work is also contained in BL. orient 700, https://archive.org/details/catalogueofethio00brituoft/page/182/mode/2up (called by wright "discourse", but apparently referred to together with the following "dərsān" as "Gadla Galāwdewos" by the EAE, so this might be given as a second title).

**Comment by Ralph-Lee-UK** [comment]
I probably should have waited before creating the file. @DenisNosnitsin1970 would you like me to change the title? I agree with your point. I can also add the attestation to BL Orient 700 in the file.

**Comment by thea-m** [comment]
thank you!

**Comment by Ralph-Lee-UK** [comment]
Work file now created and pull request made
