### ISSUE TITLE
Image of Jesus Christ??

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1460]
This page from EMIP 676 has what is catalogued as Image of Jesus Christ. 

I don't seem to be able to identify it in Chaine's work. Can anyone advise me on this?

![EMIP00676_CFRRC22_001](https://user-images.githubusercontent.com/39619238/89035905-a26bfb80-d333-11ea-9cec-f432526fc7cb.jpg)

**Comment by DenisNosnitsin1970** [comment]
It is LIT2839RepCh123. Since Chaine's article quotes only the first words, and it sometime essential to have more than this, here I append an Ethiopian eidtion of Malke'a guba'e, with the text in question (Malke'a Iyasus). If you want, you can have it introduced in Zotero, and add a few more words of the text to the work record (I wonder if Tedros Abraha, “Il Mälkeýa Iyyäsus (Effigie di Gesù)”, OrChrP 71, 1, 2005, 97–120) contains an edition/translation, that can be also used for the work record. 
[Mälk'a Guba'e.pdf](https://github.com/BetaMasaheft/Documentation/files/5008532/Malk.a.Guba.e.pdf)

**Comment by Ralph-Lee-UK** [comment]
This is very helpful. Many thanks

**Comment by thea-m** [comment]
Thank you. @Ralph-Lee-UK please close if this is solved for you
