### ISSUE TITLE
manuscript filter timeout

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1474]
I wanted to filter the manuscript list view https://betamasaheft.eu/manuscripts/list for Ethio-SPaRe manuscripts with at least two codicological units that have the keyword hagiography and run into a timeout.
I remember having carried out similar queries in the past, where (at least in my memory) it worked, so I wonder whether something can be done about it?

**Comment by PietroLiuzzo** [comment]
profiling and optimization can be done, the performance issue of the list view is a well known problem, you are right. it is taking more than usual because the db is not yet warmed up, cache is empty after I had to do a reboot early this morning.
the same query in the facet search will be quicker https://betamasaheft.eu/facet.html?query=Ethio-SPaRe&type-facet=manuscript&keywords-facet=Hagiography&msPartsCount-facet=10&msPartsCount-facet=2&msPartsCount-facet=3&msPartsCount-facet=4&msPartsCount-facet=5&msPartsCount-facet=6

**Comment by PietroLiuzzo** [comment]
just to explain, I started searching Ethio-SPaRe, then filtered item type (you could have filtered collection to the same effect), selected in the number of codicological units filter all values higher than 2 and in the keywords, under subject Hagiography, the clicked on refine results

**Comment by thea-m** [comment]
Thank you! I might benefit from a quick facet search 101 at some point ...

**Comment by PietroLiuzzo** [comment]
you can have a look at the help page, linked in the menu bar, let me know if that helps
