### ISSUE TITLE
Use of <lg> for Verse Texts (መልክእ፡, ዓርኬ፡, etc.)

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1483]
The [TEI guidelines](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-lg.html) include an `<lg>` element (line group) to be used for encoding:

>one or more verse lines functioning as a formal unit, e.g. a stanza, refrain, verse paragraph, etc.

This would seem to be a good way to denote stanzas within መልክእ፡ and similar verse compositions where it is helpful to have the lines of the stanzas clearly marked out. [TEI CAT](http://teicat.huma-num.fr/witnesses.php) implements them:

<img width="1392" alt="Screen Shot 2020-09-10 at 13 55 15" src="https://user-images.githubusercontent.com/6315671/92726044-4ef6bf80-f36d-11ea-87e0-64964ccc5f64.png">

And it helps greatly in reading, I find. Would this be something worth adding to the guidelines?

**Comment by PietroLiuzzo** [comment]
Dear @smaugustine our schema does not prevent you from using `<lg>` in any way, so you can already use it in your encoding. If no one else has to object on this, I do not have anything against adding support in the visualisation and text retrieval functionality and documenting the usage in the Guidelines.
I see that LIT3034RepCh314 has that already. I would suggest not to simply use the element, but to add to it at least `@n` and / or `@xml:id` as we do with `<div>`, e.g. which you could already add to your text above. 
- [ ] You could make a PR for a page in the Guidelines documenting this use. Please make sure that the text does not create confusion with the use of `<l>` in the encoding of e.g. biblical verses, I do not think we want to make anyone think they have to add `<lg>`s in every Psalm, for example.
- [ ] I can make sure this element is also visualised in the text view.
- [ ] I can change the rendering of the `<l>` element when the parent node is `<lg>` to use a new line
- [ ] I can edit the DTS APIs to retrieve references to text which also use `<lg>` as reference constructor, so that if you have
````xml
<lg n="1" type="stanza" xml:id="s1">
<l n="1">ናሁ፡ ተማኅፀንኩ፡ በኆኅያተ፡ ስምከ፡ ካፍ።</l>
<l n="2">ወበቀዳማይ፡ የውጣ፡ ዘጥንተ፡ ፊደሎን፡ አሌፍ።</l>
<l n="3">ከመ፡ ታድኅነኒ፡ ክርስቶስ፡ እምትንሣኤ፡ ልሳን፡ ወአፍ።</l>
<l n="4">እስመ፡ ልሳን፡ ቀተሎሙ፡ ለማኅበረ፡ ሰማዕት፡ አእላፍ።</l>
<l n="5">በነገረ፡ ውዴት፡ ጽኑዕ፡ ዘይበልሕ፡ እምሰይፍ።</l>
</lg>
```` 
you can get e.g. the first line with with LIT3034RepCh314.1.1 or LIT3034RepCh314.s1.1 or the entire stanza, and just that with LIT3034RepCh314.s1
I am struggling to understand the two `<ab>` in that record, I have to admit, and I would suggest giving the `<div>` a `@n` and or an `@xml:id`.
Just as a tail note, there are really many elements which are in TEI, are not explicitly excluded in our schema, but we just do not use or 'implement', as in this case. It is indeed the right procedure to discuss the possibility to include them in our practice. I think your argument to add support for `<lg>` holds in general as for any other element, but if we do not have a plan to really encode stanzas or reuse that encoding for some purpose, well, we do not strictly need to do anything about this (but you can still encode it as you already did, of course). So, please, @thea-m @DariaElagina @eu-genia and @DenisNosnitsin1970  tell us what you think.

**Comment by thea-m** [comment]
I agree that nothing speaks against it and that as always it has to be made clear that a possibility of encoding is no compulsion. In the same way as Augustine has used `<lg>` here I think we have always worked with `<div>`.
Augustine has kindly opened this issue after I asked him to, as this is our standard workflow for working with TEI elements etc. not yet used in BM.

**Comment by PietroLiuzzo** [comment]
well done! thanks! we will give it until Monday, in case somebody else has something to say, then I will move on.

**Comment by PietroLiuzzo** [comment]
the xslt now renders this as a block and lines with new line feed. for the DTS I will wait that the GL PR is available with an updated example in the db, using attributes on `<lg>`

**Comment by PietroLiuzzo** [comment]
I updated file and schema, @smaugustine please review and merge the PR and close this issue.
