### ISSUE TITLE
reference to a manuscript in a work record

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1486]
I am trying to create a work record for a certain Marian homily contained in Wright p. 144, no. 11. In the catalogue there is no title, however I'm aware of at least one manuscript which provides both the title and attribution (probably fictuous but still). Is there any recommended way of encoding the fact, that the title and attribution has been taken from this particular manuscript (it is not in the database, BTW) or a <note> will be enough?

(I've only today been made aware that I should create an issue before creating work record, I will follow this from now on of course)

**Comment by PietroLiuzzo** [comment]
If the manuscript is not there, I would create that and add an `msItem` with `title` without a `@ref` detailing what you wrote here. having the text would help in this case, IMHO, and I can produce a transcription if images are available, so that it can be used for comparisons

**Comment by PietroLiuzzo** [comment]
@thea-m @eu-genia @DenisNosnitsin1970 @smaugustine @DariaElagina

**Comment by eu-genia** [comment]
In addition to creating the record for the other MS, in the work record, I would add the attributedTo relation with a description which specifies exactly that
As for the title/label - these never exist and are always invented at some point, whether by scribes or by cataloguers, the true title is the incipit, of course the work record should list all labels existing, and the manuscript description provide the label as part of the `<title>` element

**Comment by MarcinKrawczuk** [comment]
Creating a record for this manuscript was actually @DariaElagina 's first thought. The problem is that the ms in question (EMML 8897, https://w3id.org/vhmml/readingRoom/view/201642 ) has no foliation nor pagination. How do I deal with that?

**Comment by DenisNosnitsin1970** [comment]
This is a good question and interesting issue. By the way, I think there is foliation in this ms, as in others EMML items, look at the fourth double page from the end, you will see a number. You will see remains of the numbers also on some other folia. The non-inked area on the images is absolutely white, very bright, with no details usual for parchment purpose, and rubrication is poorly visible. There probably was a technical issue (the light too strong) during macrofilming that affected the product. This all, however, does not help now. Difficult to say how you can do. If I were you, I would download each page, and assign a number to it and produce a "home made"/non-official set of images with reference foliation (see the file). And you store it to the digitital resources of the project. Otherwise cataloguing is not really possible. It is a bit of work, and cannot be done but in exeptional cases (since the item is in free access there is no legal problem, though), but sometimes it is the most economic solution. Of course, you also can try to attract the attention of HMML and ask if they can do smth about the images (maybe they can correct them a little, and the folia numbers will emerge).

**Comment by DenisNosnitsin1970** [comment]
Here is the file. 
[EMML 8897.docx](https://github.com/BetaMasaheft/Documentation/files/5240861/EMML.8897.docx)

**Comment by MarcinKrawczuk** [comment]
Thank you all, this is very helpful. @DenisNosnitsin1970 I did as you advised and I've managed to provide a numbering which matches perfectly to the barely visible numbers in the margins.

**Comment by thea-m** [comment]
EMML8897 already exists, without much content. Maybe by "creating" you already meant adding information to it, sorry then!
