### ISSUE TITLE
Quotation in additional

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1509]
Dear Pietro,

I would like to quote a passage from a book in "additional". How can I do this? The schema does not show an error, but there is nothing in the guidelines on this topic. Here is what I encoded:

  ```
<additional>
                  <adminInfo>
                     <recordHist>
                        <source>
                           <listBibl type="catalogue">
                              <bibl>
                                 <ptr target="bm:Zanutto1932Bibliografia"/>
                                 <citedRange unit="page">93</citedRange>
                                 <citedRange unit="item">3</citedRange>
                                 Preghiere a Dio, per i vari giorni della settimana.
                                 Precede un cantico in onore della Trinità. Scritto durante il regno di Yoʾās (1818–1821).
                                 20 x 18, f. 169, Sec. XIX, Legatura in legno non ricoperto.
                                                               </bibl>
                           </listBibl>
                        </source>
                     </recordHist>
                  </adminInfo>
               </additional>


```

**Comment by PietroLiuzzo** [comment]
why do you have to add a quote there, i.e. in additional? is this information belonging there or is it placed there to put it close to the bibliographic reference? what is that quote about? in general a quote is done with the element `<cit>` containing a `<quote>` and a `<bibl>` with `<ptr>` and `<citedRange>` https://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-quote.html 

```xml
<cit>
<quote xml:lang="it">
 Preghiere a Dio, per i vari giorni della settimana.
                               Precede un cantico in onore della Trinità. Scritto durante il regno di Yoʾās (1818–1821).
                               20 x 18, f. 169, Sec. XIX, Legatura in legno non ricoperto.
</quote>
<bibl>
                               <ptr target="bm:Zanutto1932Bibliografia"/>
                               <citedRange unit="page">93</citedRange>
                               <citedRange unit="item">3</citedRange>
</bibl>
<cit>
```

**Comment by SusanneHummel** [comment]
It is the complete quote of the reference. Since it is so short, I would like to cite the whole former brief description of the manuscript. We could provide this information for all other mss of this collection. 
I tried to  change the encoding as you suggested, but the element <cit> ist not allowed folloing      ` <listBibl type="catalogue">`

**Comment by PietroLiuzzo** [comment]
I think it belongs to `<objectDesc>`, not to `<additional>`. It is a description of the manuscript. You could add it to another paragrhic part of your description, if any or into `<support>` or make a `<p>` into `<objectDesc>`, then inside it you can add your `<cit>`.

**Comment by SusanneHummel** [comment]
I tried to insert a `<p`> before the closing` </objectDesc>` but received an error message: 

> element "p" not allowed here; expected the element end-tag or element "layoutDesc"

I found `<support>` does not fit because the citation encompasses the whole description and not only the 

> description of the materials etc. which make up the physical support for the written part of a manuscript or other object.

Sorry!!!

**Comment by PietroLiuzzo** [comment]
You are right, the content model of `<objectDesc>` does not allow a simple `<p>`, you have to add it into `<support>`.
As said, any place which contains p-like text is fine, you can choose. 
One simple option would be to add a `<sourceDesc>` before the one with `<msDesc>`, add a `<p>` there and make your quote. This way you are simply saying: here is another description of the manuscript, which is just a line, and was done by this guy in this publication. then follows your description in another `<sourceDesc>` with all the lovely tagging. perhaps this is more elegant as well.
````xml
<sourceDesc>
<p>
<cit>
<quote xml:lang="it">
 Preghiere a Dio, per i vari giorni della settimana.
                               Precede un cantico in onore della Trinità. Scritto durante il regno di Yoʾās (1818–1821).
                               20 x 18, f. 169, Sec. XIX, Legatura in legno non ricoperto.
</quote>
<bibl>
                               <ptr target="bm:Zanutto1932Bibliografia"/>
                               <citedRange unit="page">93</citedRange>
                               <citedRange unit="item">3</citedRange>
</bibl>
</cit>
</p>
<sourceDesc>
here comes your current sourceDesc with all the msDesc etc.
````
You could add in the `<p>` a few word to introduce this quote, just not to leave it orphaned.
Thinking about this again, this quotation in its entirety will not fit either in `<support>`, nor in `<msContents>`, nor in `<binding>`, because it contains information about each of these aspects, and for the same reason it does not fit in `<additional>`, IMHO. 
If you want to quote it in its entirety in the same `<sourceDesc>` of your msDesc you will have to accept an encoding compromise, and this is also included in the fact you are quoting, so changing somehow context, and within the quotation the semantics are those of the quotation. so, you are speaking about the object and quote the entire description of the manuscript by Zanutto, which happens to contain other informations. 
If you want to stick to the definitions of elements you can split and replicate the quote in each element. 
Another option you can consider is simply leaving this quote in a comment, i.e. not encoding it but leaving it in the file. 
Yet another option is to reconsider the need for this quotation in general and its usefulness in the record.

**Comment by SusanneHummel** [comment]
Thank you Pietro! I added a `<sourceDesc>` before the one with my `<msDesc>`. It is the best solution to handle the two different descriptions. 
I kept the bibliographic reference (without the citation) in the  `<additional>`

**Comment by PietroLiuzzo** [comment]
Great, I am happy this closes the issue, I think once this is live I would like to add this example in the GL to show how a description can also be entirely non structured and more than one description can live together into a single TEI file. thanks!

**Comment by SusanneHummel** [comment]
Sure. It is BGV-003. I am afraid it won't be so soon live. But can't you use it as an example anyway?

**Comment by PietroLiuzzo** [comment]
yes, I can, but it is nice if it is live, it does not need to be soon :) thanks!
