### ISSUE TITLE
viewer does not load

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1522]
There might be an issue with the manuscript viewer. Images don't load for me (my connection is fine), for example https://betamasaheft.eu/manuscripts/ESbmqm003/viewer. When I click on the viewer itself https://betamasaheft.eu/manuscripts/viewer, nothing at all loads.

**Comment by smaugustine** [comment]
Just to note, the issue is BM's iiif server, which is returning 502 errors (Bad Gateway), pointing to a bug with the server itself. Images loaded from other servers (like the VatLib) are unaffected.

**Comment by elambrinaki** [comment]
Hello! I was going to report this problem as well.

**Comment by PietroLiuzzo** [comment]
mmmm.... after restarting the server the gateaway issue is solve, but the example still does not work
perhaps

<idno facs="BMQM/003/BMQM-003" n="86">BMQM-003</idno>

instead of the current
<idno facs="BMQ/003/BMQM-003" n="86">BQM-003</idno>

which has there different abbreviations for the repository?

this image e.g. is available, but I am not sure if the repo is the correc one
https://betamasaheft.eu/iiif/BMQM/003/BMQM-003_002.tif/full/full/0/default.jpg

**Comment by elambrinaki** [comment]
Thank you @PietroLiuzzo! My problem was with Ethio-SPaRe DMB-003, and tbe images are loading now https://betamasaheft.eu/manuscripts/ESdmb003/viewer

**Comment by thea-m** [comment]
Thank you! You are probably right and the ID and repository are to be trusted more than the idno. @DenisNosnitsin1970 @eu-genia do you know more about what happened with this record?

**Comment by DenisNosnitsin1970** [comment]
BMQM-003 is correct, BMQ-003 is not.

**Comment by eu-genia** [comment]
there was an error in the facs and ID, now corrected https://github.com/BetaMasaheft/Manuscripts/pull/824
