### ISSUE TITLE
Unnecessary letters erroneously added by a scribe

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#1531]
Some of us have come across the case in which a scribe incorrectly wrote a word adding a letter or a punctuation mark within the body of a letter. For example, ዘኢይት፡ዓወቅ፡ (the colon in the middle is unnecessary, the word is ዘኢይትዓወቅ፡). Everything is written in the main hand in one single writing process, so we guess that an `<add/>` element is not what we need here.  
The current way to state that the textus receptus is incorrect is seemingly by means of `<sic></sic>`. But we want to be more precise, and want that additional letter to be visualized differently in a future printed output (e.g., ዘኢይት{፡}ዓወቅ፡ or similar, but that's another matter). 
I have found no satisfying markup strategy in the guidelines (https://betamasaheft.eu/Guidelines/?q=erased&id=text-encoding). This is basically the opposite case of an omitted letter which is supplied by the editor: it is an unnecessary letter which is "suppressed" by the editor.
 Any tips?
@thea-m @SusanneHummel @PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
I do not have a solution, but here are my 2pence and a possible solution. If I understand correctly what happened here is that

1. the scribe wrote ዘኢይትዓወቅ፡ ;
1. the scribe added ፡ within the body of, I guess, ት or ዓ ;
1. the editor sees this ፡ is unnecessary and wants to mark it as a mistake .

I think these are three separate things each of which can be encoded (but beware over-encoding is easy...). Luckily, the first is easily encoded by typing the word in.

```xml
 ዘኢይትዓወቅ፡ 
```

the added ፡ I think is really a `<add/>` as you guessed, even if by the same hand.

```xml
ዘኢይት<add>፡</add>ዓወቅ፡ 
```

We have [several values for `@place`](https://betamasaheft.eu/Guidelines/?id=add) but perhaps here we need to add 'within' and you can still add `@hand` and point to the main hand, or leave the attribute out

```xml
ዘኢይት<add place="within">፡</add>ዓወቅ፡ 
```

this would still not solve the second point, as we are not telling within which letter this is added. The colleagues of the Maya Worterbuch have this issue all the time and come up with a rather complex solution, from which I think we could take the use of simple linking system, i.e. `@corresp`. let me assume the ፡ has been added inside the ዓ, then this would need to have an `@xml:id` which I am adding with a `<c>` element.

```xml
ዘኢይት<add place="within" corresp="#modifiedዓ">፡</add><c xml:id="modifiedዓ">ዓ</c>ወቅ፡
```

now that what the scribe did is encoded, the last part, that is to say the editorial statement about the fact that this ፡ is actually unnecessary turns out to be easy, we just need `<surplus>` 

```xml
ዘኢይት<surplus><add place="within" corresp="#modifiedዓ">፡</add></surplus><c xml:id="modifiedዓ">ዓ</c>ወቅ፡ 
```

`<surplus>` is already rendered with {} while `<add>` is rendered with a popup only in the app. you should see something like

> ዘኢይት{፡}ዓወቅ፡

and hovering the ፡ it will tell you something like note added within.... 

for a print output you would get the same, without popup of course. we can however build a footnote from this markup which will say, if a surplus is present something like "`{t:add} erroneously added {t:add/@place} {sibling::t:*[@xml:id=substring-after(t:add/@corresp, '#')]} {if(t:add/@hand) then (' by ' || string(t:add/@hand) else ()}`" which in our case will result into 

> "፡ erroneously added within ዓ" 

if there was a `@hand` with value h1 it would say "፡ erroneously added within ዓ by h1" or any variation of that, e.g. if the name of the scribe was available somewhere, it could follow connections to retrieve that, so, if I was the scribe and my name was record in the record according to the GL and Pietro would be the standard name in the person file, it would say "፡ erroneously added within ዓ by Pietro"

**Comment by PietroLiuzzo** [comment]
if you like this, please say so, I would then need to
- [ ] update the guidelines
- [ ] update the schema with the value 'within' for `add/@place`
- [ ] update the visualization

your decision for print options can come with those requirements, which are not bm requirement

**Comment by MassimoVilla** [comment]
Thank you Pietro for this thorough explanation.
In fact, the most common circumstance (as far as I have come across at least) is that the scribe erroneously writes one more letter in sequence, not within the body of a contiguous letter. In this case, as far as I have understood, a simple `<surplus>` is exactly what we need.
So, if the scribe writes e.g. ክርስቶቶስ፡ instead of ክርስቶስ፡, I can encode this as `ክርስቶ<surplus>ቶ</surplus>ስ፡`, which will generate 

> ክርስቶ{ቶ}ስ፡

This - I believe - covers the majority of cases. The more sophisticated case of a modified letter is also useful, and I think it needs to be recorded in the guidelines.
Thank you also for updating the table in the guidelines (here: https://betamasaheft.eu/Guidelines/?q=erased&id=text-encoding) with the `<surplus>` markup. You can use the example above `ክርስቶ<surplus>ቶ</surplus>ስ፡`, which is fictitious but plausible.

**Comment by PietroLiuzzo** [comment]
thanks! I will carry on with the guidelines editing and ask you to review the PR, if that is fine for you

**Comment by PietroLiuzzo** [comment]
so, what should I do with the rest? do we want an example of that somewhere?

**Comment by PietroLiuzzo** [comment]
@MassimoVilla let me know if it is now ok or we should add also the 'within' thing, thanks!

**Comment by MassimoVilla** [comment]
Sorry Pietro for my belated reply. The "within" encoding can be also added, even if in my experience it is indeed (luckily for us) rarely attested in the Ethiopian scribal tradition. The example provided, though fictitious, sounds plausible:
`ዘኢይት<surplus><add place="within" corresp="#modifiedዓ">፡</add></surplus><c xml:id="modifiedዓ">ዓ</c>ወቅ፡ `
As for the visualization in the printed output, I think we - as a team - will decide the most viable solution at a later time, because it is a quite complex case and several opinions might arise. So far, no example is provided in our Oxford records.
Thank you!

**Comment by PietroLiuzzo** [comment]
ok, thanks @MassimoVilla, I will then close this.
