### ISSUE TITLE
Watermarks - very disturbing!

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1532]
I just used BM to check the text in EMIP 634. And I realized that there are watermarks over the images. 
This alone is very disturbing, but when I zoom in the watermark move along, which is even more disturbing.

It is not only irritating to the eye, but is especially very annoying when I want to read the rest. 
I am not sure I have seen this in other repositories (I am now thinking of BL, BnF, vhmml), so I do not think it can be a security issue. At least they do not seem to care - and their mss are therefore much more pleasant to use.

**Comment by PietroLiuzzo** [comment]
this has been already observed a number of times by many users. 
I have no problem removing the dynamic watermark, but it is not a change of decision for me. 
Images with dynamic watermark are more secure, especially disallowing usable screenshots.
@abausi @DenisNosnitsin1970 @eu-genia

**Comment by abausi** [comment]
We have to keep the watermarks, for several obvious reasons (including 
agreements with some institutions)

Il 23.10.2020 15:22, Pietro Liuzzo ha scritto:

**Comment by thea-m** [comment]
I completely agree with Sophia. The manuscripts with these SPARKLING watermarks are not usable. We all have already eye problems and are staring into screens the entire day, why do we need to add such strain on our eyes?  If I work with E-S manuscripts, I always take the extra steps of logging into the DOmLib database and finding the images there, because I cannot use them on BM. As Sophia, I have never seen such watermarks anywhere else at all. 
The obvious reasons are sadly not known to me, could you explain them? What does the sparkling accomplish that unmoving watermarks would not accomplish?

**Comment by SophiaD-M** [comment]
Sorry if I might not grasp the full implications here, so I have to ask - why are screen shots a problem? I thought BM is open access, and to me this implies being able to use the material, and thus, no watermarks that are in the way. 
As I said above, renown libraries do not do this. 
Maybe if there are collaborations with institutions that require watermarks the use of which can be limited to said collections?

My example here from EMIP was available on the emip website before - without watermarks obviously!

**Comment by abausi** [comment]
We have to find a solution for those who access MSS from "home", 
particularly when working on them for catraloguing: but when offering 
them, we cannot avoid this; or we have to find anyother, less disturbing 
system, that offers the same security standard

Il 23.10.2020 15:29, thea-m ha scritto:

**Comment by abausi** [comment]
It is impossible to differentiate the protection systems. In any case: 
let me discuss this with Pietro (as I already did in the past). This, at 
the moment, had appeared the best possible solution, in agreement with 
what some libraries offer.

Il 23.10.2020 15:31, SophiaD-M ha scritto:

**Comment by PietroLiuzzo** [comment]
the dynamic watermark prevent screenshots being made and used in publications without permission.
also in BnF and others the fact you can access and use the images does not mean you can publish them or reproduce them without permission.
we have several other options, like texture and transparency which we can play with. 

I could make one bigger fixed watermark which is semitransparent (now is 0.5, we could go to 0.1) for example. 
we loose the dynamic. we could also simply make it more rare by reducing the probability of the watermark

**Comment by smaugustine** [comment]
I accept that watermarks may be necessary, but surely we can change how they are implemented? Having watermarks doesn't necessarily mean having something so obtrusive and painful to see (in terms of bright, distorted colouration). The Vatican Library's watermarks are very unobtrusive, IMO.

**Comment by abausi** [comment]
Let's try with varying the degree, as Pietro and Sugutine suggests, if 
the present one is too invasive and disturbing.

Il 23.10.2020 15:36, Pietro Liuzzo ha scritto:

**Comment by thea-m** [comment]
I fail to see why non-dynamic watermarks would not be visible on screenshots.

**Comment by PietroLiuzzo** [comment]
if you have a watermark fixed in a corner of the image for example, it is enough to crop that out, even programmatically.

**Comment by smaugustine** [comment]
Vatican Library watermarks are in the centre, but are more faint and manipulate the colour far, far less.

**Comment by thea-m** [comment]
Ok, but once the screenshot is taken, aren't the watermarks fixed anyway?

**Comment by SophiaD-M** [comment]
They EXTREMELY disturbing, watermarks have to be as a rule - otherwise the would be useless ;)

I also do not see how varying degrees will improve the visibility. 

Honestly, I accuse all of us to have used screen shots or other kinds of images for presentations, and this is the beauty of digital copies, the availability, the accessibility...
(I feel like an extremist now, but I mean it)

**Comment by SophiaD-M** [comment]
I revoke what I just said - indeed in VatLib the watermarks are quite acceptable

**Comment by PietroLiuzzo** [comment]
if they are dynamically added, there is no way to programmatically cut them out. if they are fixed this is entirely possible, if not trivial. Please before further commenting, since the point is clear and so is the possible solution, let me make this changes to the settings and you will be soon able to tell me if the quality of your experience has improved.

**Comment by smaugustine** [comment]
As a side note -- one I am sure no one else noticed -- the disabling of right click on the viewer page is totally unnecessary. 

Disabling right clicks does literally nothing except create an inconvenience, as everything you can do by right-clicking you can do by other means. And, in any case, the use of watermarks and Mirador limit what one can achieve by right-clicking anyway.

All this does is make it more difficult to copy manifest URLs and other useful information. Also, given the how often server errors occur, it adds tedious steps in order to find the error information that helps diagnose what the problem was.

**Comment by abausi** [comment]
Please, Pietro go on. If your sugestion this is still disturbing, let's 
see what else can be done.

(The last observation by Augustine is another point.)

As to the argument by Sophia: there are libraries which, under other 
conditions, would not have put their images at disposal. So this 
argument does not work.

We could take as an example Mezgaba Seelat: but let's have a bit of 
patience - please! wait a moment.

Il 23.10.2020 15:41, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment]
I have substituted the image which was selected as watermark with a copy in BW, reduced probability to 0.2 and opacity to 0.3. e.g. https://betamasaheft.eu/iiif/AP/046/AP-046_014.tif/full/full/0/default.jpg 
let me know if your experience is improved.

**Comment by PietroLiuzzo** [comment]
> Also, given the how often server errors occur, it adds tedious steps in order to find the error information that helps diagnose what the problem was.

@smaugustine you are very welcome to report those errors when you find them, by any of the available channels. Complaint alone brings no improvement, and we rely on this reports for the development. The diagnose and solution of the problem is likely to be far quicker for me than it is for you for a number of reasons, among which certainly not competence. 

> Disabling right clicks does literally nothing except create an inconvenience, as everything you can do by right-clicking you can do by other means. 

given that there are people publishing entire books explaining to scholars how to do mischief, anything which disturbs those is a good thing IMHO. I have been discouraged to do so in the past, but the more I think of it, the more I am convinced it is better as it is if it can discourage the 5% of people which only know how to right click to download the image. this limitation is only on the viewer. however, if there is an agreement about this, the possibility to right click is easily added back... 
to copy the manifest url, click on it and copy it from the browser url box, I do not think this is terribly time-consuming compared to right click.

**Comment by PietroLiuzzo** [comment]
Since I am often reported to myself, but I cannot report to my self, let me remind you all that we also have [a nice code of conduct here](https://github.com/BetaMasaheft/Documentation/blob/master/CODE_OF_CONDUCT.md )!

**Comment by thea-m** [comment]
Thank you! I think this is already much better.
I am not sure for the reference to the code of conduct - has it been violated in any way in the course of the conversation taking place in this issue?

**Comment by PietroLiuzzo** [comment]
please have all a look, I think the probability is now too low.

**Comment by SophiaD-M** [comment]
> 
> 
> I have substituted the image which was selected as watermark with a copy in BW, reduced probability to 0.2 and opacity to 0.3. e.g. https://betamasaheft.eu/iiif/AP/046/AP-046_014.tif/full/full/0/default.jpg
> let me know if your experience is improved.

Pietro - thank you - I think it is a huge improvement. It is much smaller, not sparkling, and I think also it does not render the black ink to red anymore! 
(I would need to see it in live action to fully come to a final opinion.)

**Comment by PietroLiuzzo** [comment]
it is live, please load any image and it will be served with this settings
