### ISSUE TITLE
Visualization of bibliography in a work authority file

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1535]
1. I added bibliographical references to the main entry: https://betamasaheft.eu/works/LIT1455GadlaG/main

and encoded (only the last two references)

```

            <listBibl type="secondary">
               <bibl>
                  <ptr target="bm:Raineri2005EAEGeorge"/>
               </bibl>
               <bibl>
                  <ptr target="bm:Strelcyn1974CatJRylands"/>
                  <citedRange unit="page">31</citedRange>
                  <citedRange unit="item">Ms 12, I.2</citedRange>
               </bibl>
               <bibl>
                  <ptr target="bm:GrebTiss1935Codice"/>
                  <citedRange unit="page">713</citedRange>
                  <citedRange unit="item">Vat 233, 1.3</citedRange>
               </bibl>
            </listBibl>
```

The third reference is not dispayed.

2. I added specific bibliography to coloph#1 and encoded:

```
<bibl><ptr
                     target="bm:Budge1930George"/><citedRange>274–276</citedRange></bibl>
                                       <bibl>
                        <ptr target="bm:1967GadlaGiyorgis"/>
                        <citedRange unit="page">83</citedRange>
                        <citedRange unit="item">chapter 9.23</citedRange>
                     </bibl>
                     <bibl>
                        <ptr target="bm:1968GadTamMalkGiyorgis"/>
                        <citedRange unit="page">119–120</citedRange>
                        <citedRange unit="item">chapter 9</citedRange>
                     </bibl>
```

Displayed are only the range of pages and items but not the title of the referenced works.

https://betamasaheft.eu/works/LIT1455GadlaG/text

**Comment by PietroLiuzzo** [comment]
for the first instance, it looks like the tag is bm:GrebTiss1935Codice**s** not bm:GrebTiss1935Codice

**Comment by PietroLiuzzo** [comment]
I think I would also do `<citedRange unit="chapter">9</citedRange>` instead of `<citedRange unit="item">chapter 9</citedRange>`.

The bibliography added into a `<div>` in the edition is IMHO something that needs a bit of discussion. It looks like this encoding of bibliography into a note inside the text is used in [11 work records](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootW%2F%2Ft%3Adiv%5B%40type%3D%27edition%27%5D%5Bt%3Adiv%5B%40type%3D%27textpart%27%5D%2Ft%3Anote%2Ft%3Abibl%5D). I am not sure why this is preferred instead of using the bibliography `<div>` eventually [with a pointer to the appropriate `@xml:id`](https://betamasaheft.eu/Guidelines/?id=bibliographic-references) in this case `coloph1`. 

I also think these `<note>`s should perhaps be printed out in the apparatus column, not below the text block. But I may be missing some former decisions about this. Please @thea-m @eu-genia and @DariaElagina share your point of view.

**Comment by thea-m** [comment]
One reason for the inclusion of the bibliographical elements might be (probably is in my case) just habits, nothing conceptual (in cases as LIT4960Taabbeyo). This encoding is also in analogy to the widely practiced inclusion of notes as `<note>Quoted after <ref type="mss" corresp="MSxy">` and has the advantage of being very clear and explicit, both while encoding and in the current visualisation.  @PietroLiuzzo could you give an example of the preferred encoding with the bibliography div?
I find the current visualisation very good, because all informations belonging together is printed next to each other. Would that also be possible in the apparatus?

**Comment by PietroLiuzzo** [comment]
I think this was closed with https://github.com/BetaMasaheft/Documentation/issues/1554
