### ISSUE TITLE
encoding modification of characters

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1536]
How can we encode the modification of a character, e.g. something like ቦ made into በ, by the copyist or at a later moment? (What would be marked as "mutavit" in an edition.) This occurs quite often and is of course philologically relevant.
Thank you!
@SusanneHummel @MassimoVilla

**Comment by PietroLiuzzo** [comment]
would this not simply be a correction? 

```xml
<choice>
  <orig>ቦ</orig>
  <corr>በ</corr>
 </choice>
```
eventually with `@resp` on `<corr>` to indicate the hand/copyist

**Comment by PietroLiuzzo** [comment]
we do not have a rendering option for this, 
- [ ] should it behave like an editorial correction (`choice[sic][corr]`)?
- [ ] we can also add an example in our text-encoding guidelines page

**Comment by thea-m** [comment]
That seems good to me. @SusanneHummel @MassimoVilla any proposals for a rendering?

**Comment by MassimoVilla** [comment]
Well, it is not the kind of scribal phenomenon you can easily render with a bracket. In editions it is marked with _mutavit_ (as Thea said) or with _ante corr_. ("before the correction") or again _post corr_. ("after the correction"). The problem is that this rendering requires that the entire word is repeated, e.g., in such a way: 

> ወእንዘ፡ ከልቦ፡ (_ante corr_. ከልበ፡)

while the proposed markup involves only the single corrected letter.

**Comment by SusanneHummel** [comment]
For me, the bracket would be suffucient. I also marked this phenomenon with brackets ii
n my edition. The brackets clarify that the described phenomenrefers only to the characters in bracket:

another example: the following scribal practice 
![grafik](https://user-images.githubusercontent.com/28757489/97294687-9e764980-184e-11eb-9606-8c916ac6f11f.png)

I described in the App with: 5.2,25 ልቡ፡] A, ል<ባ> B, in ል{ቡ}፡ mut.(avit) B4
for clarity I added the word "in" xxxx mutavit. If however, BM opts for the broader description corr., that would be fine with me as well. 

Massimo's suggestion is, however, more clear but takes more space.

**Comment by PietroLiuzzo** [comment]
> > ወእንዘ፡ ከልቦ፡ (_ante corr_. ከልበ፡)
> 
> while the proposed markup involves only the single corrected letter.

the markup allows to print all you want that is to say, if that mark up is present we can produce the output you ask for, inline or in a note.

**Comment by PietroLiuzzo** [comment]
from that encoding we can also produce what @SusanneHummel suggested.
please make your choice and let me know when your are decided so I can implement the rendering for the app and consequently update the guidelines. thanks!

**Comment by MassimoVilla** [comment]
> For me, the bracket would be suffucient. I also marked this phenomenon with brackets ii
> n my edition. The brackets clarify that the described phenomenrefers only to the characters in bracket:
> 
> another example: the following scribal practice
> ![grafik](https://user-images.githubusercontent.com/28757489/97294687-9e764980-184e-11eb-9606-8c916ac6f11f.png)
> 
> I described in the App with: 5.2,25 ልቡ፡] A, ል<ባ> B, in ል{ቡ}፡ mut.(avit) B4
> for clarity I added the word "in" xxxx mutavit. If however, BM opts for the broader description corr., that would be fine with me as well.
> 
> Massimo's suggestion is, however, more clear but takes more space.

I am sorry, I probably misunderstood the context. Are we talking about the printed catalogue or the critical apparatus of a printed edition? The two printed output might look quite different because in the former case we have a linear sequence of text (only one "level" of interpretation: we need to keep clarity), in the latter we have both the level of the text and the level of the apparatus, which we give for granted that contains a variation of any sort.
In critical apparatuses I've also used so far the brackets to clarify the phenomenon. So e.g. my example above would run as follows: 

> ከልቦ፡] ከል{በ} _ante corr_. B

**Comment by SusanneHummel** [comment]
Sorry, Massimo is of course absolutely right!!!!
On the text level one bracket is not sufficient because we have two actions on one and the same character; therefor the action cannot be presented with one bracket (because it does not compass the process of change).
Sorry for the confusion I caused.

**Comment by PietroLiuzzo** [comment]
can this be closed? or would you like any other changes affecting the web application?
