### ISSUE TITLE
Bug? Search leads to exerr:ERROR XPTY0004

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1555]
I would like to search for all manuscripts records that include an "excerpt" from the "Gospel of John"

1. So I entered both keywords into the search form

https://betamasaheft.eu/facet.html?query=%22Excerpt%22+%22Gospel+of+John%22

However, when I click at the left column under "item type" "Manuscript" I receive an error message:
https://betamasaheft.eu/facet.html?query=%22Excerpt%22+%22Gospel+of+John%22&type-facet=manuscript

2. When I looked for ""Excerpt from the Gospel of John"
https://betamasaheft.eu/facet.html?query=%22Excerpt+from+the+Gospel+of+John%22

I found what I was slooking for :) Yeep!!!!!!!

**Comment by PietroLiuzzo** [comment]
the error is gone, thanks for spotting it, however, I am not sure this search actually gives you what you are looking for. you are actually finding those places where people have been kind enough to write the words "Gospel of John", while I would expect this to be encoded with `<title>` which however, turns out not to be the case. 
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Atitle%5B%40ref%3D%27LIT1693John%27%5D%5Bmatches%28preceding%3A%3Atext%28%29%5B1%5D%2C+%27excerpt%27%29%5D

**Comment by SusanneHummel** [comment]
For me I just need an example how an excerpt should be encoded. I encodeድ: 

```
<msItem xml:id="ms_i9">
                     <locus target="#39r"/>
                     <title ref="LIT2715John">Excerpt from the Gospel of John</title>
                     <note>The excerpt comprises John 1,1–1,5.</note>
```

**Comment by PietroLiuzzo** [comment]
your note could eventually be better encoded using [appropriate referencing](https://betamasaheft.eu/Guidelines/?id=references)
```xml
<note>The excerpt comprises <ref type="work" corresp="LIT2715John.1.1-5">John 1,1–1,5</ref>.</note>
```

**Comment by SusanneHummel** [comment]
Thank you again!. I updated my note accordingly.
