### ISSUE TITLE
PersName in red ink

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#1566]
It is often the case that a proper name (e.g. an owner or a holy name) is rubricated.
Which of the two following options is preferable in terms of hierarchy and consequences in visualization/filtering etc.? Both have been used apparently.

- `<persName ref="PRS13232EhetaMar"><hi rend="rubric">እኅተ፡ ማርያም።</hi></persName>`
or
- `<hi rend="rubric"><persName ref="PRS13232EhetaMar">እኅተ፡ ማርያም።</persName></hi>`

(example taken from ms MNC-010)

Thank you.

**Comment by thea-m** [comment]
Good question! I think I usually follow the first option, but rather intuitively, without having thought much about it.

**Comment by MassimoVilla** [comment]
I've intuitively been using the second option, because rubricated portions of text might be longer than a single persName, but perhaps there are more solid implications which make one or the other more appropriate.

**Comment by SusanneHummel** [comment]
I think I mainly used the second option. Is there any difference in the later visualization?

**Comment by PietroLiuzzo** [comment]
I would strongly encourage you not to take later visualization or one possible output form as a meaningful criterium for choices of encoding. it is simply not meaningful neither helpful to adapt semantic encoding to one ephemeral visualization. In this case however, it strikes me as a not very relevant distinction, that is to say, both encoding are fine and valid. the only distinction I could make between the two examples above is the following: the first tells me "there is a name and a part of it (in this case, all of it) is rubicated" the second tells me "there is piece of rubricated text which contains a personal name". both are fine, there is no relevant difference, neither need to harmonize or force one nesting over another, because it can be that a part only of a name is rubricated as well as it can be that a name is only part of a rubicated piece of text...

**Comment by MassimoVilla** [comment]
Thank you Pietro for your answer which - I believe - satisfies our question.
Beyond this particular case, we won't have any trouble selecting the appropriate encoding in those cases in which one personal name is partially rubricated or is part of a broader sequence of rubricated text. 
I close this.
