### ISSUE TITLE
shelf mark list 

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1580]
If I may get involved? 
I do not understand the link below:
https://betamasaheft.eu/manuscripts/browse

It is found under the header Manuscripts -> Shelf marks. But the list is not a list of shelfmarks (which are DD, or EMML, or similar), but it is a list of the repositories, am I right? 
The list is wonderful, very helpful and should not be removed!! I just do not understand why it is called "shelfmarks". If I search EMML mss in this link, I have to go to Hill Museum... thus to the repository. 

And a purely aesthetical-comment, the size of the words is really huge, could it be maybe smaller? 
Also to make scrolling easier could there be a list of the alphabet above? So I could just jump to Z if I wanted, instead of scrolling? And likewise a "go back up" button to save scrolling back up?

_Originally posted by @SophiaD-M in https://github.com/BetaMasaheft/Documentation/issues/1573#issuecomment-734271296_

**Comment by PietroLiuzzo** [comment]
that is a list of shelfmarks organized by institution (the entity providing the shelfmarks). navigation help can be provided, yes. 
you can search by shelfmarks also
- in the facet search
- using the name field in the manuscripts list view
- in the advanced search
- in the simple search

**Comment by eu-genia** [comment]
@SophiaD-M in the issue you were commenting in, my proposal was to add definitions on top of each page/list, so if you open the link you do not understand you should see the text (as suggested in the issue)

>Here you can browse a full list of manuscripts available on the platform, arranged by repositories and shelf marks (clicking on the "show list" button will expand the list for each location).

If you think this text is not clear we can make it clearer, that is what the issue is for.

**Comment by smaugustine** [comment]
Following from what @SophiaD-M said, alphabetical anchor links would really help with navigation. Some pagination, too, I think, would go a long way. The lists are really long and cumbersome to scroll through (and can take a while to load), it might be better to paginate the lists of shelfmarks (and even to have them loaded in chunks rather than all at once).

There also seems to be some issues with the sorting, that numbers are sorted "alphabetically" rather than numerically, i.e., BnF Éth. 100 is listed before BnF Éth. 2 (because 1 comes before 2).

**Comment by smaugustine** [comment]
The use of horizontal space is also odd. The lists leave this large blank space on the left that could be better used (e.g., lists spanning multiple columns).

<img width="1228" alt="Screen Shot 2020-11-26 at 14 48 44" src="https://user-images.githubusercontent.com/6315671/100358444-7d904800-2ff6-11eb-83bb-af55741379e1.png">

**Comment by PietroLiuzzo** [comment]
as said in the other issue, I am not going to invest time in design, not in the short term for sure. It is, compared to other issues and tasks related to content, simply not a priority. This was requested like this, because people did not like the paginated list which we had before.... also the alphabetical ordering is done on alphabetical string of the shelfmark. if you have suggestion on how to provide better ordering for strings with numbers in them, please put them forward, I will be happy to learn.

**Comment by smaugustine** [comment]
The sorting is a bit of an involved fix. It would depend on whether it is sorted by the database or by the app (i.e., whether the data, when requested, is returned already sorted or is sorted after being returned).

There are a number of existing libraries for "natural sort" ([one quick example](https://www.npmjs.com/package/alphanum-sort)), but of course it depends at which stage the sorting is occurring and what sort of code is required.

It would be possible also on the client, instead of the DB or the app, which would even allow for jQuery, for instance, but this would be the most inefficient, create the biggest slowdown, and would ideally be avoided.

**Comment by SophiaD-M** [comment]
@eu-genia  - the little explanation is very clear, thank you!
