### ISSUE TITLE
Occupation "scribe"

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1589]
I would like to add the element "occupation" in a newly created person record for a scribe (in addition  to the relation saws:isCopierOf).

Since there is no explicit example in the guidleines (and it seems that the existing records offer different types), I would like to ask which type is most suitable for a scribe:
"art" "literary" "ecclesiastic" "other"

https://betamasaheft.eu/Guidelines/?q=occupation&id=occupation

**Comment by DenisNosnitsin1970** [comment]
Actually, no one matches very exactly. In records you can find nearly all four in occupation=type, "literary" and "ecclesiastic" seems to dominate.

**Comment by SusanneHummel** [comment]
Exactly. For these reasons I suggest to agree on one "type". But if a uniform assignment is not necessary, I will opt for  "art".

**Comment by DenisNosnitsin1970** [comment]
I wonder if this alignment is practical and necessery, and if it is plausible to achieve it. I think once we discussed it already. Maybe someone will remember.

**Comment by DenisNosnitsin1970** [comment]
I think I always took the category "ecclesiastic" assuming that each scribe is associated with the Church, directly or indirectly, in one or another way. Historically, scribing is one of the "ecclesiastic" occupations.

**Comment by thea-m** [comment]
@DenisNosnitsin1970 , I also remember a discussion, but not its outcomes

**Comment by MassimoVilla** [comment]
I think I've used "literary" because a scribe does not merely reproduces the text in a passive way, but intervenes with intentional or unintentional alterations, sometimes producing a new text (that's why we have different work records for several redactions). He is an author in some respects.
It's fascinating to see how our several encoding practices say in fact much more about ourselves than about the task of the scribe.

**Comment by DenisNosnitsin1970** [comment]
Yes, however, there is a distance to "literary", also if you consider "alterations", from my point of view. If a scribe creates a new redaction, he assumes a new quality and becomes an author (possibly one of many), doesn't he? :) I tend to think that the result of our discussion was  "ecclesiastic", but I am not sure.

**Comment by eu-genia** [comment]
I have always put "ecclesiastic"  as well, assuming scribes were monks or deacons, reserving "literary" for "true" authors.

**Comment by SusanneHummel** [comment]
"ecclesiastic" is limited to "Occupation within a religious institution" according to the guidelines. Even though it might be true for the majority it seems too narrow to me, it excludes all "royal" scribes
"literary" refers to "Literary activities (i.e. author, translator)" but not every scribe is or even should to be "creative" 
"art" encompasses any "Artistic occupation or interests" - maybe too wide, but since we consider evry single manuscript as an "artefact" , I would be in favour of "art"

**Comment by DenisNosnitsin1970** [comment]
"Artefact" but perhaps in the sence "Gegenstand" = "material object". "Artistic" is difficult to apply to "scribal occupation", in my opinion. There seems to be no category that fits well, but they are very inclusive instead (for instance you may consider the entire Church as "religious institution", then you have no contradiction). Also, I think, if you find a true calligrapher, you can select for him category "art".

**Comment by antobrita** [comment]
I think the real problem is that we do not have enough information about the real (main) "occupation" of the persons that we find mentioned in the manuscripts. What we get from the manuscripts is only a partial picture of the real life of the people involved in the manuscript production, use, etc. I would stick to that partial picture, because this is all that we know (apart a few exceptions).

I would exclude "Art" in this case because, as @DenisNosnitsin1970 noted, the meaning of "Artefact" in English is: "an object made by a human being, typically one of cultural or historical interest" (https://www.lexico.com/definition/artefact) and would use the type "Art" only when referred to a mere artistic context.

Concerning "Ecclesiastic", it is true what @SusanneHummel says about royal scribes (but also in this case, we do not know much about their education (maybe they - or at least some of them - were also ecclesiastics). Another limit of using "Ecclesiastic" for a scribe, is that it excludes the debteras that are technically not mere ecclesiastics (at least not all of them) but they are still scribes.

"Literary", as @MassimoVilla pointed out, is the category that fits better. I understand the argument of @DenisNosnitsin1970 on this point, but even if a scribe becomes an author this won't fall far from "Literary".
 
Another solution could be to create a new type for occupation such as "scholar"/"traditional scholar"/"literate" (we know for sure that scribes are educated persons and the skills they acquire requires a long training in traditional church schools)

**Comment by SusanneHummel** [comment]
After all, I will assign "litereray" and close this issue. Thanks to all who contributed!!
