### ISSUE TITLE
bottom border of homepage first div not visible

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1614]
I did not in fact! That might be because I am using my laptop only? Look at this screenshot, the arrow pointing down is not even visible on my screen.

![image](https://user-images.githubusercontent.com/29302681/101490367-8839ce00-3962-11eb-80d1-0b12d7b47679.png)

_Originally posted by @SophiaD-M in https://github.com/BetaMasaheft/Documentation/issues/1597#issuecomment-740622507_

**Comment by eu-genia** [comment]
speaking about the homepage:
the link here
![image](https://user-images.githubusercontent.com/17987728/101615695-b7a61480-3a0e-11eb-9066-bc080b8ebe44.png)
leads to https://betamasaheft.eu/searching.html which gives a 404 error

**Comment by eu-genia** [comment]
my arrows behave in most unpredictable ways :) (I can see the arrow on the right, but when I click it it brings me two screens down, then I can go one screen up, but have no arrow on the second screen, only the fixed bottom one; if i go down i again jump a bit, and then the arrows are on the left - which I guess is desired because of the layout but quite unexpected - and again none side arrows on the bottom screen - is this correct?)

**Comment by PietroLiuzzo** [comment]
thanks for the account. no change has been introduced beside adding the button where it was requested. the bahavior of the arrows is unchanged from before, and does what was requested to do when the design of this page was discussed and implemented. if you wish to change that behaviour, please open a dedicated issue and explain what you would like to have instead so that people can have their say on that proposal.
