### ISSUE TITLE
Encoding of internal dates of manuscripts in personal records

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1620]
Dear all,

this issue is inspired by a discussion with @thea-m  in the following PR: [https://github.com/BetaMasaheft/Persons/pull/308](url)
Do we want to standardize the encoding of an internal date of a mansucript in the related person records? My proposal from the PR is to add the information in a form of a free texts: This person owned a manuscript (with a ref) dated to (internal date from a manuscript). I would add it inside the floruite, but still preserve the wide range for the floruite, as I suppose that a person was active during several years. 
Any ideas, @thea-m , @DenisNosnitsin1970 , @eu-genia ?

**Comment by PietroLiuzzo** [comment]
Dear @DariaElagina, the analytic view of a person record will automatically show a list of roles of a given person.
e.g. https://betamasaheft.eu/persons/PRS11944GabraM/analytic 
and the value owner is allowed for `@role`. this would say pretty much "{name} owned {manuscript}". There is no date printed there, but it could be easily added if any is available, i.e. without having to keydown anything, since the connection is already available (and doubled by the `<relation>`). 
However,  I am not sure about the discussion about the manuscript ([this one?](https://github.com/BetaMasaheft/Manuscripts/pull/917)) and neither about the issue in general, so perhaps I just missed the point. Could you please clarify with a statement about what you would like to achieve and an example of how you do this now and why this is not sufficient? From the PR discussion I do not understand why would an "internal date" (?) of a manuscript be copied over to a person record.

**Comment by DariaElagina** [comment]
Dear Pietro,

many thanks! The discussion was on a person, I do not why the link is not working, sorry. It works only wth copy-paste: https://github.com/BetaMasaheft/Persons/pull/308

I think that if the in the analytic view one could add an originDate from the related mansucript that would be really enough.
The issue was inspired by the fact that in case of a dated manuscript we could document this date in the personal record as well as proposed by @thea-m . But as far as I undestand she proposes to encode it as floruit, am I right @thea-m ?

**Comment by DenisNosnitsin1970** [comment]
I normally coordinated the dates before just when I created personal records, as probably everyone did when filling the field in question, as how you else would you get any date? I also keep "floruite" very broad. I usually did not write anything because if you start justifying in words, it will might be a long discussion (esp. in case of secondary owners who are in great majority). I am not sure that this is the sense of "floruite".

**Comment by thea-m** [comment]
Thank you, @DariaElagina !
The question from the PR arose from the following situation: A manuscript has an internal date of 1861 (or whatever) and a person is mentioned in the primary stratum of this manuscript, so we can assume that this person existed in 1861, hopefully for them also somewhat before and after.
I think that there are two questions related to this.
1) Is it necessary to encode any date in the person record? The attestation of the person will be picked up by the app, and often in such cases there is even an additional relation.
My opinion is that it is not necessary (there is no prescription in the guidelines), but does not hurt in any way. BM-historically, this was not done at the beginning of the project but has become more common recently and was felt useful by many project members. The lack of a date is something often bemoaned in person PRs, which is why I also started including them :) 
2) If one wishes to encode the date directly in the person record, `<floruit>` seems like the best place. Now the question is whether only the date of the manuscript - 1861 - should be given here or a broader range in which the person's lifespan probably fell. This was the question from the PR. The TEI definition of floruit is "contains information about a person's period of activity", which probably covers both. My preference has been to give the more narrow, actually attested date. I assumed that readers can understand that the person was probably active for longer. Note that this concrete example is a relatively rare case, usually no exact date would be attested in the manuscript, in which case the broader estimated production date would be given in the person record. This range will further broaden for persons attested in secondary strata. All of this being optional.

**Comment by eu-genia** [comment]
As we have already discussed in PRs, I have always added a `<floruit>` date range around the date of manuscript production as it seems to me the best and the most transparent way to disambiguate quickly the many homonymous persons. I would say that whenever we can provide some sort of date we should.

**Comment by PietroLiuzzo** [comment]
What remains to be done is 
- [ ] decide if this reasoning needs to be described in the GL. I would go for a copy paste of @thea-m comment in the GL, 
- [ ] provide additionally the date with the manuscript name in the analytic view as discussed above. 
- [ ] We can eventually pop that block up in the main view instead of leaving it in the analytic if that helps the disambiguation let me know if this would be what you want. 
- [ ] Another additional action in this direction would be to list related MS and Works in the results view as we do for witnesses of works.

**Comment by PietroLiuzzo** [comment]
<img width="1409" alt="Bildschirmfoto 2021-08-20 um 13 28 18" src="https://user-images.githubusercontent.com/508012/130226663-e952f6a9-8eaf-4efc-b527-3a93d952c664.png">

**Comment by PietroLiuzzo** [comment]
<img width="1163" alt="Bildschirmfoto 2021-08-20 um 13 43 46" src="https://user-images.githubusercontent.com/508012/130228239-deafb299-fb93-4c8f-a7df-b2332194950e.png">
