### ISSUE TITLE
search operators and ranking

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1640]
Currently, the default search operator is OR (that is, if I enter several strings, either is searched for), and the sorting at least in facet search is (I guess) primarily by record type, before a filter is applied (first all places, then all institutions, etc ?), with the result that, if I do not know exactly how to filter down the search, I may never get to the actual record I am looking for (tried for several two-component names of persons)

It would be good if the sorting could be done by "best match" (first all records where all strings appear in proximity, then all records where all strings appear somewhere, and then records where only some of the strings are present). 

Is this possible?

**Comment by eu-genia** [comment]
And - is it possible to have a prompt on the default operator and on the ways to have the AND operator, the quotation marks, etc.? Many users do not know this, not even when they use Google.

**Comment by smaugustine** [comment]
I missed this issue, but I also [wrote some remarks](https://github.com/BetaMasaheft/Documentation/issues/1642) regarding this issue.

**Comment by smaugustine** [comment]
(Minor change from sorting => ranking. In a search/db context, sorting would refer to alphabetical, numerical, etc., whereas ranking would refer to the relevance/accuracy of the result based on what was searched)

**Comment by eu-genia** [comment]
sorry for the sorting/ranking confusion but yes your issue raises the same point:)
when i search https://betamasaheft.eu/facet.html?query=amda+seyon i get anything but the emperor ʿAmda Ṣǝyon - who is hidden on page 6 of the results, after all possible combinations - and only on page 2 of the results if I limit them to persons (while he is on top of results if I do simple search - which is so hidden itself now that noone uses it of course)

Same problem if I search for John Evangelist - top result in simple search, no idea which page in unfiltered facet search (could not get to it), page 3 in search results when persons are selected.

If there is a way to improve the search behaviour it would be a great help

**Comment by PietroLiuzzo** [comment]
On the strings and matching and operator, see the linked conversation in #1642 .

I think the ranking of a ruler or let us say of a record which has more specific information higher, is a different thing.

The simple search is not "hidden", is on the homepage, where you have asked it.

This is the search you would have to do in [facet](https://betamasaheft.eu/facet.html?query=%CA%BFAmda+AND+%E1%B9%A2%C7%9Dyon&type-facet=person&occupation-facet=ruler)
the [person list search](https://betamasaheft.eu/persons/list?mainname=amda+seyon&date-range=0%2C2000&cp=), using the same string will look only in persons and only in persName, so you get straight to your record. same in the [advanced search](https://betamasaheft.eu/as.html?query=amda+seyon&element=persName&AttestedInType=1&xmlid=&work-types=pers) selecting persons, end eventually persName as element to search to speed up. 

John the Evangelist
- in the [simple search](https://betamasaheft.eu/search.html?query=John%20evangelist) the first result is PRS5695John 
- if that is the John you are looking for, I do find the same in the [facet search](https://betamasaheft.eu/facet.html?query=John+AND+Evangelist&type-facet=person) eventually with very little filtering. here the query, as already explained several time is done in a different way. the simple search looks in persName and in occupation for persons and a few other common elements. the facet search looks in TEI because people where not happy about that. you have both in any case.

We can add an additional sorting to the results of the faceted search which is the most generic, to have returned higher up records which have more information either looking at the presence of specific features (dates? occupation? ) or at the number of elements or the length of the description, the number or relations, etc. It will never match what you want only because you are looking for it (see also the presence or not of actual text in the index), that is to say, what you intend with "best match" needs to be defined better than in terms of simple string search and proximity. please consider the options offered above and suggest other if you have any obvious one in mind.

**Comment by PietroLiuzzo** [comment]
The search functionality in the new release has now a sorting of results based on number of matches. This has become a better option because the use of the expanded data does give many matches at times. just to give you an idea, the search for 'amda seyon' with no further specification with 18 matches has it on fourth position. Of course this is not very relevant because I use a limited in numer of items to allow me to work a bit faster. 
On top of this, there will be an additional 'smart' ranking function (we can name it otherwise, if you prefer) which can be combined with other options. It is applied after searching, so it can combine with any filter or mode. This takes into consideration the points above and also multiplies by 2 the scores of the results if the element in which the match occurs is coherent with the type of item in which it occurs. So, if matches in persName in a person record are more than matches in other elements, then the total score is doubled. In the test data with the new search this brings amda seyon to the top of the results even if the search is not for a phrase. Previous ways of getting the result high up remain available. With a phrase search which does not use the smart ranking, in the test dataset I get amda seyon third, which I think is in any case better than on the sixth page and comparatively better then the fourth position of the very simple search. 
This feature of the query for smart ranking has be stay optional, because it impacts on the results timing significantly. It is still faster to search without this option checked and filter down if needed. A person record like amda seyon will never come up high in the results where there exists several other records where the string, joined with or, and, as phrase, etc. occurrs simply much more often. 
An additional feature of the new search, inherited from the former advanced search will be that of limiting by item type, i.e. only search persons. this will eventually benefit from the above score enrichment (which takes into consideration the presence of occupation) but not much since most results will be benefiting from the x2 score in such context.  the number of nodes is also taken into consideration (so, a record with more info gets a higher score) and the number of relation elements (the active network) 
<img width="1272" alt="Bildschirmfoto 2021-08-17 um 14 05 07" src="https://user-images.githubusercontent.com/508012/129722638-196f5c34-15ab-4d3b-9b17-b3a906cb2d36.png">
