### ISSUE TITLE
Improved Ranking for Faceted Search (Including Proximity for Multi-Word Searches)

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1642]
It would be nice to see the ranking improved with the faceted search. The example we had where a search for `Walatta Giyorgis` returned indiscriminately records containing the words `Walatta` and `Giyorgis`, failing to rank records literally titled `Walatta Giyorgis` higher, shows that the ranking (and chunking?) of the search index needs some improvements. Any search with multiple words should rank results where the words are in close proximity higher than those where the words are further apart. This is the basic expectation of any user and a fundamental principle in searching.

Specifically in the case of fulltext search, this is usually the advantage of "chunking", whereby a keyword search on chunks of a longer text returns more meaningful results than a search on the entire text (see, for example, [this article](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/indexing-long-documents/)). In the case of including also metadata, it is more complex, but this is still a normal user expectation for a search. When someone Googles `Facebook Messenger`, their expectation is that the first result will be Facebook Messenger, not not just any page containing the words `Facebook` and `Messenger` (which, while included in the results, would rank lower).

As a postscript, I realize the use of double quotation marks is intended to assist in this case, but this is only useful in the case where the words are precisely one after the other in the specified sequence. In cases where words may be separated or in a different order, it is still generally advantageous and expected that instances where the words are in close proximity rank higher than others.

**Comment by PietroLiuzzo** [comment]
Thanks for the message. I feel that the example provided is not enough for me to understand where to act. 
If I search https://betamasaheft.eu/facet.html?query=%22Walatta+Giyorgis%22 
I get a higher score and order the results by that. Many score the same.
Same if I force the AND https://betamasaheft.eu/facet.html?query=Walatta+AND+Giyorgis 
the definition of the score function used to order these results is the following

> Returns a computed relevance score for the given node. The score is the sum of all relevance scores provided by Lucene for the node and its descendants. In general, the score will be a number between 0.0 and 1.0 if the query had $node as context. If the query targeted multiple descendants of $node (e.g. 'title' and 'author' within a 'book'), the score will be the sum of all sub-scores and may thus be greater than 1.

The context of search of the facet search is always a text index on the TEI element, which has the facets. the same search run in the advanced search, can benefit from indexes on each element, which however break the text sequence and thus are not usable for proximity, as far as I understand. 

Besides the point on the operators and quotes, it would greatly help me if you could put together an example where you point out a result scoring less than you would expect in the db. Which one of the results provided for the Walatta Giyorgis (or e.g. Wälättä Giyorgis) above scores less and is listed too far? for example, I see that https://betamasaheft.eu/persons/PRS9834Walatta.xml scores 0.5 while https://betamasaheft.eu/persons/PRS11785WalattaGiyorgis.xml scores 0.6. I think this is fine, although I am not sure why that sum is better, since both include Walatta Giorgis in title and persName. On the other side, the reason why PRS12267WalattaG comes before PRS11785WalattaGiyorgis since they both score 0.6 I think is not regulated. 

Part of this issue, if it can be defined better, is probably also related to the way in which alternative variants are included in the search. Just to give some background, the above example string is transformed into all its variants, hence the need of the OR. 

> Walattä Giyorgis Wälattä Giyorgis Walättä Giyorgis Walatta Giyorgis Walätta Giyorgis Walättä Giyorgiḍ Wälatta Giyorgiḍ Wälättä Giyorgis Walatta Giyorgiḍ Wälatta Giyorgis Wälätta Giyorgis Wälättä Giyorgiḍ Walätta Giyorgiḍ Wälattä Giyorgiḍ Walattä Giyorgiḍ Wälätta Giyorgiḍ

if the AND is used, than the single parts are passed to the conversion, and the query string will be

> (Wälatta Walätta Wälätta Walatta Wälättä Walattä Walättä Wälattä) AND (Giyorgis Giyorgiḍ)

this query is then passed to Lucene with the following options (from https://exist-db.org/exist/apps/doc/lucene )

filter-rewrite = yes

> Controls how terms are expanded for wildcard or regular expression searches. If set to yes, Lucene will use a filter to pre-process matching terms. If set to no, all matching terms will be added to a single boolean query which is then executed. This may generate a "too many clauses" exception when applied to large data sets. Setting filter-rewrite to yes avoids those issues.


default-operator = OR

> The default operator with which multiple terms will be combined. Allowed values: or, and.

phrase-slop = 0

> Sets the default slop for phrases. If 0, then exact phrase matches are required. Default value is 0.

This is the value which could be modified for a proximity search. I could add an option for that, so the user can set it.

leading-wildcard = yes

> When set to yes, * or ? are allowed as the first character of a PrefixQuery and WildcardQuery. Note that this can produce very slow queries on big indexes.

**Comment by smaugustine** [comment]
Hmmm, the issue is the defaulting to OR. Searching explicitly for `"Walatta Giyorgis"` and `Walatta AND Giyorgis` result in the expected rankings, but a simple search for `Walatta Giyorgis` (which equates to `Walatta OR Giyorgis`) does not. I would posit that this is the user's expected behaviour.

(Apologies in advance that this unintentionally duplicates #1640, that's why I had closed this one)

**Comment by PietroLiuzzo** [comment]
It does not seem a duplicate to me, unless we consider query settings to duplicate user functionality. However, the solution proposed in #1640 may be good for this issue. I think given the above considerations about alternatives, it is not that obvious that AND is the default behaviour. You would be searching for  

> Walattä AND Giyorgis AND Wälattä AND Giyorgis AND Walättä  etc.

and of course find nothing.

**Comment by smaugustine** [comment]
My assumption, again, regarding user behaviour would be that they would not at first consider alternatives. Someone is more likely to paste an incipit they're looking for and hit "search" than they are to type a string of possible alternatives that they are looking for.

I honestly frequently search for records using GitHub's search because this is how it behaves.

**Comment by smaugustine** [comment]
As an addendum, even if it defaults to OR, assuming that we are not talking about XOR, a record including both words in close proximity should still rank higher than one that includes one word or the other. I'm not sure why results that rank highly for `x AND y` wouldn't also rank highly for `x OR y`. That is to say, unless we are searching for `Walatta XOR Giyorgis`, shouldn't the highest ranked results for `Walatta OR Giyorgis` be similar to those for `Walatta AND Giyorgis`? (i.e., ranking `t OR t` above `t OR f`).

**Comment by PietroLiuzzo** [comment]
I do not know. I do not think there is a XOR option in the current version of Lucene. I will ask about the scoring or t OR t above t OR f . I will ask the exist community about this to see if they have some hints.

**Comment by PietroLiuzzo** [comment]
the new search allows to decide what kind of mode to apply to the search and pass it to lucene as such. 
<img width="1647" alt="Schermata 2021-02-08 alle 21 43 21" src="https://user-images.githubusercontent.com/508012/107279204-07c54580-6a57-11eb-8b2c-41252c22f311.png">

This, I hope, will provide enough flexibility.
Scores are also adjusted according to the parent element so that an occurrence in the expanded dataset into a title or a persName is more relevant.

The default operator is already back to and and OR is used to join options 

> (Walatta AND Giyorgiḍ) OR (Walatta AND Giyorgis) OR (Walätta AND Giyorgis) etc.

**Comment by PietroLiuzzo** [comment]
Additional optional sorting is also available. if the "smar sort" option is selected the scores of every match are computed to assign to hits a higher score 
- nodes are counted and divided by hundred to add a value which reflects the size of the file where the hit occurred.
- if the match is in `<idno>` then *5 is applied
- if the match is in `<placeName>` or `<persName>` then *4 is applied
- if the `<change>` element contains the word 'complete' 1 is added to the score
- if there is a `<occupation>` element 2 is added to the score 
This function has a deadly impact on time due to the `kwic:expand() `function being done on each match. A warning is placed just beside the check.
These may be improved with better specifications in the future.
