### ISSUE TITLE
search results to actual location of match and text view

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1648]
I would like to suggest some improvements which would be a huge help for me, unless it's already there, in which case I would appreciate some instructions.

1) One of the main reasons I use BM is to find how a particular word appears in various texts, especially when I'm trying to identify a quotation. Often in a manuscript record it is a long process because if a manuscript has a complicated structure, I need to "open" every text unit and only then search with ctrl+F. Would it be possible to make it any more efficient?

2) It would be lovely if when I open a work record I could immediately see the incipit or whatever is given under the "Text" box (I understand the difficulty here of course, that sometimes there is a lot of text, but incipits would be so helpful). BTW, it is rather frustrating that the box "Text" is always read, whereas in many cases there's nothing there.

3) It would be useful if while searching for manuscripts there would be something like "Show only manuscripts available online".

But that's just some random impressions.

**Comment by PietroLiuzzo** [comment]
Dear @MarcinKrawczuk on your 1. actually, both coming from the facet search and from the attestations search, e.g. if you start from the Dillmann website, the link should take you directly to the text block matching what you have searched for and highlight it in yellow. 
for example: I have done this search https://betamasaheft.eu/facet.html?query=መርምህናም
<img width="1234" alt="Schermata 2020-12-21 alle 12 26 15" src="https://user-images.githubusercontent.com/508012/102772428-c46c2600-4387-11eb-9dc7-d8132d45cd9d.png">

on the result I click on the indication of the place where this is found (the text of which will be improved and made more precise as a result of another issue #1640) and the main view should shows all items uncollapsed and highlight the matching one in greenish/yellow as below
<img width="411" alt="Schermata 2020-12-21 alle 13 08 48" src="https://user-images.githubusercontent.com/508012/102775785-d5b83100-438d-11eb-81cd-1c2d70dbed5d.png">

This was not working for an inconsistency in the js, which I have now repaired. Thanks for pointing that out!

If you can please describe more in detail, even better with an example, the inefficiency you are facing, I would be happy to analyse it and suggest areas of improvement.

I will split your second point in 2. On 2a. the split view of text's metadata and actual text was a requirement of the project and makes sense especially if we do have a lot of metadata and a lot of text, which is rarely the case... we can change that if others also find it better otherwise. We could for example print a part of the text, e.g. the one described as incipit, or incipits from manuscripts in which the work is attested. 

On 2b, the presence of the red text button itself is determined by the presence of a `div[@type='edition']/ab` with some text in it. this is sometimes a white space, and then you see nothing. Please give me an example so I can investigate if I can make that better or there is another kind of error somewhere.

For 3 I think we do have that feature, if I interpret that well, that is "show manuscripts for which **_images_** are available online". You can achieve that filtering the results of your text search by "Images Availability"

<img width="606" alt="Schermata 2020-12-21 alle 13 20 18" src="https://user-images.githubusercontent.com/508012/102776593-49a70900-438f-11eb-9b4f-6b29d0813038.png">

**Comment by MarcinKrawczuk** [comment]
@PietroLiuzzo thank you, this is all very helpful, I will definitely devote some time in the future to test these and other functionalities and if I find any shortcomings  I will come back to you with examples. I appreciate very much that you have dotated time to my inquiries.
