### ISSUE TITLE
Greeting to Lalibela, ሰላም፡ ለከ፡ ጽድቀ፡ ላሊበላ፡ in EMIP 2337

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1672]
This work does not appear in Chaine's work. Any suggestions most welcome!

![EMIP02337__Weiner305_001](https://user-images.githubusercontent.com/39619238/104575951-83e28e00-564f-11eb-8d3e-0ef5765623c6.jpg)

**Comment by DenisNosnitsin1970** [comment]
Yes, this hymn I know. It is a rare salam hymn for Lalibaba that is found in a few mss.
It was published here by Turaev, see pp 59-61
https://azbyka.ru/otechnik/books/file/24947-%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%B8%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B9-%D0%92%D0%BE%D1%81%D1%82%D0%BE%D0%BA-%D0%A2%D0%BE%D0%BC-1.pdf
In one of Ethiopi-SPaRe mss, EStmg001, see the report https://www.aai.uni-hamburg.de/en/ethiostudies/research/ethiospare/missions/mission7-8-2014.html#_Toc006, fig. 58. 
It seems to exist in at least two slightly different versions. If it is not in the BM yet, a record can be created. One record for all varianst might be enough, Dorothea, what do you think?

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 many thanks for this. I certainly haven't been able to find anything in BM yet. I'll wait for confirmation.

**Comment by smaugustine** [comment]
It can also be found in IES 1016 (digitized as EAP286/1/1/133), ff. 21r-22r, in which case it's part of the lengthy "ተረፈ፡ መልክእ፡" accompanying መልክአ፡ ላሊበላ፡.

**Comment by thea-m** [comment]
Thanks everyone, this will be a wonderful improvement to the data!
If there are no objections until the end of this week, I will:
- create a new ID for the short hymn posted here by @Ralph-Lee-UK (from the other witnesses given here I would also think that for now one ID is enough, the differences are rather minor and would need deeper study to establish recensions),
- change the title of LIT4551Salam to Malkəʾa Lālibala (this ID will be kept in BDLaethe4)
- update the reference in IVEf47 to the newly created ID.

@smaugustine , help my ignorance - what's a tarafa malkəʾ?

**Comment by Ralph-Lee-UK** [comment]
@thea-m this would be much appreciated - presumably @DenisNosnitsin1970 can supply the reference in Russian text for the published version?

**Comment by DenisNosnitsin1970** [comment]
The reference exist, it is bm:1912Turaev, pages here 59-61 (however, the tag is created not in accordance with the rule "If your entry is to be used in BetaMasaheft or Dillmann Online, then you need to add a tag with this format and using only Latin alphabet letters
bm:AuthorYYYYkeyword", should I edit the tag?)

**Comment by thea-m** [comment]
Thanks, no, let's leave the tag as it is, it has already been used

**Comment by smaugustine** [comment]
@thea-m In my opinion, I would not consider this a መልክእ፡. Precisely what "ተረፈ፡ መልክእ፡" is is a question I have as well (haha).

In carefully copied መልክአ፡ ጉባኤ፡ MSS (and sometimes books), there is a clear separation between the መልክእ፡ proper (so to speak) and short poems that follow them (which may not appear in all copies of the same መልክእ፡, but also may appear in most copies). One can distinguish these in most manuscripts simply by a change in structure: they usually have only 3 or 4 lines per stanza (instead of 5), often shorter lines, and fall somewhat outside the typical content of a መልክእ፡'s stanza. In carefully copied manuscripts (as I alluded to above), they will be very clearly separated, not only with some sort of decorative line or punctuation, but also, in cases where the stanzas are numbered, by a separate numbering (see the example below). In one printed book, the stanzas had 5 lines, as in the መልክእ፡, but it was separated by an explicit title. I struggle with titling these, since, while መልክእ፡s are, in some manuscripts at least, given clear titles (መልክአ፡ ማርያም፡, መልክአ፡ ቍስቋም፡, etc.), there is never a distinct title given to the "ተረፈ፡ መልክእ፡".

![122r](https://user-images.githubusercontent.com/6315671/105356142-55d2f000-5bf3-11eb-80ce-056aca010171.jpeg)
![malk](https://user-images.githubusercontent.com/6315671/105356486-c0842b80-5bf3-11eb-8bab-950d8e86ba8a.jpg)

**Comment by DenisNosnitsin1970** [comment]
I eather do not know what is "ተረፈ፡ መልክእ፡". It occurs in some malke'-hymns, but its exact purpose is not clear to me. Perhaps hymn with "taraf" represent a "marked" festive variant of the malke' for the annual feast of the church, or for another special ocassion. You try to enquire Memher Hiruy what it is.

**Comment by smaugustine** [comment]
It's simply the "remainder" or the "rest of it", no? An added poetic conclusion?

After the መልክእ፡ and the ተረፈ፡ መልክእ፡ we usually find a short supplication, "ኦ፡ አምላከ፡ ቅዱስ፡ ..." or the like. It seems to me to be somewhat akin to what we find in ሰዓታት፡, when there are the readings from ድርሳን፡/ተአምር፡ and these are concluded ("እምድኅረ፡...") with a couple of stanzas and a supplication (e.g., after ተአምረ፡ ኢየሱስ፡, "አመ፡ ትመጽእ፡ ለኰንኖ፡..." + "ስብሐት፡ ለከ፡ ኢየሱስ፡ በአፈ፡ ኵሉ፡..."). Even ስንክሳር፡ readings have a set of "እምድኅረ፡..." stanzas, though no supplication.

I contacted a couple of qǝne teachers about "the short poems that come after a መልክእ፡", even just to see if they could give them a name, but they didn't have anything to say on it. It's on my to-do list to keep looking through literature on the genre and asking more teachers regarding this topic.

I also recall seeing in at least some of the EMML catalogues that Prof. Getatchew had separated them, so that the contents appeared as "Malke' to...; Salām to...; Malke' to...; Salām to...; etc.".

**Comment by DenisNosnitsin1970** [comment]
It can be also interpreted in terms of "redundancy, redundant", in whatever indirect sense.  It is difficult to compare it with anything else, because the (liturgical?) functions of these small texts will be probably different (except the fact that they serve to conclude another bigger composition). Some prosaic texts have short poetic conclusions, but here both are poetic :)  I came across it in one of the recent manuscripts with Acts and Miracles of St Mäzgäbä Sellase.  I wonder what results will be if one collects some of such "tarafs" and compares them systematically with the related "malke'".

**Comment by thea-m** [comment]
Thank you for this extremely enlightening discussion (which I believe also supports my insistence on the value of recording explicits as well as incipits whenever possible during cataloguing).
The absence of such poetic supplications in Synaxaria might be due to the proliferation of short supplications either after each commemoration or each day in many manuscripts. Having another set of supplications might have been too much.
