### ISSUE TITLE
Canons of Hippolytus

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1681]
In [BL Or. 600, f. 3v-4r](http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_600_f001r) there are two canons of Hippolytus i. e. no. 22 (on the week of Passover) and no. 38 (on the night of Resurrection, incomplete). Should I create records for these two canons or rather catalogue it under "LIT1544Gebrah#Introduction"?
@eu-genia @abausi @thea-m @DariaElagina @DenisNosnitsin1970

**Comment by abausi** [comment]
The "Canons of Hippolytus" exist (so far) in Gǝʿǝz exclusively as part of other works. Contrary to what is reported sometimes, there is neither any independent occurrence of them nor do they exist, in whatever form, in their entirety. So, thre should be the cross-refenrece ot other repertories (CPG), but there should not be any "work" entry for the "Canons of Hippolytus"; they are just part(s) of other works.

**Comment by MarcinKrawczuk** [comment]
Thank you, does that mean that LIT1225Canons should be deleted or rather expanded with crossreference?

**Comment by abausi** [comment]
If to keep it means that they exist in Gǝʿǝz as an indepent or complete 
work, they should be deleted. Yet, we have many similar cases, and one 
should investigate which are the guidelines in similar cases. This is 
the typical case of a work only few excerpts of which are attested. 
Should this reference be kept or not? in the cases of the counciliar 
canons, for example, I advocated that we should have separate entries 
for each councilias canons, even though they are not transmitted as 
completely independent texts, because this is the regular way, 
everyhwere (that is, in all traditions), how they are transmitted. In 
this case, as in many similar cases, there are pros and cons. I would 
welcome an input from those who have a better memory of how we solved 
similar issues. To keep the entry has the great advantage that we 
provide clearly the evidence to those who are interested in the "Canons 
of Hippolytus" coming from, for example, the Coptic or Arabic tradition, 
that there is this, yet indirect, evidence also in Gǝʿǝz.

Il 02.02.2021 09:44, MarcinKrawczuk ha scritto:

**Comment by eu-genia** [comment]
No, the ID should remain, as it appears in different constellations, it would otherwise be impossible to collect all occurences in one place.

**Comment by abausi** [comment]
Good, that's fine.

Il 02.02.2021 09:57, Eugenia ha scritto:

**Comment by eu-genia** [comment]
So, the ID should be expanded, with derived IDs for separate versions/canons/languages, so that from collections one could point, with a `corresp`, to the exact content

**Comment by DariaElagina** [comment]
Maybe, one should consider the usage of a narrative unit instead of a work ID? I am not well acqainted with the topic, but it seems to be a case for a narrative unit.
