### ISSUE TITLE
A hymn to the Trinity from BL Or 613 f. 177v

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1738]
I am kindly asking for help in indentification of the enclosed [hymn from BL Or 613](http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_613_f001r) or a permission for creating a work record (in which case I would appreciate suggestion of a title).
![BLorient613f177v](https://user-images.githubusercontent.com/62760230/115114545-4106be00-9f90-11eb-9fe6-378bf9d65940.JPG)
@thea-m @smaugustine

**Comment by thea-m** [comment]
I also can't identify it and would be in favour of a new record. "Hymn to the Trinity" or simply the incipit would work as a title.

**Comment by smaugustine** [comment]
Apologies for being too late, but this is Chaîne 262 (`LIT2981RepCh262`). He lists Wright 188 and 220, corresponding to Or 613 and Or 578.

I would say that it ought to be titled መልክአ፡ ሥሉስ፡ ቅዱስ፡. There are many compositions confusingly titled either መልክአ፡ ሥላሴ፡ or መልክአ፡ ሥሉስ፡ ቅዱስ፡. The title is rarely explicitly given, but it seems to follow from line 3 of each stanza, whether it has ሥላሴ፡ or ሥሉስ፡ ቅዱስ፡, though I think there is at least one with አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡. It's also possible that many are the same but appear to be different due to stanzas being added/removed at the beginning (also at the end), which does happen sometimes, but that's why I'm trying to build up a collection of texts to compare against.

**Comment by MarcinKrawczuk** [comment]
Thanks @smaugustine, that's very helpful!
