### ISSUE TITLE
New Work Record for EMIP 2716

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1749]
The first work in this ms is 'Mysteries revealed by Jesus Christ to John son of Zebedee before his Assumption.' 

This work is also found in BL Add 16192 http://www.bl.uk/manuscripts/Viewer.aspx?ref=add_ms_16192_f008v and so probably deserves a work record. I have included the first two images in case 
![EMIP02716_Weiner428_001](https://user-images.githubusercontent.com/39619238/118774570-e528a100-b87d-11eb-9f06-0c88456ef530.jpg)
![EMIP02716_Weiner428_002](https://user-images.githubusercontent.com/39619238/118774567-e3f77400-b87d-11eb-8084-e4a790f7efa8.jpg)

**Comment by thea-m** [comment]
I think that this is the introduction to the miracles of Jesus, LIT2382Taamme#Introduction, cp. for example ESamq005. But since it does seem to be attested independently from the miracles of Jesus in BL Add 16192 it does probably warrant an independent record. That would seem to exist already in LIT6396MJIntroduction, so we could add the relation to LIT2382Taamme there.

**Comment by Ralph-Lee-UK** [comment]
Would you like me to do this?

**Comment by DenisNosnitsin1970** [comment]
You may find many more examples in Ethio-SPaRe mss if you look for "On John the Evangelist as the author of the book...", all included into "Miracles of Jesus". By the way, LIT6396MJIntroduction was used in only one manuscript EMIP02392 that cannot be viewed. That this text is used separately or added to smth else seems to happen rarely.

**Comment by thea-m** [comment]
Thank you! Since it is attested here outside of the miracles of Jesus in BL Add 16192, I think that the independent record is fine (though the reference in EMIP02392  could be changed to LIT2382Taamme#Introduction´- for the manuscript in this issue the ID to be used would depend then on whether it's a manuscript of the Miracles of Jesus or whether the introduction is followed by other texts). I'll edit LIT6396MJIntroduction if that's fine for everyone.

**Comment by Ralph-Lee-UK** [comment]
@thea-m sorry for the delay, but just in case you were waiting to hear, please do go ahead with the edit you proposed to LIT6396MJIntroduction

**Comment by thea-m** [comment]
Now I see that the relation is already present in the record, so I believe there is nothing more to be done here. Please re-open if I missed something.
