### ISSUE TITLE
bibliography display in new app

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1754]
In LIT1651Homily I have provided a link to NASSCAL's e-clavis which I think is quite important. I did it in a following way:

<ptr target="bm:nasscal"/>
   <citedRange unit="item">ECCA 685</citedRange>
  <ref target="https://www.nasscal.com/e-clavis-christian-apocrypha/encomium-on-the-four-bodiless-creatures-by-pseudo-john-chrysostom/"/>

But alas, it doesn't display in the app or I cannot find it. What is the reason?

@PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/Documentation/issues/1622

**Comment by PietroLiuzzo** [comment]
sorry, I did not see this. The reason is simply that there is no bibliographic record in Zotero. The one I added has been removed apparently.

**Comment by PietroLiuzzo** [comment]
this will still not show the link in the current app. this will be included in the new XSLT. thanks!

**Comment by PietroLiuzzo** [comment]
Dear all, this requires your attention. 
I am very much inclined, due to a tremendous saving in terms of loading time and processing, to abandon the use of the direct transclusion from Zotero. This would in practice mean that instaed of waiting for things like the following to be loaded by javascript clientside

<img width="920" alt="Bildschirmfoto 2021-08-24 um 15 10 05" src="https://user-images.githubusercontent.com/508012/130622214-5a59c08c-dc0c-4aa6-b7db-9ad76d7cd727.png">

we would have, with no waiting overhead the following (rendering can be adjusted but will never be the same as using the CSL style).

<img width="906" alt="Bildschirmfoto 2021-08-24 um 15 06 28" src="https://user-images.githubusercontent.com/508012/130621702-ed71985a-2df5-4a43-9b5c-aba29fc1eca2.png">

In line with the request to have things spelled out instead of hidden behind icons, in this proposal the three basic further navigation options for bibliographic entries are offered for each entry in a block bar on the side (highlighted on hovering, so it is obvious that one can click there). The entry reflects then the TEI data imported at expansion time if available and call on the Zotero API only if no solution can be found, but always at expansion time, that is to say then the incoming TEI is enriched.
This has the disadvantage of a style which will never match the print, no matter how much I improve the XSLT. The correctly styled record is one click away only, however, if one wants to use that, on demand and without impacting by default on load time and performance. The advantage, beside performance is that we also become able to sort the result and more easily report the added information in a `<bibl>`.
Off course there are other workarounds to keep in sync the bibliography with the data, but the frequency at which the bibliography is edited makes me unsure it is worth trying. I mean, we _did_ until now offer the latest status of the bibliography linked, at a considerable waiting time for page load. 
@thea-m @eu-genia @DariaElagina @DenisNosnitsin1970 what do you think?

**Comment by eu-genia** [comment]
For me, this is more than reasonable, I only wonder if @abausi is OK with the style issue.

**Comment by thea-m** [comment]
I'm fine with this solution.

**Comment by DariaElagina** [comment]
I am fine with it as well, thank you!

**Comment by DenisNosnitsin1970** [comment]
I agree.

**Comment by PietroLiuzzo** [comment]
Thanks for the feedback, I will proceed this way.

**Comment by PietroLiuzzo** [comment]
the refactoring is producing the output with the correct bibliogrphy format. Syncing is still an open end, but the principle works already and this issue can be closed.
