### ISSUE TITLE
New work records for BLorient768

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1762]
I would need the following work records for [BLorient768](http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_768_f001r):

1) Two letters of John Chrysostom to the monk Theodore  - I would suggest just one record for the two letters to keep in line with CPG (it's CPG 4305)
2) Homily of Ephraim Syrus on the repentance of Nineveh
3) Homily of Ephraim Syrus on king David

The link to Wright's catalogue is [here](https://archive.org/details/catalogueofethio00brituoft/page/176/mode/2up).

@thea-m @DariaElagina

**Comment by DariaElagina** [comment]
Thank you! I could not find them in the db as well, I think the entries should be created. Concerning your suggestion to create one record for both letters, I think it is completely legitimate. As far as I could see in the manuscript the letters are rather treated as two sections of one textual unit (I mean the absence of a divider between them, which is otherwise present).
