### ISSUE TITLE
New work record for Malkəʾa Fānuʾel

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1788]
I would like to create a new record for a Malkəʾa Fānuʾel attested in EMIP00616 (96v-100v). Its first stanza is also attested in the scroll RDW009 (the first text, see the transcription on the branch DR_21_07_RDW009, folder HLC).
Would you suggest to create another ID for this independently attested first stanza or not?
@DariaElagina @smaugustine

**Comment by DariaElagina** [comment]
Maybe I am missing something, but I think that the scroll contains another type of the text, namely a prayer. You could refer to the Malkəʾa Fānuʾel  in its record, but I think that the scroll does not contain just the first stanza...

**Comment by DariaElagina** [comment]
Thank you! I would be for the first proposal, because at the end one has not studied if those introductory texts are really decisive for the introduction of different "recensions" or if they are just optional and rather correspond to the context of copying. If we follow the first proposal we would have the general record anyway, which can in the future be split into different records if needed.
