### ISSUE TITLE
changing IDs

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1800]
@DariaElagina and I would like to change the IDs of some manuscripts of the small private collections we're working on in order to harmonise them. Since the old IDs might have already been mentioned outside of BM, will adding the betmas:formerlyAlsoListedAs relation with the old ID then lead to a redirection to the updated record? I'm asking because as far as I'm aware, we have only discussed the use of this relation in work records, and only for deletions, not renamings.
Thank you!

**Comment by PietroLiuzzo** [comment]
Dear @thea-m and @DariaElagina please, do consider with attention if this effort is actually necessary. IDs are  arbitrary strings. If they have been cited and used this is one more reason not to touch at least the identifier. If you still want to enter this business, yes the relation will guarantee that behaviour within the application (and only there, and only until the application is live). There is no actual difference between deleting and renaming, renaming is simply a deletion followed by a creation of an item with another name, just like moving an item. Relying on that support for instances where this is necessary because of doublets or other cases is necessary. I do not think personally that the harmonisation of arbitrary strings is a sufficient reason to proceed that way.

**Comment by DariaElagina** [comment]
Thank you, @PietroLiuzzo ! @thea-m , do we want to just change the `<idno>`?

**Comment by thea-m** [comment]
Thank you!
I would do it, because from experience, it is very difficult for ourselves and others to deal with varying IDs and shelfmarks, particularly if they so closely resemble each other. They aren't many files and it won't happen again.
