### ISSUE TITLE
text not displayed

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1877]
In https://betamasaheft.eu/manuscripts/BNFabb66A/text, no text is displayed. In https://betamasaheft.eu/manuscripts/BNFabb66A.xml, everything seems normal.

**Comment by thea-m** [comment]
also in the work record: https://betamasaheft.eu/works/LIT4032SenkessarS/text

**Comment by PietroLiuzzo** [comment]
the fix has been applied, but the db is still reindexing. I will let you know when this can be checked

**Comment by thea-m** [comment]
This is just in case that the closing of the issue was the information that it can be checked: the text still is not displayed.

**Comment by PietroLiuzzo** [comment]
The issue was closed because it is closed and the text in both examples can be seen. Please use the navigation to get to the section of text which you want to see and if there is something missing or not shown, you can still report it.
https://betamasaheft.eu/manuscripts/BNFabb66A/text
https://betamasaheft.eu/manuscripts/BNFabb66A/text?ref=ms_i1.1&edition=
https://betamasaheft.eu/manuscripts/BNFabb66A/text?ref=ms_i1.1.10&edition=

the third is the place where you will actually see text because this is how your encoding is. 
````
<t:div type="edition">
<t:div type="textpart" subtype="month" n="1" xml:lang="gez" corresp="https://betamasaheft.eu/BNFabb66A#ms_i1.1">
<t:div type="textpart" subtype="day" xml:lang="gez" corresp="https://betamasaheft.eu/BNFabb66A#ms_i1.1.10">
<t:div type="textpart" subtype="commemoration" xml:lang="gez" xml:id="Taodora" corresp="https://betamasaheft.eu/BNFabb66A#ms_i1.1.10.1">
<t:ab>
....
````
https://betamasaheft.eu/works/LIT4032SenkessarS/text
https://betamasaheft.eu/works/LIT4032SenkessarS/text?ref=FirstHalf&edition=
https://betamasaheft.eu/works/LIT4032SenkessarS/text?ref=FirstHalf.Maskaram&edition=
https://betamasaheft.eu/works/LIT4032SenkessarS/text?ref=FirstHalf.Maskaram.MaskIntroduction&edition=


the third is the place where you will actually see text because this is how your encoding is. 

```
<t:div type="edition">
<t:div type="textpart" xml:id="FirstHalf">
<t:label>First half of the year</t:label>
<t:note>....
</t:note>
<t:div type="textpart" subtype="chapter" xml:id="Maskaram">
<t:label>
Commemorative notices for the month of
<t:foreign xml:lang="gez">Maskaram</t:foreign>
</t:label>
<t:div type="textpart" subtype="chapter" xml:id="MaskIntroduction">
<t:label>
Introduction for
<t:foreign xml:lang="gez">Maskaram</t:foreign>
</t:label>
<t:ab>በስመ፡ አብ፡....
</t:div>
......
```

Or did I miss something?

**Comment by eu-genia** [comment]
I just have taken a look at this issue and, while clicking on the direct link to the subsubchapter provided by Pietro above does work I cannot navigate there in the main text view for some reason
main view
![image](https://user-images.githubusercontent.com/17987728/150520798-9bb892c7-5167-45b1-9014-3e169d05e166.png)

if I click
![image](https://user-images.githubusercontent.com/17987728/150520846-fe01b0fa-f58a-40a6-be3c-9b7130a44824.png)

I get
![image](https://user-images.githubusercontent.com/17987728/150520910-9d0105bc-bfc8-4883-a4a9-1e493059e955.png)

because the link actually resolves to
![image](https://user-images.githubusercontent.com/17987728/150521075-7c758cb6-a926-4ffe-8e2e-d1bc308cef25.png)

The links on the left resolve to e.g. https://betamasaheft.eu/manuscripts/BNFabb66A/text#ms_i1.1
![image](https://user-images.githubusercontent.com/17987728/150521155-942f1f94-9a23-4754-91d9-a112dc40dc1c.png)

and do not reveal any text either. @PietroLiuzzo @thea-m do you get the same results?

**Comment by PietroLiuzzo** [comment]
the text links to the current view, the arrow links to the view of that passage alone. click the arrow to navigate.

**Comment by eu-genia** [comment]
OK thank you this worked!
What about the URI error in the text box? (I mean the text "Paris, ..." appearing as an active link and resolving to https://betamasaheft.eu/https://betamasaheft.eu/BNFabb66A#ms_i1.1 which produces an error)?

**Comment by PietroLiuzzo** [comment]
I have read. Thanks. Please, wait.

**Comment by thea-m** [comment]
Thank you for having looked into this again!
For the manuscript, I now also managed to find the text displayed.
For the work, what confused me is that the list of `<label>`s for the textparts is, as far as I can see, no longer displayed. For example, for the 1st Maggabit, the work record has 
```
    <div type="textpart" subtype="chapter" xml:id="Magg1">
                     <label>
                        <date>1st <foreign xml:lang="gez">Maggābit</foreign>
                        </date>
                     </label>
                  
                     <div type="textpart" subtype="commemoration" xml:id="Magg1Barkisos" corresp="NAR0019SBarkisos">
                        <label>Commemoration of <persName ref="PRS12017Barkisos"/>
                        </label>
                     </div>
                  
                     <div type="textpart" subtype="commemoration" xml:id="Magg1Marqoryos" corresp="NAR0021SMarqoryos">
                        <label>Commemoration of <persName ref="PRS12018Marqoryos"/>
                        </label>
                     </div>
                  
                     <div type="textpart" subtype="commemoration" xml:id="Magg1Eskenderos" corresp="NAR0020SEskenderos">
                        <label>Commemoration of <persName ref="PRS12019Eskenderos"/>
                        </label>
                     </div>
                  </div>
```

I believe https://betamasaheft.eu/works/LIT4032SenkessarS/text?ref=SecondHalf.Maggabit.Magg1&edition= is the correct link, and there, the labels are not displayed (an nowhere else as fas as I was able to check). Since this is where the legible identification of commemorations took place, which would allow non-specialists to identify the correct recension of manuscripts

I know that these records are quite lengthy, but this is due to the nature of the work. I believe I encoded everything according to the guidelines. I am also aware that it is not terribly important in the big picture, these are simply the records I know well.

**Comment by thea-m** [comment]
Thank you! The links given here for the work (eg  https://betamasaheft.eu/works/LIT4032SenkessarS/text?ref=SecondHalf.Maggabit.Magg1&edition=) function now and the labels are printed. But trying to access the text starting from the text tab from the main entry is not possible for me:
in https://betamasaheft.eu/works/LIT4032SenkessarS/text, when clicking on the arrows in the navigation next to FirstHalf and SecondHalf, this error message shows up:

> HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/works/LIT4032SenkessarS/text: exerr:ERROR cannot convert xs:string('SecondHalf') to a node set [at line 640, column 71, source: /db/apps/BetMasWeb/modules/dtslib.xqm] In function: dtslib:parseRef(item()*) [787:14:/db/apps/BetMasWeb/modules/dtslib.xqm] dtslib:selectorRef(item()*, item()*, item()*, item()*) [851:14:/db/apps/BetMasWeb/modules/dtslib.xqm] dtslib:pasRef(item()*, item()*, item()*, item()*, item()*, item()*, item()*) [260:9:/db/apps/BetMasWeb/modules/dtslib.xqm] localdts:Navigation(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [68:56:/db/apps/BetMasWeb/modules/localdts.xqm] dtsc:text(item()*, item()*, item()*, item()*, item()*, item()*) [435:4:/db/apps/BetMasWeb/modules/dtsclient.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [144:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:gettext(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]

**Comment by PietroLiuzzo** [comment]
That should be fixed now.

**Comment by thea-m** [comment]
Yes, thank you!
