### ISSUE TITLE
Search problem?

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1891]
I wonder if the main general search for Ethiopic words in Fidel functions correctly. If I simply type in an Ethiopic word in whatever way, I do not get anything.
[Seach issue.docx](https://github.com/BetaMasaheft/Documentation/files/7872267/Seach.issue.docx)
.
But it works out if I do the same through "Manuscript", "Search".

**Comment by PietroLiuzzo** [comment]
Please, also @thea-m @eu-genia @abausi , read my email.

Please, read the code of conduct for writing issues. This will not stop to apply. Other people in the future will unlikely take the time to open your attached doc, enlarge it to  see what you intend to search and retype " ትእዛዘ " . You can simply provide a [link](https://betamasaheft.eu/newSearch.html?searchType=text&clavistype=&query=%E1%89%B5%E1%8A%A5%E1%8B%9B%E1%8B%98&defaultoperator=OR&mode=phrase&signature-operator-field=AND&signature-field=&handDesc-operator-field=AND&handDesc-field=&decoDesc-operator-field=AND&decoDesc-field=&binding-operator-field=AND&binding-field=&supportDesc-operator-field=AND&supportDesc-field=&msContent-operator-field=AND&msContent-field=&additions-operator-field=AND&additions-field=&incipit-operator-field=AND&incipit-field=&explicit-operator-field=AND&explicit-field=&colophon-operator-field=AND&colophon-field=&titleStmt-operator-field=AND&titleStmt-field=&text-operator-field=AND&text-field=&person-operator-field=AND&person-field=&place-operator-field=AND&place-field=). 

Although your issue is vaguely and misleadingly described, very poorly documented and hard to reproduce, I looked at it. 

"Searching for fidal" in general worked as usual. [See this example](https://betamasaheft.eu/newSearch.html?searchType=text&mode=any&query=%E1%88%98%E1%88%AD%E1%88%9D%E1%88%85%E1%8A%93%E1%88%9D
) which returns

<img width="1629" alt="Schermata 2022-01-15 alle 05 28 41" src="https://user-images.githubusercontent.com/508012/149608840-46fc7902-a53c-413c-abee-c7ead85c2105.png">

The particular search query you had in your hidden example returned an HTTP Error 500, which can be copy-pasted in a issue report as below instead of making a photo.

`HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/newSearch.html: An unknown error occurred: Determinizing automaton would result in more than 10000 states. `

Also adding some further examples would not have armed. For example, [running the search filtered to manuscripts only](https://betamasaheft.eu/newSearch.html?searchType=text&clavistype=&query=&defaultoperator=OR&mode=none&homophones=on&signature-operator-field=AND&signature-field=&handDesc-operator-field=AND&handDesc-field=&decoDesc-operator-field=AND&decoDesc-field=&binding-operator-field=AND&binding-field=&supportDesc-operator-field=AND&supportDesc-field=&msContent-operator-field=AND&msContent-field=&additions-operator-field=AND&additions-field=&incipit-operator-field=AND&incipit-field=&explicit-operator-field=AND&explicit-field=&colophon-operator-field=AND&colophon-field=&titleStmt-operator-field=AND&titleStmt-field=%E1%89%B5%E1%8A%A5%E1%8B%9B%E1%8B%98&text-operator-field=AND&text-field=&person-operator-field=AND&person-field=&place-operator-field=AND&place-field=)  
did not produce the error (this is what I think you meant with "works out if I do the same through "Manuscript", "Search"."

I have run the search for each type to find out that the error occurs only for works. Doing this would have spared anyone looking at sorting this issue a good amount of time and is entirely at your fingertips.
