### ISSUE TITLE
BNF IIIIF Images in Viewer

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1894]
It seems that the URIs added to the BNF manuscripts under facs are those to the web page and not to the JSON manifest. 
They have all to be replaced 

(I now did as test for BNFet2 
from 
https://gallica.bnf.fr/ark:/12148/btv1b100828466
to
https://gallica.bnf.fr/iiif/ark:/12148/btv1b100828466/manifest.json)

The same change should be applied throughout - and be also considered for the links to be added / newly catalogued mss. Only manifest links, not normal URIs.

(nb for some reason I still cannot see the BNFet2 images in the viewer but I do not know why; the guidelines suggest that pointing to the manifest should be sufficient)

There are 127 files at the moment, I guess I will do them in small portions and not as "batch"

objections observations @thea-m @DenisNosnitsin1970 @PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
They **do not** have to be replaced anywhere. Please investigate properly before jumping to conclusions. Please, stick to the guidelines https://betamasaheft.eu/Guidelines/?q=iiif&id=images . They were always handled by the script so that this change was not necessary. I will look at this while doing the migration next week.

**Comment by eu-genia** [comment]
Sorry... At least now the viewer showed the metadata correctly so I thought this was needed, and I got confused by the Vat instructions. Sorry.
