### ISSUE TITLE
aligne lines, display style

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1899]
I have a cosmetic suggestion for the way the publication statement is displayed. To me it looks rather difficult to see for the eyes as the lines are not alinged (marked in red below).
And another comment for the date (marked in yellow), could there be a space between the date and the time? Again, simply to make it easier for the eyes.
And lastly, the last part - here 57.706+01:00 - what is this, fractions of time?

My example is https://betamasaheft.eu/works/LIT1011Abusak/main, but applies obviously for all records.

Thank you

![grafik](https://user-images.githubusercontent.com/29302681/150973402-c825b88d-d2d8-44cf-adf4-536cb5123824.png)

**Comment by PietroLiuzzo** [comment]
Please, do not assign me.

**Comment by eu-genia** [comment]
For your information: 
- in order to align the "availability" line it is enough to omit the `<p></p>` elements in `availability` (as tested in LIT1011Abusak)
- the date is printed as this is the outcome of the standard function `fn:current-dateTime` (see also here https://docs.marklogic.com/fn:current-dateTime), so one cannot edit the outcome without writing an additional script for transformation, I wonder if this is necessary (`+1:00` at the end is clearly the time zone, GMT +1)

**Comment by eu-genia** [comment]
We can discuss if we want the date-time stamp or just the date, then there will be simply 
2022-01-05+1:00 (date and GMT+1)

**Comment by SophiaD-M** [comment]
ha, indeed, on mobile screen this is impossible. But also the original version I complained about is confusing to look at. 
Sorry that there is no simple solution

**Comment by SophiaD-M** [comment]
Really nice, looks much better like this

**Comment by eu-genia** [comment]
Ok, I found out.
The lines are not aligned because `idno`, which is the element behind, is always visualized with a paragraph
```
declare %private function viewItem:idno($node as element(t:idno)) {
    <p>{$node/text()}</p>
};
```
(viewItem.xqm line 2972)
I will try to see if one can have it without `<p>` (but it may disturb other situations where `idno `is used, so I have to do some checking first)

**Comment by eu-genia** [comment]
seems fixed now
