### ISSUE TITLE
title not synchonised

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1912]
the title on the page https://betamasaheft.eu/places/LOC6653EastTegray/main is not synchronised, it shows an old version

**Comment by thea-m** [comment]
same for https://betamasaheft.eu/works/LIT5679MagicPrayer/main

**Comment by eu-genia** [comment]
I updated LIT5679MagicPrayer on github and it does seem OK?

**Comment by eu-genia** [comment]
I am not sure which should the title in LOC6653 be?
I see another strange thing there maybe worth another bug report
![image](https://user-images.githubusercontent.com/17987728/152330792-875b2729-3e8b-4cb5-8b2a-e8a8fe382890.png)

**Comment by thea-m** [comment]
LIT5679MagicPrayer  is fine now (strange - I had also pushed an empty commit). 
For [LOC6653EastTegray](https://betamasaheft.eu/places/LOC6653EastTegray/main), the title should be Mǝsrāqāwi Tǝgrāy, Mǝbrāqāwi has been corrected everywhere

**Comment by eu-genia** [comment]
Very interesting, when I open https://betamasaheft.eu/places/LOC6653EastTegray.xml (the generated XML) I see 
```
<title type="full">Mǝbrāqāwi Tǝgrāy</title>
<title xml:lang="ti" xml:id="t1">Mǝsrāqāwi Tǝgrāy</title>
```
so an additional title type="full" is taken from somewhere and not overwritten,  the rest is correct

**Comment by eu-genia** [comment]
This must be from some index that is not updated

**Comment by eu-genia** [comment]
I now just for a test updated directly the expanded XML in the app, and it shows what I wrote ;) but of course this is not a solution, the next time the file is regenerated the error re-emerges. I am trying to find out if I can fix the index...

**Comment by eu-genia** [comment]
It might be some data exchange with Pelagios...

**Comment by PietroLiuzzo** [comment]
Please, see https://github.com/BetaMasaheft/Documentation/blob/master/split%20applications%20release%20process.md The data displayed by the application is not the data synced from GitHub. Checking the xml source points to the expanded data used by the application. When expanded it uses lists of names and updates them when needed. Editing the expanded data as you did has indeed the indicated consequences. Following the debug procedure documented here  https://github.com/BetaMasaheft/Documentation/wiki/Application-maintenance-and-routine-operation-documentation you will arrive here and see immediately that the problem is that the hook is not delivering.
https://github.com/BetaMasaheft/Places/settings/hooks/9455913/deliveries 
redelivering the last commit with this file (250d2326-84f3-11ec-999b-a9f4c00b77b5) keeping open the backend will show you that the syncing script is called but times out. As detailed in the linked page above this indicates nothing bad but needs further investigation. I did the investigation and found out that the syncing script had an error. Interesting is that this showed up only now. I have left there some logging to the console for future debugging.

**Comment by PietroLiuzzo** [comment]
The bm: tags under other were caused by a selector in viewItem.xqm which took in also note elements from the Zotero import they are now excluded.

**Comment by eu-genia** [comment]
Thank you very much. 
Unfortunately fixing scripts I am afraid is beyond us...
Checking the "new" subfolders in the BetMasData for Persons and Works I saw that there have been no updates there since 4.1 or 5.1. Is there a script error there too?
We could not see the problem, since the expanded files are still generated. The "new" subfolders in the expanded folder do contain all the xml files.

**Comment by eu-genia** [comment]
I will try to redeliver one by one (?)

**Comment by PietroLiuzzo** [comment]
This would be unnecessary. next time a release is done, the mirror collection BetMasData will be updated as a first step.

**Comment by eu-genia** [comment]
I am sorry I am again confused. Is it important that BetMasData is uptodate or not? I don't think we can expect a release any time soon... What is the danger of underlivered payloads?

**Comment by eu-genia** [comment]
I am trying to redeliver the Persons webhook c8c72ef2-84e5-11ec-95de-fd78b1576bb0 to see if this solves the Eleni problem (?) but it also gets timed out continuously
