### ISSUE TITLE
The new version of DB - some comments

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2013]
I want to try to slowly come back to working in the BM with my own projects, meanwhile encouraged by Dorothea I would like to share some things that I see as problematic (for me) in the new version. They are not very sophisticated but let me enumerate them nevertheless: 

- [x] (1) One of the most useful things for me were searches within only one type of records (work, person), now I don't know how to do them. For example, how to search by clavis CAe or CPG?

- [x] (2) A big gray square appears in the right hand top corner, it is extremely irritating.

- [x] (3) In work records keywords are not visible (or I am unable to find them) cf. https://betamasaheft.eu/works/LIT6045SerataSegdat/main

- [x]  (4) Publication statement, edition statement and encoding description take up too much space.

- [x] (5) Type of addition is not visible.

@thea-m @eu-genia

**Comment by eu-genia** [comment]
Dear Marcin, thank you so much, also for your questions, which will surely help us improve.

1) we now have one search page for all, but all searches are still there. i tried to add explanations but maybe they are not enough, we can add more. 
when you go to the search page https://betamasaheft.eu/newSearch.html
you see
![image](https://user-images.githubusercontent.com/17987728/158448412-25c8faea-b53a-4d36-840d-1a66c2ecbb66.png)

so you have the dropdown above for the search type (including clavis search), and the search field below, and underneath, as indicated in the red box on the right, you have buttons you can click to have additional filters. 
you can also run the simple search and then filter down (faceted search) by refining search by item type or other aspects.
do you have a concrete proposal how the page may be improved to make these options more obvious to anyone?
(i would not want to fully return to separate search pages as in the past, even if this is of course possible in principle, just i am not sure if this is the best solution)
2) i agree, i will try to find a solution to that. we wanted to have prompts for the users with explanations but we did not expect them to become so overwhelming - and blocking. we all have been experiencing the difficulty, i will try to update the code, but it may take a while for me to find a good solution, since we do want to have the hints, too. please be patient, i will try to find a way. thank you!

3) thank you, i will try to find a way to get them viewed (were they there before the last release? i don't remember... anyway i will try to fix this too)

**Comment by eu-genia** [comment]
- tasks in this issue:
- [ ] make search page clearer
- [ ] find a solution for prompt boxes
- [ ] keywords in works

**Comment by eu-genia** [comment]
currently the code foresees the keywords for all types of entities just before the publication statement, but for some reason I could not yet identify (I tried last night) they appear only in MSS.

I have reduced the publication statement font, is it better now?

The type of addition should be printed now (I hope)

Do any of you have a constructive idea where the explanations which are now in the grey dropdowns could go?

And also concerning the search page - you can write your ideas here https://github.com/BetaMasaheft/Documentation/issues/1971 (reopening the issue; I closed it only because no further suggestions came)

**Comment by eu-genia** [comment]
And yes last year the keywords of works were here as menu
![image](https://user-images.githubusercontent.com/17987728/158591571-ddf82541-7427-4aee-a3bb-96ec3b335470.png)
will try to see if I can get it back...

**Comment by eu-genia** [comment]
Dear all (also @SophiaD-M who mentioned the issue, also @DenisNosnitsin1970 ), can you check if you find the way the definitions of the categories are displayed now better/worse (I tried to get rid of the grey dropdowns but I can roll back if you think it looked nicer before). Or maybe you have other ideas on where to put the infos. Thank you!

**Comment by DenisNosnitsin1970** [comment]
In my opinion, it looks fine.

**Comment by eu-genia** [comment]
Thank you. I have also added short intros for the "Hi" and "Resources" tabs for more uniformity. 
Is the bottom red bar with explanations for submenus OK as it is or should I make it a different colour/smaller/align left etc.?
I mean this one
![image](https://user-images.githubusercontent.com/17987728/158785997-f2a381bc-ae01-4121-a4a7-310d4a813d78.png)
(with the text "In this search form...")
Feel free also to notify me if any of the intro/explanation texts should be adjusted.

**Comment by DenisNosnitsin1970** [comment]
That is fine, perhaps it is a small bit too long. I would propose to drop/change a few words. Is "(filter)" absolutely necessary n the first line? Is it "defaults" or "default"? "Hints button" without "clicking on", then "which will provide more guidance". I would also say: "For more on lists and filters visit..."

**Comment by eu-genia** [comment]
Thank you, please also do check other prompts (there are many) and let me know!

**Comment by eu-genia** [comment]
(Actually in the example above a lot does not apply in the new release, we cannot change the number of items per page, etc., so all must be checked if are valid)

**Comment by thea-m** [comment]
Absolutely better than before.

**Comment by DenisNosnitsin1970** [comment]
„Shelf marks (full list)“ is ok. 
“List of Images Available Elsewhere”: I would drop “Elsewhere”, frankly speaking; I would drop “to a manifest for”, what means “in this mirador instance” (or Mirador?)? I would say, “and go the the manuscript record”.
“Catalogues encoded”: perhaps, “will open a list of”, and “for which we have records”?

“Inscriptions” are fine.

**Comment by DenisNosnitsin1970** [comment]
Should I read through "Texts", "Art Themes" etc.?

**Comment by eu-genia** [comment]
Sure, I have gone through them now but of course - we must all be satisfied with the way we present ourselves!

**Comment by MarcinKrawczuk** [comment]
@eu-genia Thank you very much for the changes and the helpful tips. To me it looks much better. Let me add some more comments:
1) One thing which I do a lot (and perhaps others as well) is to look for a work and then chec
![ex1](https://user-images.githubusercontent.com/62760230/158882816-1d1ce076-ad78-4d19-9c09-ad462e1662a7.jpg)
k in which manuscripts it is attested. I see two small problems here. When I click the list of mss. (see the image) a) there is an empty right column b) there is a search box on top. Are they necessary?
2) Also I don't like the fact that the independent textual units appear which make the search result very long in many cases e. g. here https://betamasaheft.eu/works/LIT2222RetuaH/main
3) In the case of person records there the link to the works attributed to them in the database is hidden under "Relations", I think before it was immediately visible alongside other data cf. https://betamasaheft.eu/persons/PRS5720JohnChr/main, right now it's under "Show attestations"  and what you get is not very satisfying.

**Comment by eu-genia** [comment]
Dear Marcin, thank you!
1) the thing is, we have now one search page for all types of searches. so the layout is used by different searches; maybe there are cases when the third column is used, I honestly do not know, will try to explore, maybe I can make it narrower at least. The search box remains on top, this is the way it is programmed now, that one stays on the search page. 
2) I think the list of units was once someone's wish... of course it can be suppressed if everyone finds it annoying
3) I shall create a separate issue for this one and try to explore whether I can get it back...

**Comment by DenisNosnitsin1970** [comment]
Reading further texts in submenus: 
"Clavis aethiopica": fine, I wonder if we can say just "title" instead of "label"; "a keyword" is probably not "a passage in Ethiopic", the last is the most common way of search (just a small portion, usually from the incipit).
"Narrative Units": I would drop "recurring motifs" and "thematically".
"Studies": ok. 

Under"Art Themes":
"Index": I have difficulty reading through "The decorations filtered search", just "The search" would be sufficient. "If an image is..." - I would say it more clearly: "If an image of the decoration is...", and would drop "also" and "for that manuscript".
"Art Keywords" ok
"Illuminations": I would say "manuscripts with miniatures of which...".

Under "Places": 
"Repositories": at the end, I would say, "associated with the repository". Otherwise ok, unless the change between "location" and "place" may cause some perception problem. 

Under "Persons": 
"Ethnic units": I would say, "We consider", not "We see".
Is this all? I did not find anything under "Resources".

**Comment by eu-genia** [comment]
Resources - I only invented the general text, should I write the prompts for submenus too?

**Comment by DenisNosnitsin1970** [comment]
It might be useful, the user would expect smth.

**Comment by eu-genia** [comment]
In the search results as I thought the third column is used so I won't be narrowing it
![image](https://user-images.githubusercontent.com/17987728/159136354-b100a253-58aa-49b8-9482-45edb4e17ef3.png)

**Comment by eu-genia** [comment]
Now the persons record lists the attributions not in the relations box but in the main text body.
I believe all issues raised here have been addressed.
