### ISSUE TITLE
wrong expand of derived IDs in mss

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2020]
the problem here was not fixed by nesting, the sections with derived IDs in title do not get expanded!
https://github.com/BetaMasaheft/Manuscripts/pull/1513

**Comment by eu-genia** [comment]
the error comes from the encoding problem in LIT6576MiraclesMabaSeyon

**Comment by eu-genia** [comment]
It took me 6 hours of work to find the error, as it was in a third file.
We must be VERY careful with `xml:id`

**Comment by DenisNosnitsin1970** [comment]
Oh, I am very sorry about this. 
Thanks for correcting!

**Comment by thea-m** [comment]
If I remember correctly (I did not find it in the guidelines), such problems also arrise when the value for any xml:id is identical to the defined values in the schema, such as the types of additions or titles (because they are the xml:id of the corresponding authority records, I suppose). This is tricky, because no error message will be shown, and a few of the names are quite generic, so it is not a far-fetched scenario.

**Comment by eu-genia** [comment]
Yes, maybe we should write it in somewhere in the guidelines, for future reference. 
To be sure that nothing beginning with LIT, PRS etc is used as custom xml:id inside the records, and to check the list of keywords, too.
