### ISSUE TITLE
Link to Zotero not working?

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2023]
I've just noticed this. Is there a problem with connection to Zotero?
![ex2](https://user-images.githubusercontent.com/62760230/158885421-f4a91250-42e9-4348-b6a3-ed6eaed181bd.jpg)
@eu-genia

**Comment by eu-genia** [comment]
Dear Marcin, please always provide the link to the precise record you experienced the problem, I cannot debug otherwise. Most probably there is a problem in encoding, but I can only check if I know where to look. Thank you.

**Comment by MarcinKrawczuk** [comment]
Sorry, here it is: https://betamasaheft.eu/manuscripts/Tanasee142/main

**Comment by eu-genia** [comment]
The connection is OK but there are two things to consider:
1) `bm: `type Zotero references are only parsed inside of the `<bibl><ptr target=/></bibl> `element, and not everywhere in the description.
2) `resp `attribute is only for persons, not books or other objects according to TEI definitions
the record is fixed by this commit: https://github.com/BetaMasaheft/Manuscripts/commit/29ba5f0a0e46905657add55493b53027a630e0fa

(the date transformation is funny I know but I am not going to work on it, at least not for now)
