### ISSUE TITLE
Problem with creating a work record

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2029]
Yesterday I was trying to create a work record and this happened. Should I do anything or just create it again with another name?
![Zrzut ekranu 2022-03-19 000822](https://user-images.githubusercontent.com/62760230/159127859-672b2d3c-ca79-4fd7-a89d-40d3fc302f7f.jpg)
 @eu-genia

**Comment by eu-genia** [comment]
This happens when for some reason you got logged out, as you see the app is calling you "guest" and guests have no rights.
The record was not created. You should log in and recreate it (6583 has been now taken by another work so there will be another number assigned)
Thank you!
(I see that you created two records after that, so I guess all is OK otherwise)
