### ISSUE TITLE
new record for poem

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2046]
In BLorient567, there is this poem as an addition (ignored by Wright, but not by me, ha!):
![image](https://user-images.githubusercontent.com/19650382/159904558-a49493ab-aca9-4e76-a6bf-f9b0616a6bf1.png)
The first part/stanza/poem (?) is also attested in ESdmd013 as the last part of the hagiographic dossier of Kiros (not an addition as currently encoded in the record, I believe).
It would probably make sense to create a new record. It's not clear to me whether the second part in BLorient567 constitutes another individual poem. I would probably only create one record and note the variation. 
The text itself only mentions Rufāʾel in both parts, so I think that it is dedicated to him, not Kiros? But of course its integration in ESdmd013 is meaningful.
@DenisNosnitsin1970 @eu-genia

**Comment by DenisNosnitsin1970** [comment]
I would say, the first short poem is dedicated to Kiros, despite mentioning Ruphael". 
"Fatahe mahtsan" is Kiros (unless Ruphael does the same, but Kiros is well known in this function). ሩፋኤል፡ ለኩሉ፡ እንተ፡ ትሰእል፡ ምሕረተ፡ - i think one can still understand here Kiros as subject. The part starting with "salam" seems to be another text, indeed,  dedicated to Ruphael, it is possible that both were conflated (because the first part was interpeted as dedicated to Ruphael too?). Or sometimes such poems are written one after another without any internal boundaries. But probably one record would be fine here.
