### ISSUE TITLE
images ESmac002

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2054]
There is some problem with the images, they should be there but are not shown, probably there is a mistake in the record. Could you check?
https://betamasaheft.eu/manuscripts/ESmac002/viewer

**Comment by eu-genia** [comment]
This is the same issue as here https://github.com/BetaMasaheft/Documentation/issues/2052
The images are not on the aai-hlz-bm storage, they were never put there.

**Comment by eu-genia** [comment]
PS I took the images from the User resized folder, which is for MAC on Ethio-SPaRe2 (aai-hlz-ethiospare\Gemeinsam\HLZ2\Ethio-Spare2\MAC-Chähat Mädhane Aläm\MAC-002\2010-12-06\MAC-002 User resized)

**Comment by DenisNosnitsin1970** [comment]
Very good, though I do not see those images on Ethio-SPaRe2, i see the folder on Z:\aai-hlz-ethiospare\Gemeinsam\HLZ5\Ethio-Spare5\MAC-Chähat Mädhane Aläm - User\MAC-002 User resized which is now empty (possibly someone deleted them by chance, or never saved). I am not going to save anything anywhere on bm, no warries.

**Comment by eu-genia** [comment]
Go to "Z:\aai-hlz-ethiospare\Gemeinsam\HLZ2\Ethio-Spare2\MAC-Chähat Mädhane Aläm\MAC-002\2010-12-06\MAC-002 User resized"

**Comment by DenisNosnitsin1970** [comment]
I see, this is a mistake, it should not be there. I will move it to where it should be.

**Comment by eu-genia** [comment]
Since after some searching and learning and trying it out the solution in the end was quite simple and easily applicable by anyone I have added a chapter on image transformation to the guidelines, so that everything is clearly documented for everyone to see and reuse.
https://github.com/BetaMasaheft/guidelines/commit/2d475e0dbc14d5b5717f912abb13598b782c955f
