### ISSUE TITLE
Merging problem

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2161]
https://betamasaheft.eu/manuscripts/BNFabb54/main

@eu-genia

**Comment by eu-genia** [comment]
It is NOT a bug. - this is the same issue that you create.
If you create a record through the app (through the betamasaheft.eu page) you MUST save it in the NEW folder, then do the PR and merge, and only then move it to the library folder. All records created on betamasaheft.eu must be first in the NEW folder.
Otherwise you can simply create a new record in the library folder from a template in your offline xml editor without using the app. Then there will be no conflicts.
Otherwise this will happen every time: when you create a record on betamasaheft.eu it is automatically saved by the app to the new folder in the live version (not synced with github). If you do not save to new and merge to sync, then you create two files of the same name, and they cannot be displayed. 
I have removed the doublet now but please try to avoid creating more - note that I am on vacation until the end of the month with very limited access to Internet.
Thank you very much!
