### ISSUE TITLE
missing source repositories

### ISSUE THREAD

**Issue by line-o** [BetaMasaheft/Documentation#2174]
The `BetMasData` collection on the live server has several subcollections.

- authority-files
- Chojnacki
- corpora
- institutions
- manuscripts
- narratives
- persons
- places
- studies
- works

While there is a one-to-one relation of data repository to sub collection in BetMasData for almost all of them, for 

- Chojnacki
- corpora

the source is not found.

If there is a source repository it should be published in this GitHub organisation in order for JinnTec to be able to integrate it into the new workflow.

If there is no source repository we need to find out if these collections are no longer needed or if we need to set up a repository for them.

refs #2173

**Comment by eu-genia** [comment]
Will look into it as soon as I am back. I guess I will have to create new repositories on github to store the data.

**Comment by duncdrum** [comment]
@line-o from the [release procedure](https://github.com/BetaMasaheft/Documentation/blob/master/split%20applications%20release%20process.md)

> corpora is added from the current data on the server (very rarely changed) can be copy-pasted from server into BetMasData.
choniajki is added from the current data on the server (static) can be copy-pasted from server into BetMasData.

**Comment by line-o** [comment]
Good find @duncdrum 
I would still want to change the workflow from
- copy paste from server
to
- reinstall xar
:)

**Comment by duncdrum** [comment]
@line-o agreed new repo's it is

**Comment by PietroLiuzzo** [comment]
It was an explicit requirement that this data is not in github when it was added. so it is shipped only in the application as required. The same is true for all the IHA subcollections in each of the main data directories. It was always much easier for me to copy from the server than to attempt xarififcation and reupload which so often incur in issues: I am sure you will manage this improvement!

**Comment by PietroLiuzzo** [comment]
There are several other vital data directories, e.g. log and lists which were at the /db/app level when I left at least.

**Comment by PietroLiuzzo** [comment]
additionally, let me remind here as well that the entire Dillmann setup, for which the data was required not to be in github, is also on the server, and only there.

**Comment by eu-genia** [comment]
@duncdrum @line-o I hope we are not touching upon Dillmann (gez-en + DillmannData) which is a separate application? 

should I create repos also for lists? logs are as far as I understand contains files generated by the application - should they be copied to GitHub? How can they be kept uptodate?

should I manually download and paste
- chojnacki
- corpora
- manuscripts > IHA
- institutions > IHA
- places > IHA
- persons > IHA
- works > IHA
into new repos or is there a better way to do it?

NB to explain: chojnacki/corpora/IHA subcollections all originate from different projects, the files were not created by BM or are edited/editable by BM, they were only "inherited" to be able to share and display and search, therefore there never has been a reason to have them on GitHub. But of course if 1:1 correspondence is desired we can do it.

The problem again is that since we never worked e.g. with IHA files they surely **do not validate** against our schema. They are too many to edit, and they are not our scope of work. If nothing helps we might have to relax our schema to allow their tags to be validated but this too is a lot of work.

**Comment by eu-genia** [comment]
As for DillmannData - it was a request that the source data in Dillmann application (which is linked to BM but is not part of it) is not available on GitHub, because there is much work behind by many persons who did not provide their approval for it to be open access, only for the data to be searchable/displayable online through the app. 
Therefore the web-based workflow was created in that case.
We explicitly do not want to have this data synced on GiitHub.

In this connection, it may also be problematic to have the complete backup readily available here https://github.com/BetaMasaheft/betamasa-prod 
(unless this repository can only be seen by developers/owners - can this be set up?)
We have many members on the GitHub organization who should not easily be able to view what's inside - whether the data that is meant to be hidden or also the user accounts

**Comment by line-o** [comment]
@eu-genia there is the option to have the data in a private repository. And it does not have to be on GitHub either.
What we see as necessary is that the Dillmann application with its data can be installed in a simple and reproducible way.
This is key for the ability to upgrade the underlying system and recover from disasters.

**Comment by line-o** [comment]
About IHA, as noted in #2183, there might be other options to add external data sources while maintaining the ability to search in them.

**Comment by line-o** [comment]
To summarise: the data currently not on GitHub can be classified as external.
We need to identify a solid solution how to incorporate those sources without them being made public and maintaining the same feature set on the production system.
Does that sound reasonable?

**Comment by eu-genia** [comment]
Sounds good. 
Does this mean that we also leave out chojnacki and corpora repos for now? 
(These are small collections, and part of cooperation, so potentially could be "internalized", but maybe can be also left "external")

**Comment by line-o** [comment]
That is totally up to you @eu-genia
Anything that legally can be made publicly available and can live here in a repo makes our life easier.

**Comment by duncdrum** [comment]
@eu-genia the only ppl who can see what is in `betamasa-prod` repo are the owners of this organisation, and the jinntec team members, who already happen to be owners I just realised. 

The same is true for any private repo, owners of the organisation can see those contents, but members cannot, unless being granted access. 
<img width="971" alt="Screenshot 2022-08-02 at 15 29 15" src="https://user-images.githubusercontent.com/6205362/182386784-5111c67e-21d4-4b81-a1b2-05356effa766.png">

**Comment by eu-genia** [comment]
this is OK then, thank you!
I will create repos for corpora and chojacki this week

**Comment by eu-genia** [comment]
created
https://github.com/BetaMasaheft/corpora
https://github.com/BetaMasaheft/chojnacki

**Comment by eu-genia** [comment]
Updates on "missing" repos:
-- we are OK with having everything on GitHub, I will be moving IHA records as subfolders, just as they are on the server 
-- we could also have the DillmannData on GitHub BUT there is a problem: the workflow for the dictionary app, which is a separate application, even if using BetMas data via API, is web-based. The data is being continously created and edited directly on production server. So if I copy the data to GitHub it will be outdated in a matter of minutes. What are the syncing opportunities there? (the good thing there is that they are all valid to the dictionary schema)

**Comment by line-o** [comment]
DillmannData will not be in scope for this project. It will be left as is for the moment.
Closing this since we now have repositories for the missing data in BetMasData.

thanks @eu-genia
