### ISSUE TITLE
Recent STU records are not visualized

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2201]
The recent STU records that I created manually (STU0005Dictionnaire, STU0006Abrege, STU0007Abregevers) 
are not visualized in the Bm. On the contrary, the older STU records are visualized.

**Comment by eu-genia** [comment]
I guess gitsync has not been set up for studies, will have a look now

**Comment by eu-genia** [comment]
the webhook is in place but BetMasData/studies is completely empty

**Comment by DenisNosnitsin1970** [comment]
The files are on my machine in "Studies", at least.

**Comment by DenisNosnitsin1970** [comment]
All repositories have "master" beside all branches, as I see, in "Studies" it is called "main". Does it matter?

**Comment by eu-genia** [comment]
(1) pushing to `Studies `does not launch `gitsync `script. I don't know why yet, so the files are not synced to `BetMasData`.
(2) I have uploaded and expanded manually, now the files are there -- BUT still are not shown.
At the moment I have no explanation, will dig more

**Comment by eu-genia** [comment]
The issue is fixed, but among other things I did rename the default branch to '`master`' for more uniformity.
Please delete the folder and reclone the directory. Thank you!
`Studies `can also now be created through the app just like other types of records
https://github.com/BetaMasaheft/Documentation/issues/2199

**Comment by DenisNosnitsin1970** [comment]
Thanks a lot!

**Comment by eu-genia** [comment]
There is a work created LIT6704Dictionnaire - I assume it should be deleted?
@DenisNosnitsin1970, for the future, it is very important - if you create a record with an app, which you decide you do not need any more, you still MUST download it, push, merge, and then delete. Otherwise the app and the git are out of sync, and the clavis number remains assigned.

**Comment by eu-genia** [comment]
In general, also for @thea-m - it is better if the records created through the app are downloaded and soon pushed to sync; one can complete them later, but it is good if we have at least stubs for the records that are in the system. This also helps avoid errors for the system when it looks for records that are not there... There are CAe 6702, 6703, 6705, which are probably in some branch since Aug 12...

**Comment by eu-genia** [comment]
https://betamasaheft.eu/works/LIT6704Dictionnaire/main

https://betamasaheft.eu/works/LIT6702MashafaKobor/main
https://betamasaheft.eu/works/LIT6703HymnMik/main
https://betamasaheft.eu/works/LIT6705CompGM/main

**Comment by thea-m** [comment]
I see. I will try to remember! (mine got stuck in PRs :) )
