### ISSUE TITLE
small question on CJN002 

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2209]
@DariaElagina MS CJN002 has a change element `<change when="2021-09-29" who="HAs">Correction to text from images</change>` - do you know who HAs is? the value is not in the schema. Is it a typo?

**Comment by thea-m** [comment]
I think a summer school participant of last year, Mr Asnake. It was probably an exercise during the XML training

**Comment by DariaElagina** [comment]
I think Dorothea is right, because I have no other idea who this person might be.

**Comment by eu-genia** [comment]
Should I add his name to the schema, or take the element out?

**Comment by DariaElagina** [comment]
If we want to keep track of all changes, I think the name should be added. I honestly do not know what is the rule for workshop participants.

**Comment by eu-genia** [comment]
I am not really sure it is worth it and whether corrections were significant

**Comment by thea-m** [comment]
It's probably not worth it, but still a question of principle to acknowledge everyone. Maybe we could solve it by instead having a change element by ES, in which you describe that he carried out changes and you deleted his element due to schema adherence? (Sorry: I cannot come up with a good formulation for this right now)

**Comment by DariaElagina** [comment]
I think the suggestion of Dorothea is good.
