### ISSUE TITLE
Several Maṣḥafa gǝnzat entries

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2216]
Hello! Could the difference between CAe 6155 and CAe 1931 be clarified? Or if they are the same, could the entries perhaps be merged?

**Comment by eu-genia** [comment]
Do you mean MY 013? LIT6155MashafaGenzat is attested in MY 013.
Yet the two entries are disambiguated by the relation
`saws:isShorterVersionOf` (that is, 6155 is shorter version of 1931 used in MY 013)

**Comment by eu-genia** [comment]
One can of course add an abstract for those who do not read relations, but I do not see a huge necessity of merging if it is a distinct redaction, even if present in a single ms

**Comment by thea-m** [comment]
(Regardless of this particular case, which Denis will know what to do with, we have often made the experience that people do not see the relations, so it is better to also include an abstract that summarises them for user friendliness, even if it feels redundant)

**Comment by DenisNosnitsin1970** [comment]
Yes, I mean MY-013. We can leave it as it is, of course, but the reason will not be very transparent. The issue is that MG has a very complex history, and more versions exist but this should be studied more consistently which is for the moment hardly possible. "Shorter version" does not explain much (probably at that time I assumed that CAe 1931 represent the "standard version" which is not, as it turned out later - I can comment also on this in CAe 1931). Maybe it is better to have one general record that bundle all Mgenzats than split one on not very solid basis.

**Comment by karljonaskarlsson** [comment]
I agree with what Denis said in that it might be reasonable to have a “general record”, and then future studies will clarify which different version there are.

I also agree with Zhenia’s comment about how short notes formulated in words  increase the user-friendliness in cases like this.

**Comment by DenisNosnitsin1970** [comment]
I can remove CAe 6155 and add a kind of explanation under CAe 1931. Should I do this?

**Comment by eu-genia** [comment]
if you think this is reasonable then yes, if there is a distinct redaction we can keep 6155 for that, but this then should be made clear. if we do not distinguish recensions then better keep just 1931
