### ISSUE TITLE
Same text - two IDs?

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#2244]
I wonder if these two Clavis IDs refer to the same text? https://betamasaheft.eu/works/LIT6251Months/main  and  https://betamasaheft.eu/works/LIT4991Months/main 
The Paris ms is available online, I am not sure if there is a chance to check the Petersburg ms? 
The description of both titles is suspiciously similar.

Thank you

**Comment by eu-genia** [comment]
these are clearly two different things, the former ID (6251) is the earliest layer of Ethiopic literature and part of Aksumite collection, the second (4991) is a recent multi-lingual list.
I am not sure though whether the one in BNFabb39, which is part of Sawasew, is 6251, it should be either 4991 or a third, separate ID. @DenisNosnitsin1970 can you please have a look?

**Comment by DenisNosnitsin1970** [comment]
They are different. 6251 is a  text from UM-039 Aksumite collection, the ID contains only one reference to an Italian publication and not quite transparent, you have to look very carefully through Relations. BNFabb39 contains a different text, though to the same topic for which an ID may be needed. Should I create it (unless there is already smth for this)? There are a few lists of months in different languages in the mss, but no one made a survey. Different variants are possible as to what belongs to which tradition. But ID 4991 was introduced exactly because the ms from St Petersburg can hardly be checked.

**Comment by eu-genia** [comment]
you used 6251 in bnfabb39 but yes i think a new id is needed and the msdesc corrected accordingly, or we can use 4991 as a generic record, surely 6251 is wrong there

**Comment by DenisNosnitsin1970** [comment]
I will have a look at this.
