### ISSUE TITLE
integrate zoho database with WORKS

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#227]
https://creator.zoho.com/comstudies/ethiopictexts/#

**Comment by PietroLiuzzo** [comment]
@eu-genia might need to work together on this

**Comment by PietroLiuzzo** [comment]
I don't remember what is meant here by "digitized". we could add this informations easily from the zoho xml export to our work records.
e.g. we could add 
- link (1 and 2) to digitized text
- author of digitization
- comments
- source book
- source manuscript

most of this I think would go into bibl elements and relations

**Comment by PietroLiuzzo** [comment]
see https://github.com/SChAth/ScAthiop/wiki/SRC2

**Comment by eu-genia** [comment]
this database still has a slightly different purpose - it only lists texts that have been processed to OCR or retyped and are thus available for edition/annotation etc. and it is publicly modifiable, anyone can add their texts, so that transcribing efforts are not doubled.
we can add the info to BM but then we have to introduce types for available text formats, also relations (transcribedBy? but then we would need IDs for all the scholars, us included), and the other things also make sense if the text is provided - then most of the metadata goes into the encodingDesc. source book / source manuscript only make sense in that case, as otherwise we may have many more witnesses.
we have to see field by field how they map.
what definitely should be done (by me I guess) is add the BM ID to the database
