### ISSUE TITLE
Other works in MS BDLaeth e.39

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#2273]
In addition to the miracles of Gabra Manfas Qǝddus, MS BDLaeth e.39 also transmits other texts related to other subjects:

1. One (ff. 86va-87va) is a text which is seemingly also found in BLadd16211#1.33, "On the subdivision of the year", as a part of a Sawāsǝw. Incipit: ```እጽሕፍ፡ ነገረ፡ ዓመት፡ ዘይትከፈል፡ ክረምት፡ ዘመዋዕለ፡ ዘርእ፡ ፫ አውራኅ፡ መጸው፡ ብ፡ መዋዕል፡ ጽጌያት፡ ፫ አውራኅ፡ 
                                ኃጋ<gap reason="illegible" unit="chars" quantity="1"/> ብ፡ መዋዕለ፡ በጋ፡ ፫ አውራኅ፡ ፀደድ፡ ብ፡ መዋዕለ፡ ጰንጠቈስጤ፡```. The incipits of the two witnesses match. I think this text deserves its own record as here it can be found independently. I would name this text "Nagara ʿĀmat".

3. Another (f. 87vb) is a very short interpretation of the seven alphabetical orders of the Ethiopic script. It might be a much shorter version of LIT4099MashafaT, which is found in BLadd16223#_i4 and BLadd16204#_i2 (we have no incipits for these manuscripts, but on MS BLadd16204 the text is said to be on ff. 27-30, which makes it definitely longer than the text at issue here). The full text is: `ትርጓሜ፡ ቅዱስ፡ ፊደል፡ ግዕዝ፡ ወራብዕ፡ አብ፡ <sic resp="MV">ካዕበ፡</sic> ወኀምስ፡ ወልድ፡ ሣልስ፡ ወሳድስ፡ መንፈስ<supplied reason="omitted">፡</supplied> ቅዱስ፡
                                ሳብእ፡ ፩ አምላክ። ካልእ፡ ትርጓሜ፡ ግዕዝ፡ አብ፡ ካዕበ፡ ወልድ፡ ሣልስ፡ መንፈስ<supplied reason="omitted">፡</supplied> ቅዱስ፡ ራብዕ፡ ቤተ፡ ክርስቲያን፡ 
                                ኃምስ፡ ጥምቀት፡ ሳድስ፡ ምስሐ፡ ደብረ፡ ጽዮን፡ ሳብእ፡ ትንሣኤ፡ ሙታን።`. It is different from LIT6460Letters (On Various Significations of Letters), which is described as " A short tract on the various significations of the 22 letters of the alphabet". There is also another record on this subject (LIT2452Tergwa, that is "Tǝrgʷāme fidalāt" or "Commentary on the Gǝʿǝz letters"), probably inherited from the EAE index, but I would not use this record as it is currently used for a different text found in MS Saint Petersburg, IV Orlov 20 (incipit: ዝንቱ፡ ፊደል፡ ሃ፡ ብሂል፡ ሀልዎቱ፡ ለአብ፡ እምቅድመ፡ ዓለም፡). I would create a new record for this very short text.

4. Finally, on ff. 88ra-90va is found a chronological text indicating the years of reign of several emperors, which I haven't found elsewhere. Incipit:  ``` እምጉባኤ፡ ሐዋርያት፡ እስከ፡ መንግሥተ፡ ዲዮቅልጥያኖስ፡ ፪፻፸ወ፯ ዓመት። ወእመንግሥተ፡ ዲዮቅልጥያኖስ፡ በ፶ወ፱ ዓመት። ኮነ፡ ጉባኤ፡ ኒቅያ፡ በመዋዕለ፡ 
                                       ቈስጠ<supplied reason="omitted">ን</supplied>ጢኖስ፡ በእንተ፡ አ<gap reason="illegible" unit="chars" quantity="1"/>ርዮስ። አመ፡ ፻፲ወ፯ ዓመተ፡ ዲዮቅልጥያኖስ፡
                                        ኮነ፡ ጉባኤ፡ ቈስጥንጥንያ፡ በመዋዕለ፡ ቴዎዶስዮስ፡ ዘየዐቢ፡ በእንተ፡ መቅዶንዮስ።```

Any clue? Shall I proceed with the creation of new records?
There's no rush of course!

**Comment by thea-m** [comment]
Thank you! 
- I agree regarding the creation of a new record for text 1.
- For text 2, that might also make sense, however I wonder whether the existence of numerous records for these understudied texts could lead to an erroneous impression of preciseness...It is difficult to decide due to the scarcity of available images. I wonder whether creating a general record (or narrative unit?) would be appropriate here. Possibly LIT4099MashafaT could be made a general record, as there is no text available for the manuscripts in which it has been used. But you decide, if you feel another work ID would be better, let's do that.
- For text 3, this search https://betamasaheft.eu/simpleSearch.html?query=%22%E1%8A%A5%E1%88%B5%E1%8A%A8%E1%8D%A1+%E1%88%98%E1%8A%95%E1%8C%8D%E1%88%A5%E1%89%B0%22 led me to the Mazgaba Hāymanot, but I don't have Cerulli's edition available right now. Do you have it? If not, I will see if I find it in the next days.

**Comment by thea-m** [comment]
f. 88ra-vb corresponds to the edition of the Mazgaba Haymanot by Cerulli, pp.33-34, ending abruptly. The text on the following folia reads as if it could also be part of this work, but I could not identify it now. If you have the edition, you could try, if not, I could try again to read through it in its entirety.

**Comment by MassimoVilla** [comment]
Thank you Thea! Accurate as always!
I will create a new record for the first text, I will use LIT4099MashafaT as a general record for the second text, and I will encode the third text as an incomplete excerpt from the last two chapters of the Mazgaba Hāymanot (I just checked Cerulli's edition). Text from fol. 89va seems to be LIT6075DiscourseOnSoul as found in MS London, British Library, BL Oriental 593.

**Comment by thea-m** [comment]
Can this be closed?
https://github.com/BetaMasaheft/Works/pull/917/files
