### ISSUE TITLE
Do we need ID for alleluiatic tables in Dəggwā? Shall I encode Dəggwā as Maṣḥafä Ziq?

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2312]
@DenisNosnitsin1970 @eu-genia @thea-m @karljonaskarlsson 

The first part of BMLacq306 is described by Marrassini as "Dəggwā". I attributed therefore LIT3178Deggwa to it. Marrassini stated, that it does not have neither a Ṣomä dəggwā nor alleluiatic tables. I found an ID for Ṣoma dəggwā  (= LIT2361somade), but i could not find an ID for the latter (yet alone 21f results for ሃሌ ሉያ in works). Do we need a new ID or is it already existing but difficult to identify?

I showed this manuscript also to Jonas. He remarked, that it might be a part of a Ziq. As far as I understood, this is not certain. For that reason I made a comment in a note, that it my be part of LIT1979Mashaf. Is this correct or is this information safe in a way, that I should nest it into LIT1979Mashaf?

**Comment by DenisNosnitsin1970** [comment]
In my understanding, ideally ID should be given to a text with independent circulation,  and when we know exectly what it is (I propose an ID for a text when I have more than one witnessof the same) Otherwise a part-text may be sufficient, or even just sufficient information in <title></title>. If the info is not certain, better not to include it into the work record or anywhere, until it has been checked, if found important enoigh (rejected or accepted, on the basis of some arguments).
