### ISSUE TITLE
LOC-ID for አረማዊ 

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2350]
@DenisNosnitsin1970 @thea-m @eu-genia 

አረማዊ፡ is a term, that signifies Aramaeans, gentiles or evem Greeks. It is recorded in Dillmanns lexicon also as አረማይ. I came across in BMLacq, but it is also quite frequent in many other manuscripts. I want to create a LOC-ID for it. Do you agree?

 The incipit text of ms_i1.10.2 in BMLacq776 (Miracle of the Christian with withered hands and feet) on f. 90vb is as following:
<incipit xml:lang="gez"><hi rend="rubric">ተአምሪሁ፡ ለመል</hi>አክ፡ ክቡር፡ <hi rend="rubric">ሚካኤል፡</hi>
                                        ሊቀ፡ መላእክት፡ ትንብልናሁ፡ የሀሉ፡ ምስለ፡ ገብሩ፡ ገብረ፡ <hi rend="rubric">ሚካኤል፡</hi> ለዓ፡ 
                                        <gap reason="omitted" unit="chars" quantity="3"/> ተብህለ፡ ከመ፡ ሀሎ፡ ፩ብእሲ፡ 
                                        <placeName ref="LOC0000">አረማዊ፡ </placeName>ባዕል፡ ጥቀ፡ በንዎዝ፡ ዓለም፡ ኃላፊ፡ ወአኃዘ፡ 
                                        የሐውር፡ በህገ፡ አበዊሁ፡ ረከበ፡ ብእሲ፡ ከርስታናዌ፡ እ</incipit>

**Comment by thea-m** [comment]
Maybe an ETH record (sub-category of person records) might be more appropriate, because the term refers more to an (albeit vague) ethnicity than an actual or imagined place. 
The issue raised by Denis (same as with Talason) is valid - anything can be marked up in as much depth as we want, we have to set the limits. If you have a clear aim in encoding proper names of protagonists etc go ahead, but it is not necessary for the manuscript descriptions.

**Comment by DenisNosnitsin1970** [comment]
In the sense of confession it is very common; despite the etymological background, I assume that Ethiopians would understand it mostly as "pagan". I think it is here opposed to ከርስታናዌ፡.

**Comment by CarstenHoffmannMarburg** [comment]
OK. I see that the meaning "pagan" is dominant here and I will skip the LOC ID.

**Comment by AaronButts** [comment]
I write only because I find this quite interesting! I also think it means 'pagan' here as opposed to ከርስታናዌ. 

Interestingly the same meaning of 'aramean' as 'pagan' occurs in Aramaic, especially Syriac, where it can be much more fraught and complicated to separate out the distinctions!
