### ISSUE TITLE
Letter of the 318 Fathers of Nicaea concerning apostates

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2355]
In Vat Borg. et. 2, f. 173r-174v (Senodos) there is a letter of the 318 fathers concerning apostates who want to return to the church. I have managed to locate it in only one other Senodos ms. i. e. BnF Eth. 121 f. 70r. I cannot find a work record for it.

My intuition is that it is something like LIT1313Discou or LIT2693CanR i. e. a text which is included in the Senodos relatively rarely. 

Would it be correct to create a work record for it?

@thea-m @DenisNosnitsin1970 @eu-genia 

![Zrzut ekranu 2023-05-10 223351](https://github.com/BetaMasaheft/Documentation/assets/62760230/0a164b03-9a6e-4122-996a-6b243e405752)

**Comment by eu-genia** [comment]
let us check with @abausi he would know for sure

**Comment by abausi** [comment]
In fact, I know this text very well, since I edited it, also using this manuscript, and discussing its position in the _stemma codicum_: see Alessandro Bausi, ‘L’Epistola 70 di Cipriano di Cartagine in versione etiopica’, _Aethiopica_, 1 (1998), 101–130.
It is in fact a text that occurs rarely in Sinodos MSS, but occurs also in the _Aksumite Collection_, there with a foreword a list of names. It has already received the CAe 1348. The attribution to the Nicaene fathers in this MS is pseudepigraphical (but it occurs also in other MSS).

**Comment by abausi** [comment]
In fact, I know this text very well, since I edited it, also using this 
manuscript, and discussing its position in the /stemma codicum/: see 
Alessandro Bausi, ‘L’Epistola 70 di Cipriano di Cartagine in versione 
etiopica’, /Aethiopica/, 1 (1998), 101–130.
It is in fact a text that occurs rarely in Sinodos MSS, but occurs also 
in the /Aksumite Collection/, there with a foreword and a list of names. 
It has already received the CAe 1348. The attribution to the Nicaene 
fathers in this MS is pseudepigraphical (but it occurs also in other MSS).

Il 11/05/2023 11:36, Eugenia ha scritto:

**Comment by eu-genia** [comment]
so please use LIT1348Epistl
