### ISSUE TITLE
ESam019 504 Gateway Time-out

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2388]
ESam019 currently has a very long loading time (I always get 504 Gateway Time-out). As it is used in some publications and presentations, it would be nice if it would be displayed (in case anything can be done about it?). Would it help if I would split the record with xi:include?
@DenisNosnitsin1970
@eu-genia

**Comment by eu-genia** [comment]
You will be at the moment getting time out for a lot of things, there is indexing going on.
xi:include does nothing at all, it was introduced for better syncing through gitsync; the expanded file that must be visualized will have the included parts anyway

**Comment by eu-genia** [comment]
I have now stopped the indexing and it does load.

Another thing would be, since at the moment the functionality of aligning text and image does not work anyway, that we comment out the `facsimile `part; I have now tested it in the expanded file and it improves the performance. The text (`edition`) remains of course

**Comment by thea-m** [comment]
Thank you! If that would help, I will proceed to comment out facsimile in all my synaxaria.
