### ISSUE TITLE
Foliation Ṭānāsee 1

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2404]
I have turned to encode Ṭānāsee 1, because this manuscript is very relevant to my research at the moment. I have seen, that there are foliation marks, that have been inserted with small pieces of paper put on the manuscript during the digitization process. Alas there are just only every fifth folio marked like this and for the last folios (after f. 200) the inserted foliation marks are incorrect (mark 205 is infact on folio 204 and so on till the end). This has confused the cataloguer Ernst Hammerschmidt, who did not give correct folio numbers for these folios and it will confuse very many users even if I describe it in the foliation record. Do you think it is worth the time to insert folio number manually in the pictures or does it take to much time and energy to do this for all the manuscripts with distorted foliation marks?

_Originally posted by @CarstenHoffmannMarburg in https://github.com/BetaMasaheft/Documentation/issues/2390#issuecomment-1634540047_

**Comment by DenisNosnitsin1970** [comment]
In theory, the best would be to correct it (and include folia numbers everywhere), but is it possibe technically? Another issue to be considered - if a lot of work has been done on that manuscript, won't the correction result in an even greater confusion? (the catalogue became an important work and has been frequently quoted, was the text on those folia used in editions?). Another  option, in my opinion, would be just clearly commenting upon the mistake in "Foliation" and in ms items. By the way, you can check if Tanasee 1 - Kebran 1 is among the hmml mss. Many from kibran were rephotographed in 1980s, 
see Bosc-Tiessé, Claire und with the collaboration of Patrick Tiessé (plans et planches). „L’histoire et l’art des églises du lac Ṭana“. Annales d’Éthiopie 16 (2000): 207–70. If it is the case, and the ms was foliated at that occassion, and the images are accessible, maybe it is an argument in order to run along the correct foliation.

**Comment by CarstenHoffmannMarburg** [comment]
I think consistency is already lost in this point. At least it is Roger Schneider who refers to folio 238v in an article in JES (Schneider, Roger: Notes ethiopiennes, in: Journal of Ethiopian Studies 16 (1983), p. 108.), what is 237v according to Hammerschmidt and infact according to my own counting 236v. And yes indeed, Schneider has better photos in his publication. I will check the literature, that @DenisNosnitsin1970 recommended to me.

**Comment by CarstenHoffmannMarburg** [comment]
As far as I can see, this manuscript is not available in [https://www.vhmml.org/readingRoom](url)

**Comment by DenisNosnitsin1970** [comment]
The manuscript is not available, but it (EMML 8308) can be easily requested from EMML for viewing, for free (sorry I partly misled you as  Bosc-Tiesse's article strangely does not provide a concordance for Kibran mss - EMML).

**Comment by CarstenHoffmannMarburg** [comment]
Thank you for the hint to EMML 8208! I just wrote a request to help@vhmml.org.
