### ISSUE TITLE
Person ID escaped saving (PRS14082WaldaAmanuel)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2426]
@eu-genia 

I created a new ID for PRS14082WaldaAmanuel, but I did not safe it properly to the BetMas/person/new folder. Now, I cannot find the file anymore and I can make no changes or pull requests. I can already see the record in betamasaheft.eu/PRS14082WaldaAmanuel, but I cannot find it in Oxygen. This is confusing to me. Can you help me to find this file? Otherwise, I may create a new one.

**Comment by eu-genia** [comment]
Please never recreate the files, this only creates duplicates, and then you will be finding multiple copies!
Files created through the app are immediately saved on the web server and in the application.
In order to sync GitHub and the app you MUST always immediately download to the new folder and make a PR, then the online and the github versions are the same.
In any case, once a file has been created you can easily recover them by adding .xml extension at the end
so in this case https://betamasaheft.eu/PRS14082WaldaAmanuel.xml
Open the link and save the file to your github persons new folder and continue as per workflow. Thank you.
