### ISSUE TITLE
 A work record for the homily by ʾAstonā preserved in EMML 8509, f. 162-164

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2442]
I would like to create a work record for the homily by ʾAstonā preserved in EMML 8509, f. 162-164. 

Some remarks:
* of the literature mentioning it I am aware of bm:Nosnitsin2012FourGospelAstona and nothing more
* there are two person records at the moment PRS13640Astona and PRS2164Astona, I think they refer to the same (although mysterious) person and the latter could be deleted
* if anyone of you has looked at it  before, am I correct to assume that this text has something to do with "Epistle of Christ from Heaven" (CANT 311) and it might be useful to do a relation with LIT1978Mashaf?

@eu-genia @abausi @DenisNosnitsin1970 @thea-m

**Comment by DenisNosnitsin1970** [comment]
Yes, Marcin, you are right, LIT1978Mashaf appears to refer to that text, but as far as I understand the Homily from EMML 8509 is its shorter and older version. There are two more witnesses of that text, both recent. The (doublet) personal ID emerged because Astona is mentioned in an old note in `https://betamasaheft.eu/manuscripts/ESmy008/main`. I assume that it is the same Astona, though the story remains a mistery. I discuss it a little in a manuscript catalogue which I have been prepairing for years, about the collection of MY (But I will not discuss the texts in details). Osvaldo Raineri printed the short version in his catalogue,  Raineri, O. 2000. Codices Comboniani Aethiopici (Bibliothecae Apostolicae Vaticanae codices manuscripti recensiti), [Città del Vaticano] 2000, after a recent witness, and made some statements; this version probably should be treated separately from LIT1978Mashaf and get an independent ID. Back to the point, it looks I was a creator of PRS13640Astona, I overlooked the PRS2164Astona. I will remove PRS13640Astona.  Marcin, you are welcome to interlink PRS2164Astona with text ID(s), but I guess an ID should be created for the short version of the homily.

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 since PRS13640Astona is already pointed to it might be easier to delete PRS2164Astona and use only PRS13640Astona

**Comment by DenisNosnitsin1970** [comment]
Ok

**Comment by thea-m** [comment]
Can this be closed?

**Comment by MarcinKrawczuk** [comment]
The record has been created (CAe 6909) so probably yes.
