### ISSUE TITLE
doublet Malkǝʾa Wǝddāse Māryām

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2455]
LIT1869Malkea and LIT3118RepCh398 might refer to the same text. 
LIT1869Malkea is based on the text referred to in EAe III, p. 704b as "Malkǝʾa wǝddāse" (No. 43 in the edition of the Malkǝʾa gubāʿe by Tasfā Gabra Śǝllāse 1959 A.M. which I don't have – @smaugustine do you?) and used only in https://betamasaheft.eu/manuscripts/EMIP03243/main for which no manuscripts are available.
LIT3118RepCh398  is based on Chaîne and widely used.
Does anyone have access to the edition quoted by the EAe so that it would be possible to determine whether they are identical? 

@smaugustine @DenisNosnitsin1970 @CarstenHoffmannMarburg

**Comment by CarstenHoffmannMarburg** [comment]
No, I do not have any edition of Malkǝʾa.

**Comment by smaugustine** [comment]
I have the 1996 A.M. printing and it's the same. The only difference is that prior to Monday (ፈቀደ፡ እግዚእ፡ ለአዳም፡ ያግዕዞ፡) he adds a common introductory stanza (ሰላም፡ ለኪ፡ እንዘ፡ ንሰግድ፡ ንብለኪ፡). But the 1974 A.M. መልክዐ፡ ጉባኤ፡ from Asmara does the same plus one further stanza (ታዐብዮ፡ ነፍስየ፡ መጠነ፡ ኅሊናየ፡ ክህለ፡), which is the common practice. So, in addition to each of the weekday parts, there is the 1-2 stanza common introduction (marked in printed books) and a 2-3 stanza common conclusion, not usually marked explicitly, though I do have a book in which it is (as ዘኅ፡ = ዘኅብረት፡).

I don't remember whether we ended up merging all the records for መ/ውዳሴ፡ ማርያም፡ from Chaîne into one, though we had discussed it at one point. Since the stanzas for individual days of the week don't occur independently, it would make sense to combine them and assign IDs to each of the weekdays in the text `<div>` alongside the introductory and concluding stanzas. On the off chance that they are found incomplete elsewhere using the text IDs in reference to the main work might be better than having separate work records.

**Comment by thea-m** [comment]
Thank you, then if there are no objections, I will merge the two records, and include your remarks in the abstract.

**Comment by eu-genia** [comment]
This issue already exists https://github.com/BetaMasaheft/Documentation/issues/1538
