### ISSUE TITLE
Better disambiguation for Book of Daniel

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2478]
@eu-genia @DenisNosnitsin1970 @thea-m 

I found two records for the biblical Book of Daniel: 
LIT3529Daniel (entitled: "Daniel, Book of (includes Daniel, Susanna and Bel and the Dragon)")
LIT1259Daniel (entitled: "Daniel, Book of")

There is no abstract and so, I do not know, whether the latter record refers neccessarily to a (protestant) version without Susanne, Bel, the three Youths in the Furnace and other deuterocanonical parts. I personally think this would be unlikely. I rather think, it might be a doublet or a generic title. I suggest to explain the differences between the two LIT better.

However, for BLorient8822 from Strelcyns catalogue, there is no further information and I would prefer the ID for the conventional (complete/orthodox) version of the book. Which LIT should I use for this case?

**Comment by thea-m** [comment]
You are right, the records are not well described. I do believe that LIT1259Daniel is intended to refer only to the Book of Daniel without the deuterocanonical parts, while LIT3529Daniel includes all (see for example the usage in BNFet50). 
That said, I also believe it to be likely that in cases of catalogues only mentioning "Daniel", LIT1259Daniel has been used by default, while in fact the manuscript contains LIT3529Daniel.
So I would suggest that you can use LIT3529Daniel for your manuscript. Since you are already looking into the matter, it would also be great if you could add abstracts to both records. It might be worthwhile of discussion whether it makes sense to create a new general ID for Daniel in cases the precise content is not known, or whether LIT3529Daniel can normally be assumed.

**Comment by eu-genia** [comment]
As mentioned now under the PR actually 

LIT3529Daniel with the `title  `"Daniel, Book of (includes Daniel,  Susanna and Bel and the Dragon)" was initially created as the container for

LIT1259Daniel (which clearly has no subtexts)
LIT3194Susanna 
LIT3195Bel
LIT2250salota = LIT1828Mahale#ThreeYouths1 

I checked and they seem to already have the relation in place

But of course it seems that the title and the relations alone are not sufficient for users to disambiguate, this is something that must be also kept in mind for the future: we have many cases where we had assumed that the difference in the title and relations are sufficient to clarify, but probably this is not the case, if it does not work even for us internally.
