### ISSUE TITLE
Malkǝʾa Madḫane ʿAlam - ʾƎsaggǝd in BLorient13273 and EMIP00017

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2508]
@eu-genia @thea-m @DenisNosnitsin1970 @smaugustine 

I found a Malkǝʾ in BLorient13273. It is entitled Malkǝʾa Madḫane ʿAlam - ʾƎsaggǝd by Strelcyn, who also gives an long incipit:

```
<msItem xml:id="ms_i6">
                            <locus from="99r" to="108v"/>
                            <title ref="LIT00000000000000000000" type="incomplete">Malkǝʾa Madḫane ʿAlam - ʾƎsaggǝd</title>
                            <note>In 33 stanzas, 29 of which beginning with <foreign xml:lang="gez">እሰግድ፡ </foreign>.</note>
                            <incipit xml:lang="gez">ሰላም፡ ዕብል፡ ለልደትከ፡ መድምም።
                                                                         እምድንጋሌ፡ ሥጋ፡ ኅቱም፤
                                                                         ኢየሱስ፡ ክርስቶስ፡ መድኃኔ፡ ዓለም።
                                                                         ልብየ፡ አንቅህ፡ ወነፍስየ፡ ለስብሐቲከ፡ አዳም።
                                                                         ለሥጋየስ፡ አኃዞ፡ ድካም።</incipit>
                        </msItem>
```
I wonder if this could be from LIT2861RepCh142, which is also mentioned with this title in the Bm record: https://betamasaheft.eu/works/LIT2861RepCh142/main. However, the incipit given by Chaîne in the Répertoire is very different, which leads me to believe that it is either from a different stanza of this text or from a different work altogether. Unfortunately, all four witnesses mentioned in this record and in Chaîne do not provide images for verification.

I found a strikingly similar text in EMIP00017:
```
               <msItem xml:id="ms_i1.11">
                           <locus from="59r" to="65v" facs="062"/>
                           <title>Hymn to Jesus Christ, beginning with “I prostrate before your conception,” <foreign xml:lang="gez">እሰግድ፡ ለፅንሰትከ፡</foreign>
                           </title>
                           <note>Composed in the style of <foreign xml:lang="gez">መልክእ፡</foreign>
                           </note>
                           <incipit xml:lang="gez">
                          እሰግድ፡ ለፅንሰትከ፡ ወለልደትከ፡ መድምም።
                          እምድንጋሌ፡ ሥጋ፡ ኅቱም።
                          ኢየሱስ፡ ክርስቶስ፡ መድኃኔ፡ ዓለምልል<gap reason="omitted"/>,
                          ለዝክረ፡ ስምከ፡<gap reason="omitted"/>ለሥእርተ፡ ርእስከ፡<gap reason="omitted"/>ለርእስከ፡<gap reason="omitted"/>,
                          ስብሐት፡ ለከ፡ አምላኪየ፡ በኈልቈ፡ ሰብእ፡ ወመላእክት፡<gap reason="omitted"/>
                        </incipit>
                        </msItem>
```

I would suggest creating a new LIT ID for the work attested in these two manuscripts, unless we can identify it as part of something else.

**Comment by eu-genia** [comment]
OK
the incipit quoted seems to be an arke stanza also used in the synaxary (? maybe @thea-m can check better if she has come across it, here I found it inserted before the reading for 29 Yakatit https://www.facebook.com/100069703417025/posts/2234263313548259/)

**Comment by smaugustine** [comment]
In these cases it's only possible to compare by using the first 2–3 stanzas (and/or counting the total number of stanzas) since it's exactly these stanzas (those at the start or end of hymns) that end up either being excerpted and used elsewhere or inserted from elsewhere (having been lone stanzas in origin). With this case, too, it can be tricky because the headword (እሰግድ፡) also may not be consistent in every copy. For example, I have noted ones that use "ሰላም፡ እብል፡ ለፅንሰትከ፡ ..." instead.

I'm sure I've seen the title "Malkǝʾa Madḫane ʿAlam - ʾƎsaggǝd" in at least one printed book (ie from Ethiopia) before. Here in EMML 6251 (below) it is considered to be "መልክአ፡ መድኃኔ፡ ዓለም፡ ካልእ፡", though such numbering can also vary from collector to collector.

In case it's helpful, my records count the number of stanzas for the malkəʾ as 33.

![slice1](https://github.com/BetaMasaheft/Documentation/assets/6315671/42864cf3-a596-4c86-b1e0-547b1da64c8d)

**Comment by CarstenHoffmannMarburg** [comment]
@smaugustine @eu-genia,

if I understand you correctly, you remarked, that the given 10 words are not enough to identify this piece as LIT2861RepCh142 or to create a new LIT ID from it. Do you agree to leave it unmarked e.g. without LIT ID in both cases?

**Comment by eu-genia** [comment]
I think that you could provisionally create the same ID to be also used in EMML 6251; if it ever comes out that the text is different it can be updated
