### ISSUE TITLE
Discourse in honour of the Archangel Michael

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2563]
@eu-genia @DenisNosnitsin1970 

I found a text in BLorient4849, that St. Strelcyn refers to as "Discourse in honour of the Archangel Michael". I cannot find this text in the search.

```
<msItem xml:id="ms_i1">
                            <locus from="21r" to="32r"/> 
                            <title ref="LIT00000000000000000000">Discourse in honour of the Archangel Michael</title>  
                            <note>The name of the saint is missing, the spaces reserved for the rubrics being left blank.</note>
                            <incipit xml:lang="gez">ወእምድኅረ፡ ተጠምቁ፡ ነበሩ፡ ወርኃ፡ ፍጹመ፡ ኀበ፡ ጳጳስ፡ እንዘ፡ ይሜህሮሙ፡ ነገረ፡ ሃይማኖት፡ ርትዕት፡ ወማቴዎስ፡ ነግድ፡ እምብዝኃ፡
                                ፍሥሐሁ፡ ወሀበ፡ ኵሎ፡ ዘረከበ፡ ለቤተ፡ ክርስቲያን፡ ለሊቀ፡ መላእክት፡ ቅዱሰ፡ <add resp="PRS8999Strelcyn">ሚካኤል፡</add> ብዙኃ፡ ወርቀ፡ 
                                ወብሩረ፡ በእንተ፡ መድኃኒተ፡ ነፍሱ፡</incipit>
                        </msItem>
```

**Comment by DenisNosnitsin1970** [comment]
Check here, http://books.good-amharic-books.com/dirsana-2.PDF, p. 128a, below?

**Comment by eu-genia** [comment]
Extract from LIT1295Dersan (or rather LIT3961Homily)

**Comment by CarstenHoffmannMarburg** [comment]
> Extract from LIT1295Dersan (or rather LIT3961Homily)

The following msItem is indeed LIT1295Dersan. However, I cannot find LIT3961Homily or something similar among the subdivised parts of LIT1295Dersan.

**Comment by eu-genia** [comment]
LIT3961Homily is the Homily for Maggabit from LIT1295Dersan as the relation clearly specifies. 

we have Homilies for each month as separate entities BUT the `corresp `has not been added under `LIT1295Dersan ` because noone has closely studied the text and clarified if it is always the same homily for the same month, see also https://github.com/BetaMasaheft/Documentation/issues/2361

Most probably we are dealing with a merger of two manuscripts of DM (a composite, also judging by handDesc), of which from the first cod. unit only the homily for Maggabit was inserted
