### ISSUE TITLE
<date/> or <seg/> in hand descriptions

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2573]
We have very many descriptions of hands in our manuscript records, which are defined by `<date/>` and very many which habe `<seg/>`. E.g. 
```
<handNote script="Ethiopic" xml:id="h4">
                                    <desc>Mediocre handwriting, a little larger and straighter</desc>
                                    <date notBefore="1700" resp="PRS8999Strelcyn"/>
                                </handNote>
```
or 

```
<handNote xml:id="h1" script="Ethiopic" corresp="#p1 #p2_i2">                                        
                                        <seg type="script">18th-century script.</seg>                                        
                                    </handNote>
```

In principal, both are very similar, because they give an approximate dating for a handwriting mostly based on palaeography. What is the preferred way to describe the hands? Should we use  `<date/>` or `<seg/>` or both as it is given in an example in the [Guidelines](https://betamasaheft.eu/Guidelines/?q=hand&id=handDescription):

```
<handNote script="Ethiopic" xml:id="h1" corresp="#p1.2 #p1.3 #a4">
            <seg type="script">First half of the twentieth-century script.</seg>
            <seg type="ink">Black, red.</seg>
            <seg type="rubrication"></seg>
            <date notBefore="1900" notAfter="1949">First half of the 20th century.</date>
            <desc>
                Careful, somewhat irregular; by a good scribe (name:
                <persName role="scribe" ref="PRS11958WaldaM">Walda Māryām</persName>
                ).
            </desc>
        </handNote>
```
Cf. https://github.com/BetaMasaheft/Manuscripts/pull/2499

@karljonaskarlsson @eu-genia @DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
I do not use `<date notBefore="1900" notAfter="1949"/>` because it turned out redundant. 
`<seg type="script"/>`  is actually supposed to contain smth different from date indication, referring to script/style type (and in other traditions it is the case), but for Ethiopic manuscript, it still coincides with (palaeographic) period/time indication. `<desc/>` is supposed to contain the description of a handwriting, for Ethiopic it is not codified (the name of the scribe is very essential, and indications to his level - from crude to caligraphic, according to my opinion). I have my own "quasi" script description scheme, but I would not add it to each catalogue description I digitize.  I simply take over what I find in the cataloge, if I disagree I might indicate this, and the reasons why, and propose a new dating. For some mss, new datings have been proposed by S. Uhlig and elsewhere.
