### ISSUE TITLE
textClass link does not work

### ISSUE THREAD

**Issue by nafisa-valieva** [BetaMasaheft/Documentation#2648]
https://betamasaheft.eu/Guidelines/?q=key&id=keywordsIntro <textClass>[↗] link does seem to work. May be it can be easily fixed.

**Comment by eu-genia** [comment]
where exactly do you see a link that does not work? 
please show the specific example of where you encountered the link, where it should point, where it currently points.

If you mean this https://betamasaheft.eu/Guidelines/?id=textClass then the link works very well, it tells you that we have no local page but you can go to the TEI guidelines because we have nothing to add to them.

**Comment by eu-genia** [comment]
TEI has well over a thousand elements https://www.tei-c.org/release/doc/tei-p5-doc/en/html/REF-ELEMENTS.html we only have local guidelines for when these are modified or need to be additionally explained.
It is not possible to create local copies for over a thousand TEI pages, they are already available, and the link brings you there just fine, if you read the text that contains the link.

**Comment by nafisa-valieva** [comment]
You are right, thank you! I was too quick. my apologies!
