### ISSUE TITLE
DL Abbrev.: specifying "Canons of the Councils" (e.g. Apostolic Canons)

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Documentation#329]
- there are two entries of the "Apostolic Councils", also named "Canons of the Apostles" (LIT1141Aposto & LIT2642CanonsAp); which one refers to printed DL Abbrev.: "Can. Ap." ?
- on the "Canons" in general there is an issues of underspecification of the canons contained in which compilation of Ethiopic literature (no additional infos so far included in database); 
- there is a set of "Canons of the Councils of" [+ City/Place name] - these works are not named consistently (sometimes: LIT[No.]CanonCouncils, somtimes: LIT[No.]Place name);
- Is "Canons of Nicaea" (LIT1226Canons) an umbrella term for "Nicaea I" (LIT2650CanonsNicaea1) [= DL "Can. Nic."] and Nicaea II (LIT2688CanonsNicaea2) [= DL "Can. II Nic."]? probably not, but please verify.

**Comment by MassimoVilla** [comment]
As to the first point, concerning the Canons of the Apostles. "Can. Ap." actually refers to both LIT2670AC56 (the first recension of the Apostolic Canons, 56 in number) and LIT2675AC81 (the second recension, 81 in number).
For instance, Dillmann's Lex. col. 262, sub voce ሥዩም፡ I Can Ap. 1. 2 (= canons 1-2 of the first recension); col. 47 sub voce ተልእከ፡ II Can. Ap. 69 (= canon 69 of the second recension), again on cols. 152 (II Can. Ap. 35), 195 (II Can. Ap. 2), etc.

**Comment by MassimoVilla** [comment]
As to the last point, LIT1226Canons seems to me an ambiguous record: it was extracted from the EAE index, from occurrences of "Canons of Nicaea", "Canons of Church Fathers", "Canons of the Nicean Fathers" (EAE II:534b, IV:48a, 624a). Only on IV:624a it refers to the two sets of 20 and 84 canons of Nicaea (= Nicaea I and Nicaea II); the first two occurrences deal with the Fǝtḥa nagaśt and unspecified excerpts contained in the Book of Ritual for the Ordination, respectively.
LIT1226Canons seems to have been never employed so far in MSS descriptions. It could be used as a general record for those instances of the "Canons of Nicaea" which cannot be more precisely identified due to underspecification of the cataloguers (as we do for those recensions of Vitae for which no incipit is provided), or simply deleted as unnecessary.

**Comment by eu-genia** [comment]
LIT1141Aposto is umbrella term (general record) for LIT2670AC56 and LIT2675AC81 
LIT1226Canons is umbrella term for all possible Canons of Nicaea

There is no consistency in record IDs - it is not needed either - these shall not be changed as long as they exist

While we are working to complete the BetMes app with all the comments/data for disambiguation it may be helpful for Martin to use the spreadsheet [https://docs.google.com/spreadsheets/d/1a0LtliOVuXoRcDhgj3p5V1Z2i-M5k5_MkT6YgPgh04s/edit#gid=299181318](https://docs.google.com/spreadsheets/d/1a0LtliOVuXoRcDhgj3p5V1Z2i-M5k5_MkT6YgPgh04s/edit#gid=299181318)

**Comment by PietroLiuzzo** [comment]
@fitawari Please, if you use the spreadsheet make sure you double check the record in the app, because there might be records which have been deleted but are still there as this file should not be any more updated since December 2016.

**Comment by thea-m** [comment]
can this issue be closed? 
@MassimoVilla @fitawari

**Comment by thea-m** [comment]
no one seems to be working on this anymore, in case of new related problems, new issues can be opened
