### ISSUE TITLE
"continuation" of scroll

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#369]
I have a question about BDLaethf11 and BDLaethf12 (Ullendorff 90 and 91): 
Both are scrolls containing magic prayers which belonged to the same owner. Ullendorff writes at the end of his description of BDLaethf11 "Continuation in no. 91". 
I'm not quite sure what this means: were they originally one scroll and are now kept separately? Or were they apparently written one after the other? The prayer ending BDLaethf11 doesn't seem to be continued in BDLaethf12, as far as I can tell from the description.
Both are relatively short compared to the other scrolls in the collection.

**Comment by DenisNosnitsin1970** [comment]
I think they were once one scroll consisting of two parts, which were separated at some point and described by Ullendorff as nos 11 and 12. Each of the items is composed of 1 piece of parchment (cp. the rolls around, normally it is more). The owner is the same. no. 11 has only one image and no image at the end, this is also not common. Of course, Ullendorff could have explained it better in a couple of additional words, because one cannot be 100% secure and gets slight doubts, as, for instance, the width of the pieces in not the same. (In no. 12 "a man on horseback riding over the body of a women" must be St,. Susenyos).

**Comment by thea-m** [comment]
Thank you!

**Comment by eu-genia** [comment]
another case for msFrag then

**Comment by PietroLiuzzo** [comment]
@thea-m I think this needs to be fixed as the current description IMHO represents in n.11 both, and in n.12 only 12. I think the TEI description in the file should strictly describe the scroll in question, and not reproduce the content and description of the other, i.e. in BDLaethf11 the msParts need to go and only the content of the current msPart 1 should remain as content of msDesc. idno and altIdno also need to be changed. thanks

**Comment by thea-m** [comment]
I updated both records, which reflected the use of msFrag (made unnecessary by the syntaxe du codex relations).  There had also still been some references to the deleted #f ids in the BDLaethf11 .
