### ISSUE TITLE
collation 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#406]
The guidelines concerning collation seem to be not quite up to date. 
Lists containing items as
```xml
  <item xml:id="q2">
           <dim unit="leaf">10</dim>
           <locus from="11r" to="20v"/>
       </item>
```
lead to an error on the app (See BLadd16220 and many Vatican records). Apparently, @n has to be added for each item. However, many records using @n here also produce errors (BNFet117, BAVet12, BAVet17, BAVet73 and many more) - I don't know where the problem is here.

**Comment by PietroLiuzzo** [comment]
the problem is in the accounting of dimensions of the quire.

`<dim unit="leaf">3</dim>` is ok, but needs specification, otherways the compulsory even number of folios in a quire is not going to be accountable. 

guidelines are quite clear on this when saying 

Quires with an uneven dim[@unit] will ALWAYS need clarification of the phenomenon occurring as below. No item view will be loaded if only the following is given
````xml
WRONG ENCODING EXAMPLE
<item xml:id="q2">
           <dim unit="leaf">9</dim>
       </item>
````
you need at least the following
````xml
<item xml:id="q2">
           <dim unit="leaf">9</dim>
1 added
       </item>
````

**Comment by PietroLiuzzo** [comment]
The manuscripts should now visualize and report an error

**Comment by thea-m** [comment]
works well, thank you!

**Comment by MassimoVilla** [comment]
In many catalogues the reason why a given quire has an odd number of leaves is not further specified. It is in most cases a matter of a single leaf (counterparted by a stub), but we do not know in which position it occurs. 
I would suggest to use a minimal formula (e.g., "the structure of the quire can not be further specified") which, even though does not provide a satisfying explanation of the phenomenon, at least prevents from generating an error in the app.

**Comment by PietroLiuzzo** [comment]
I think this is now well handled. the formula suggested can be safely used.
