### ISSUE TITLE
encoding of supplications

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#497]
related to #408 
How should a supplication as ስረዩ፡ ወባርኩኒ፡ ለጸሓፊሁ። be encoded? If no more information is available and I cannot check the manuscript, I would assume that this was added at the same time or directly after finishing the copying, so it is no addition - is this correct? Or are these supplications usually added in a later hand?
If they are no additions, should we, in analogy to subscriptions, add a type="supplication" to `<explicit>`? Or is there a better way of encoding this?

**Comment by DenisNosnitsin1970** [comment]
I think it is not an addition (it could be if it would have been added in a different hand; there are some cases, but one should evaluate each one separately). To my opinion, it is a supplication included in explicit (if one defines "explicit" less strictly). I think it doesn't have to be encoded separately, but can be referred to unders "scribes" (otherwise it has to be continued with supplication for the donors).

**Comment by thea-m** [comment]
We need to discuss more generally the encoding of various cases of colophons and subscriptions in the next meeting
