### ISSUE TITLE
always assign period keywords to records

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#523]
PRS8746Semon

It would be great to include the dates of his life, or if not known at least the century he lived in.
This does actually apply to all persons!

**Comment by PietroLiuzzo** [comment]
this could be expanded to a general question about assigning at least a period (from the six we have in our keywords) of attestation to all entries.

**Comment by abausi** [comment]
I agree! I have not exactly in mind now what PRS8746Semon refers to.

**Comment by PietroLiuzzo** [comment]
please note that our keyword/periods are now in PeriodO
http://n2t.net/ark:/99152/p03tcss

this is going to be quite useful to group information both when it is dated more precisely and when it is not, moreover it will be useful for our maps which might then gain more meaning diacronically. 

in the updated places encoding guidelines we have included this as a standard existence statement.
https://github.com/SChAth/ScAthiop/wiki/guidelinesPlace

**Comment by abausi** [comment]
I know about the period, and this should remain as it is ; I wonder whether we should additionally add a more precise dating whenever known

**Comment by PietroLiuzzo** [comment]
at the moment we have often precise dates in records which have been edited but we do not systematically also assign a label for a period. I think this would be useful but would need some planning as regards how it is done, because we probably do not want to go through each of our 23k records but at the same time there is little I can do to mark this up programmatically. I would suggest to
- enforce this guideline in the creation of new records
- enforce this guideline in the schema, requiring that at least one of the six period keywords is used in each record
- slowly go through persons and works to classify them with these periods systematically whenever possible.

**Comment by abausi** [comment]
I agree with Pietro's suggestion.

Il 26.06.2017 07:09, Pietro Liuzzo ha scritto:

**Comment by thea-m** [comment]
If we enforce the inclusion of a period keyword in the schema, we also need a solution for records which don't strictly belong to the Ethiopian tradition, such as mss copied by European scholars or all non-Ethiopian person and place records (maybe a different set of keywords?).

**Comment by abausi** [comment]
We could simply use a rough categorisation by centuries or 
half-centuries (1601-1650, 1651-1700 etc.). This seems to me to be the 
least arbitrary and the simplest solution as well.

Il 18.08.2017 14:33, thea-m ha scritto:

**Comment by DenisNosnitsin1970** [comment]
Maybe centuries would be a little more preferable.

**Comment by abausi** [comment]
It is OK, we could also have different ranges, for example 1401-1500, 
1501-1600 etc. but then starting from 1801-1850 each 50 years.

Il 21.08.2017 10:43, DenisNosnitsin1970 ha scritto:

**Comment by DenisNosnitsin1970** [comment]
Yes, this is optimal.

**Comment by thea-m** [comment]
So we would categorize by centuries until 1800AD and by 50 years from 1801-today and possibly enforce the use of these keywords in the schema for all records.
Should the periodization by literary periods (the ones proposed in #390 which are already in use) be used parallelly where applicable (for example for mss, works and authors)?
It is of course always possible to delete or change keywords (and we absolutely should do so if it improves our consistency and adds value to the project), but obviously considering the number of records concerned this is a lot of work and it would be wonderful if it didn't happen too often. So if different literary period keywords would for some reason be preferable, it would be good if this could be discussed here or in the next meeting.

**Comment by abausi** [comment]
OK but the question posed regarded non-Ethiopian periods, if i understood
it correctly

Il 26/giu/2017 08:09 AM, "Pietro Liuzzo" <notifications@github.com> ha
scritto:

**Comment by thea-m** [comment]
yes, I just wanted to be sure, thank you!

**Comment by thea-m** [comment]
Summing up for the meeting: 
- The suggestion is to add a period keyword to all (works, persons, mss?) records, enforcing this in newly created records and slowly working through the existing keywords.
- The six already existing keywords should be used only for records belonging to the Ethiopian tradition strictly speaking:
Aks = Aksumite = 300-700 CE
Paks1 = Postaksumite I = 1200-1433
Paks2 = Postaksumite II = 1434-1632
Gon = Gondarine = 1632-1769
ZaMa = Zamana Masāfǝnt = 1769-1855
MoPe = Modern Period = 1855-1974
@DenisNosnitsin1970 had some remarks on this periodization
- For all other records, a new set of keywords has to be added, categorized by centuries until 1800AD and by 50 years from 1801-today
- If the inclusion of the period keywords is enforced we will need a "uncertain" keyword

**Comment by PietroLiuzzo** [comment]
I am very sorry to cime so late in this discussion.

- period keywords are useful to group marked data and facilitate search. See comment above. Their application to all data should be perhaps limited to what is meaningful and managed in the workflow. adding a task to go through each file is perhaps an overkill. I would suggest to limit the effort to works records and start from those which have been already given some attention, then move on. If this is done with any systematic organization, I would suggest to do contemporarily the assignation of Clavis id, another classification task which we have deferred for a quite long while, starting with the Coptic Clavis for example. 
- the absence of a period keyword (or any keyword for what matters) is already a statement of uncertainty and I would say a much better one than the wild assignation of a an ambiguous keyword.  I have argued agains unknown, uncertain, etc. also in other occasions. I would be for saying nothing where we know nothing rather than saying something for the sake of filling a box, which is not what we are doing when we encode. 
- I am also against the creation of arbitrary or locally defined generic periods. We could use periodO definitions, there are plenty and well defined. But more generally I do not see the need to have such usage when we can assign dates we have. if your concern is the date search, I should add that periods are use to this end only where no other dating criteria is present

**Comment by PietroLiuzzo** [comment]
@MassimoVilla will start going through a KRZ and BHO and will enter the Clavis ids, the period and related bibliography.

**Comment by PietroLiuzzo** [comment]
Postaksumite = 700-1140
Postaksumite I --> Zagwe/Early Solomonic = 1140-1433
Zagwe =  1140 - 1270
Early Solomonic = 1270 - 1433 
Postaksumite II --> Mid Solomonic

**Comment by abausi** [comment]
To be added:
South-Arabian, Pre-Aksumite and Proto-Aksumite periods = 1000-1 BCE
Early Aksumite = 1-300 CE
