### ISSUE TITLE
"donor" to be used for modern persons?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#525]
From idscussion with @DenisNosnitsin1970 
should role="donor" also be used for modern persons who acquired manuscripts and gave them to institutions?

**Comment by PietroLiuzzo** [comment]
would you expect these to be in a list of donors? then yes.

**Comment by eu-genia** [comment]
yes of course, "donor" has no time dimension

**Comment by DenisNosnitsin1970** [comment]
But the motivation of the scholars presenting the manuscripts to modern libraries is completely different from that of the medieval donors. Should we not keep apart these categories? (otherwise it is like calling the modern scholars of textual criticism medeaval scribes equally "philologists", because they work and "correct" texts).

**Comment by PietroLiuzzo** [comment]
added beqeather.
update schema in repository. check for options in app.
