### ISSUE TITLE
document use of floruit in guidelines

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#590]
In our person records, all biographical information is contained in `<floruit>` - this seems not to be conform to the definition of floruit (and is actually stated nowhere explicitely in the guidelines), but since this use is uniform in our records, I suppose it has been discussed previously. However, the fact that this section is (logically) entitled "Floruit" on the app can be confusing to users, who would expect there only information about the approximate date of life of the person in question. Could the title maybe be changed to "Bibliographical Information" or something similar?

**Comment by sologebre** [comment]
**Actually, floruit denotes a date or period during which a person was known to have been alive or active in the historical discourse. It refers mainly, however, to the major active years recorded under his occupation. For example, a floruit of a king represents the years of his reign (i.e. the year he became a king until a year he was deposed or he died), it does not encompass the years from his birth to death. For the Ethiopian metropolitans, abbots, bishops and Alexandria patriarchs the floruit refers to the year of appointment to the year of death or in some cases the year of replacement. It applies equally to active years of persons with various occupations. Thus, historical data given under <floruit> do not describe the whole history of the person from birth to death, rather they focus on what a person has done or accomplished in his or her active years of occupation so that readers can have better understanding the active years of the person. In some cases, where information is available, the story of a person's role in producing manuscripts will also be considered.
Biographical information is so broad that the information given under floruit does not replace it or we cannot take only floruit as biographical information. Indeed, if we consider all elements under the person collectively represent a brief biographical information of a person, then the floruit is only one element that must be treated as it is. However, thank you for having raised the issue; we will update the guidelines if necessarily.

**Comment by thea-m** [comment]
Thank you for the clarification, I understand your approach. However, the theoretical background behind the final visualization of the person entries might not be immediately obvious to everyone. What people see when opening a person record on the app is the name, the dates of birth and death (if known) and "floruit" where they will in many cases find the only paragraphic information on the page (for example, PRS9038Susenyos or PRS6643MananLi). I understand that the entirety of the record, including all elements and relations, constitutes the biographical sketch, but I believe it is understandable that someone not steeped in this work would expect the largest chunk of text to contain the main information about this person. Maybe `<floruit>` could instead be visualized as "Period of main activity"? But I am certainly not an expert on historical work and conventions!

**Comment by PietroLiuzzo** [comment]
Please @sologebre  update the guidelines with the text in the comment in the relevant places.
I am opening a new issue for the visualization of person data, but is a separate look and feel issue.

**Comment by thea-m** [comment]
I have added two paragraphs to the guidelines, http://betamasaheft.eu/Guidelines/?id=persons:  

> The elements of a person's record constitute in their entirety a brief biographical sketch of the record's subject. It is therefore not necessary to limit the description of the person's life to a single element. Instead, all information should be encoded at the appropriate place in the record, for example <birth>↗, <death>↗ or <floruit>↗.

> <floruit>↗ contains the date of the major active years of the record's subject. The paragraphical information given in <floruit>↗ does not aim at describing the whole life of the person in question, but focusses on what they have done in their active years. For instance, for metropolitans, kings etc. it would usually encompass the years between their appointment and death or replacement. See for example ʾAbbāy Habta Ṣǝyon:

Please reopen if there is anything you disagree with or that has remained unclear
