### ISSUE TITLE
@resp="PRS4805Grebaut PRS9530Tisseran" not visualized

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#608]
@resp="PRS4805Grebaut PRS9530Tisseran" (in `<corr>` or `<gap>` for example) is not visualized, for example BAVet102, incipit of ms_i1

**Comment by PietroLiuzzo** [comment]
is it really necessary to have two values in resp? have the two independently provided the same correction?

**Comment by thea-m** [comment]
They have written the catalogue together, so it's probably not possible to say which one of them provided the correction
@MassimoVilla

**Comment by PietroLiuzzo** [comment]
I remember having already dealt with this case in the past. I will look why this issues comes back again

**Comment by PietroLiuzzo** [comment]
This script adds in the content of the tooltip on gaps and other edition phenomena names which are collected in a separate hidden div and populated with a query to the api. the resp.js queries need to wait for those to have finished. thus now the script uses the event ajaxStop.

**Comment by MassimoVilla** [comment]
The reason is the one indicated by Dorothea. I think it is necessary to have the chance to indicate more than one value in `resp`. The same phenomenon may occur in other catalogues (e.g., the EMML ones by Getatchew Haile and Macomber), as well as in articles written by two or more authors we might want to refer to, e.g., for dating a MS.

**Comment by PietroLiuzzo** [comment]
sure, this is now fixed and you will see it in release 2.3
