### ISSUE TITLE
no spaces after references on the map

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#651]
In the pop up window of the Wagara polygon on the map of the homepage, there are no spaces after referenced entities in the text, i.e.:

> north of `<placeName ref="LOC5888Tana"/>` and south 

(in http://betamasaheft.eu/places/LOC6144Wagara/main itself everything is fine)

**Comment by PietroLiuzzo** [comment]
The map is now based on static data. Probably the export was made before the spaces after tana where added. there are still missing spaces in this record, so there will be errors if I rebuild the geojson now. you can check the current geojson and thus the content of the popup by hitting the geoJson button. http://betamasaheft.eu/LOC6144Wagara.json. Tana is now ok, but you have forGondar, because in the data there is `for<placeName ref="LOC3577Gondar"/>` instead of `for <placeName ref="LOC3577Gondar"/>`. with the next release this export will be done again and thus updated **only for the cases in which the data is correct**. Closing this as not needing any fix.
