### ISSUE TITLE
keywords for miniatures

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#652]
To separate this from the discussion on decoDesc encoding in #641 
@PietroLiuzzo had written:

> ## keywords use in encoding of manuscripts
> I do not want to direct your content choices in any way, but to add some practical principles for the encoding:
> - you don't have to add any keywords to the manuscript description. These will theoretically have no msItems and a lot of decoNotes. there is no need to assign keywords if they are not needed. 
> - One different point is weather we want to retrive all such manuscripts, then it might be useful to ad dd a generic keyword to describe this type like miniatureCollection or something similar. In the description it will be spelled out, but the keyword will facilitate retrievability of all and only these type of manuscripts. I would be strongly against a keyword like 'figure' which is semantically rather generic and servers no purpose which is not already supported by the current encoding.
> - if the contents of the images are about hagiography, etc. and you think these manuscripts should come up if you click on that keywords, then please freely and inclusively add all those keywords  which you feel relevant and helpful.  

I think that it would be helpful to retrieve these manuscripts and that it makes sense to use generic keywords for them, such as hagiography. I also think that, in the same spirit, these manuscripts should come up when one searchs for all Christian items in Beta Masaheft. It seems to be the easiest to relax the definition of "ChristianLiterature" to include non textual items, but it would also be possible to create a new keyword, such as ChristianMiniature or ChristianItem, which someone who uses the advanced search would then immediately become aware of when scrolling through the keywords.
I would also be in favour of adding the "miniatureCollection" keyword proposed by Pietro.
What do you think?

**Comment by PietroLiuzzo** [comment]
I have added miniatureCollection in the taxonomy category special mss with GoldenGospel

**Comment by thea-m** [comment]
Still open is the question whether the keyword ChristianLiterature should be assigned to items containing no text, or whether another keyword should be created

**Comment by Gnisci** [comment]
Had the opportunity do discuss this with @thea-m and we had a couple of points to raise:

1) Relaxing the definition of "ChristianLiterature" certainly serves the purpose if one wishes to have a term to encompass all works that are Christian in character and describes the keyword in such terms as "Object related to Christian Literature." 

2) However, images are most certainly _related_ to ChristianLiterature, but they _do not_ constitute Literature. This leads to the second point, what would a user, who cannot access these definitions in the schema, currently think when he finds the three keywords: a) Christian; b) Christianity; c) ChristianLiterature?  Both me and @thea-m thnk the user might be inclined to click on Christian rather than on ChristianLiterature. The problem could perhaps be solved by:
         
- applying both a) and b) to manuscripts and just a) for objects with only images
- allowing the user to preview the definition in the schema when his mouse hovers over the keyword
- assuming the user will eventually understand that the keyword "ChristiaLiterature" applies to everything that is Christian in character, and simply add an extra keyword (I would suggest _PictureBook_, which has been used, for instance in the Encyclopaedia Aethiopica to refer to one such item painted by Brancaleone) for objects that are of the type mentioned by Dorothea.

**Comment by thea-m** [comment]
The various similar keywords are now disambiguated in the advanced search by indicating the group they belong with (#674 )

**Comment by PietroLiuzzo** [comment]
@thea-m will update taxonomy with "ChristianContent" and this will be used for the 2 manuscripts with only images.
