### ISSUE TITLE
PRS11482Yohannes

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#680]
in this record the name contains a supplied text. this is legitimate, but IMHO not very well suited for our current app structure. if the person cannot be associated with a name, but that is an attestation of the person I would leave the mark up in the manuscript record and leave the persname with either a standardized name or just the attested portion. the attestation, independent from the values of the persname are otherways collected. are there many? is this case documented?

**Comment by thea-m** [comment]
I think that there is currently only this one record with this encoding (this record was actually created and edited by @DenisNosnitsin1970 , but we had talked it over together - not sure though why I'm recorded as editor, maybe we had created it together). 
In this case (IVefiopsk5), if I understand the manuscript record correctly, the name of the scribe is apparently only mentioned by the cataloguer and doesn't occur in any text given in the catalogue, so the information on him would be encoded in the manuscript record as an extra in additions. To me it seems better to have this information in the person record as is done currently - maybe in a note, if the current encoding leads to problems for the app?
We had previously (in the case of names transcribed or translated by cataloguers) agreed against standardising names, since it might be misleading for users researching the original orthography, but maybe like this it would be clear:
```xml
<persName xml:lang="gez" xml:id="n1" resp="DN">ዮሐንስ</persName>
<persName xml:lang="gez" type="normalized" corresp="#n1" resp="DN">Yoḥannǝs</persName>
<note>Only the last two letters of the name are visible in the manuscript.</note>
```

**Comment by PietroLiuzzo** [comment]
if I understand, then do please normalize the person record if you need to keep it. you might also not link it to any record, isn't it?
the name encoded with the supplied and all should only occur in the part of the manuscript description where this text is recorded, IVefiopsk5 in the addition text or where this part of name appears.

**Comment by thea-m** [comment]
I updated the person record and the guidelines, @DenisNosnitsin1970 , could you please add the information on this person as it is given in the catalogue in an "extra" in `<additions>` in the manuscript record?
```xml
   <item xml:id="e1">
  <desc></desc>
    </item>
```
