### ISSUE TITLE
Dillmann catalogue numbers

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#697]
It might be helpful if Dillmann catalogue numbers were stated in the record in Arabic as well as Roman numerals, what do you think?

**Comment by MassimoVilla** [comment]
Two ways (both Arabic and Roman) seem to me redundant (and also potentially misleading, since Rüppel's mss are indicated with both a Roman and an Arabic number). 
The Roman numbers do not seem problematic to me. Do you think we could have an improvement of readability if we adopt Arabic numerals?

Btw, the same issue also involves other catalogues, e.g. Wright's BLorient mss. Whichever decision we take, I would suggest to extend it to all catalogues which make use of Roman numerals.

**Comment by thea-m** [comment]
The search, when it includes `<idno>`, will probably not find Roman numerals if one searches for an Arabic numeral? 
@PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
you want to search for 1  and find I 5 and find V or viceversa? that is not possible.

**Comment by thea-m** [comment]
So the question is, would someone search for example for BL Add. 11,620 with "51"? For Frankfurt Ms. or. 14 with "Rüpp. 3" or "X"? What do you think, @DenisNosnitsin1970 ?
People have had many difficulties finding manuscripts through the search (though this should get easier once it searches idno as well), so I would be tendentially in favour of adding rather too much than not enough...

**Comment by MassimoVilla** [comment]
> I would be tendentially in favour of adding rather too much than not enough...
> 

I agree, and since part of the scientific literature sometimes refers to mss through the catalogue numbering instead of the shelfmark numbering I think we need to add as much as possible.
Let's replace all Roman numbers with Arabic numbers then. What I meant is just to avoid to display the very same information in the app in two ways (e.g., LI and 51).

**Comment by thea-m** [comment]
@MassimoVilla I agree with you that having both LI and 51 displayed in the app (under Other identifiers in this case) would be a bit unfortunate. However, my concern is that people might search for the Latin catalogue number in Arabic numerals (or possibly vice versa) and thus not find the record in question.

**Comment by MassimoVilla** [comment]
we might then encode the catalogue numbering in both systems (LI and 51), so that both searches would be successful, but then let only one system appear in the app.

**Comment by thea-m** [comment]
How could we do that? There is no fixed number of `<idno>`'s after which we would want any following identifiers not to be displayed. Could we add attributes to `<idno>` or `<altIdentifier>` to distinguish those we don't want to be displayed from the regular identifiers? 
@PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
so, you actually do want now to enter it in different ways but you do not want to display one or the other. Question is: why? does it disturb so much to have both 51 and LI? this needs to be encoded as alternative identifiers `altIdentifier/idno`.

**Comment by thea-m** [comment]
I wouldn't find it dramatic to have both displayed, especially if it reduces the amount of unsuccessful searches for manuscripts. I'll add this to the guidelines and change the concerned records
