### ISSUE TITLE
overlapping in the menu

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#703]
In many composite manuscripts, there is overlapping in the menu on the left (between "No major relationship with any other item yet." and "Show more links") , see for example FSUor41 or BNFet104

**Comment by thea-m** [comment]
same as #648 - it is hidden when the menu is expanded, but it would still be nice if there was no overlapping at all, if possible

**Comment by PietroLiuzzo** [comment]
I have added live a css workaround. the problem here is that the div with the list of CU is variable and thus its height. the container nav element in the html has a relative position because of the collapsible and relation to the top nav bar. I have tried several combinations of position, overflow and margins and I have added a fix setting the distance of the div with the relations to a set 80px. this will overlap if there are more CU. and will be very low if there is no CU.

**Comment by PietroLiuzzo** [comment]
@thea-m please could you have a look and tell me if it is now better?

**Comment by PietroLiuzzo** [comment]
the other option is off course to remove entirely "no major blablabla"

**Comment by thea-m** [comment]
Seems to be better now, thank you! But (on my laptop), there still is overlapping in FSUor41, now between "No major relationship with any other item yet." and "Author". I think that nothing would be missed if we remove "No major relationship with any other item yet."...
