### ISSUE TITLE
use of <witness>

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#714]
There are inconsistencies in our current use of `<witness>` in work records:
At the beginning of our work, we used to add all known witnesses of a work  to `<listWit>`, and then later decided to instead to limit this to the witnesses actually used in our edition (presuming that the other other witnesses will be displayed in the app if they contain the work's ID), cf. the guidelines:

> We use `<witness>` for those manuscripts which are actually used for the edition we are going to provide in the div[@type='edition']. All catalogued manuscripts containing the work are displayed in the app anyway.

However, there seem to be still many cases where all known witnesses are added to work records (for example LIT4825GadlaAbIrai or LIT1531GadlaZ). This is also helpful, since we are far from creating records for all known manuscripts, and it is of course valuable to have this information in the work records. However, adding these IDs in `<listWit>` without creating mini ms records obviously leads to many errors: 
http://betamasaheft.eu/manuscripts/BNFabb14/main
I think that it might be useful to add the witnesses to work records in cases where there is currently no record for the manuscript in question (in which case we should probably be more thorough in creating mini ms records). It does, however, seem redundant in cases where there already is a manuscript record referencing the work. What do you think?

**Comment by PietroLiuzzo** [comment]
I think the principle of adding to newly encoded works only the mss used for that edition holds even if there are cases where all possible witnesses have been encoded. I would keep that as the leading principle and would neither modify the existing files or add more of those which have a mixed approach. the data entry for manuscripts follows a different sequence (by catalogue) and eventually adding some when they come across might simply result in slowing down the work, because then eventually somebody will have to do that mss again, and will also have no certainty about its existence. so, I do not think this is much of a problem, it can stay as it is.

**Comment by thea-m** [comment]
The current approach of adding only ms IDs to the witness list that are used for the edition can be kept. As @PietroLiuzzo stated, there is no need to go through all existing work records and modify the witnesses listed. 
Added to the work guidelines:
As information provided by the catalogues we are working with should not be lost, whenever a catalogue description contains references to other manuscripts containing the same work, mini ms records containing the work ID should be created for those manuscripts. This assures that all the manuscripts containing the same work can be retrieved by the app while reserving `listWit` in the work records mainly for the manuscripts used for the edition.
