### ISSUE TITLE
relations in institution creation form

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#726]
relations chosen while creating a new institution record on the app are not transferred to the xml file

**Comment by PietroLiuzzo** [comment]
I cannot reproduce this issue, the relations are saved correctly when creating a new institution

**Comment by thea-m** [comment]
Sorry, what doesn't get transferred is the id written in the "attested in" field, which should become a lawd:hasAttestation relation in the record

**Comment by PietroLiuzzo** [comment]
thanks for noting this. I have updated the form and the attested in lookup. 
you will be able to check if you want to enter an id or a title part, the form will look it up and populate the selector below, so that you can select the value you want. but attention! there will be one option for each match! it can be that you get more than one time the same item.
you will also get a new confirmation message, blinking and annoying.

**Comment by PietroLiuzzo** [comment]
@thea-m is this now fine?

**Comment by thea-m** [comment]
no, still doesn't work...
