### ISSUE TITLE
manuscript pdfs not generated

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#742]
As pointed out by @SusanneHummel, the pdfs of BAVet83, FSUor133 and IVefiopsk10 are not generated correctly: 

> An error has occurred
> Something has gone wrong. Sorry! This error has been generated by the application.
> try to specify the collection name.

Maybe there is a problem with the links?

**Comment by PietroLiuzzo** [comment]
is the normal view working? thanks

**Comment by thea-m** [comment]
yes

**Comment by PietroLiuzzo** [comment]
three different problems, all should be sorted now. took occasion to update code and avoid use of xqjson package.

**Comment by thea-m** [comment]
thank you, it's working now for all the mentioned manuscripts except FSUor133 (504 Gateway Time-out). The normal view is working

**Comment by PietroLiuzzo** [comment]
I just tested and got the pdf correctly... could you try again?

**Comment by thea-m** [comment]
Still not in Chrome, but works in firefox

**Comment by PietroLiuzzo** [comment]
unfortunately given your test that is most certainly the cache (memory), not sure if of your browser  or of the server. I had set it to cache a bit more to improve a little the speed, tomorrow morning I will reset the server not to cache anything, so you can see updates immediately, otherwise it should be the metter of waiting a bit before trying. However I did not experience this, I have download it in a metter of seconds several times.
