### ISSUE TITLE
manuscripts, repositories and catalogue view filter by catalogue and by institution

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#788]
The catalogue and institution filter in the list views for manuscripts, repository and catalogue all have a filter by catalogue which queries the zotero API BEFORE loading the result page. this filter should be instead optional and load the selector with these values only when requested by the user

**Comment by thea-m** [comment]
When I click on the catalogue filter menu in the manuscript view (after having clicked on "load") in order to select a catalogue, I immediately get this nice black view:
![image](https://user-images.githubusercontent.com/19650382/39465265-ab5cb570-4d22-11e8-92f4-d2e667c5a78f.png)
After a while the screen goes back to the normal list view, but it's not possible for me to select a catalogue from the list

**Comment by thea-m** [comment]
Now a list (slowly) loads, but apparently not completely, only catalogues from Abbadie to Derat are shown. I can chose one of these, but not scroll up or down
