### ISSUE TITLE
persname printed (gesù christo)

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#792]
in the xml file PRS5684JesusCh everything seems OK to me, I cannot explain why Gesù Christo should be printed (unless the string itself was wrong)

**Comment by thea-m** [comment]
I think that it prints the first persName with @corresp="#n1", which according to http://betamasaheft.eu/tei/PRS5684JesusCh.xml is the Italian one. 
In the xml record in oxygen, however, I see
```xml
  <persName xml:lang="gez" xml:id="n1">ኢየሱስ፡ ክርስቶስ፡</persName>
               <persName xml:lang="gez" type="normalized" corresp="#n1">ʾIyasus Krǝstos</persName>
               <persName xml:lang="en" corresp="#n1" type="main">Jesus Christ</persName>  
```        
so apparently there is a synchronizing problem?

**Comment by thea-m** [comment]
(speaking of this record, I find
```xml
 <nationality type="Israel/Palestine"/>
               <occupation type="other">Son of God</occupation>
```
slightly problematic...can we delete them? We have the link to wikidata, and this information, which stands not in a specific relation to the Ethiopian tradition can be found there)

**Comment by PietroLiuzzo** [comment]
Please note that nothing has changed in how the main title is chosen from a person record. Perhaps it is poorly or not documented (I could not find it in the guidelines), in which case it should be (but not as it is in this comment, because it would condition people to encode for the result instead of encoding what they are actually encoding!)

the title selector looks for
1. persName[@type = 'main'][@corresp = '#n1']
2. persName[@corresp = '#n1'][@xml:lang = 'gez']
3. persName[@corresp = '#n1'][@xml:lang = 'en'][@type = 'normalized']
4. persName[@corresp = '#n1'][@xml:lang[not(. = 'en')][not(. = 'gez')]]
5. persName[1]

The record, updated at the end of January did not make it to the app back then. I have now reloaded it manually.
