### ISSUE TITLE
magical drawings

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#794]
might we need an extra deconote type for them (e g Seal of Solomon) or do they count as ornamentation? or drawings?

**Comment by Gnisci** [comment]
To my mind, when it can be done with certainty, (e.g. they complement a magical text) it makes sense to identify them as you suggest rather than lable them as ornamentation or drawrings.

**Comment by eu-genia** [comment]
@PietroLiuzzo , can you add a type to the schema? `<deconote type="magic"/>`

**Comment by PietroLiuzzo** [comment]
Dear Eugenia, you can do that yourself, adding a value is quite straight forward. Just open the tei-betamasaheft.rng and edit it. I would in this case argue with you that it would be much better to use drawing, as this are still this type of decoration, but then you can use the term[@key='magic'] into the description (see [guidelines](https://github.com/BetaMasaheft/Documentation/wiki/guidelines#decoration-description)), to have this additional specification. this is semantically more correct in my opinion and from the user search point of view it will mean that you can see also magical drawings if you only filter that, you can get all the magical drawing ONLY if you use that as a filter instead of clicking on drawing, and you can combine the parameters with others. moreover magic is already a keyword, so you should not even need to edit the schema.

**Comment by PietroLiuzzo** [comment]
can we close this?

**Comment by PietroLiuzzo** [comment]
@eu-genia

**Comment by thea-m** [comment]
In the specific case of the Seal of Solomon, wouldn't it be more straightforward to create an Art Theme for it? This record could then receive the "magic" keyword. There is also the unused "SealofSolomon" keyword, which similarily could receive the "magic" keyword.
 The current way of encoding, as agreed in this issue,
` <desc><term key="Magic">"Seal of Solomon"</term>.</desc>` seems to me to be a bit circuitous?
If using the "magic" keyword is the only way to make the manuscripts in question show up in https://betamasaheft.eu/decorations?legendText=&otherText=&target-keyword=Magic, it could still be done additionally.
@Gnisci @eu-genia @PietroLiuzzo

**Comment by thea-m** [comment]
I've created the AT1140SealSol Art Theme, please reopen the issue if you object

**Comment by Gnisci** [comment]
Nope sounds fine :)
