### ISSUE TITLE
place "parts"?

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#812]
Which is the best way to encode (provide sub-ids?) to items within a place/institution?
e.g. the several churches/chapels within a monastery?

**Comment by PietroLiuzzo** [comment]
the question not clear enough, please provide an example. there are many ways you can do this. what would the use be?

**Comment by eu-genia** [comment]
e.g. institution INS0103AKM (this is a wide spread case though)
has 2 churches:
```
<ab type="history">Dabr. &#xD;
                     The old rock-hewn church dedicated to <persName ref="PRS6298Libanos">Maṭṭāʿ/Libānos</persName>, below, located in a hardly accessible place and is now deserted. The church of <persName ref="PRS10776Kidan">Kidāna Mǝḥrat</persName> was built in 1930s, specifically in more accessible place near the road.  &#xD;
</ab>
```

in a manuscript description, e.g. ESakm008
we have
```
<item xml:id="a1">
                           <locus target="#125v">f. 125v</locus>: <desc type="OwnershipNote">Ownership note.<q xml:lang="gez">
                               ዛቲ፡ መጽሐፈ፡ ግንዘት፡ &lt;...&gt;
                              ወርቀ፡ ቤተ፡ ክርስቲያን፡ ዘአቡነ፡ ሊባኖስ፡ ወቀይሰ፡ ገበዝሂ፡ ቀሲስ፡ ወልደ፡ ክርስቶስ፡ ወመኰንንሂ፡ ወልደ፡ አምላክ፡ … </q>
                           
                           The note mentions the church of ʾabuna Libānos as the owner of the Ms. Besides, the names of qaysa gabaz Walda Krǝstos and makʷannǝn  ‘ruler’ Walda ʾAmlāk are mentioned.</desc>
                        </item>
```
- the owner is not the entire institution but one of its churches

same for e.g. ESakm006
```
<item xml:id="a3">
                           <locus target="#151r">f. 151r</locus>: <desc type="OwnershipNote">Ownership note.<q xml:lang="gez">
                               ዝመጽ[ሐ]ፍ፡ ግብረ፡ ሕማማት፡ ዘአቡነ፡ ሊባኖስ፡ አበሰት[sic]፡ ዘሠረቆ፡ ወ{ዘ}ሤጦ፡ ወዘፈሐቆ፡ በሥልጣነ፡ ጴጥሮስ፡ ወጳውሎስ፡ እሱር፡ ከመ፡ ዲያብሎስ፡ ውጉዝ፡ ከመ፡ አር[er.]ዮስ፡ ለይኩን፡ በ&lt;...&gt;፫፻፡ በ፲ወ፰፡ ርቱአነ፡ ሃይማኖት፡ ውጉዝ፡</q>
                           <quote xml:lang="en"/>
                           The note states that the Ms. belongs to the church of ʾabuna Libānos  ʾAmbasat.
The note is written in red and in black. It is separated from the previous erased note by red lines and it is followed by the picture (in black and red ink) of a dragon (?) pierced by a sword.</desc>
                        </item>
```

**Comment by PietroLiuzzo** [comment]
My first feeling is that this would be over encoding at the current stage. the information is already provided by the link to the institution from the manuscript and the church is named in the manuscript description. marking up that placeName with the id of the institution and a anchor to an element carrying an id in that record would be possible of course, but what purpose would it serve? if the church is an institution, than it should have a institution record, but if it is agreed it is the monastery, and the church is inside the monastery the information provided is complete and does not need any further encoding. A placeName with a ref containing that text could point to the institution record without further unnecessary specification.

**Comment by eu-genia** [comment]
the churches are not really institutions in our sense, but they are churches in their own right, each with a building, an altar, etc. at the moment they are not properly named either. if someone wants to look for all churches in the database no way to find them. if that means they should get their own place records would create those and make a partOf relationship

**Comment by PietroLiuzzo** [comment]
well, actually you can quite easily do that, based on the church type added to the place element. 

http://betamasaheft.eu/authority-files/list?keyword=church

this page search specifically would also find records which contain a term[@key='church']

you cannot find '_all_ churches' because we possibly don't have a record for each and every church, but that will unlikely get better in 25 years: it is enough time to build several and destroy even more! :)

The question based on the example was on the manuscripts and institutions not on places. So I would definitely do as I suggested (i.e. not over encode) for the case of the issue. 

If you then want to create other place records with type church and relate them to other entities like institutions and manuscripts, you can of course do that, it is just a matter for you to establish your own working priorities for the task you are carrying on weather to do this or not. If you do so, please pick a relation from the schema gn:locatedIn seams better suited, for example. if it is not fine, please search in LOV for a domain specific relation.
