### ISSUE TITLE
schema and guidelines not in sync

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#816]
there is some confusion in the schema and the guidelines regarding the definitions of some of the values of @reason in `<gap>` (especially lost, omitted). 
- In the schema we have:

lost: No better specification available, there is simply a gap.
illegible: Traces of text remains on the surface but cannot be
                                        interpreted
omitted: Text erroneously omitted from the surface by the
                                        scribe/cutter

- In the guidelines there is:

lost: used to indicate a material loss or a portion of text that is to be hypothesized for material reasons ("it was there!"), but which is lost for loss of the material
illegible: a sign, pointing to the place where the text should be added
omitted:  Words or lines skipped in omitted by the editor in transcription

In the schema, there is also @rubrication for `<gap>` (rubrication: spaces left for rubrication, which were left unfilled), while the guidelines have `<space reason="rubrication">` with the same definition.

**Comment by PietroLiuzzo** [comment]
the guidelines definitions are the correct ones and need to be carried over to the schema. one reason more to have the guidelines draw the definitions from the schema directly instead of retyping them and getting them out of sync like in this case. 

I have updated the first group of definitions in the schema
I have removed the only occurrence of gap @reason rubrication from BAVet114 
I have removed definition of gap reason rubrication from the schema.

**Comment by PietroLiuzzo** [comment]
please remember that schema updates are possible for all of you using oxygen. if you need guidance on how to do that, please ask.

**Comment by PietroLiuzzo** [comment]
@thea-m notes that the correction for the definition of omitted was wrong.
now 
- [ ] changing the schema with the old definition of omitted
- [ ] updating the guidelines not to duplicate the information but to link to the element page
