### ISSUE TITLE
Ethio-SPaRe transformation - additiones

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#828]
add the `<desc>` element around the text in additiones

**Comment by PietroLiuzzo** [comment]
There are several text() nodes in a `<item>` inside a `<list>` of `<additions>`.

I am dealing only with those which have already some markup and a sequence of `<locus>`, text(), `<quote>`, text()

I am wrapping with `<desc>` only the first text() and in `<note>` the last. 
````xml
<item xml:id="a1">
     <locus target="#75rb">f. 75rb</locus>
     -rc: Extensive rhymed purchase note.
     <quote xml:lang="gez">
                              <locus target="75rb">75rb-</locus>
                              rc: ዝመጽሐፍ፡ &lt;...&gt; ወተሳየጦ፡
                              በርቁ፡[sic] &lt;...&gt; ከመ፡ ይኵኖ፡  መድኃኒተ፡ ሥጋ፡ ወነፍስ፡…
       </quote>
       <quote xml:lang="en"/> 
       The name of the original donor who bought the Ms. has
       been erased. The initial part, probably mentioning the name(s) of the
       owners, has been erased as well. 
</item>
````

becomes 

````xml
<item xml:id="a1">
     <locus target="#75rb">f. 75rb</locus>
     <desc>-rc: Extensive rhymed purchase note.</desc>
     <quote xml:lang="gez">
                              <locus target="75rb">75rb-</locus>
                              rc: ዝመጽሐፍ፡ &lt;...&gt; ወተሳየጦ፡
                              በርቁ፡[sic] &lt;...&gt; ከመ፡ ይኵኖ፡  መድኃኒተ፡ ሥጋ፡ ወነፍስ፡…
       </quote>
       <quote xml:lang="en"/> 
       <note>The name of the original donor who bought the Ms. has
       been erased. The initial part, probably mentioning the name(s) of the
       owners, has been erased as well.
       </note> 
</item>
````
notice here some further thing **needing hand correction** and namely  the locus information of the type 75rb-rc. where the locus breaks the information in trying to split this. 
such cases still need to be hand fixed so that the present example looks like in the following example this

````xml
<item xml:id="a1">
     <locus from="75rb" to="75rc">f. 75rb-rc</locus>
     <desc>Extensive rhymed purchase note.</desc>
     <quote xml:lang="gez">
                              <locus from="75rb" to="75rc">75rb-rc</locus>
                              ዝመጽሐፍ፡ &lt;...&gt; ወተሳየጦ፡
                              በርቁ፡[sic] &lt;...&gt; ከመ፡ ይኵኖ፡  መድኃኒተ፡ ሥጋ፡ ወነፍስ፡…
       </quote>
       <quote xml:lang="en"/> 
       <note>The name of the original donor who bought the Ms. has
       been erased. The initial part, probably mentioning the name(s) of the
       owners, has been erased as well.
       </note> 
</item>
````
things like
- &lt;...&gt; which I think might mean an omission or an ellipsis in the transcription. 
- [sic]
also need to be tagged, and the first case could be done with a find and replace using any software, IF the actual meaning of that is stable

**Comment by PietroLiuzzo** [comment]
please check the committed files, I have already looked at 30 of them and it looks to me that the requested improvement was achieved with the specification above.

**Comment by eu-genia** [comment]
in the files i've hand-corrected i had to wrap `<desc>` around the whole content as otherwise the `<quote>` or `<q>` (whichever) did not get visualized in the app. if only the definition should be tagged as `<desc>` then there is a problem with visualization. check e.g. ESamm004 (or any other to that matter)

**Comment by PietroLiuzzo** [comment]
Please refer to the guidelines for encoding. 

https://github.com/BetaMasaheft/Documentation/wiki/guidelines#additions

Please do not change the encoding to get the view do what you want. 

Encode according to the guidelines and notify the issue with the web view if any with the id of the record which presents the issue and the description of what you expected.

**Comment by PietroLiuzzo** [comment]
@eu-genia please close issue if this is now ok.
