### ISSUE TITLE
tabots

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#837]
- the search mask should include all `<ref>`s, not only `persNames `
- the search mask should include specific "manifestations" of names, e.g. for 
`<persName ref="PRS5684JesusCh#MadhaneAlam"/>`
it should be Jesus Christ -- Madḫāne ʿĀlam 
(       
```
    <persName xml:lang="gez" xml:id="MadhaneAlam">
                  <addName type="epithet">መድኃኔ፡ ዓለም</addName> 
               </persName>
               <persName xml:lang="gez" corresp="#MadhaneAlam" type="normalized">Madḫāne ʿĀlam</persName>
               <persName xml:lang="en" corresp="#MadhaneAlam">Saviour of the World</persName>
```

)

for `<persName ref="PRS6819Mary#Zion"/>`
it should be Mary - Ṣǝyon

```
<persName xml:lang="gez" xml:id="Zion">
                  <addName type="epithet">ጽዮን፡</addName> 
               </persName>
               <persName corresp="#Zion" xml:lang="gez" type="normalized">Ṣǝyon</persName>
               <persName corresp="#Zion" xml:lang="en">Zion</persName>
```

**Comment by eu-genia** [comment]
the printing rules should apply also here to the name subset (the normalized type)

**Comment by PietroLiuzzo** [comment]
trying to rephrase in order to clarify this requirement

- [ ] the search filter for tabots in the advanced search should include all `<ref type="tabot">`s from `<ab type="tabot">` in an Institution/place record, not only the `<persName type="tabot"> ` elements
- [ ] in the search filter options the labels should include specific "manifestations" of names, e.g. if both
`<persName ref="PRS5684JesusCh"/>` and`<persName ref="PRS5684JesusCh#MadhaneAlam"/>` occur there should not be only one option "Jesus Christ" but also one for "Jesus Christ -- Madḫāne ʿĀlam" the first option will search including also the second, the second will only get the specific ones. 
- [ ] this means that a value "tabot" needs to be allowed for `ref/@type`

**Comment by PietroLiuzzo** [comment]
![schermata 2018-05-02 alle 13 45 32](https://user-images.githubusercontent.com/508012/39521529-205fc884-4e0f-11e8-809d-c62df1ba29d4.png)

**Comment by PietroLiuzzo** [comment]
selecting jesus christ 3 results (includes 2 madhane alam),
selecting jesus madhane alam, 2 results

**Comment by PietroLiuzzo** [comment]
the AS returns an empty box.
the place list returns only two, not all.

**Comment by PietroLiuzzo** [comment]
app:tabots, called from formtabots.html works fine, so, it is either not reached or some parameter fails to be passed on. I am reindexing the db.

**Comment by PietroLiuzzo** [comment]
And Tabot should have the long a!

**Comment by PietroLiuzzo** [comment]
This was linked to the issue of the titles module. This is now solved
