### ISSUE TITLE
Ethio-SPaRe Institutions - missing data

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#839]
the DomLib file for INS0007AM has

> Founder : | Established (or re-established) in the second half of the 15th cent., in the time of təgre mäkwännən ˀAkalom, by ˀAbäkärazun, Gäbrä Mäsiḥ (most probably, members of the Stephanite movement).
> -- | --

the information seems lost in BM, probably in all records that have something there

**Comment by eu-genia** [comment]
true for all records

INS0017UM

> Founder : | Local tradition claims the foundation of the church in the time of King Gäbrä Mäsqäl. The church must have been founded in the pre-15th century period, and be re-established during the reign of King Yoḥannǝs IV (1872-89). The church of ˁUra Mäsqäl (now deserted), on the top of the rock, appears to be an older institution.
> -- | --

in BM: `<desc type="foundation"/>` (empty)

the information must be recovered for all institutions

**Comment by PietroLiuzzo** [comment]
there are 62 such <founder> elements in the institution data from ES, so not much really. 
trying to match them automatically is useless, as since the data was created in BM a lot has been modified. I can copy in the desc[@type='foundation'] what is in ES, but somebody will have to check it and merge the sentences in something meaningful. 

e.g. INS0219EMQ has

                  <desc type="foundation">During the reign of King ʿAmdä Ṣǝyon I (r. 1314-44).</desc>

and the missing information from the ES data is 
                
                According to local tradition the
                monastery was founded by monk Yämanä ʾAb, under King ʿAmdä Ṣǝyon I (r.
                1314-44).
 
I can add it in there to have

                <desc type="foundation">During the reign of King ʿAmdä Ṣǝyon I (r. 1314-44). According to local tradition the
                monastery was founded by monk Yämanä ʾAb, under King ʿAmdä Ṣǝyon I (r.
                1314-44).</desc>

**Comment by eu-genia** [comment]
OK
