### ISSUE TITLE
description of hands

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#865]
There are inconsistencies in how and where we describe hands. The guidelines http://betamasaheft.eu/Guidelines/?id=handDescription have the (fictional?) example:
```xml
     <handNote script="Ethiopic" xml:id="h1" corresp="#p1.2 #p1.3 #a4">
            <seg type="script"> 15th Century square script?</seg>
            <seg type="ink">Black, red</seg>
            <seg type="rubrication">nomina sacra</seg>
            <persName role="scribe" ref="PRS1691Alib"/>
            <date>Mid 15th - mid 15th-cent.</date>
            <desc>Regular, by a well-trained hand</desc>
        </handNote>
```
where the hand is described in `<desc>` while the script is categorized in `<seg type="script">`.
I have often described the hands in `<seg type="script">` and not in `<desc>`, which is inconsistent with the guidelines.
In some manuscripts, there is a general assessment of the hand in `<seg type="script">` and a more detailed description of palaeographic features in `<desc>` (for example BAVet7), but this does not seem to be the general case (for example BLadd16217, where I would expect "Gwǝlḥ-script" in `<seg type="script">`). Often just a date range is given in `<ab type="script">` (for example BAVet89) - is this really useful, since it is repeated in `<date>` anyway?

It would be good if a definition for `<seg type="script">` could be added to the schema - maybe @DenisNosnitsin1970 could do that?

(There are also many MNC and BAV manuscripts which have `<ab type="script">` instead of `<seg type="script">` , but that is probably an error?)

**Comment by PietroLiuzzo** [comment]
yes, please @MassimoVilla fix your entries which have that ab[@type='script'].
as for the definitions in the schema and the update with a non fictitious example of the guidelines, it is certainly to be done. there is however no task for me here, and I will unassign my self

**Comment by MassimoVilla** [comment]
The mss that erroneously had  ab[@type='script'] have been already corrected.

**Comment by thea-m** [comment]
I would propose for `<seg type="script">` to contain a categorization, as "square script" in the example, Gwelh or similar and for `<desc>` to contain any other or more general description of the script. So in the case of many catalogues, we would in fact only have `<desc>`. 
It would maybe be very useful to have your input, @DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
Reasonable, but i think there are some obstacles for this.  
We are not that far as to introduce the proper taxonomy of the scripts. Categorization "square script", "gwelh", "compressed script", etc. is based on S. Uhlig's works and relates to very broad "palaeographic periods", not really to true, well-defined scripts. Thus definition "broad script"  is, according to this system, equivalent to mid-14 - mid-15th century. But this is "terminus technicus", after all, "square" is not necessarily the property of those scripts (it is also not easy to understand exactly what is exactly "square"!). Technically, one tries to compare the handwriting in a manuscript with uhlig's division (working closely with the book and samples, or just doing this "in mind") and locate the script broadly within one of the periods or between them (or just one watches that the dating obtained from other sources would not be contradicted by palaeographic evidence - this is even better). This is also the practice of the cataloguers. 
E.g., BAVet7: 
<handNote xml:id="h1" script="Ethiopic">
<seg type="script">Written in a mediocre handwriting.</seg>
<seg type="ink">Black, red</seg>
<date notBefore="1400" notAfter="1499">15th century</date>  
I agree that now the system looks a little strange because it somewhat obscures the basic division between "script" and its variaty produced by an individual scribe, which is "hand". But it is not to the grade that it is completely ununderstandable, and most catalogues include the quality evaluation: fine, mediocre, poor. even if subjective, it is helpful.

**Comment by PietroLiuzzo** [comment]
in the linked PR I have taken a real example and text from this discussion, rephrased it lightly to update the GL.
