### ISSUE TITLE
ruling indexing and exploitation

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#871]
We have this information which is not exploited about ruling.

>  Ruling pattern: 1A-1A/0-0/0-0/A.

how is this to be parsed and indexed to provide a proper search capability for this feature?

**Comment by thea-m** [comment]
I'm also not sure how far this information is understandable for people not familiar with the work done in Ethio-Spare - is this a universally known ruling pattern formula?

**Comment by DenisNosnitsin1970** [comment]
This is the scheme invented for the description of the ruling invented by Denis Muzerelle, http://palaeographia.org/muzerelle/index.htm, it is indeed used (belongs to the up-date cataloguing). It would be extremely useful to be able to encode and visualize it.

**Comment by PietroLiuzzo** [comment]
how would you like to have it visualized?

**Comment by thea-m** [comment]
Thank you. Maybe this link could be displayed somewhere on the app?

**Comment by DenisNosnitsin1970** [comment]
There are some small imperfections in the system of Muzerelle as the formula refers precisely only to the ruling (as it was designed to capture the layout in the first line), but less exactly to the pricking. Or I have to check it again. Visualizing - smth like scheme 1, 2, 3 etc. here 
https://www.aai.uni-hamburg.de/en/comst/pdf/bulletin1/pp094-109.pdf

**Comment by PietroLiuzzo** [comment]
thanks, I will try to understand from this hints how to produce a scheme like the one in your article starting from the string definition given.

this is useful for the item view I believe, but how do we usefully compare this information and chart data coming from it? what are the meaningful variables to be compared if I have a selection of manuscripts?

**Comment by abausi** [comment]
Since Marilena Maniaci is here in Hamburg at the CSMC as a visiting 
scholar until July, it would be wise to ask her too, how this difficult 
feature could be encoded at best; I will meet her tomorrow and I can 
tell her that we would be interested in having her advice; but two/three 
people should be available for this. Who volunteers?

Il 12.06.2018 14:53, Pietro Liuzzo ha scritto:

**Comment by DenisNosnitsin1970** [comment]
I can com either.

**Comment by abausi** [comment]
OK, I will tell her to come to us, Denis you will be the main contact person for this. Tomorrow I will see her for other reasons

**Comment by DenisNosnitsin1970** [comment]
Pietro, each element of the scheme refers to an element of the formula, but the schemes in the article contain more elements than the formula does. Probably you can hardly spring directly from the formula  1A-1A/0-0/0-0/A to the scheme since the position of the pricks is not reflected in the formula, neither the position of the upper written line in relation to the upper ruled line. The formula directly refers only to designs like here, for instance, http://palaeographia.org/muzerelle/grecs1.htm. 
 Ok, at what time approximately will M. Maniaci come?

**Comment by abausi** [comment]
Denis, I do not know, I will meet her tomorrow but not in the HLCES; I 
had an appointment for other questions, elsewhere. I will fix an 
compatible appointment ad hoc, preferably in the morning where more 
people wil be there. I will inform you tomorrow.

Il 12.06.2018 15:10, DenisNosnitsin1970 ha scritto:

**Comment by PietroLiuzzo** [comment]
I have prepare a few chart visualisations based on the parsing of available ruling formulas.

the pie chart takes the complete formula and groups the value, this gives immediately an idea of the diversity of patterns.

The column charts instead take each one of the Zones in the formula.

The columns show the total of the manuscripts for one of the standard periods defined in all charts which have one type (if any) of Zone pattern description.

the example in the screenshot is for the manuscripts from INS0144MHG (relevant here the first 5 charts)

![schermata 2018-06-22 alle 10 29 27](https://user-images.githubusercontent.com/508012/41766395-2ed50a30-7607-11e8-92a1-76ff1285d269.png)

**Comment by PietroLiuzzo** [comment]
We will add the possibility to add the syntetic information about the type of pattern defined in Denis's article. it will be a non compulsary subtype attribute to one of the ab in the layout element. @DenisNosnitsin1970 will provide short definitions and examples, which will will add to the guidelines (http://betamasaheft.eu/Guidelines/?q=ruling&id=objectDescription).

**Comment by PietroLiuzzo** [comment]
I added to the guidelines the link to Muzerelle presentation
