### ISSUE TITLE
add direct link to lemma in dillmann for persons

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#882]
During the traces meeting a suggestion was made by @eu-genia to associate person record explicitly with the lemma in Dillmann.

I would suggest to do this within a `<relation>` unless anyone has a better idea.

- [ ] we need a property name for the relation
- [ ] this value needs to be added to the schema
- [ ] we need to document this in the guidelines

**Comment by thea-m** [comment]
Should any person then have a relation to the lemma of the name (if existing), whether it refers to this specific person or not? So all Salomons would have a relation to http://betamasaheft.eu/Dillmann/lemma/Lf381b98d8ee4478db9466709865180de ? But PRS8387SalamaI would be linked to b) in this lemma http://betamasaheft.eu/Dillmann/lemma/L974d5e89550e4e2ba6226b7427e4a5c2 , since it refers to this specific person?
Should the same be done with place names? 
I fail a bit to see the additional value of adding such a relation: when one clicks on a geez name there is the link to Dillmann anyway, and from Dillmann, the occurences in bm are given.

**Comment by eu-genia** [comment]
There are no records for exact persons in Dillmann but for names.

The added value was for the TraCES texts encoded in GeTa to also be linked to the Dillmann entries for names especially in cases where names are also common nouns or are composed. e.g. for now Takla Haymanot is annotated there as two common nouns (linked to lemmata), but the Dillmann also has "Takla Haymanot" as lemma, which is currently not linked - there shall also be no direct link there from clicking on a geez name in this case.

**Comment by PietroLiuzzo** [comment]
deciding which ones need to be linked is then very ambiguous. I think @eu-genia is the only one possible candidate for this task. 
We still need to decide on a property name, which will necessarily be a local one. what do you want to call this relation?

**Comment by PietroLiuzzo** [comment]
no, this would be definitely confusing. perhaps there are options in the attributes which are allowed in persName and placeName, but the kind of connection which is meant here is so peculiar that I think I would avoid abusing any of those and anyway prefer a relation with a defined property which explains as well as possible what is the meaning of that relation.

**Comment by eu-genia** [comment]
can we call it simply something like lexicalEntry?

**Comment by PietroLiuzzo** [comment]
perhaps better hasLexiconEntry 
for @passive, please use entire URL 
http://betamasaheft.eu/Dillmann/lemma/L65ae0746b7f9428da90682226ae6cc75

@eu-genia said she will update the guidelines and the schema to close this isse

**Comment by eu-genia** [comment]
schema and guidelines updated

**Comment by PietroLiuzzo** [comment]
the example file LOC7011Meskwa has still the wrong encoding. 
please @eu-genia fix and commit it to close this issue with a proper example, which should also be linked in the guidelines (use `ref[@type='bm']` with the id of the file where the example is in a target).
