### ISSUE TITLE
hand of additions

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#887]
It is not explicitely mentioned in the guidelines when a handNote should be created for additions, though we must have discussed this at some point?
Since per defitionem additions are added later to the ms, it can be assumed that they are not written in the main hand, and when working with images of the manuscript it would of course be preferable that each identifiable hand is described in a handnote and associated to the items of the manuscript it produced. 
However, when working from catalogue entries, I have only created handNotes for additions if the catalogue provides any particular information for this hand, or when for example it is mentioned that two additions were written by two different hands. It is my general impression that you have also followed this principle, but it would be good to confirm or discuss it so that I can then document it in the guidelines. 
Thank you!

**Comment by eu-genia** [comment]
Yes, me too so far only created an additional handnote (or more) when I had some information (whether ink, type of script, or information like "same hand as the previous addition", making it necessary to point), otherwise I have not.
It is a fuzzy thing, but in E-S manuscripts they sometimes had described additions as "written in main hand" or "in the hand of text XY", so it would be too dangerous to assume that each addition means a new hand.
I would suggest to document this practice.
If we get to work with images and identify more hands then of course the descriptions can be revised.

**Comment by thea-m** [comment]
I added

> In additions as anywhere in the manuscript description, a handNote should be created for each identifiable hand, whether it can be described from available pictures of the manuscript or whether the catalogue provides sufficient information for assigning certain additions to individual hands. If no such information is available, no handNote should be created, as it cannot always be excluded that the addition is written in the hand of the main text.

to http://betamasaheft.eu/Guidelines/?id=additionsVaria, please reopen the issue if there is more need for discussion
