### ISSUE TITLE
double relation

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#901]
as noticed by @sologebre , in http://betamasaheft.eu/works/LIT1919Mashaf/analytic the same relation is listed twice, we could not find out why

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.eu/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%27%29%2F%2Ft%3Arelation%5B%40name%3D%22saws%3AisAttributedToAuthor%22%5D%5B%40active%3D%22LIT1919Mashaf%22%5D%5B%40passive%3D%22PRS10626ZaraY%22%5D

you can run this search yourself in both oxygen and in the app as in the link above. if you need guidance on XPATH, just ask.

as you can see in the results, also in LIT1921 there is this same relation which is then correctly picked up by the app. 

it is probably a copypaste error, but I do not know what the fix is.

**Comment by thea-m** [comment]
thank you!
