### ISSUE TITLE
TraCES texts and metadata on BM

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#925]
1) When TraCES texts are exported in TEI they should be published on BM but in some cases they cannot replace the already available texts. For example, in TraCES only parts of the Kǝbra nagaśt (LIT1709Kebran) have been checked and annotated and are to be exported; the text currently reproduced cannot therefore be replaced completely, both versions should be kept.
Which is the best way to organize and visualize the metadata, to make it clear who is responsible for what?
We may have different persons responsible for BM metadata, for digital text(s), for possible mark-up, etc. 
Possibly more "role" elements should be assigned to "editors" and visualized accordingly.
e.g.
```
            <editor key="SH" role="encoder annotator" corresp="#text1"/>
            <editor key="RHC" role="encoder" corresp="#text2"/>
            <editor key="ES" role="metadata"/>
```
???
or something similar???

2) in any case the contents of `<editionStmt>` and `<abstract>` should be shown with an appropriate subheader. 

3) the content of `<publicationStmt>` in particular of `<availability>` and of `<encodingDesc>` is not currently displayed

**Comment by PietroLiuzzo** [comment]
3 points are three issues!! please split them up. 

What is not displayed where? 
please check the views. http://betamasaheft.eu/works/LIT1709Kebran/text the encodingDesc is in the right column.

publicationStmt is not there because in principle it applies to the XML only, not to the HTML, to which the copyright printed on each page should apply. having two statements on each page would at least make some confusion. please clarify and let me know.

for editions and attribution we have already several methods, we need not to add others IMHO. Please check the guidelines, e.g. http://betamasaheft.eu/Guidelines/?q=resp&id=work-teiHeader

I have not received any other Traces Text in TEI, and I am still waiting for the updated Amda Seyon. I will have as you know to enter this data after further adaption, then you can point out places where attribution is not clear enough

**Comment by eu-genia** [comment]
I have checked the header guidelines but probably do not understand something...
Under LIT1709Kebran we shall have 2 text versions. Where and how can I disambiguate that RHC is responsible for having encoded one, and SH the other, if both are part of the same record? Now it seems as if both edited the record together, which is not correct, there is the record editor and two encoders, each of a separate text or text part.

Also the encodingDesc is now confusing the two versions of the encoding (these are not two text versions, these are two persons having digitized the same edition, RHC completely but with some errors, SH corrected thoroughly but only selected chapters).

The problem arises because in the coming days the TraCES data shall be uploaded, in the ANNIS format, to the server of the Hamburger Zentrum für Sprachkorpora, and for that the texts shall be linked to metadata - which is the one hosted on BM as it has been decided to not duplicate the metadata about texts. When there is no digital text provided as yet, or where the text (as in Amda Seyon) is from TraCES all is clear, but with the Kebra nagast I am at a loss how to explain it to the users as to who is responsible for the TraCES version exclusively.
