### ISSUE TITLE
visualization dates in person records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#938]
Dates given as values in `<birth>`, `<death>` or `<floruit>` with @notBefore or @notAfter and @cert="medium" are not visualized, for example PRS1906Ananyao

**Comment by PietroLiuzzo** [comment]
I think there was already an agreement that they should not, since there is text in the element itself. You see the dates in there in the list view
http://betamasaheft.eu/persons/list?mainname=%CA%BEAn%C4%81ny%C4%81&date-range=0%2C2000&cp=

perhaps you wish to have a box with summary information about dates in these three elements (i.e. excluding date elements which might occur inside them)?

**Comment by thea-m** [comment]
Thank you! I now remember the discussion about this (#663)...the guidelines have 

> When the date is given as a value and no further information is provided, it is not necessary to repeat the dating in the content of the element: `<death when="1636" evidence="internal">`↗ is sufficient. However, if the element contains text, the value will not be visualized

And there are actually many instances where the dates are not included as text in the element, as for PRS10062Warqitu for example. I think they are only not visualized if the element has @cert as well. 
A box is maybe a good idea as well, if it doesn't crowd the page too much (could it  be integrated into the box with the names?).

**Comment by PietroLiuzzo** [comment]
added

**Comment by thea-m** [comment]
wonderful, thank you!
