### ISSUE TITLE
Single records of miracles

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#961]
While working with a Taʾamməra Māryām manuscript, I have searched the existing miracle records a lot (usually successfully!) and noticed some inconsistencies (unsurprising, considering the amount of records and time span over which they were created). It could be helpful to standardize these records somewhat, now that we already have quite a large corpus to work with. 
I noticed the following points:
- title format: I believe it would make sense if all titles contained the word "miracle" as well as the name of the saint who performed the miracle and a very short summary or key words allowing readers to identify the miracle (many records already follow this format), possibly in a standardized formula, i.e. "Miracle of Mary on the Syrian potter" or "Miracle of Mary: Syrian Potter"
- we have the keyword "miracle", so let's use it :) it is occasionally absent from the records
- references to Mary in English text: there is a lot of variety here, i.e. "Mary", "St(.) Mary", "Our Lady Mary", "Blessed Virgin" etc. Are we fine with this or would it be better to agree on a form?

What do you think?

**Comment by DenisNosnitsin1970** [comment]
If I understand right - I agree with including the name of Mary, Jesus or saint for identification (but then for all texts of the miracle genre). What do you mean under short summary or key words? I assume this may be more problematic. To be more or less correct, you need to read the miracle; otherwise we invent the appelation following a secondary description or a quick look. I would rather suggest pay attention to the bibliography (to be consequent at least with a few main publications) to be able to identify the miracle. While applying different variants of names, we follow the style of the catalogues. I am not sure we should standardize this. There can be some editorial guidelines to reach some kind of unity (St mary or St. Mary) but they should not be too complicated as many people work in the database independently from each other.

**Comment by thea-m** [comment]
I am now going systematically through the macomber list and adding the information contained there to the existing miracle of Mary records / creating new records. I think that a reasonable degree of standardization and searchability will be reached through this work (which will still take some time to finish, considering the amount of miracles...)
