### ISSUE TITLE
Encoding of Letters (general issue)

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#962]
Dear all,
I think we have to decide how (and whether) we encode private letters, written on single leaves (not as an addition to any text). By now I created manuscript records for each letter, but no work record or narrative unit record for them. These letters are unique private messages. 
Here are the examples of my records:
http://betamasaheft.eu/manuscripts/IVEf921/main
http://betamasaheft.eu/manuscripts/IVEf922/main
http://betamasaheft.eu/manuscripts/IVEf923/main

My question is, should I create a narrative unite record or a work record for each text? I think that would be not the best solution. Maybe I should create a generic work-record (although these letters are not literary works from my point of view) for "private letters" and assign these ID to all letters? This would be something usefull from the point of view of a user, I think.
There is even a much more general issue, whether these letters should be considered by the project. I personally think they should, but different opinions might exist. These particular letters are dated to the beginning of the 20th century.

**Comment by abausi** [comment]
I would be in favour to have a solution parallel to that for documentary texts. To be able to display letters as a precise typology of single "works" would be certainly an added value to the project. Letters are not much studied, but there must have been more than we think and they deserve to be duly highlighted.

**Comment by PietroLiuzzo** [comment]
Encoding letters on parchment or paper or whatever, written in ink or typed with a machine count as unique manuscripts with no doubt IMHO and there is where they belong. In the similar case of inscriptions, we have used the value of `@form` in `<objectDesc>` to specify an inscription, but in this case I am not sure it would actually be useful. The transcription of the letter would belong there and have its identifier. So I think it is ok as you have done @DariaElagina and no further work is needed. You can add the keyword 'Letter' there however.

Another case is a letter which is copied into a manuscript, which has no independent support, and is thus a secondary or main content according to the criteria to decide on that. In this case the criteria for contents apply, and you might or not want to create a work record. If you do so, then give to that work record the keyword 'Letter'.

There might be cases where you need to split a work and a manuscript record, if for example a letter of which we do have the original is mentioned somewhere for its text and a work record has been created for it to point it. this is fine, and if and when we might end up having a record for the actual manuscript letter then we will have it and point to the work record as usual. If for example one of these letters is mentioned in a manuscript (another of the same letters?) and you want to refer to it, then you could actually do that directly to the manuscript record, with no need to create a work record.

I am not considering part of this discussion Letters as a literary genre of course, which would, in case we hand up having work records for actual letters, need to be distinguished.
 
I found no work record with the Letter keyword however. @thea-m could you point me to one of the emperors letters?

In terms of finding all letters, you can do that from the keyword. 
http://betamasaheft.eu/authority-files/list?keyword=Letter
because people have been nice enough to add the keyword and the addition type, so that you actually find them all also here (one by one, as compared to the previous search returning the items)
http://betamasaheft.eu/additions?termText=&otherText=&type=Letter

In facts the Letter concept record would need to be reworked to be more generic and the guidelines should include specific instructions on this as well as on inscriptions

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/guidelines/pull/4

**Comment by DariaElagina** [comment]
@PietroLiuzzo thank you very much! I would come with my suggestion for guidelines

**Comment by PietroLiuzzo** [comment]
cool. please let us work on the dedicated branch (let me know if you need help with that) I have created for this edit to the guidelines.

**Comment by PietroLiuzzo** [comment]
closed by http://betamasaheft.eu/Guidelines/?id=letters
