### ISSUE TITLE
Description of māhdar

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#970]
Dear all,
I would like to duscuss how we are going to encode the presence of māhdar. So far I could find three cases of its description, all of them EMIP under collation. Would it be the right place?

**Comment by thea-m** [comment]
I don't know what it is and cannot find it in the files :) Could you give the examples?

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.eu/as.html?query=māhdar
@jonahsandford and @Ralph-Lee-UK can certainly help here.
My impression is that those note are actually part of binding and not collation? could it be?

**Comment by DariaElagina** [comment]
@thea-m  it was my very first time to meet the description of this as well :) here are three examples we have: 
http://betamasaheft.eu/manuscripts/EMIP00108/main 
http://betamasaheft.eu/manuscripts/EMIP00110/main
http://betamasaheft.eu/manuscripts/EMIP00109/main

**Comment by DariaElagina** [comment]
@PietroLiuzzo  I have the same impression, but I am not sure about that.

**Comment by DariaElagina** [comment]
We seem to have an opportunity to describe such things in the biding description: http://betamasaheft.eu/Guidelines/?id=decoNote
SlipCase | for use in binding description. Portable leather case with attached slip where the manuscript is kept.

**Comment by larkvi** [comment]
A mahdar is not a slipcase, and decoNote would seem inappropriate in any case, since the mahdar is not decorative and generally not decorated. I would suggest that the best solution is physDesc/objectDesc, treating it as an object separate from the codex: separate items for codex, chemise, and mahdar.

(If you were set on treating it as a binding, bindingDesc/binding is unbounded.)

**Comment by larkvi** [comment]
If you were going to note it in plain text, I believe the note should be in bindingDesc, not decoDesc.

**Comment by PietroLiuzzo** [comment]
We use deco_Note_ in bindingDesc (as well as in decoDesc) quite regularly, as allowed by TEI. See also chapter 10 of the Guidelines for an example of this use. This allows us also to group nicely decoNotes when needed. 
You will forgive my ignorance, could we get a short description of Mahdar and also chemise so that we might all understand each other? I am a bit reluctant to multiply objectDesc in physDesc, but it that needs to be done, it is ok.
 have we definitely ruled out collation as well as binding as places for the description of these features ?

**Comment by DariaElagina** [comment]
@larkvi  many thanks for your feedback!
We certainly need a description of all such objects, I have never seen them irl.
I think that collation is not an appropriate place anyway.

**Comment by larkvi** [comment]
A mahdar is a leather case (usually with a strap) that may be made in one or two pieces, and acts like a box.
A chemise is a cloth jacket which is pulled over the binding as a decorative or protective element. 
Neither is integral to the binding, and while I treat them in my chapter on binding (see pp. 256--262 https://tspace.library.utoronto.ca/handle/1807/71392 ),they are both separate and potentially created at radically different times or even repurposed, in the case of mahdars. Bill Hanscom has written an article about mahdars: http://www.seattlebookcompany.com/suave-mechanicals-essays-on-the-history-of-bookbinding-vol-3/

**Comment by ElianaDalSasso** [comment]
Maybe also this point could be better encoded in guidelines (together with issue #972). At the moment  there is the possibility to describe a mahdar as "slipcase" in DecoNote in binding. We can agree on a different term and improve terminology...and then decide if it's correct to keep it in the description of binding. 
Same for the chemise. Could it be a keyword in a DecoNote for Cover description?Even if it's a secondary cover?

**Comment by ElianaDalSasso** [comment]
I think that the description of a mahdar is interesting when it's decorated, for example with blind tooling. And maybe could be useful to describe the decorative pattern of a chemise.

**Comment by PietroLiuzzo** [comment]
Thanks @ElianaDalSasso ! if slipcase and mahdar are the same thing, we have the solution of the problem already, and it is one of these suggested, so, all good.

What needs to be done I think is to specify this in the SCHEMA, so that it will appear here: http://betamasaheft.eu/Guidelines/?id=decoNote. I can do this if you give me the wording.

In the guidelines pages we could certainly do with a couple more examples, including this and the one on the bookmarks in this page.
http://betamasaheft.eu/Guidelines/?id=bindingDescription

**Comment by thea-m** [comment]
Sorry for the late remark without having participated in the discussion, but from reading this discussion it is not yet clear to me

- whether slipcase and māḥdar are identical
- whether we encode the presence of a māḥdar in a decoNote in `<binding>` 

(and unrelated to the codicology and its encoding...shouldn't māḥdar be marked up with `<foreign xml:lang="gez">` when written in text?)

Thank you!

**Comment by ElianaDalSasso** [comment]
Hi!At the moment is possible to encode a slipcase with a decoNote in `binding`, meaning māḥdar. 
But, if it's not appropriate to describe a māḥdar as a slipcase, it would be better to encode it with its original name. 
I don't know, I've found different terms: two parts leather slipcase, satchel, satchel-like slipcase.
Actually it's not clear to me if māḥdar is only the internal case while the external is a difat.

**Comment by DenisNosnitsin1970** [comment]
Please, no ethiopisn terms. We should find a neutral English term, even if it is not perfect at the end (but I would look for the most general, since there are several types of mahdärs, not all of them are "two-parts"). Similar devices are used in other manuscript cultures around (if you think of the Sudanic unbound Qurans etc.).

**Comment by larkvi** [comment]
I have not had enough time to really follow up on this, but I have looked a bit more closely, and I think there is a better answer. LoB defines [slipcase ](http://www.ligatus.org.uk/lob/concept/4466)  in a way that specifically and exclusively refers to the type of case that is commonly understood by that term ([example](https://www.tbclrarebooks.com/pictures/31515.jpg?v=1317445033)), effectively excluding types of cases, like mahdars, where the book slips in, but does not have that specific form. However, there is another term, [short-edge opening satchels](http://www.ligatus.org.uk/lob/concept/3022), which specifically describes this general format of case, even explaining the use of it being hung on the wall.

As to it being `binding/decoDesc`, I strongly advise against this use, as I believe it will create problems for people searching the data, since it breaks the logical discoverability of the information (the decorative description will have junk data about non-binding, non-decorative elements). It also sets bad precedent for other objects that are archived under the same shelf number / boxed together, as sometimes happens. I have seen loose sheets of other manuscripts archived under the same number through simple insertion, (clearly not bound together in any way that we would normally understand the term). I have also seen various objects stored with manuscripts that have never been bound with them (in one case, an old, but very decorative box that it was stored in, but which was not created for it). I think it also proves problematic where the box, even if created specifically for the manuscript, has a completely separate set of decoration from the boards, as in [this Burmese example](https://collections.artsmia.org/art/13689/manuscript-box-burma). I strongly advise using the existing TEI structure of msDesc/physDesc/[objectDesc](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-objectDesc.html) in order to describe object which are not integral to the manuscript, including chemises and cases.
