### ISSUE TITLE
Transliteration of Cyrillic in Zotero

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#971]
Dear all, 
The basis for transliteration of Cyrillic should be this table http://kodeks.uni-bamberg.de/AKSL/Schrift/Transliteration.htm
There are however further issues to face. Publications in Russian before the spelling reform of 1918 follow the old orphographic rules, which is of no problem for the titles. In that case, we have often another spelling for the authors' names as well, so Bolotov (Болотов) following the old spelling should be transliterated as Bolotov" (Болотовъ), Turaev (Тураев) as Turaev" (Тураевъ), and so on. This might be confusing. Do we want in the of pre-reform publications standardize authors' names? Or give a sandardized name in brackets? Like: Bolotov" (Bolotov)
Another related issue: 
If the author transliterates his or her name in a way different to the way we do, do we want to give the standardized name in brackets as well? For example, for publications in Russian we use Turaev, or even Turaev" according to the trasliteration rules, for his publications in other languages - Turaiev, which corresponds to the spelling used in the publication. Both spellings are correct in their own way, but the usage of two (or even more) alternative names for the same person might be confusing as well. All these issues are relevant rather for Zotero.

**Comment by PietroLiuzzo** [comment]
Dear @DariaElagina, please, once settled, add this to the relevant pages of the guidelines directly.

**Comment by DariaElagina** [comment]
@PietroLiuzzo Sure, I will

**Comment by eu-genia** [comment]
1)
I personally would follow the post-1918 orthography for the names (especially for the "hard sign" at the end) in order to avoid too many variant spellings, and preserve the original orthography in the titles only. This is also what we did in the COMSt Handbook (see e.g. Lavrov, Marr, Simoni, etc). 

2)
Of course for publications already in Latin script the spelling used by the author/publisher should be given, we must decide though which is given first and which in brackets. 

In the COMSt Handbook we tried to choose one standard version of the name first, and then give other forms in square brackets.

When the author did not have a well-known name in Latin script, the standard form was the "correctly transcribed" form from the main author's language and other forms were in brackets (see e.g. Cereteli, Giorgi [Cereteli, Georgij Vasil'evič]; Cubinašvili, Niko [Cubinov, N.] - for Georgian authors writing in Russian, for example; Georgyan, Astłik [Guévorkian, Astghik] - an Armenian writing in French; Kaʒaia [Kadžaia], Lamara - Georgian [Russian] and the same author as Kaʒaia [Kajaia] for Georgian [French] etc.).

For authors frequently publishing in Latin script and preferring one way of quoting we respected the authors' choice and gave the "correctly transcribed" version in brackets (e.g. Frantsouzoff [Francuzov], Serguei [Sergej], would also mean Turaiev [Turaev]).

We used the same principle for authors writing under nick-names or pen-names or similar (e.g. Desreumaux, Alain [as A. Jacques])

This was discussed back then with @abausi - but of course we all must agree on this and carry the decision.

**Comment by PietroLiuzzo** [comment]
I would advise against entering the two variant name forms in the name or surname field in zotero. it might make you life easier in searching, but it will break all the rest, starting with reuse of the zotero record in BM. On the other side this is not a problem for us to solve, there are authorities for this, VIAF in this case, and the DNB. I would suggest in order to preserve the functionality and aims of the zotero library and its consistency to stick, when in doubt about a transliterated form of a name, to the standardisation choice made by DNB which appear in VIAF. e.g.
http://viaf.org/viaf/34609737/#Turaev,_B._(Boris),_1868-1920
would be transcribed Turaev.

**Comment by DariaElagina** [comment]
Well, the problem is not the fact that we have doubt about the transliterated form, but rather when the author him or herself uses an alternative transliteration for publications in foreign languages. There is no doubt that the correct transliteration is Turaev, but he, himself, used Turaiev. So, all his publications in Russian are written by Turaev and all publications in other languages by Turaiev. This is a simple and obvious case, but there might be really misleading ones as well. Especially with the growth of Zotero database.

**Comment by PietroLiuzzo** [comment]
yes, I did get that, my point is simply that the personal taste of the author should not affect us when providing data for reuse. We should simply stick to national and international standards.

**Comment by DariaElagina** [comment]
I don't think we can change the name of the author provided in the publication...

**Comment by eu-genia** [comment]
The personal taste of the author MUST affect us. we cannot ignore the name form appearing on the book cover, this is a bibliographic error. The publication would not be retrievable otherwise!
Eg all publications by Frantsouzoff have Frantsouzoff, this is the name he is known under internationally, and the name appearing above all the articles in English/French etc. We cannot ignore that. Yet of course when he publishes in Russian we have to transliterate as Francuzov. There is no other way since we do not actively link from the bibliography to VIAF.
Same for Ethiopian authors - e.g. we write Mersha Alehegne when we quote his articles in the EAe or in Aethiopica (https://journals.sub.uni-hamburg.de/aethiopica/article/view/83) etc. but we of course must write "Maršā 'Allahañ" when we quote e.g. his "ዜና ጳጳሳት ኢትዮጵያውያን". 
We can simply say we do not provide anything in brackets of course and leave it to the users to establish the identity.

**Comment by eu-genia** [comment]
Maybe in order to keep the records clean and avoid brackets we could consider using the field "Extra" in Zotero for listing all name variants (or also the VIAF ID) - then the records at least will be searchable and one could retrieve the information when completing bibliographies in publications.

**Comment by PietroLiuzzo** [comment]
I think we have to if we care about reusability and consistency of our shared library. 
A different matter is the title, where we should not change from the publication.
Again to be distinguished is what is in Zotero and what you want in the printed Bibliography. IMHO the db should definitely standardize according to authorities. the printed bibliography (not necessarily our style! can follow this principle with the square brackets for sure. This information might be kept in a note in Zotero, and that would be a useful and reusable piece of information

**Comment by PietroLiuzzo** [comment]
sorry @eu-genia, I read your post on reloading... Extra is used for other things and also by the style, adding this kind of information there would mean chain changes which are probably not needed. notes are better in this case I think.

**Comment by abausi** [comment]
I am reading everything, from the train, before a seminar/workshop on 
philology that will start in a few hours in Naples.

I agree that we have to respect standards and observe the criterion of 
reusability, but there are cases when we have to do better: and this 
seems to me to be one of those cases.

I think that there is still room for using better the Zotero 
bibliography. I can imagine that we can still use Extra and/or other 
fields to get what we need. This also applies to some other features, 
that are still not satisfactorily working, in consideration of our needs.

Il 16.10.2018 10:26, Daria Elagina ha scritto:

**Comment by PietroLiuzzo** [comment]
No doubt Zotero styles can be improved, and we have issues about that which are documented and wait for some attention (my fault!), but it will be very hard to make any of the parts of the bibliographic workflow do things satisfactorily if we do not stick to standards with the data we enter. 
I think these are cases in which the very best we can do is to enter standard data correctly and preserve the information about the variant in a note so that the user of the database might know about that. 
If the user will want or need in his bibliography, to use the name favoured by the author, he will find a note about that in the bibliographic record and will be happy, if he does not want to use that he will be using a correctly standardised name and will be happy(er). 
Users of the style in conjunction with the database (e.g. BM and Dillmann) will also remain happy, because they will not have brackets in the data making things very hard to handle, neither face unexpected behaviour because of a mixed use of the Extra field in the db.

**Comment by eu-genia** [comment]
I still am convinced that the titles can only appear accompanied by the name form as it is present in the publication.

This is not the matter of what is "preferred" by the author but of the retrievability of a title in a library catalogue or other bibliographies. The main rule remains: name and title must be as they are provided by the publication. It is the standardized variant that, if deviating, can be present in the Notes or Extras or other suitable field.

Otherwise we can define a field where ONLY the published name form is saved and change the API so that this is the name printed whenever the title is quoted or the bibliography is extracted from Zotero. Then the Notes field is not usable, as anything can be and is provided under Notes.

**Comment by PietroLiuzzo** [comment]
Hopefully library catalogues in 2018 will normalise by linking their authority files to VIAF or national libraries, but we do not have this possibility in a bibliographic database as far as I know, and it is not our task to do so. Zotero might implement this, but from a quick inquiry this is not yet supported.
If the needs are thus of a clean reusable database which is able to produce in conjunction with a style a correct bibliography, I still think we should normalize. This will make the group library a reliable research tool and print a correct bibliography, with correct alphabetic order for example (which would be broken by having all variants).
If you really want to keep the names as they are in the publication, that is fine for me, it is how it is documented already, and what raised the issue, and people have links to get to the documentation and see these principles, so, not a big problem. Since we have set a use of Extra in the guidelines, simply do not use that field for other things like these variant names.
I do not understand what API you are speaking about and I am pretty much sure you cannot define further fields in Zotero. If you are speaking about the style, I doubt that such condition is actually implementable for names, but again, I really did not understand what you are trying to suggest.
Notes are there and are generic exactly because they will typically not be used from styles and can contain additional remarks of any kind. If you stick to the names in publication I would avoid wasting time to add VIAF identifiers there in notes or extras, because as opposed to applying standardization and recording a variant in the cases where this occurs, it would imply that you do have to provide the VIAF identifier everywhere, and I do not think we need to do so, there is already enough work to be done there as far as I know.

**Comment by abausi** [comment]
Please, exclude me from this conversation, I cannot do five things at 
the same time. Later on or in the next days.

Il 16.10.2018 11:48, Pietro Liuzzo ha scritto:

**Comment by DariaElagina** [comment]
The guidlines are updated.
