### ISSUE TITLE
Navigation System: color threads

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#972]
Dear all,
another question I have: how do we want to encode the existence of color threads for navigation in the manuscript. Some manuscripts of EMIP have these feature, which is described in the collation. For example, http://betamasaheft.eu/manuscripts/EMIP00128/main#generalphysical
I do not quite agree with that, but if it is an appropriate way to encode this feature, should we probably document this in guidlines? Or should we rather encode it in varia? Or somewhere else?

**Comment by PietroLiuzzo** [comment]
@ElianaDalSasso had done something related to this, please have a look at the binding section, I think that is the appropriate place, also for #970 and yes, when this is settled you could update the guidelines with the specific bit of information about how to encode these features.

**Comment by larkvi** [comment]
Since they are generally added after the manuscript is complete, by the user, in order to mark important divisions in the manuscript, perhaps `milestone` is the correct treatment, with a corresponding note in `physDesc`?

**Comment by DariaElagina** [comment]
<milestone> marks a boundary point separating any kind of section of a text, typically but not necessarily indicating a point at which some part of a standard reference system changes, where the change is not represented by a structural element.
I think it might be a good option!
Thank you!

**Comment by PietroLiuzzo** [comment]
I am not sure what is varia in your first suggestion Daria. I do not feel very confortable with milestone either, however. If you look at the examples also. Paradoxically, you might end up having to update the value of milestone every time the bookmark is moved... I instead like the physDesc note option. I would suggest to add this in a `<note>` element inside `<support>`. 
ok?
somebody might also want to search thread and move that information to this position to make the data a more consistent. I found less then 80 in the EMIP data.

**Comment by ElianaDalSasso** [comment]
Dear all,
In COMSt in the description of ethiopic bookbinding (p.174) there is this definition: "Several manuscripts are furnished with bookmarks made of coloured threads or pieces of leather fastened to the outer margin of a leaf some 50 mm from its upper corner. In the de luxe manuscripts it is a small, colourful bunch of silk threads."
So far when I encountered these threads I encoded them in bindingDesc as a DecoNote.
For example  http://betamasaheft.eu/manuscripts/SHOr400/main
`<bindingDesc>
 <decoNote xml:id="b12" type="other">
   Textile bookmark inserted in the upper text prick of fol. 35
</decoNote>
</bindingDesc>`

What do you think about it?

**Comment by PietroLiuzzo** [comment]
so, we have a feature here, variously encoded which was not regularized. however, there was no demand for that. If we want to do this, then I think decoNote in binding is as good as a note in physDesc, but the latter is preferable because the bookmark as far as I understood is not part of the binding.

**Comment by DenisNosnitsin1970** [comment]
The quote from p. 174 is actually not a definition, but just an attempt to describe what one sees. As far as I understand, "bookmark" is a general term for several types of devices facilitating the use of the book (but also I see that it may refer to one of the types). So the terminology is a bit complex. What I see specifically for Ethiopic manuscripts is: "finger tab" and "edge tab", e.g. in Miller, Books Will Speak Plain, p. 297; in some Ethiopic manuscripts another type is used, textile ribbons (apparently, as above), called again in a slightly different way. It looks like this all belongs to the description of the of the textblock, but otherwise to the description of the binding. If there is no other place, it can be also as "DecoNote", to my opinion, but we have to establish how the things are to be called, and make it visible in the guidelines. I see only problematic that we want to pick this one, but what is about other features which are on the same level.

**Comment by PietroLiuzzo** [comment]
Thanks @DenisNosnitsin1970 ! that is I think a strong point for `//binding/decoNote`

**Comment by ElianaDalSasso** [comment]
Yes, @DenisNosnitsin1970 sorry actually it's a description. 
In general, a bookmark is described within the features of the binding when it is attached to the spine or to another part of the cover. Ligatus in the Thesaurus distinguishes three main types of bookmarks: movable (for example fixed to the spine), fixed (linked permanently to a leaf) and free. 
Then there are different definitions according to the shape, the function and the position of the bookmark. Among them "ribbon markers", "leaf tab markers" and "leaf string markers".
http://www.ligatus.org.uk/lob/concept/2837
Maybe we can evaluate if one of their definition can be applied for ethiopic manuscripts.

**Comment by DariaElagina** [comment]
> I am not sure what is varia in your first suggestion Daria.
I meant that we have this list for Varia or extra, which is not fitting at all as I see.
I agree with Denis we should also think, how do we name this, because it seems to be much more descriptions of that kind, but they use different terms.
I would agree on using decoNote in binding.
Once we establish the rule, I volonteer to update guidlines and to update the description according to our solution.

**Comment by DariaElagina** [comment]
Sorry, my comment has a strange format :)

**Comment by ElianaDalSasso** [comment]
If we agree to encode it in binding we can work together or I can do that, as preferred, since I still have to update the part concerning endbands, sewing stations, boards... (!)

**Comment by DenisNosnitsin1970** [comment]
I agree; then as a narrative <DecoNote>
 but preferably with a fixed or partly fixed statement.  What are "leaf string markers?"

**Comment by ElianaDalSasso** [comment]
"Leaf string marker" is a bookmark sewn directly through a leaf while the term "leaf tab marker" indicates a small, rectangular bookmark folded or pasted to the fore-edges of the leave. But if "tab" is more common for Ethiopic manuscript maybe it's better too keep it
Maybe..is Iit possible to use a general term "bookmark" and specify, if necessary, the type with keywords like "ribbon" and "sewn" or "tab"?

**Comment by DenisNosnitsin1970** [comment]
It is better to keep apart those made of textile piece and those made of threads' bunch.  I am not sure if "leaf tab marker" type is common, if I understand it right. Just to summarize:
1) threads coloured or uncoloured, inserted in the corner or upper edge of the leaf; 2) textile ribbon inserted in the corner or upper edge of the leaf; 3) I read about one more type: a slit is made on the fore-edge, to make a kind of parchment tongue, which is folded and create a tab; but I personally do not know any example. If you agree with these categories, what would you propose for them? 
As far as I understand we have one this way, using "bookmark" as a general term, with further specification, placing this info into a <DecoNote>

**Comment by ElianaDalSasso** [comment]
@DenisNosnitsin1970 I think the last part of the comment is lost. 
As far as I understand reading the Ligatus "language of binding" the 2) typology, textile ribbon, is referred to those movable stripes attached to the spine of the book. For them I would propose to use simply "ribbon marker". 
3) I don't know any example of it too and I am not sure that I understood correctly. Is it something inserted in the slit or is the tab created starting from the leaf itself?
1) For the threads it is more complicated. There can be a single thread or a small piece of textile inserted in the fore-edge. Do we want to distinguish between them?Maybe "leaf string markers" and "leaf tab markers"?Or would it better to use for both "leaf markers"?

**Comment by PietroLiuzzo** [comment]
@DariaElagina I really need a precise reference to where these Varia list are, I am not figuring it out, sorry!

I think for the purposes of the current encoding, it would suffice to close this issue to add a line to the guidelines for binding, where it says very simple
"also bookmars are encoded in this way".

to specify which bookmark type, I think the best and most flexible way, also given that this information is not currently reused in any way, is to point directly to the Ligatus concept in the Thesaurus, which are stable URI.

These are all SKOS Concepts (see at the bottom of the Ligatus page linked by Eliana), so, you would enter something like 

`<relation 
active="MSSid#b3" 
name="crm:P2_has_type" 
passive="http://w3id.org/lob/concept/2837"/>`

This would let you also free to decide what to link from that thesaurus.

**Comment by DenisNosnitsin1970** [comment]
Pietro, we are not far from the end :)  Eliana, i think it is better to separate, because it is not difficult whenever we can see it. Then it might be like ): 1) threads coloured or uncoloured, inserted in the corner or upper edge of the leaf - "**leaf string markers**" (or "marks", if we say "bookmarks"?) 2) a piece of textile ribbon inserted in the corner or upper edge of the leaf (in fact "ribbon" means "a narrow strip") - "**leaf tab markers**". Would be interesting to learn, in the future, if Coptic-Arabic mss have this feature, and how it is catalogued. 
 3) the tab is created from the leaf itself, it is not an addition. This device is mentioned in the said Miller's book, on p. 297. Curious and very simple. But since neither of us know any single example, we can leave it for the moment. 
Links to Ligatus can be, by I would prefer to have a clear definition in the guidelines of Beta masaheft (with a couple of references to good visual examples).

**Comment by PietroLiuzzo** [comment]
pointing to the definitions of ligatus, either in the schema or as previously suggested in the single instances for this Thesaurus terms is definitely best practice especially when looking at the same features in other catalogues. So having a link in the schema to ligatus could be an extra level of definition. Indeed I am also for more examples and more examples with images!

**Comment by DariaElagina** [comment]
@PietroLiuzzo  I meant this: http://betamasaheft.eu/Guidelines/?q=varia&id=additionsVaria
but it does not fit anyway...

**Comment by DenisNosnitsin1970** [comment]
Hoping to conclude this soon, 
here are proposals for the formulas, to be considered for the Guidelines:
- bookmark of the type "leaf string mark" - made of one or several twisted threads, coloured or uncoloured, inserted in the leaf
- bookmark of the type "leaf tab markers" - made of a textile ribbon inserted in the leaf
Links to Ligatus from Eliana?

Possible cases:
1) Bookmarks: leaf string mark inserted in the upper edge/the upper corner/the upper text prick/the outer margin of ff. .... 
2) Bookmarks: leaf tab mark inserted in the upper edge/the upper corner/the upper text prick/the outer margin of ff. ....

Examples: 
image 1: leaf string mark inserted in the upper corner (MKMG 006)
image 2: leaf string mark inserted in the upper text prick (SSB-003) 
image 3: leaf string mark inserted in the outer margin (MAKM-086b)

The same as above can be with "leaf tab mark"; only one example is here, 
image 4: leaf tab mark inserted in the outer margin (KY-013)

It is actually a bit complicated if you want to be precise. Sometimes only one thick thread is inserted in the leaf, sometimes it is indeed (several) threads which can be coloured or uncoloured. 
Should we try to indicate all these features, or we stop at this point? 
Sometimes it the place of the insertion is not really obvious from the image (is it known where the corner of the leaf ends and the edge starts?), and also the type is uncertain 
![1 mkmg-0060094](https://user-images.githubusercontent.com/18533839/47851718-ca829f80-ddd9-11e8-9a89-a4d21f3a197a.JPG)
![2 ssb-003_096](https://user-images.githubusercontent.com/18533839/47851725-ceaebd00-ddd9-11e8-94e3-a53dcf569223.JPG)
![3 makm- macro 8 dn0014 2](https://user-images.githubusercontent.com/18533839/47851730-d3737100-ddd9-11e8-8161-f232fc8a76c0.jpg)
![4 ky-013_022](https://user-images.githubusercontent.com/18533839/47851739-dcfcd900-ddd9-11e8-8907-01b5134a0078.JPG)

**Comment by ElianaDalSasso** [comment]
Thank you @DenisNosnitsin1970, I agree with the proposals.
I think that, at the moment, could be enough to distinguish between tabs and strings.
Tabs could be used to study history or manufacture of textiles while I don't know which studies could be done on the position of the string. It's actually difficult to go in details from photographs and I wouldn't know how to define the boundary between the edge and the corner. However it's always possible to specify the position with free text. 
What do you all think if:

- In the schema, we insert bookmarks in bindingdesc and then use two keywords to distinguish "leaf string mark" and "leaf tab mark"?

`<bindingDesc>
<decoNote xml:id="bX" type="Bookmark">
<term key="leaf string mark" </term>inserted in the the upper text prik of ff. 10, 20, ...
</decoNote>
</bindingDesc>`

- In guidelines, we describe what a bookmark is and point to Ligatus general concept http://w3id.org/lob/concept/2837
then specify what is a "leaf string marker" and a "leaf tab marker ". 
I agree with @PietroLiuzzo on using a link to Ligatus because it is widely endorsed terminology and could help the comparative research on those topics!
Unfortunately, speaking about leaf tab markers, Ligatus seems to consider them only pasted and not sewn through the leaf (http://w3id.org/lob/concept/2945). Could pointing here create confusion?
Leaf string marker are described here http://w3id.org/lob/concept/2944.

I have one question: do we find in Ethiopic mss a bookmark like a textile ribbon that lies in the centrefold of the quires and can be moved?

**Comment by PietroLiuzzo** [comment]
Thanks @ElianaDalSasso and @DenisNosnitsin1970 I see here the very nice beginning of a photographic documentation for our guidelines. Great!

I agree with @DenisNosnitsin1970 to stop at the point of string/tab the position of which I would specify as text in the decoNote as in the suggestion by @ElianaDalSasso here above. I believe this would be interesting without forcing us to write a new project for the encoding of this features in more detail (but why not to write one?) This could be added to the Guidelines: who is up for summarizing the discussion and branching the guidelines repo to make a PR with this update?

The keywords (please without spaces!) would need to be added to the taxonomy and to the Authority-Files. @ElianaDalSasso , could you do that?  I can then update the schema accordingly.

However, because there is no exact correspondence I would make the linking to LIGATUS as suggested in the previous post with a `<relation>` element. It is indeed extremely important that it is there and I would make sure that this stated in the guidelines.

**Comment by ElianaDalSasso** [comment]
Yes, sure!I can do that. So the keywords to be added are leafStringMark and leafTabMark right?
@PietroLiuzzo I am reading the guidelines but I don't understand how to use a <relation> element in this case, could you give me an example?

**Comment by DenisNosnitsin1970** [comment]
Eliana, if "Ligatus" treats "leaf tab markers" as you say, perhaps we can better take a different term. Concerning your question: I think we do find such bookmarks, in the centrefold. I mean, they are used and I saw some. We could have a term for them. But also other objects can be used as removable bookmarks: a simple strow, or a candle, or a piece of paper. You will find them ocassionally in the images, but only few, since the digitizers tend to remove them while photographing (actually, two images are necessary, one with the object and one without, but most of the time only one is done).

**Comment by PietroLiuzzo** [comment]
The example above should be ok, or is it not? You are making a statement which you can place anywhere where you say X is Y, subject predicate and object. Your subject is the identifier of the decoNote, the property the one defined there, the object is the URI of the concept in Ligatus.
the page is here http://betamasaheft.eu/Guidelines/?id=relations

**Comment by ElianaDalSasso** [comment]
- Yes, it's a pity that it seems to be confined to pasted or cut and folded markers because leaf tab is a nice term to indicate that it is a bookmark wider than a string and attached to a leaf. Could I write a quick email to the ligatus staff to settle this doubt?

- We could also record the "centrefold bookmark" only when it is adhered somehow to the cover and it's not completely movable..."ribbon mark" could work?Ligatus describe them as follows:

> Narrow strips, often made of silk, used as a bookmark. Ribbon bookmarks could be used singly or in multiples, the latter being common on bound liturgical works. They were most often attached to the book by being adhered to the head of the spine and brought out under the endband, if there was one. Ribbon markers can also be found attached by other means, such as pierced through the covering material, tied round the endband, etc., though these will often be later additions made by the owners of the books.

- We could also indicate that there is something, of any material, inserted and loose in the textblock and we can choose a word for it. But it could be tricky to state that the function of the object was actually to mark a part of the text.

@PietroLiuzzo, I am sorry I've never used it...is it correct like this?
`<bindingDesc> 
<decoNote xml:id="bX" type="Bookmark"> 
<term key="leafStringMark"</term>inserted in the the upper text prick of ff. 10, 20, ... 
<relation>name="Bookmark" active="leafStringMark" passive="http://w3id.org/lob/concept/2944"></relation>
</decoNote> 
</bindingDesc>`

**Comment by DenisNosnitsin1970** [comment]
Sure, please write to them, maybe they have a better term. If i understand you right, by the way, if you take the term "ribbon mark", you can interpret it as nothing more than a textile ribbon used as bookmark, irrespective of the way it is applied to the book and the place it is fixed which are clarified in an additional statement.  Actually the same for "leaf tab markers"; if it is not already taken for smth very specific and used as a fixe term, I would not have any difficulty with "ribbon mark/leaf tab mark inserted in the corner" (or, textile ribbon mark). 
"We could also indicate that there is something.... But it could be tricky to state that the function of the object was actually to mark a part of the text." you are right, at least with the candle we cannot be sure. the function of all these objects can be mixed, at least.

**Comment by PietroLiuzzo** [comment]
@ElianaDalSasso no, you need `<listRelation>` around `<relation>` 
as in the guidelines examples. here is the correct code snippet

````xml
<bindingDesc>
<decoNote xml:id="b1" type="Bookmark"> 
<term key="leafStringMark"/> 
inserted in the the upper text prick of ff. 10, 20, ... 
</decoNote> 
....
<listRelation>
<relation 
     active="MSid#b1"  
     name="crm:P2_has_type"
     passive="http://w3id.org/lob/concept/2944"/>
</listRelation>
</bindingDesc>
````

note that in `active` you will need to have the id of the manuscript before the anchor.
in the first part of the encoding you are saying there is a leaf string mark. In the second part inside `listRelation/relation` you are saying that that one and only that one thing with id b1, which happens to be your decoNote in bindingDesc corresponds to one of the concepts in Ligatus (the uri in `passive`).
In this way, you can still use leafStringMark, or leafTabMark if it fits our definition here, and avoid linking it to Ligatus if it does not correspond to their concept.

**Comment by ElianaDalSasso** [comment]
Thank you @PietroLiuzzo!!
Sorry for the delay, I wrote to Ligatus and they are discussing the question, but there is not an answer yet. Shall we wait for it?

**Comment by DenisNosnitsin1970** [comment]
I do.

**Comment by DenisNosnitsin1970** [comment]
I assume there will be no objections from the others.

**Comment by DenisNosnitsin1970** [comment]
Dear Eliana, would you mind compiling short clarifications for "leafStringMark"/"leafTabMark", to be included into the guidelines (with the images above as examples)? Then we would finish it and properly close the issue.

**Comment by thea-m** [comment]
I am very sorry, I have read this issue and the related commits and still am not sure how to encode what has been called leaf string mark here.

Can the last example by @PietroLiuzzo be followed? (If all values are included in the schema, which they are not yet)

```xml
<bindingDesc>
<decoNote xml:id="b1" type="Bookmark"> 
<term key="leafStringMark"/> 
inserted in the the upper text prick of ff. 10, 20, ... 
</decoNote> 
....
<listRelation>
<relation 
     active="MSid#b1"  
     name="crm:P2_has_type"
     passive="http://w3id.org/lob/concept/2944"/>
</listRelation>
</bindingDesc>
```
 The value leafStringMark has been added to the taxonomy and there is an authority file, but it has not been added to the schema yet. Is it because the discussion is still open?

From https://github.com/BetaMasaheft/guidelines/pull/19 I understood instead that they should be encoded as a decoNote @type other:

```xml
 <bindingDesc>
                 <decoNote xml:id="b5" type="Other">
                 <term key="leafStringMark"/>
                 inserted in the the upper text prick of ff. 10, 20, ...
                 </decoNote>
             </bindingDesc>
```

**Comment by eu-genia** [comment]
These keywords (leafStringMark leafTabMarker) are not yet part of the schema are they?

**Comment by ElianaDalSasso** [comment]
Dear Thea, you are right, at the moment a bookmark is encoded in a decoNote @type other. 
Eugenia, I added the keywords in the taxonomy but the schema doesn't prompt them, could I have missed a step?

**Comment by eu-genia** [comment]
They are probably in the taxonomy but not in the ODD

**Comment by eu-genia** [comment]
have added to ODD leafStringMark leafTabMark, are there others not yet added that should be there?

**Comment by ElianaDalSasso** [comment]
Yes, there are the keywords related to the description of turn-ins corners:
- mitredCorner
- openMitredCorner
- overlappingCornerFO
- overlappingCornerHTO
- stitchedCorner
- tonguedCorner

And related to the cover:

- quarterCover
- overCover

**Comment by eu-genia** [comment]
all added

**Comment by thea-m** [comment]
Everything seems to be added to the guidelines and schema now. Please open a new issue if anything from this discussion is not yet resolved or something similar comes up.
