### ISSUE TITLE
Encoding of BL Orient 829*

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#974]
BL Orient 829* (see Wright's index https://archive.org/stream/catalogueofethio00brituoft#page/334/mode/2up) seems to contain fragments of many different manuscripts bound together (possibly, nothing on the binding is stated in the catalogue). Wright has single entries for each of the fragments, sorted in his catalogue according to their content. 
We already have two single records for one fragment each and one record which incorporates both these fragments (BLorient829 - to be renamed since there is another BL Orient 829 (without *) manuscript -, BLorient829a and BLorient829b). I think that it would be better to only have one record for all units, since currently, they seem to form one unit of circulation. In other cases, we do not create records for units of manuscripts that used to be independent either.
What do you think? Does anyone have more information about this manuscript that I have missed?

**Comment by PietroLiuzzo** [comment]
sounds like very interesting case for modelling!

**Comment by thea-m** [comment]
I agree that we cannot be sure about the binding, but that's why I'm not convinced either to add something like "Folder". Actually it is possible to have no `@form` at all, maybe we could do that (with a note) until someone has checked the situation at the library.
I would prefer having one record (with no `@form` for the record as a whole and `@form="Leaf"` for the single msParts) and then splitting it later if necessary, mainly because all parts have the same shelfmark.

**Comment by DariaElagina** [comment]
I agree with @thea-m, that would be a more economic variant in the sence of time.

**Comment by PietroLiuzzo** [comment]
All this depends on getting the missing information, and I do not think any suggestion can be made at the moment. I think the encoding of this/these items needs to be paused until better knowledge can be gathered. perhaps we can email BL about this?

**Comment by eu-genia** [comment]
I agree, I have now written to Ilana Tahan (oriental mss curator), let us see if she can help, or I can ask Eyob Derillo, if he is still around the manuscripts there, to check and let us know.

**Comment by eu-genia** [comment]
Ilana has written:

Dear Eugenia, 

 

I have called up Or 829* and checked it through.

It consists of parchment and paper manuscript fragments of different  sizes on guards.  The subject matter varies, which might explain why there are so many catalogue entries in Wright.  

The manuscript has 82 folios in total.  The first 4 folios are illustrated (3 are coloured illustrations).

An inscription of the front fly-leaf reads: Deposited by the Secretary of India 28 August 1868.  With a few written fragments bought by B. Holmes, Dec. 1868

 

I do not recommend having this manuscript digitised.  It would be rather difficult to photograph it.

 

I hope the above is of some assistance.  With renewed apologies for the very, very late reply.

 

Warmest wishes, 

 

Ilana

**Comment by eu-genia** [comment]
(From this response I am still not sure how the fragments are kept together, the unit was clearly created in the British Museum after December 1868)

**Comment by DariaElagina** [comment]
Dear all, I am about now to create the record for the BL Orient 829 (without *), which has been mentioned by Dorothea in the first message. So, I have to rename our problematic BL Orient 829  which actually stands for BL Orient 829*. Since the special signs are not allowed, which ID should I assign:  BLorient829bis, BLorient829fragments?
And concerning, the description of the fragments belonging to BL Orient 829* should I skip them for the time being?

**Comment by eu-genia** [comment]
We still have no final decision how we treat the unit created in the BL. 
I would rename (not delete) the single fragments, as suggested above, and create a new BLOrient829 record which unites the msFrag

**Comment by DariaElagina** [comment]
Sure, how should we name the BLOrient829*? We have the "normal" BLOrient829, which has nothing to do with BLOrient829*. Is just a normal manuscript.

**Comment by PietroLiuzzo** [comment]
please, do not use * in the id or filename.

**Comment by DariaElagina** [comment]
That I have mentioned in my previous message: 
Since the special signs are not allowed, which ID should I assign: BLorient829bis, BLorient829fragments?

**Comment by DenisNosnitsin1970** [comment]
Indeed, it is not clear from th answer of Mrs Tahan if the leaves are kept together in a kind of binding (she says "on guards", but are they kept together?) If they are in a binding, even if modern and supplied by the library but still holding together, in my opinion, it is a composite manuscript with many parts. If not, any solution can be applied, extending the ID BLorient829 with whatever - maybe just Latin letters BLorient829a, BLorient829b, BLorient829c, BLorient829d etc (but it should be a kind of standard system for BM).

**Comment by PietroLiuzzo** [comment]
I do not understand why the current BLorient829 needs to be changed. If I understand the original message and there are two named the same (?how is that possible?)  BLorient829fragments, sounds good, but it is indeed the same for me. The shelfmark in the record which can be accessed currently under BLorient829  already contains that star, if the concern is keeping with the catalogue. the fragments can continue with the ID assignation convention already in place for BLorient829a and BLorient829b, as also noted while I am writing, by Denis. I do not see much reason to deviate from that, in any case arbitrary, convention. When evidence to be able to construct this description will be available, having the records for each fragment or one record for all msPart/msFrag will be the same, technically, statements will point to the Identifiers. hope this helps!

**Comment by DariaElagina** [comment]
Sorry, my initial question was a little bit different. We have to distinguish between BLOrient829* and BLOrient829. The latter is a normal manuscript, which has nothing to do with BLOrient829* ( https://archive.org/stream/catalogueofethio00brituoft#page/334/mode/2up). But now this signature (BLOrient829) is blocked by BLOrient829*. Before we continue to encode BLOrient829* and its fragments, we have to decide on its ID. Because the ID it uses now belongs actually to another manuscript.

**Comment by DariaElagina** [comment]
Here is the link to the BLOrient without star [https://archive.org/details/catalogueofethio00brituoft/page/324/mode/2up?view=theater](url)

**Comment by DenisNosnitsin1970** [comment]
Oh, I see, it is so complex, and Wright solved the issue in an unusual way. But why BLOrient829 is blocked by BLOrient829*? BLOrient829 is now not possible? Another way, I assume,  would be perhaps to use BLOrient829 (for the original one) and for the complex one BLOrient829 + marked in whatever way (BLorient829bis, BLorient829fragments - as already indicated above, that is clear enough). It is very strange that they could not continue with 830, as far as I can see.

**Comment by DariaElagina** [comment]
> 
> 
> Oh, I see, it is so complex, and Wright solved the issue in an unusual way. But why BLOrient829 is blocked by BLOrient829*? 

Because we use BLOrient829 for BLOrient829* at the moment. So, we have to rename it, in order to be able to use BLOrient829 for the manuscript BL Orient829 (without star).


BLOrient829 is now not possible? Another way, I assume, would be perhaps to use BLOrient829 (for the original one) and for the complex one BLOrient829 + marked in whatever way (BLorient829bis, BLorient829fragments - as already indicated above, that is clear enough). It is very strange that they could not continue with 830, as far as I can see.

This is exactly what I have proposed in my initial message.

**Comment by DenisNosnitsin1970** [comment]
I have no objections.

**Comment by eu-genia** [comment]
yes, sorry, sure, the composite (folder) should be remained, BLorient829fragments sounds good, thank you

**Comment by anaiswion** [comment]
(sorry i am not sure if I understand all the discussion above on the shelfmark so I do not know if my information is any helpfull !)

**Comment by eu-genia** [comment]
Dear @anaiswion , thank you for checking this old ticket.
The discussion here was not about the provenance or content but purely technical, how to name the files to respect the catalogue and the library arrangement, considering our technical context. 

We normally (1) use shelfmarks for filenames and (2) follow the catalogues in the initial description, and in this case both were impossible, as 
(1) the shelfmarks are 829 and 829* and we may not have symbols like asterisk in the filename so had ti name the second one differently (this has been solved above, so now we have BLorient829 and BLorient829fragments)
(2) there are two shelfmarks and two library units but while BLorient829 corresponds to one catalogue number (Wright 401), each fragment in BLorient829fragments is described separately in the catalogue, so there are 21 catalogue numbers for just one current unit of circulation (Wright 406, 407, 408, 409, 30, 100, 110, 199, 159, 403, 394, 167, 143, 204, 142, 202, 198, 172, 203, 205, 402) - this has also been solved, as we opted for one record BLorient829fragments which unites the catalogue entries from the different pages in the catalogue (I had contacted Ilana Tahan to make sure that these fragments all are kept together in the library, or otherwise we would have described each as a separate manuscript)..

Thank you very much for ypur remarks.
