### ISSUE TITLE
keywords Apocrypha and Pseudoepigrapha

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#982]
We currently have the three keywords Apocrypha, Pseudoepigrapha and ApocryphaPseudoepigrapha. In the famous #175, Massimo suggested only using ApocryphaPseudoepigrapha ("1-2: "Apocrypha" and "Pseudoepigrapha" substantially reduplicate the same value as “ApocryphaPseudoepigrapha” and should be avoided for the sake of clarity and consistency. There is a terminological question around the use of Apocrypha and Pseudoepigrapha, that we may perhaps avoid by employing the comprehensive term "ApocryphaPseudoepigrapha" (as in Ethio-SPaRe)."), to which there were no objections or remarks and which I think most of us have done since then. Can we delete Apocrypha and Pseudoepigrapha (after making sure that all files that used only one of the terms have ApocryphaPseudoepigrapha instead)? It would clean the list up a bit. If not, we would need definitions and examples for both.

**Comment by abausi** [comment]
At best, "Apocrpypha" will work as well and is the most widely used; "ApocryphaPseudoepigrapha" is very much OT oriented (there are no "Pseuedoepigrapha" in the narrow sense for the NT); I would also slightly change the definition, since the inclusion or not of some works is really a question of points of view and of accident as well, starting from the tradition we are most familiar with, so that to define as "Apocrypha" the "Book of Enoch" sound really strange. Something of this kind could work: "works not universally recognised in the Christian and Jewish religions as belonging to the fixed set of canonical scriptures, either for reasons of tradition or of secundary development or doubtful authorship or heterodox opinions and for this rejected from one or the other bible canon of the respective tradition: e.g. the Book of Enoch, Jubilees, Herma, the Miracles of Mary, the Miracles of Jesus, Maṣḥafa ṭomār, the apocryphal Acts of the Apostles, etc."

**Comment by thea-m** [comment]
I have added this definition to the schema, should "Pseudoepigrapha" and "ApocryphaPseudoepigrapha" be deleted now? This will lead to many invalid records, obviously.

**Comment by thea-m** [comment]
Yes, @abausi,  that's what I understood and why I unassigned you from this discussion. My current question was more regarding the technical workflow. Thank you!

**Comment by PietroLiuzzo** [comment]
@thea-m could you please commit the changes to the schema? thanks
